### ISSUE TITLE
Hey! 👋 

### ISSUE THREAD

**Issue by caoxiemeihao** [alex8088/electron-vite#1]
### Clear and concise description of the problem

兄弟！直接进组织可好。

### Suggested solution

<img width="295" alt="image" src="https://user-images.githubusercontent.com/26263658/161940902-0a374aea-e55c-4477-911b-44e5c31be54f.png">

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by oceanlvr** [comment]
看起来我们想法完全一致，有兴趣把仓库迁移到 electron-vite 下吗？我们可以把这个阻止扩大，人多力量大更容易涨星~（不是
