### ISSUE TITLE
关于环境变量不生效问题

### ISSUE THREAD

**Issue by sfyang2** [alex8088/electron-vite#10]
### Describe the bug

在项目根目录添加环境变量配置文件后，在项目里无法通过import.meta.env获取到，是我配置有问题还是不能像正常的vite项目那样配置呢？

在项目根目录下已添加以下文件
.env.development 和 .env.production 后

//.env.development文件内容
VUE_APP_TEXT = 'development'

在package.json中修改了
"dev":"electron-vite dev --mode development"

//在app.vue中访问
console.log(import.meta.env.VUE_APP_TEXT) ;//打印未定义

### Electron-Vite Version

1.0.2

### Electron Version

17.3.1

### Vite Version

2.9.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
it‘s a bug and i will fix it soon

**Comment by sfyang2** [comment]
好的，辛苦大佬。  请问这一两天内能修复吗，经过测试就差这个问题了，准备将旧的webpack项目迁移使用您这个了

**Comment by alex8088** [comment]
at weekend

**Comment by alex8088** [comment]
@sfyang2 
变量名以`VITE_`为前缀，才能使用  https://vitejs.cn/guide/env-and-mode.html

**Comment by sfyang2** [comment]
@alex8088  使用VITE_为前缀也是不可以，还需要配置什么其他地方吗

**Comment by alex8088** [comment]
@sfyang2 两种方式可以解决，

1.在renderer中使用时，可以在renderer目录下添加

```
└──renderer
     ├──src
     ├──index.html
     └──.env
```

2.在electron.vite.config中指定目录，参照一下配置

```
export default defineConfig({
 ...
  renderer: {
    plugins: [vue()],
    envDir: '../../'
  }
})
```

主进程和preload中使用是不需要配置的，可在root目录设置，在渲染进程中使用则需要配置。

这是由于electron-vite将渲染进程的工作目录指定在renderer目录中，这个问题也会在下一个版本优化，将不在要配置

感谢你反馈的问题。

**Comment by sfyang2** [comment]
@alex8088  感谢大佬，配置后可以使用环境变量了
