### ISSUE TITLE
electron verison select

### ISSUE THREAD

**Issue by lvbirui** [alex8088/electron-vite#100]
### Clear and concise description of the problem

in some times some native js packages have to used in different electron version. such as ZMQ.
so if we can choose electron verison , the useage will be more convenient

### Suggested solution

when init project people can select electron version.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
It is recommended that you modify the electron version in `package.json` after initializing the project and then install it.  And not use tilde `~` and caret `^`. This limited version behavior is not well suited for scaffolding.
