### ISSUE TITLE
如果直接把vite build过的文件放到renderer里面，npm run start报错

### ISSUE THREAD

**Issue by kknono** [alex8088/electron-vite#101]
### Describe the bug

如果直接把其他vite build过的文件放到renderer里面，npm run start报错.

error during preview electron app:
RollupError: Identifier '__vitePreload' has already been declared

### Electron-Vite Version

^1.0.19

### Electron Version

^23.0.0

### Vite Version

^4.1.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
为什么不直接让electron-vite来构建，出于什么场景要这样做，vite 最终打包还是基于rollup来打包，rollup是基于es设计的，因此构建完成的包在由vite再次打包必然失败（已不是es）。如果非要这样处理，可以将renderer配置项移除，但就失去了开发的模式 的能力了。也许你是想要renderer能够web和electron两用，实际electron-vite也可以达到此目的。

**Comment by kknono** [comment]
谢谢回复。老的web项目，用electron-vite的dev模式有许多迁移方面的问题。 有没有办法，electron-vite启动vite的preview模式，预览的是renderer下已打好的包。把vite当做web服务器。

**Comment by alex8088** [comment]
可以，跳过构建预览  `electron-vite preview ---skipBuild`,  也可以把配置中renderer项移除。相关可以看看https://cn-evite.netlify.app/guide/cli.html

**Comment by alex8088** [comment]
@kknono 问题是否解决？

**Comment by kknono** [comment]
没有解决。暂时先用loadUrl代替了。"build:mac": "electron-builder --mac --config",  去掉build了。

**Comment by kknono** [comment]
dev模式加载会慢，且各种因素会报错。vite的preview模式比较稳定吧，或许可以loadUrl到本地服务。可否dev和preview模式两者兼得？

**Comment by alex8088** [comment]
实际上你只需要在main进程通过load File 加载你build的index. html就好 ，同时移除renderer配置项即可(不移除就会去尝试重新构建，因为已构建过再去构建必然各种错误)，无论开发，生产还是预览都可以

**Comment by kknono** [comment]
谢谢。尝试了下不知道对不对。删除了electron.vite.config.ts下的renderer配置。同时把build后的文件都放入到out的renderer目录下。运行pnpm run build:mac，可以打包，但是报错了。
<img width="902" alt="截屏2023-02-13 19 43 30" src="https://user-images.githubusercontent.com/2398446/218449668-06463340-22f0-4e96-9444-d9efe1e32b47.png">

**Comment by alex8088** [comment]
应该是electron-builder相关库下载不成功，这个常见问题，检索一下解决方案。
也不一定要放out/renderer，因为打包时就会清除重新生成，可以放root，main中loadfile路径正确就可以

**Comment by kknono** [comment]
好的。谢谢，库的问题解决了。不改动template的结构，只是在out里面添加build之后的内容，修改main.ts里面的loadfile路径。
目前出现这种情况如果是普通的index.html则能展示，如果是其他vite编译出来的项目，则不能展示。是不是需要提供一个web服务器来渲染？

**Comment by alex8088** [comment]
> 好的。谢谢，库的问题解决了。不改动template的结构，只是在out里面添加build之后的内容，修改main.ts里面的loadfile路径。 目前出现这种情况如果是普通的index.html则能展示，如果是其他vite编译出来的项目，则不能展示。是不是需要提供一个web服务器来渲染？

不需要，问题可能在于你编译出来的项目，你可以通过devtool看看是什么问题，如果使用了路由，也应该注意，loadFile 是需要配置 hash 参数 （`loadFile('XXXX', { hash: 'home' })`）

**Comment by kknono** [comment]
大佬，你好。加进去也不行。有可能是原项目的编译方式和包的问题，但是修改老代码代价有点大。
现在是把demo里面的代码修改了一下。
  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    const previewServer = await preview({
      build: {
        outDir: join(__dirname, '../preview')
      }
    })
    if(previewServer.resolvedUrls &&previewServer.resolvedUrls?.local.length>0 ){
      mainWindow.loadURL(previewServer.resolvedUrls?.local[0])
    }else{
      mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
    }
  
  }


可以加载本地的了。
谢谢。

**Comment by alex8088** [comment]
正常直接这样 `mainWindow.loadFile(join(__dirname, '../renderer/index.html'))` 就好了，如果有问题可能是原项目的编译方式和包的问题
