### ISSUE TITLE
Unable to use preload.build.rollupOptions

### ISSUE THREAD

**Issue by theogravity** [alex8088/electron-vite#103]
### Describe the bug

My `electron.vite.config.ts` file:

```
import { resolve } from 'path';
import { defineConfig, externalizeDepsPlugin } from 'electron-vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()],
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          main: resolve(__dirname, 'src/preload/main.js'),
          'screen-share-picker': resolve(__dirname, 'src/preload/screen-share-picker.js'),
        },
      },
    },
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src'),
      },
    },
    plugins: [react()],
  },
});
```

In my project directory, I have

<img width="373" alt="image" src="https://user-images.githubusercontent.com/855434/218187376-2233186e-d481-4b17-b716-3960f0e0c67b.png">

When I run `electron-vite dev --watch`, I do not see output in the preload directory:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/855434/218187496-ab32de12-cce1-4d75-bcd8-7cf55a02ea3f.png">

### Electron-Vite Version

1.0.18

### Electron Version

22.2.0

### Vite Version

4.1.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
The preload script path you configured is incorrect.
There are subdir `ipc-invokes`

**Comment by theogravity** [comment]
`main.ts` and `screen-share-picker.ts` isn't under `ipc-invokers` though.

This is my `tsconfig.node.json`:

```
{
  "extends": "@electron-toolkit/tsconfig/tsconfig.node.json",
  "include": ["electron.vite.config.*", "src/**/*"],
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "declarationDir": "src/types",
    "types": ["electron-vite/node"],
    "target": "ES2022",
    "module": "esnext",
    "moduleResolution": "node"
  },
}
```

**Comment by alex8088** [comment]
`main: resolve(__dirname, 'src/preload/main.js')` ->  `main: resolve(__dirname, 'src/preload/main.ts')` 

`js -> ts`

**Comment by theogravity** [comment]
Thank you, that fixed it!

**Comment by theogravity** [comment]
Oh, it still did not work:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/855434/218280544-5aad0bf4-e8cc-456f-98ab-3ba8b7f649b5.png">

<img width="345" alt="image" src="https://user-images.githubusercontent.com/855434/218280551-c1b5903d-1e4e-4ddd-a662-836ea515c4f0.png">

```
  const mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    show: false,
    autoHideMenuBar: true,
    webPreferences: {
      preload: join(__dirname, '../preload/main.js'),
      ...commonWebPrefs,
    },
    icon,
  });
```

`electron.vite.config.ts`:

```
  preload: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          main: resolve(__dirname, 'src/preload/main.ts'),
          'screen-share-picker': resolve(__dirname, 'src/preload/screen-share-picker.ts'),
        },
      },
    },
  },
```

**Comment by alex8088** [comment]
try `sandbox: false`

**Comment by alex8088** [comment]
https://www.electronjs.org/blog/electron-20-0 ,

If your preload scripts do not depend on Node, no action is needed. If your preload scripts do depend on Node, either refactor them to remove Node usage from the renderer, or explicitly specify sandbox: false for the relevant renderers.

**Comment by theogravity** [comment]
> https://www.electronjs.org/blog/electron-20-0 ,
> 
> 
> 
> If your preload scripts do not depend on Node, no action is needed. If your preload scripts do depend on Node, either refactor them to remove Node usage from the renderer, or explicitly specify sandbox: false for the relevant renderers.

We don't have any dependencies on node and we use sandbox: false for security reasons, along with context isolation true and node integration false.

Our app runs fine, it's just when I try to split the preloaders up, there are issues.

**Comment by alex8088** [comment]
When two preload scripts refer to a common module, a chunk will be generated. You can copy common codes for independent reference, which can temporarily solve this problem.

Maybe the preload script require one file. I will try to reproduce and find the problem.

**Comment by theogravity** [comment]
Thinking about it, it's probably more an issue with the vite / rollup tooling than it is with your framework. If you're unable to come up with anything, that's ok. I appreciate the time you've spent to respond to me!

Thank you!

**Comment by alex8088** [comment]
🤝 This is probably related to rollup. How to not split the code and generate a chunk.

**Comment by alex8088** [comment]
Multi-file preload script support needs to disable `sandbox`. see https://www.electronjs.org/docs/latest/tutorial/sandbox#preload-scripts
