### ISSUE TITLE
Failed to resolve import after configuring tsconfig paths

### ISSUE THREAD

**Issue by Konglomneshued** [alex8088/electron-vite#105]
### Error with my tsconfig
![Error with my tsconfig](https://user-images.githubusercontent.com/94726665/218278487-692e85c7-3962-4973-ab70-1edd45c61e1d.png)

### My project structure showing that, in fact, the files exist
![My project structure showing that, in fact, the files exist](https://user-images.githubusercontent.com/94726665/218278507-3c932992-5c78-4018-bd6f-745c2975c22d.png)

### The index file for the app header component
![The index file for the app header component](https://user-images.githubusercontent.com/94726665/218278563-c84880d8-35a7-431d-bb99-03da0ca5ef42.png)

### Electron-Vite Version

^1.0.17

### Electron Version

^21.3.3

### Vite Version

^4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
webstorm IDE ? try remove `files: []` in tsconfig.json, and restart ide.

**Comment by Konglomneshued** [comment]
It is Webstorm.

I removed it and restarted my IDE but I still have the issue.  :(

**Comment by alex8088** [comment]
@Konglomneshued 

you also need to add `alias` in config file, like this:

``` js
renderer: {
  resolve: {
    alias: {
      '@renderer': resolve('src/renderer/src')
    }
  }
}
```

**Comment by Konglomneshued** [comment]
I don't understand.  Where does that go?  In the main tsconfig after my references?

I'm thinking it's not JSON code from looking at it.

**Comment by alex8088** [comment]
@Konglomneshued  in `electron.vite.config.ts`, not tsconfig, need to tell Vite how to resolve.

**Comment by Konglomneshued** [comment]
Thanks for clarification.  I seem to already have that.  However, I can see now that all I need to do is change the current alias and add a new one for my components path.

That has it working now, thank you very much for your help.
