### ISSUE TITLE
渲染进程中 webview 设置 preload 的文件路径问题

### ISSUE THREAD

**Issue by hehehai** [alex8088/electron-vite#107]
### Clear and concise description of the problem

```vue
<webview src="https://www.github.com/" preload="file:// ...... /preload/webview.js"></webview>
```

out 文件
```txt
.
├── main
│   ├── chunks
│   │   ├── .... files ....
│   └── index.js
├── preload
│   ├── index.js
│   └── webview.js
└── renderer
    ├── assets
    │   ├── .... files ....
    └── index.html
```

如何引入 preload ?

### Suggested solution

有解决办法吗？

参考：https://github.com/electron/electron/issues/1958

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
1.在 webview 中使用 preload 应该指向 输出目录的 preload，即是 `out/preload/webview.js` ;
2.开发模式下，使用的是开发服务，因此这个时候要使用file协议来指向preload文件；生产模式下可以使用相对路径 `../preload/webview.js`；
3.可以通过环境变量`import.env.PROD` 来判断处理
