### ISSUE TITLE
打包时存在遗漏main或preload 依赖的js文件的问题

### ISSUE THREAD

**Issue by cutesparrow** [alex8088/electron-vite#109]
### Describe the bug

1. vite配置保持默认
![image](https://user-images.githubusercontent.com/46345059/219027671-8e041440-fb14-48c8-8fae-8ce2b5f36f7e.png)
2. 在preload.js 文件中导入同目录下的其他js 文件
preload.js
`const moduleA = require('./lib/lib')`
lib.js
```
var Add = () => {
    console.log(3)
}

module.exports = {
    Add
}
```
3. 打包运行出现以下错误（lib.js文件不存在）
![image](https://user-images.githubusercontent.com/46345059/219028129-76a858f6-f59c-4135-9c70-1d70929d4ea7.png)

4. 检查发现out目录下没有lib.js文件，打包时没有将src/preload目录下的js文件复制到out目录下。

![image](https://user-images.githubusercontent.com/46345059/219028378-d58d0e7b-67a2-4575-b8af-6cf70069c5fe.png)

### Electron-Vite Version

1.0.17

### Electron Version

23.0.0

### Vite Version

4.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
You need to use `es` syntax.  需要使用`ES`语法导入模块

```js
import moduleA from './lib/lib'
```

**Comment by alex8088** [comment]
https://github.com/alex8088/electron-vite/discussions/106

**Comment by cutesparrow** [comment]
> You need to use `es` syntax. 需要使用`ES`语法导入模块
> 
> ```js
> import moduleA from './lib/lib'
> ```

Thanks. It works
