### ISSUE TITLE
开箱即用体验不足，希望能进一步完善

### ISSUE THREAD

**Issue by chenweihan** [alex8088/electron-vite#11]
### Describe the bug

做到这个程度，100步基本到了80步，已经花费了大量精力在里面了，在开箱即用或者已有项目的引用上给vue-cli-plugin-electron-builder易用性上差距比较大。

1：固定的目录就决定了已有项目使用的改造的工作成本
2：手工的配置脚本等增加了工作成本
3：已有项目的vite配置也增加工作成本
4：......

https://nklayman.github.io/vue-cli-plugin-electron-builder/

在多花20%精力参照vue-cli-plugin-electron-builder整理出来，不一定像他要有专门的官网嘛，或许会成为vue3+vite下的类似vue-cli-plugin-electron-builder的经典插件，成为经典插件是值得花费这部分精力的。

### Electron-Vite Version

13

### Electron Version

13

### Vite Version

2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
非常感谢您的宝贵意见。`electron-vite`以作为`electron`开发构建工具为定位，针对`electron`开发设计，内置了很多配置，开发者并不需要太多配置，本质是简单和快速的。其目标就是减少开发者的配置心智负担并提高`electron`的开发构建效率。

当然，`electron-vite` 也有其开发规范，这是基于开发经验总结和`electron`官方推荐的开发模式而设计的，比如项目目录结构的设计。对于你提到旧项目迁移问题，尤其是大型固有结构的项目，如何改造，如何配置，实际是复杂的。也如你所说的确实需要一些总结指引。

最近也在总结研究，编撰官方文档中，包括`electron-vite`的设计思路，配置指引，旧项目迁移等等内容，希望对开发者有帮助。

此外，对于新项目我推荐你使用脚手架工具[create-electron](https://github.com/alex8088/quick-start/tree/master/packages/create-electron)，更好的开箱即用体验。

**Comment by chenweihan** [comment]
你其实考虑掉了另外一个问题，目前很多项目新项目都是基于脚手架比如element-ui等UI库或者开始是做WEB系统，后期改造electron。 如你上面所说，实际改造成本也不小。  在我使用vue-cli-plugin-electron-builder中，任何项目添加vue-cli-plugin-electron-builder感觉都比较丝滑。 你是做插件实现引入electron而不框架的，至于项目目录是实际开发者考虑的，给你插件无关啊，我引入一个插件，你居然要影响我的目录结构改造，是不是有点喧宾夺主了。

我的建议是，把重点放到系统引入插件使用即可，插件添加简单，使用灵活，配置方便。 


vue-cli-plugin-electron-builder 优点：
1：自动在根目录直接生成background.js，可以在调通最小可用的原则上，实际开发者自己改造喜欢的结构或者推荐结构，这样改造难度也最小，心智理解也比较容易。
2：自动在package.json生成script执行脚本
3：有vue-cli-plugin-electron-builder官网以及配置说明和难点FQA

有这3点，已经足够了...  vue-cli-plugin-electron-builder确实可以借鉴

**Comment by alex8088** [comment]
electron-vite对于目录结构，只是一种推荐，这是基于开发经验的和官方的推荐总结，目录结构是自由的，可通过配置指定入口文件来改变的。对于熟悉vite的开发者而言，这种改造工作是容易的。对于不熟悉的，是需要要一定的配置指引。可能这是对于目录结构的推荐产生的误会，electron-vite追求最小化配置这是目标。

还有最重要一点，electron-vite并不只是针对vue2或者vue3,它也支持react，sevlet等等前端框架，它是全能的，正如vite一样，这是插件所无法比拟的，同时它自身也是支持插件的。其实从vue2到vue3的迁移改造是从webpack到vite的过程，这一部分的改造工作是必不可少的，这与目录结构没有太大关系。

**Comment by chenweihan** [comment]
嗯，正如你说。 1：electron-vite实现的是electron-vite的集成，至于目录只是推荐
                           2：electron-vite追求最小化配置这是目标
                           
                           electron-vite并不只是针对vue2或者vue3这点而言，如果是按照上面2点来，自然不会仅限于vue方向了。专注于electron-vite的集成，本身electron和vite就不关注前端框架。
                           
        一个实际需求就是：已有的项目，可以添加该插件而不会要求修改目录结构就可以使用，更进一步可以说是配置也不需要修改而是通过增加一个配置文件，更好的配置整合或者目录推荐，可以在后续文档进一步指导完善。 
        
        维护一个开源软件，确实会花费太多额外精力.（如果不是公司KPI要求）

**Comment by alex8088** [comment]
New official website released

**Comment by chenweihan** [comment]
看了你的官网，不错。 但无法便捷的解决我实际问题。

场景1：开始我是一个web项目，然后突然老板让增加桌面版，我不会依赖就构建一个基于electron的桌面全新应用
场景2：我需要开发一个桌面版的应用，但是我还是想保留web的场景使用

怎么能灵活随意的插拔式的无缝能使用才是重点，目录结构怎么优秀或者推荐的其他都不是重点，实际解决的痛点是集成，管用户用什么结构，推荐目录无所谓，解决我的痛点就是了。我最近已经开发的项目是vue3.0的web系统，但是预估后面可能会使用electron的场景，我也想使用个插件，无奈都不太好用，采取了自己手工集成electron和electron-builder。

这个插件解决的痛点就是能不能便捷的集成，至于其他可以放到高级指南里。我上面也说了 vue-cli-plugin-electron-builder 解决痛点做的很好。

只要是基于vue-cli的项目无论新旧项目集成electron，vue-cli-plugin-electron-builder ，只需要执行一个命令就搞定 
vue add electron-builder 然后就能跑起来集成electron.

说一大堆不如一个命令就解决集成来的的牛逼，这才是理解了用户的真实需求。
