### ISSUE TITLE
api is not defined

### ISSUE THREAD

**Issue by Konglomneshued** [alex8088/electron-vite#111]
### Trying to use the api from preload in my renderer

```
// Custom APIs for renderer
const api = {
   // Function
};
```

```
// Somewhere in my renderer
api.someFunction();
```
![image](https://user-images.githubusercontent.com/94726665/219976492-a05ea598-0f00-4325-956f-765346071553.png)

### main.ts
```
function createWindow(): void {
   // Create the browser window.
   const mainWindow = new BrowserWindow({
      width: 900,
      height: 670,
      minWidth: 500,
      minHeight: 500,
      show: false,
      autoHideMenuBar: true,
      ...(process.platform === 'linux' ? { icon } : {}),
      webPreferences: {
         preload: join(__dirname, '../preload/index.js'),
         sandbox: false,
      },
   });
// ...
```

### Electron-Vite Version

^1.0.17

### Electron Version

^21.3.3

### Vite Version

^4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
e.g. `window.api.someFUNC`
https://evite.netlify.app/guide/dev.html#using-preload-scripts

**Comment by Konglomneshued** [comment]
![image](https://user-images.githubusercontent.com/94726665/219992719-0109417d-9510-4f09-a483-3c7217ebc8f6.png)

**Comment by liuyike98** [comment]
you just declare `const api = {...}` in preload, but not mount it to `window`
eg: `window.api = api`

**Comment by Konglomneshued** [comment]
I do

```
// Use `contextBridge` APIs to expose Electron APIs to
// renderer only if context isolation is enabled, otherwise
// just add to the DOM global.
if (process.contextIsolated) {
   try {
      contextBridge.exposeInMainWorld('electron', electronAPI);
      contextBridge.exposeInMainWorld('api', api);
   } catch (error) {
      console.error(error);
   }
} else {
   // @ts-ignore (define in dts)
   window.electron = electronAPI;
   // @ts-ignore (define in dts)
   window.api = api;
}
```

**Comment by Konglomneshued** [comment]
### preload > index.d.ts
```
import { ElectronAPI } from '@electron-toolkit/preload';

declare global {
   interface Window {
      electron: ElectronAPI;
      api: unknown;
   }
}
```

**Comment by alex8088** [comment]
**Type Error**

```js
export const API = {
  func: () => {}
}

if (process.contextIsolated) {
  try {
    contextBridge.exposeInMainWorld('api', API)
  } catch (error) {
    console.error(error)
  }
} else {
  // @ts-ignore (define in dts)
  window.api = API
}
```

 ```js
import { API } from './index';

declare global {
    interface Window {
       api: typeof API;
    }
 }
 ```

in renderer

```
window.api.func()
```

**Comment by alex8088** [comment]
If you can use `window.electron.ipcRenderer`, you can use your custom api. 

```
console.log(window.electron)
console.log(window.api)
```

**Comment by Konglomneshued** [comment]
Both are undefined when I console log them.

I haven't changed anything in my main or preload (aside from adding the function to api) since starting my project with Electron-Vite.

**Comment by alex8088** [comment]
capture you electron window and take a look

**Comment by alex8088** [comment]
see  `src/renderer/src/components/Versions.tsx`, use `window.electron.process.versions`. if not work, these versions will not display.

**Comment by Konglomneshued** [comment]
I don't understand.  I don't have a Versions component.

**Comment by alex8088** [comment]
if  you start with electron-vite should have versions component.

 Preload script api just inject to electron not your browser.

**Comment by Konglomneshued** [comment]
Somehow I fixed it.  Maybe providing type declarations, I don't know, I had tried that before.

Anyway it's working now.

**Comment by eliot-ye** [comment]
![image](https://github.com/alex8088/electron-vite/assets/48172584/6c297860-9801-4acf-8a0c-9d388d241f10)

![image](https://github.com/alex8088/electron-vite/assets/48172584/95543f54-da7b-4d9b-b5db-4487e6e223ca)

I have the same problem when I use sandbox mode

**Comment by alex8088** [comment]
> ![image](https://private-user-images.githubusercontent.com/48172584/298435572-6c297860-9801-4acf-8a0c-9d388d241f10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTAxNjcsIm5iZiI6MTcwNTg4OTg2NywicGF0aCI6Ii80ODE3MjU4NC8yOTg0MzU1NzItNmMyOTc4NjAtOTgwMS00YWNmLThhMGMtOWQzODhkMjQxZjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNmIwNWUxYWJhODA0NGI5NTJjNzAyZjM5ZTkxMTg2NmI0ZjRhNTNmN2U4NGFkZWU4NThjMDBkYjU3ODY5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u63Sk3TmTaXr7PiYFZFa_M1uq7R5YzoyPIGno7M5U14)
> 
> ![image](https://private-user-images.githubusercontent.com/48172584/298435625-95543f54-da7b-4d9b-b5db-4487e6e223ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTAxNjcsIm5iZiI6MTcwNTg4OTg2NywicGF0aCI6Ii80ODE3MjU4NC8yOTg0MzU2MjUtOTU1NDNmNTQtZGE3Yi00ZDliLWI1ZGItNDQ4N2U2ZTIyM2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlM2E4NTgzOWM3MDJjY2UyYTUyMDgxNzU4ZmY2OTQ2ZmM5ZjdkYjUyNWFhNDZhNGUzNWYwY2E0NGU3YjI5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mPkdFeeZHhnJxtCAWzpYBKpSQHz9WHfJB1gpIaWsNpU)
> 
> I have the same problem when I use sandbox mode

https://electron-vite.org/guide/dev#limitations-of-sandboxing

**Comment by Android789515** [comment]
Same issue. However, this is not the fix:

```ts
// preload/index.ts

import { contextBridge, ipcRenderer } from 'electron';
import { electronAPI } from '@electron-toolkit/preload';

// Custom APIs for renderer
export const api = {
  method: (args: ArgsType) => {
    ipcRenderer.send('method', args);
  },
};

try {
  contextBridge.exposeInMainWorld('electron', electronAPI); // <- don't do this
  contextBridge.exposeInMainWorld('api', api);
} catch (error) {
  console.error(error);
}

// preload/index.d.ts

import { ElectronAPI } from '@electron-toolkit/preload';
import { api } from './index';

declare global {
  interface Window {
    electron: ElectronAPI; // <- don't do this
    api: api,
  }
}
```

You will get this error in your `tsconfig.web.json`:
```
Cannot write file 'project/src/preload/index.d.ts' because it would overwrite input file.
```

The correct fix is this:

```ts
// preload/api.ts

export interface API {
  method: (args: ArgsType) => ReturnType;
}

// preload/index.d.ts

import { API } from './api';

declare global {
  interface Window {
    api: API;
  }
}

// preload/index.ts

import { contextBridge } from 'electron';

import type { API } from './api';

// Custom APIs for renderer
const api: API = {};

try {
  contextBridge.exposeInMainWorld('api', api);
} catch (error) {
  console.error(error);
}

```

Note: I added comments explaining not to expose the electron API to renderer process, see [here](https://www.electronjs.org/docs/latest/tutorial/context-isolation#security-considerations) for why that's a security risk.
