### ISSUE TITLE
How to reduce build filesize?

### ISSUE THREAD

**Issue by rahmat-dev** [alex8088/electron-vite#114]
### Describe the bug

I am interested in trying Electron Vite and I try to create a simple counter application. It works.
![image](https://user-images.githubusercontent.com/40190205/220686665-7456ed58-26bc-4eb6-a8e3-e4499948da79.png)

But I'm confused why the file size after I build is so large just for simple applications like this?
DMG file: 88,5MB
After I install: 223MB
![image](https://user-images.githubusercontent.com/40190205/220686881-61bc15a7-2fff-41d1-aedf-a8447642fc01.png)

### Electron-Vite Version

^1.0.17

### Electron Version

^21.3.3

### Vite Version

^4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
This is normal for Electron, and there is nothing to reduce.
