### ISSUE TITLE
Use Widevine CDM 

### ISSUE THREAD

**Issue by gabrielrosas** [alex8088/electron-vite#115]
### Describe the bug

I'm trying to use Widevine CDM on my Electron app. I followed [this](https://www.electronjs.org/docs/latest/tutorial/testing-widevine-cdm#verifying-widevine-cdm-support) tutorial but it didn't work. To work in the Electron-Vite you need to do something different?

### Electron-Vite Version

1.0.17

### Electron Version

21.3.3

### Vite Version

4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
This doesn't seem to have anything to do with electron-vite. 

You should set `webPreferences.plugins` to `true`. Maybe there is an Electron version compatibility issue.
