### ISSUE TITLE
The compiled app does not find the js files?

### ISSUE THREAD

**Issue by MatiasEsf** [alex8088/electron-vite#116]
### Describe the bug

After compiling the windows app, the app is not able to find the scr files, they are supposedly in app.asar but it doesn't read them? what am I doing wrong? I am compiling with the default command:

`"build:win": "electron-builder --win --config"`

![aaaaa](https://user-images.githubusercontent.com/49958478/221088687-20f13ccc-9165-4a11-a425-a9e612bfe6a8.png)

### Electron-Vite Version

1.0.19

### Electron Version

23.1.0

### Vite Version

1.0.19

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
How do you import file. All import modules will be bundle to `out` dir. And the source dir `src` will be excluded when packing.

**Comment by MatiasEsf** [comment]
> How do you import file. All import modules will be bundle to `out` dir. And the source dir `src` will be excluded when packing.

I already resolved it, it was simply a mistake of mayor and minuscules in the files. Years of study and I'm still a noob. Close the issue
