### ISSUE TITLE
静态资源的编译路径问题

### ISSUE THREAD

**Issue by fwjyttbtx** [alex8088/electron-vite#117]
### Describe the bug

outDir被设置后，编译后静态资源的引用地址会变成相对地址加全路径的样式
outDir那怕设置和默认的输出地址`out/main`一致也会出现此现象
![image](https://user-images.githubusercontent.com/6520518/221127445-37c4050c-8578-460a-910c-15f07ec8dfef.png)

### Electron-Vite Version

1.0.19

### Electron Version

23.1.0

### Vite Version

4.1.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
如何引入静态资源？

**Comment by fwjyttbtx** [comment]
使用的文档的`?asset`引入的资源
```ts
import logo from '../../resources/icons/logo.ico?asset';
import logoTemplate from '../../resources/logoTemplate.png?asset';
```
配置如下：
```ts
import { defineConfig } from 'electron-vite';

export default defineConfig(({ mode }) => {
  return {
    main: {
      build: {
        outDir: 'dist/main',
        lib: {
          name: 'mdos',
          entry: 'src/main/index.ts',
        },
      },
    },
})
```

**Comment by fwjyttbtx** [comment]
> 如何引入静态资源？

脚手架下载的项目做配置也会有这样的问题
```ts
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()],
    build: {
      outDir: 'dist/main'
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin()]
  },
  renderer: {}
})
```
![image](https://user-images.githubusercontent.com/6520518/221130719-2c2f2e85-ec38-4ed4-911e-7ea804b3e320.png)

**Comment by alex8088** [comment]
初始化项目是否正常？

**Comment by alex8088** [comment]
可重现这个问题，独立修改某个配置`outDir`，会有此问题。

处理方式有两种：

1. main/preload/renderer 的 outDir 都配置
2. 通过CLI处理 `electron-vite dev/build/preview --outDir=dist`

**Comment by alex8088** [comment]
通常要确保main、preload和renderer都要输出到一个目录中。各项独立配置时需要确保一级目录是一致的即是这里的`dist`, 推荐第二种处理方式， 无效太多配置。此问题待后续版本优化处理。

谢谢反馈问题 🤝

**Comment by fwjyttbtx** [comment]
ok, 感谢解答

**Comment by alex8088** [comment]
@fwjyttbtx 提醒一下，因为electron-builder默认构建输出目录是dist，因此将代码输出目录改为dist时，需要修改electron-builder的输出目录（查阅文档），不然会有冲突，会导致打包包裹上一次打包的文件。

**Comment by fwjyttbtx** [comment]
> @fwjyttbtx 提醒一下，因为electron-builder默认构建输出目录是dist，因此将代码输出目录改为dist时，需要修改electron-builder的输出目录（查阅文档），不然会有冲突，会导致打包包裹上一次打包的文件。

因为改动了构建的输出目录为release所以才会出现这样的问题 :)
