### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by mengdebiao** [alex8088/electron-vite#119]
### Describe the bug

装完依赖之后，始终无法启动项目，
![image](https://user-images.githubusercontent.com/17793848/221808733-cd227a82-ac63-4484-9602-160acdcd4dc9.png)

### Electron-Vite Version

1.0.19

### Electron Version

21.4.2

### Vite Version

4.1.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
electron 没有安装成功，设置一下electron的下载代理： ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/

**Comment by alex8088** [comment]
@mengdebiao 问题是否解决
