### ISSUE TITLE
配置环境变量问题

### ISSUE THREAD

**Issue by NZNB** [alex8088/electron-vite#12]
### Describe the bug

当我添加了一个.env.test环境变了文件，并且打包时将--mode 设置为test，构建安装后，打开应用，静态资源引入到路径全部是错误的，--mode为production时是正常的，如果方便的话希望可以加一下您的微信

### Electron-Vite Version

1.0.7

### Electron Version

17.3.1

### Vite Version

2.9.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
是问题，时候还需要帮助？

**Comment by NZNB** [comment]
已解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 下午5:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alex8088/electron-vite] 配置环境变量问题 (Issue #12)




 
是问题，时候还需要帮助？
