### ISSUE TITLE
求助：如何将使用 BrowserWindow 加载的开屏动画的 静态页面一同构建

### ISSUE THREAD

**Issue by aidenup** [alex8088/electron-vite#120]
### Clear and concise description of the problem

我使用 BrowserWindow 加载一个.html 文件作为开屏页面，但是构建后静态文件没有被一同打包，导致开屏页面丢失。

我尝试过 vite-plugin-static-copy  copy 到renderer 下，但这似乎不是明智的方法。

请问这种情况我该怎样做才能使开屏页面有效。

另外 在开发模式下 我也是使用 esbuild 脚本将开屏页面构建到out/renderer 下，请问是否有更合适的方法
谢谢~

### Suggested solution

null

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
不需要这么复杂，这是多页的场景
1. https://cn-evite.netlify.app/guide/dev.html#%E5%A4%9A%E7%AA%97%E5%8F%A3%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F 参考构建多页
2. https://cn-evite.netlify.app/guide/hmr-in-renderer.html#%E5%9C%A8%E6%B8%B2%E6%9F%93%E8%BF%9B%E7%A8%8B%E4%B8%AD%E4%BD%BF%E7%94%A8-hmr 参考加载页面

**Comment by aidenup** [comment]
谢谢您的回答，问题已经解决 :+1:，刚开始学习，我这部分和文档没有对应起来
