### ISSUE TITLE
auto generate exposeInMainWorld and types for preload export function or value

### ISSUE THREAD

**Issue by subframe7536** [alex8088/electron-vite#121]
### Clear and concise description of the problem

as title, wish to add builtin support

### Suggested solution

like https://github.com/cawa-93/unplugin-auto-expose

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by subframe7536** [comment]
any update?

**Comment by alex8088** [comment]
close with duplicate #141
