### ISSUE TITLE
How to add an application menu

### ISSUE THREAD

**Issue by TheAutomaTom** [alex8088/electron-vite#122]
### Describe the bug

I've tried to add an application menu to this template numerous way, but something seems to override it... even the default menu.  Can you please explain where to insert `electron.Menu` within `src/main/index.ts`?

### Electron-Vite Version

^1.0.19

### Electron Version

^21.3.3

### Vite Version

^4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
```js
import { Menu } form 'electron'

const menuTemp = [
  {
    label: ''
  }
]

const menu = Menu.buildFromTemplate(menuTemp )
Menu.setApplicationMenu(menu)
```

https://www.electronjs.org/zh/docs/latest/api/menu#%E7%A4%BA%E4%BE%8B

**Comment by TheAutomaTom** [comment]
_If this is not the proper repo to bring this issue to, excuse me..._
Following the instructions in your Getting Started section (near the end of these docs):
> Getting Started
> `npm init @quick-start/electron`
Next, install dependencies, build, then run to check it works.  There is no default app menu.
Now, in `src\main\index.ts`, within `app.whenReady().then(() => {` add:
```js
  const template = [
    { id: '1', label: 'one', after: ['3'] },
    { id: '2', label: 'two', before: ['1'] },
    { id: '3', label: 'three' }
  ] as MenuItem[]
  // Add app menu to header.
  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
```
I have tried it before and after the execution of `createWindow()`
I have run the build script before each attempt.

I have had no problem adding the menus when I start from a less robust template.  There are no console or terminal errors.

Any advice?  Thanks.

**Comment by alex8088** [comment]
You should set BrowserWindow `autoHideMenuBar` option to `true`

**Comment by TheAutomaTom** [comment]
Omg, that's the problem, it _IS_ set to true in the template's BrowserWindow constructor.  What an odd choice.  Maybe the template is aiming to emphasize mobile interfaces more.  Thanks for helping sort that out.

**Comment by alishefaee** [comment]
This is my first time using this template and I also have this problem:
OS: ubuntu 20.04
```
  mainWindow = new BrowserWindow({
    minWidth: 1500,
    show: false,
    // autoHideMenuBar: true,
    ...(process.platform === 'linux' ? { icon } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,
      // allowRunningInsecureContent: true,
      // webSecurity: false,
      // contextIsolation: false,
      // nodeIntegration: true
    }
  })
```
```
  "dependencies": {
    "@electron-toolkit/preload": "^2.0.0",
    "@electron-toolkit/utils": "^2.0.0"
  },
  "devDependencies": {
    "@electron-toolkit/tsconfig": "^1.0.1",
    "@types/node": "^18.17.5",
    "@types/prop-types": "^15.7.5",
    "@types/react": "^18.2.20",
    "@types/react-dom": "^18.2.7",
    "@types/react-input-mask": "^3.0.2",
    "@vitejs/plugin-react": "^4.0.4",
    "electron": "^25.6.0",
    "electron-builder": "^24.6.3",
    "electron-vite": "^1.0.27",
    "prettier": "^3.0.2",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-transition-group": "^4.4.5",
    "redux": "^4.2.0",

    "typescript": "^5.1.6",
    "vite": "^4.4.9"
  }
```

**Comment by TheAutomaTom** [comment]
@alishefaee did you set `autoHideMenuBar: true`, like I mentioned above?  There seems to be some poorly crafted verbage in some parts of the API, but I see folks sorting it out:
https://stackoverflow.com/questions/39091964/remove-menubar-from-electron-app

**Comment by alishefaee** [comment]
@TheAutomaTom Yes, I set it to ```false``` and also commented it.
I also created a new project ```npm create @quick-start/electron```. and tried these two commands:
```win.setMenu(null)``` ```Menu.setApplicationMenu(null)``` but didn't work.

**Comment by TheAutomaTom** [comment]
Are you trying to show or hide the menu?

**Comment by alishefaee** [comment]
@TheAutomaTom I want to show them.
