### ISSUE TITLE
After building: Uncaught TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by Konglomneshued** [alex8088/electron-vite#125]
### Describe the bug

I run npm dev script `"dev": "electron-vite dev -w"` and my code is working.  However, if I run the start script `"start": "electron-vite preview"`, I see error:

![image](https://user-images.githubusercontent.com/94726665/222870283-352c3987-e452-48b8-93e7-62e54f1dd72c.png)

![Screenshot from 2023-03-03 20-09-59](https://user-images.githubusercontent.com/94726665/222870318-2dd0b8c5-3aef-43b1-b7d6-89ec20d3ce93.png)

![Screenshot from 2023-03-03 20-10-07](https://user-images.githubusercontent.com/94726665/222870325-794a6662-edb5-4778-b33c-3ac286d824b9.png)

### Electron-Vite Version

^1.0.17

### Electron Version

^21.3.3

### Vite Version

^4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
This looks like a problem with vite. Please provide more details, which may solve your problem

**Comment by Konglomneshued** [comment]
I'm trying to figure out what I need to provide.  The plus icon, which is having the issue, is simply imported as a static asset just like my other icons I use.

![image](https://user-images.githubusercontent.com/94726665/222975486-6d054866-848f-4c58-a0fd-9137680314fa.png)

Here is my Vite config:
```
import { resolve } from 'path';
import { defineConfig, externalizeDepsPlugin } from 'electron-vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
   main: {
      plugins: [ externalizeDepsPlugin() ],
   },
   preload: {
      plugins: [ externalizeDepsPlugin() ],
   },
   renderer: {
      resolve: {
         alias: {
            'renderer': resolve('src/renderer/src'),
            'namespace': resolve('src/renderer/src/namespace.ts'),
            'components': resolve('src/renderer/src/components'),
            'features': resolve('src/renderer/src/features'),
            '@utils': resolve('src/utils'),
            '@globalTypes': resolve('src/types'),
            '@api': resolve('src/api'),
            'types': resolve('src/renderer/src/types'),
            'hooks': resolve('src/renderer/src/hooks'),
         },
      },
      plugins: [ react() ],
   },
});
```

I tried looking for my issue or something similar on the Vite Github issues but no luck.

**Comment by Konglomneshued** [comment]
If I comment out my plus icon import I get the same error with the next icon I import.

**Comment by Konglomneshued** [comment]
### Look at this code [(Link to first comment)](https://github.com/alex8088/electron-vite/issues/125#issue-1609541062):

```
const plusIcon$1 = "" + new URL("plus-98d25721.svg", import.meta.url).href;
const newTabButton = "_newTabButton_1xtnb_1";
const plusIcon = "_plusIcon_1xtnb_15";
const styles$j = {
  newTabButton,
  plusIcon
};
```
![image](https://user-images.githubusercontent.com/94726665/223297603-49abe366-ae1c-4963-a5c4-d8d2acc5b6b1.png)

### This is causing it.
![image](https://user-images.githubusercontent.com/94726665/223297788-8b70d75d-ad74-4552-bc00-f8629bf9866d.png)

**Comment by alex8088** [comment]
`uuid`  is a pure nodejs module,not support renderer.

**Comment by Konglomneshued** [comment]
It works in dev script.

**Comment by alex8088** [comment]
> It works in dev script. And I used it in web apps.

dev mode is nobundle, but pro will be bundled. Remove `uuid` module, it will work.

**Comment by Konglomneshued** [comment]
It supports ECMAScript modules
![image](https://user-images.githubusercontent.com/94726665/223303255-7e45da60-656c-4ddf-a23e-780ccdb8a662.png)

**Comment by Konglomneshued** [comment]
I can try maybe using without library.

**Comment by Konglomneshued** [comment]
Yeah, using v5 from uuid is causing it.  v4 works, though.  That explains why I was able to use it before, as I had never used v5, only v4.
