### ISSUE TITLE
Issues loading external dependency

### ISSUE THREAD

**Issue by korodarn** [alex8088/electron-vite#127]
### Describe the bug

I have written a typescript module for performing queries and such in another folder, and was looking to build a UI to call those functions from electron-vite. 

I'm having a couple of issues.  I'll start with the most pressing as I think maybe the other one is something I can resolve with a simple config change

1) I am using argon2 library to allow pulling passwords from keepass files on users machine, the files containing passwords for the query connectivity.  When attempting to load the argon2 implementation from .node file, I get this error, 
imported by ...JS_Query/node_modules/argon2/argon2.js): The argument 'path' must be a string o Uint8Array without null bytes. Received '\x00\C:/path/to/argon2.node'

I assume the \x00 is the problem. 

The argon2.js module works just fine when I'm running the scripts in the JS_Query folder via command line, and the error occurs during the vite build process, specifically "[vite:node-asset] Could not load ... "

2) The other issue is that if I comment out the argon2/kdbx dependency, I'm using inlineSoucemap on the other project, and I don't know how to switch electron-vite to use inlineSourcemap so it doesn't error out for that as well.  It was giving me errors about missing .map files but with inline those won't exist. I think probably just switching from inline to regular sourcemap on the other project would fix, but with electron-vite I couldn't figure out how to enable inline if I wanted to go that route instead.  

### Electron-Vite Version

1.0.17

### Electron Version

21.3.3

### Vite Version

4.1.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
install  `argon2` in `dependences` and use `externalizeDepPlugin`, it will externalize argon2
