### ISSUE TITLE
m1 mac 启动 dev 模式报错Electron uninstall

### ISSUE THREAD

**Issue by longqi0** [alex8088/electron-vite#129]
### Describe the bug

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
error during start dev server and electron app:
Error: Electron uninstall
    at getElectronPath (/Users/long/project/tools-electron/node_modules/.pnpm/electron-vite@1.0.19_vite@4.1.4/node_modules/electron-vite/dist/chunks/lib-ddb42891.js:68:19)
    at Object.startElectron (/Users/long/project/tools-electron/node_modules/.pnpm/electron-vite@1.0.19_vite@4.1.4/node_modules/electron-vite/dist/chunks/lib-ddb42891.js:123:26)
    at createServer (/Users/long/project/tools-electron/node_modules/.pnpm/electron-vite@1.0.19_vite@4.1.4/node_modules/electron-vite/dist/chunks/lib-b694cd80.js:75:21)
    at async CAC.<anonymous> (/Users/long/project/tools-electron/node_modules/.pnpm/electron-vite@1.0.19_vite@4.1.4/node_modules/electron-vite/dist/cli.js:47:9)
 ELIFECYCLE  Command failed with exit code 1.

### Electron-Vite Version

1.0.17

### Electron Version

21.4.2

### Vite Version

4.1.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@longqi0 问题是否解决

**Comment by longqi0** [comment]
node_modules中有electron
![Uploading image.png…]()

**Comment by longqi0** [comment]
node_modules中有electron
![iShot_2023-03-12_20 50 47](https://user-images.githubusercontent.com/118588863/224545840-193d370f-dde7-4bfe-bc1b-14c962c2d19c.jpg)

**Comment by alex8088** [comment]
有包不等于下载成功，electron安装完成后会执行postinstall下载electron可执行程序，下载完成后electron目录下会有dist目录，目录中有相对应程序

**Comment by alex8088** [comment]
这是electron开发常见问题，有梯子可能好点，你可以添加一个.npmrc文件内容ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/，删除node_module重新安装

**Comment by alex8088** [comment]
重新用脚手架创建，最后选项启用下载代理也会自动生成rc文件

**Comment by longqi0** [comment]
我在创建时勾选了启用代理，项目中也存在rc文件
再次执行postinstall和pnpm install也是正常的，但启动时还是异常

**Comment by alex8088** [comment]
node_module/electron/dist下有electron.app ? 如果没有就安装成功，pnpm下一次没有安装成功比较麻烦，后续安装该版本都不成功，可以查一下pnpm如何清理缓存

**Comment by longqi0** [comment]
我再尝试一下

**Comment by alex8088** [comment]
你可以改其他版本electron再安装，或者用npm

**Comment by HondryTravis** [comment]
有点强啊

**Comment by Songmengdi** [comment]
另一种情况是忽略的包内的脚步预下载设置,需要修改npm或者yarn的设置
yarn config set ignore-scripts false

**Comment by wenxb** [comment]
我找到了一个解决办法：
1. 首先 `npm instal`或者`yarn install`
2. 执行 `npm install electron-fix -g`
3. 接着 `electron-fix start`

**Comment by 1940879828** [comment]
我试了上面的解决办法 `pnpm install electron-fix -g` 
然后使用 `electron-fix start` 出现了报错：
exec error: Error: Command failed: unzip -o C:\Users\admin\AppData\Local\Temp\electron-v31.0.2-win32-x64.zip -d D:\WorkSpace\My\Electron\electron-app2\node_modules\electron\dist
只要把这句命令手动完成就行了。
报错信息意思是`node_modules\electron\`路径下少了dist文件夹，只要把这个修复库下载的内容解压到dist下就可以启动项目了

**Comment by 1940879828** [comment]
我发现了真正的原因！是node版本不匹配！，`node` 版本：20->18.20.1 。

**Comment by godcop** [comment]
我是windows11系统，pnpm版本10.3.0，运行pnpm create @quick-start/electron electron-vite --template vue创建的项目

PS D:\code-demo\electron-vite> pnpm install
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing pnpm@10.3.0+sha512.ee592eda8815a8a293c206bb0917c4bb0ff274c50def7cbc17be05ec641fc2d1b02490ce660061356bd0d126a4d7eb2ec8830e6959fb8a447571c631d5a2442d.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager

 WARN  deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
 WARN  7 deprecated subdependencies found: @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3, boolean@3.2.0, glob@7.2.3, inflight@1.0.6, lodash.isequal@4.5.0, rimraf@3.0.2
Packages: +441
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 496, reused 451, downloaded 2, added 441, done

> electron-vite@1.0.0 postinstall D:\code-demo\electron-vite
> electron-builder install-app-deps

  • electron-builder  version=24.13.3
  • loaded configuration  file=D:\code-demo\electron-vite\electron-builder.yml

dependencies:
+ @electron-toolkit/preload 3.0.1
+ @electron-toolkit/utils 3.0.0 (4.0.0 is available)
+ electron-updater 6.3.9

devDependencies:
+ @electron-toolkit/eslint-config 1.0.2
+ @electron-toolkit/eslint-config-ts 2.0.0
+ @electron-toolkit/tsconfig 1.0.1
+ @rushstack/eslint-patch 1.10.5
+ @types/node 20.17.18 (22.13.2 is available)
+ @vitejs/plugin-vue 5.2.1
+ @vue/eslint-config-prettier 9.0.0 (10.2.0 is available)
+ @vue/eslint-config-typescript 13.0.0 (14.4.0 is available)
+ electron 31.7.7 (34.1.1 is available)
+ electron-builder 24.13.3 (25.1.8 is available)
+ electron-vite 2.3.0
+ eslint 8.57.1 (9.20.1 is available) deprecated
+ eslint-plugin-vue 9.32.0
+ prettier 3.5.0
+ typescript 5.7.3
+ vite 5.4.14 (6.1.0 is available)
+ vue 3.5.13
+ vue-tsc 2.2.0

╭ Warning ───────────────────────────────────────────────────────────────────────────────────╮
│                                                                                            │
│   Ignored build scripts: electron, esbuild.                                                │
│   Run "pnpm approve-builds" to pick which dependencies should be allowed to run scripts.   │
│                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────╯

Done in 8.3s

然后运行pnpm dev后报错：
PS D:\code-demo\electron-vite> pnpm dev

> electron-vite@1.0.0 dev D:\code-demo\electron-vite
> electron-vite dev

vite v5.4.14 building SSR bundle for development...
✓ 2 modules transformed.
out/main/index.js  1.48 kB
✓ built in 108ms

build the electron main process successfully

-----

vite v5.4.14 building SSR bundle for development...
✓ 1 modules transformed.
out/preload/index.js  0.42 kB
✓ built in 15ms

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
error during start dev server and electron app:
Error: Electron uninstall
    at getElectronPath (file:///D:/code-demo/electron-vite/node_modules/.pnpm/electron-vite@2.3.0_vite@5.4.14_@types+node@20.17.18_/node_modules/electron-vite/dist/chunks/lib-BmEkZIgk.mjs:129:19)
    at startElectron (file:///D:/code-demo/electron-vite/node_modules/.pnpm/electron-vite@2.3.0_vite@5.4.14_@types+node@20.17.18_/node_modules/electron-vite/dist/chunks/lib-BmEkZIgk.mjs:198:26)
    at createServer (file:///D:/code-demo/electron-vite/node_modules/.pnpm/electron-vite@2.3.0_vite@5.4.14_@types+node@20.17.18_/node_modules/electron-vite/dist/chunks/lib-t2ExBjL5.mjs:74:14)
    at async CAC.<anonymous> (file:///D:/code-demo/electron-vite/node_modules/.pnpm/electron-vite@2.3.0_vite@5.4.14_@types+node@20.17.18_/node_modules/electron-vite/dist/cli.mjs:67:9)
 ELIFECYCLE  Command failed with exit code 1.

根据提示运行pnpm approve-builds后会在packages.json中添加：
  "packageManager": "pnpm@10.3.0+sha512.ee592eda8815a8a293c206……",
  "pnpm": {
    "ignoredBuiltDependencies": [
      "electron",
      "esbuild"
    ]
  }
再执行pnpm install和pnpm dev仍然报错。查了下资料是因为pnpm10版本以后新的安全机制导致的，将pnpm改为9.15.5版本后重新走一套流程就没问题了。但是如何做才能继续用最新的pnpm版本呢？

**Comment by zhangzhi93** [comment]
> 我是windows11系统，pnpm版本10.3.0，运行pnpm create @quick-start/electron electron-vite --template vue创建的项目
> 
> PS D:\code-demo\electron-vite> pnpm install ! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing pnpm@10.3.0+sha512.ee592eda8815a8a293c206bb0917c4bb0ff274c50def7cbc17be05ec641fc2d1b02490ce660061356bd0d126a4d7eb2ec8830e6959fb8a447571c631d5a2442d. ! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
> 
>  WARN  deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.  WARN  7 deprecated subdependencies found: @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3, boolean@3.2.0, glob@7.2.3, inflight@1.0.6, lodash.isequal@4.5.0, rimraf@3.0.2 Packages: +441 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ Progress: resolved 496, reused 451, downloaded 2, added 441, done
> 
> > electron-vite@1.0.0 postinstall D:\code-demo\electron-vite
> > electron-builder install-app-deps
> 
> • electron-builder version=24.13.3 • loaded configuration file=D:\code-demo\electron-vite\electron-builder.yml
> 
> dependencies:
> 
> * @electron-toolkit/preload 3.0.1
> * @electron-toolkit/utils 3.0.0 (4.0.0 is available)
> * electron-updater 6.3.9
> 
> devDependencies:
> 
> * @electron-toolkit/eslint-config 1.0.2
> * @electron-toolkit/eslint-config-ts 2.0.0
> * @electron-toolkit/tsconfig 1.0.1
> * @rushstack/eslint-patch 1.10.5
> * @types/node 20.17.18 (22.13.2 is available)
> * @vitejs/plugin-vue 5.2.1
> * @vue/eslint-config-prettier 9.0.0 (10.2.0 is available)
> * @vue/eslint-config-typescript 13.0.0 (14.4.0 is available)
> * electron 31.7.7 (34.1.1 is available)
> * electron-builder 24.13.3 (25.1.8 is available)
> * electron-vite 2.3.0
> * eslint 8.57.1 (9.20.1 is available) deprecated
> * eslint-plugin-vue 9.32.0
> * prettier 3.5.0
> * typescript 5.7.3
> * vite 5.4.14 (6.1.0 is available)
> * vue 3.5.13
> * vue-tsc 2.2.0
> 
> ╭ Warning ───────────────────────────────────────────────────────────────────────────────────╮ │ │ │ Ignored build scripts: electron, esbuild. │ │ Run "pnpm approve-builds" to pick which dependencies should be allowed to run scripts. │ │ │ ╰────────────────────────────────────────────────────────────────────────────────────────────╯
> 
> Done in 8.3s
> 
> 然后运行pnpm dev后报错： PS D:\code-demo\electron-vite> pnpm dev
> 
> > electron-vite@1.0.0 dev D:\code-demo\electron-vite
> > electron-vite dev
> 
> vite v5.4.14 building SSR bundle for development... ✓ 2 modules transformed. out/main/index.js 1.48 kB ✓ built in 108ms
> 
> build the electron main process successfully
> 
> vite v5.4.14 building SSR bundle for development... ✓ 1 modules transformed. out/preload/index.js 0.42 kB ✓ built in 15ms
> 
> build the electron preload files successfully
> 
> dev server running for the electron renderer process at:
> 
> ➜ Local: http://localhost:5173/ ➜ Network: use --host to expose error during start dev server 和 electron app: Error: Electron uninstall at getElectronPath (file:///D:/code-demo/electron-vite/node_modules/.pnpm/electron-vite@2.3.0_vite@[5.4.14_@types](mailto:5.4.14_@types)+node@20.17.18_/node_modules/electron-vite/dist/chunks/lib-BmEkZIgk.mjs:129:19) at startElectron (file:///D:/code-demo/electron-vite/node_modules/.pnpm/electron-vite@2.3.0_vite@[5.4.14_@types](mailto:5.4.14_@types)+node@20.17.18_/node_modules/electron-vite/dist/chunks/lib-BmEkZIgk.mjs:198:26) at createServer (file:///D:/code-demo/electron-vite/node_modules/.pnpm/electron-vite@2.3.0_vite@[5.4.14_@types](mailto:5.4.14_@types)+node@20.17.18_/node_modules/electron-vite/dist/chunks/lib-t2ExBjL5.mjs:74:14) at async CAC. (file:///D:/code-demo/electron-vite/node_modules/.pnpm/electron-vite@2.3.0_vite@[5.4.14_@types](mailto:5.4.14_@types)+node@20.17.18_/node_modules/electron-vite/dist/cli.mjs:67:9)  ELIFECYCLE  Command failed with exit code 1.
> 
> 根据提示运行pnpm approve-builds后会在packages.json中添加： "packageManager": "pnpm@10.3.0+sha512.ee592eda8815a8a293c206……", "pnpm": { "ignoredBuiltDependencies": [ "electron", "esbuild" ] } 再执行pnpm install和pnpm dev仍然报错。查了下资料是因为pnpm10版本以后新的安全机制导致的，将pnpm改为9.15.5版本后重新走一套流程就没问题了。但是如何做才能继续用最新的pnpm版本呢？

遇到了同样的问题，用新的pnpm安装之后，运行报错

**Comment by Your-Ehsan** [comment]
I am using pnpm and i solved this by 
```json
  "pnpm": {
    "onlyBuiltDependencies": [
      "electron",
      "esbuild"
    ]
  }
```
in `package.json` file

**Comment by arvinxx** [comment]
@Your-Ehsan Thanks! It works for me.

**Comment by Your-Ehsan** [comment]
> [@Your-Ehsan](https://github.com/Your-Ehsan) Thanks! It works for me.

😄 Glad to hear.

**Comment by AbrahamJulian** [comment]
Thanks it works for mac arm as well

> I am using pnpm and i solved this by
> 
>   "pnpm": {
>     "onlyBuiltDependencies": [
>       "electron",
>       "esbuild"
>     ]
>   }
> in `package.json` file

**Comment by fudjet** [comment]
看下是否提示这个

![Image](https://github.com/user-attachments/assets/3864644c-3c8e-4c0e-a9c8-47699000ef8b)

1. 执行 `pnpm approve-builds`
2. 按`a`全选
3. 按`y`，
pnpm 才会执行 electron 的安装脚本

![Image](https://github.com/user-attachments/assets/d7cc693c-3cee-48c6-8b9d-e8197226398d)

**Comment by smilecc** [comment]
> 1. pnpm approve-builds

work for me, thank u

**Comment by firework-a** [comment]
The problem in this issuse maybe caused by  `pnpm` ,as we all know, `pnpm` dependencies are managed in the way of content addressing storage+symbolic links. Dependencies are stored in the global cache. Only symbolic links exist in the node_modules of the project. This structure isolates the dependency range of the package more strictly, which may cause some compilation scripts to fail to find dependencies or access system resources correctly, thus skipping the compilation step. Which may not execute the postinstall hook to build the exe file in dist folder.

So to avoid happen this question,we should use `npm install` instead of `pnpm install`.
