### ISSUE TITLE
How to debug electron renderer

### ISSUE THREAD

**Issue by lionelhorn** [alex8088/electron-vite#130]
### Describe the bug

Hello, 

I've seen https://github.com/alex8088/electron-vite/issues/19 but it's related to debugging the main process.

I'm trying to debug the renderer process from webstorm.

I've used `pnpm create @quick-start/electron` to scaffold my project.
I managed to set breakpoint in the node side of the application and it works properly from within webstorm with the following configuration.
![image](https://user-images.githubusercontent.com/50528276/224375568-5d717131-7573-4d5e-b9b7-92e21472f11d.png)

For instance on 
![image](https://user-images.githubusercontent.com/50528276/224375149-1c17f4c8-6f0c-4c71-9ff2-56982fca752f.png)

But i'm not able to get breakpoints to break on for instance.
![image](https://user-images.githubusercontent.com/50528276/224374902-1dff762e-f45d-4598-9f75-b6a13ee21b2b.png)

How can it be configured?

### Electron-Vite Version

1.0.17

### Electron Version

21.3.3

### Vite Version

4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@lionelhorn 
Renderer process debugging is currently not supported, but a solution has been found and will be supported in the next version. It won't take long.

**Comment by alex8088** [comment]
new ver 1.0.20 is out! check out https://evite.netlify.app/guide/debugging.html#webstorm

**Comment by alex8088** [comment]
重新用脚手架创建，最后选项启用下载代理也会自动生成rc文件

**Comment by vacnex** [comment]
@alex8088 
Just see new launch.json, if i have sub folder in renderer so i need create new config with diff port and path to view for new render process, then put new one to configurations in compound?
correct me if i wrong

**Comment by alex8088** [comment]
Usually specifying the root of the renderer process code is fine.

**Comment by alex8088** [comment]
https://user-images.githubusercontent.com/25053004/224887324-a9d8c612-4e60-469c-b3e6-37aa81312ce9.mp4
