### ISSUE TITLE
White screen when config Multiple Windows App

### ISSUE THREAD

**Issue by vacnex** [alex8088/electron-vite#131]
### Describe the bug

Hi I'm having trouble configuring multiple Windows apps
specifically I got a white screen when running the application, localhost is also not accessible
View folder structure
![image](https://user-images.githubusercontent.com/37587399/224415479-eb807ea7-e1e0-4bbc-96b5-4bfb4ecad51d.png)
electron.vite.config
![image](https://user-images.githubusercontent.com/37587399/224417735-11affe99-46e0-415b-b8e3-693832079eba.png)

tsconfig.node
![image](https://user-images.githubusercontent.com/37587399/224415594-c858be40-637f-4c3a-8dfc-6290bfa57e40.png)
tsconfig.web
![image](https://user-images.githubusercontent.com/37587399/224415645-3fea7663-a8e2-4fb1-ba55-4b79c06d05e0.png)
createMainWindows
![image](https://user-images.githubusercontent.com/37587399/224415793-152dc16f-3e97-4175-a507-902df7e887dd.png)
i had to used mainWindow.loadFile because ELECTRON_RENDERER_URL localhost not up
result when run app
![image](https://user-images.githubusercontent.com/37587399/224418388-bcc426f4-6a0c-44e2-8db2-b064e3a4f4ad.png)

maybe i had wrong config Multiple Windows App.
Thank for help

### Electron-Vite Version

1.0.14

### Electron Version

21.3.0

### Vite Version

3.2.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Learn more https://evite.netlify.app/guide/hmr-in-renderer.html

You have defined a new output name `browser`.  And you can check the output under `out/renderer`, then you will understand

```js
if (!app.isPackaged && process.env['ELECTRON_RENDERER_URL']) {
  mainWindow.loadURL(`${process.env['ELECTRON_RENDERER_URL']}/browser.html`)
} else {
  mainWindow.loadFile(path.join(__dirname, '../renderer/browser.html'))
}
```

**Comment by vacnex** [comment]
> 

thank for reply, I had added name like this
![image](https://user-images.githubusercontent.com/37587399/224462590-436cafac-f24f-4d36-813d-1c7529f071a1.png)
and edit rollupOptions like this
![image](https://user-images.githubusercontent.com/37587399/224462611-0c909410-93a8-45df-9c0f-26776aa359a2.png)
I also restructured the directory as follows
![image](https://user-images.githubusercontent.com/37587399/224462677-92831ad1-fd2d-4a22-a8d0-f276940227b6.png)
then i still got white screen
![image](https://user-images.githubusercontent.com/37587399/224462756-1670f830-486f-4279-b7d8-4076ebb2c1b2.png)

**Comment by alex8088** [comment]
subdir for renderer: 

```js
if (!app.isPackaged && process.env['ELECTRON_RENDERER_URL']) {
  mainWindow.loadURL(`${process.env['ELECTRON_RENDERER_URL']}/MainWindows/index.html`)
} else {
  mainWindow.loadFile(path.join(__dirname, '../renderer/MainWindows/index.html'))
}
```

**Comment by alex8088** [comment]
You can run the preview command  to view the output files

**Comment by vacnex** [comment]
> You can run the preview command to view the output files

thank you so much, it worked!!!

I just want to ask more that my app is organized as follows
http://127.0.0.1:5173/MainWindows/index.html
and
http://127.0.0.1:5173/Page/settings/index.html
is there any solution using http://127.0.0.1:5173/ instead of http://127.0.0.1:5173/MainWindows/index.html
main page?
i think i will take the src and index.html folder out of mainwindows folder, set the same level as page folder?

**Comment by alex8088** [comment]
According to vite's design, `index.html` needs to be placed in the renderer directory (root).

```
└──renderer
  ├──src 
  ├──index.html
  ├──one.html
  ├──two.html
  └──...
```

http://127.0.0.1:5173/  index.html by default. Other page like `http://127.0.0.1:5173/one.html`
