### ISSUE TITLE
在控制台输出的日志显示行号

### ISSUE THREAD

**Issue by zzzZZZ1117** [alex8088/electron-vite#132]
### Clear and concise description of the problem

在控制台输出的日志无法看出对应行号列号

### Suggested solution

1.补全功能。
2.开发插件。
3.添加配置。

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
感谢你提出的建议，这个体验需求在IDE中实现可能更为合理，electron-vite目前更专注于代码构建和快速简洁的DX，这个需求暂不考虑。
