### ISSUE TITLE
如何解决第三方依赖中存在require

### ISSUE THREAD

**Issue by jiangjunfeng98** [alex8088/electron-vite#134]
### Describe the bug

你好！我在electron node 引入了exceljs，exceljs里面存在require，electron-vite构建时不会构建cjs，导致build后运行时缺少对应的依赖。请问这种有解决方式吗？

关键信息：

```js
// src/main/file.js
import ExcelJS from 'exceljs'

// exceljs/utils/stream-buf.js
const {.PassThrough } = require('readable-stream');
```
![image](https://user-images.githubusercontent.com/12987428/225205656-72d92cb0-f242-40c8-802f-8d16b0fa5263.png)

### Electron-Vite Version

1.0.17

### Electron Version

21.3.3

### Vite Version

4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
cjs模块无需构建，安装在deps，插件externalizedepplugin会自动排除
https://cn-evite.netlify.app/guide/dev.html#dependencies-vs-devdependencies

**Comment by jiangjunfeng98** [comment]
感谢，在 `externalizeDepsPlugin` 添加 `exceljs`后就正常了！！这种第三方包中含有require的依赖都需要这样处理吗？

**Comment by alex8088** [comment]
取决于引用依赖模块支持模块标准，通常会支持cjs和esm，对于支持esm的模块需要让vite重新去构建它，构建成cjs标准以支持electron。上面的连接做详细的解释。

**Comment by alex8088** [comment]
安装在deps就好

**Comment by jiangjunfeng98** [comment]
是安装在dep的，这个是 exceljs 的 dep依赖



![image](https://user-images.githubusercontent.com/12987428/227513028-8ca7bb36-72c6-4c3a-8f5b-26d73d2718af.png)

![image](https://user-images.githubusercontent.com/12987428/227512973-223034da-8518-4cea-94b5-cab6f17278ef.png)

**Comment by alex8088** [comment]
这个问题不于excel，在于electron-builder打包时，一些模块没有一并打包，是否使用pnpm

**Comment by jiangjunfeng98** [comment]
找到问题了，的确是pnpm的原因
