### ISSUE TITLE
build:win安装后空白页面

### ISSUE THREAD

**Issue by liyangyangi** [alex8088/electron-vite#135]
### Describe the bug

electron-vite  用了vue模板创建后 加了 router路由 hash模式， build:win 后安装空白页有人碰到过吗

### Electron-Vite Version

1.0.17

### Electron Version

21.3.3

### Vite Version

4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by liyangyangi** [comment]
问题解决了 要在后面配置 hash 参数
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'), { hash: 'home' })

**Comment by 027xiguapi** [comment]
我也有这样的问题，我试了上面的方法也不行，我使用的是"react-router-dom": "^6.11.1",

**Comment by alex8088** [comment]
> 我也有这样的问题，我试了上面的方法也不行，我使用的是"react-router-dom": "^6.11.1",

https://cn.electron-vite.org/guide/troubleshooting.html#vue-router-%E6%88%96-react-router-dom-%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E6%AD%A3%E5%B8%B8%EF%BC%8C%E4%BD%86%E5%9C%A8%E6%9E%84%E5%BB%BA%E5%90%8E%E6%97%A0%E6%95%88

**Comment by 027xiguapi** [comment]
我试了还是不行

**Comment by alex8088** [comment]
> 我试了还是不行

是否是 `HashRouter`

按照 [故障排除](https://cn.electron-vite.org/guide/troubleshooting.html#%E6%8A%80%E5%B7%A7) 章节 技巧指引， 逐步排除原因

**Comment by 027xiguapi** [comment]
> > 我试了还是不行
> 
> 是否是 `HashRouter`
> 
> 按照 [故障排除](https://cn.electron-vite.org/guide/troubleshooting.html#%E6%8A%80%E5%B7%A7) 章节 技巧指引， 逐步排除原因

是的，我已经解决了，代码如下：
win.loadFile(path.join(__dirname, '../renderer/index.html'), { hash: '/home' })

**Comment by Formsoftware** [comment]
> > > 我试了还是不行
> > 
> > 
> > 是否是 `HashRouter`
> > 按照 [故障排除](https://cn.electron-vite.org/guide/troubleshooting.html#%E6%8A%80%E5%B7%A7) 章节 技巧指引， 逐步排除原因
> 
> 是的，我已经解决了，代码如下： win.loadFile(path.join(__dirname, '../renderer/index.html'), { hash: '/home' })

牛啊bro，我整了一天没解决，我还纳闷呢怎么各种方法都试了还是不行。你是怎么想打前面加了个“/”的哈哈

**Comment by 027xiguapi** [comment]
还有问题可以参考我的项目：https://github.com/027xiguapi/pear-rec  😀

**Comment by wusp1994** [comment]
解决了，为什么，模板本身的代码就有这个问题。。。。

**Comment by alex8088** [comment]
这和模板没有关系，如何在electron中使用router的问题

> 解决了，为什么，模板本身的代码就有这个问题。。。。

**Comment by zmm2tysu** [comment]
借个楼，如果上述都没有解决你的问题同时你使用了Outlet，请检查你的rollup版本，特别如果是4.16版本会造成outlet对应的路由空白的bug。
详见：
https://github.com/remix-run/react-router/issues/11480

**Comment by zmm2tysu** [comment]
借个楼，如果上述都没有解决你的问题同时你使用了Outlet，请检查你的rollup版本，特别如果是4.16版本会造成outlet对应的路由空白的bug。
详见：
remix-run/react-router#11480
