### ISSUE TITLE
开发的时候希望可以增加命令行参数   

### ISSUE THREAD

**Issue by liu1435533520** [alex8088/electron-vite#136]
### Clear and concise description of the problem

开发的时候启动electron无法给程序增加参数

### Suggested solution

开发的时候启动electron无法给程序增加参数

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Electron 有非常多的命令行参数，通过CLI来支持并不太友好：

1. 非常多参数，逐一实现不太现实
2. 不同版本Electron支持的不一样
3. 可能追加新的参数
4. 也可能breaking一些参数

如何附加electron命令行参数，可通过 `app.commandLine.appendSwitch` 附加， 参照https://www.electronjs.org/docs/latest/api/command-line-switches。

同时，可能利用[环境变量和模式](https://cn-evite.netlify.app/guide/env-and-mode.html)，灵活控制附加：

```ts
import { app } from 'electron'
if (import.meta.env.MAIN_VITE_LOG === 'true') {
  app.commandLine.appendSwitch('enable-logging', 'electron_debug.log')
}

app.whenReady().then(() => {
  // 在这里写入你的代码
})
```

**Comment by liu1435533520** [comment]
开发阶段想给process. argv 增加参数   但是运行 npm  run dev 就没法加参数   运行的是 "electron-vite dev", 后面加的参数都是electron-vite 的参数。   “electron .  --devtool” 这样加参数打包后 可以使用  "electron.exe --devtool" 启动程序  。在electron-vite里面怎么处理呢？

**Comment by alex8088** [comment]
> 开发阶段想给process. argv 增加参数 但是运行 npm run dev 就没法加参数 运行的是 "electron-vite dev", 后面加的参数都是electron-vite 的参数。 “electron . --devtool” 这样加参数打包后 可以使用 "electron.exe --devtool" 启动程序 。在electron-vite里面怎么处理呢？

建议通过环境变量来处理

```ts
const devtool = import.meta.env.MAIN_DEV_TOOL === 'true' || /--devtool/.test(process.argv[2])
```
开发阶段通过 ` import.meta.env` 识别处理，生产阶段通过 `process.argv` 识别处理
