### ISSUE TITLE
终端命令行停止后，electron程序未自动退出

### ISSUE THREAD

**Issue by dupingwei** [alex8088/electron-vite#137]
### Describe the bug

当我停止命令后，electron程序不会自动退出，窗口+docker都存在
<img width="801" alt="image" src="https://user-images.githubusercontent.com/26299159/228121265-87c35e81-1e56-45b3-a538-0fae58c5cda6.png">

### Electron-Vite Version

1.0.20

### Electron Version

22.3.3

### Vite Version

4.1.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
在macos中

```ts
// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```

**Comment by dupingwei** [comment]
> 在macos中
> 
> ```ts
> // Quit when all windows are closed, except on macOS. There, it's common
> // for applications and their menu bar to stay active until the user quits
> // explicitly with Cmd + Q.
> app.on('window-all-closed', () => {
>   if (process.platform !== 'darwin') {
>     app.quit()
>   }
> })
> ```
不是这个原因，我有上述代码，录屏如下
![iShot_2023-03-28_17 14 50](https://user-images.githubusercontent.com/26299159/228189427-4dfc19a2-c232-45ae-9b53-a70be344dcb4.gif)

**Comment by alex8088** [comment]
就是上述代码控制的，这是Mac OS软件通常的设计，不想就可以去掉

**Comment by dupingwei** [comment]
> 就是上述代码控制的，这是Mac OS软件通常的设计，不想就可以去掉 Quit when all windows are closed, except on macOS. There, it's common for applications and their menu bar to stay active until the user quits explicitly with Cmd + Q.

跟上面的无关。

是终端结束后，通过spawn启动的子进程并未结束的原因。
因为我发现下面代码并未执行
https://github.com/alex8088/electron-vite/blob/3a69fbf4895842de0b617d3989f02d19d38d165a/src/electron.ts#L129

参考 https://nodejs.cn/api/child_process.html#optionsdetached 的介绍，感觉这个情况不会发生。
但是确实发生了，原因还不太清楚

**Comment by rico0808** [comment]
退出时子进程杀死了吗，没杀死退出不掉的。

**Comment by alex8088** [comment]
> 感觉这个情况不会发

有可能被vite devserver 拦截，待研究看看

**Comment by xzifan** [comment]
我遇到了同样的问题。是window上存在close监听，并且使用了e.preventDefault阻止了窗口关闭造成的。
![image](https://github.com/alex8088/electron-vite/assets/34232484/80831fc6-7f8f-465e-9d0d-822c3b08fe41)

但是app before-quit事件可以正常触发，可以尝试增加如下代码。
```js
  app.once('window-all-closed', app.quit);
  app.once('before-quit', () => {
    const windows = BrowserWindow.getAllWindows();
    windows.forEach(win => win.removeAllListeners('close'));
  });
```

**Comment by xzifan** [comment]
https://github.com/electron/electron/issues/2312#issuecomment-153966902
