### ISSUE TITLE
静态文件引入问题

### ISSUE THREAD

**Issue by kekekezi** [alex8088/electron-vite#14]
### Describe the bug

我在根目录下创建了public 文件 再渲染进程读取这个文件 本地是没有问题的 但是打包以后 这个路径就改变了 我的理解这个应该会被打包 但是大暴出来的文件里面没有

### Electron-Vite Version

^1.0.7

### Electron Version

^1.0.7

### Vite Version

^3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
你 在打包前是否先 执行 electron-vite build，你在打包前可以看看  out 目录是否有文件

**Comment by alex8088** [comment]
问题是否解决？

**Comment by kekekezi** [comment]
> 

electron-vite build 我尝试了这个命令不能执行

**Comment by kekekezi** [comment]
我的理解是 
不管本地还是打包以后 最外层的public都应该通过“/public”就能取到里面的文件 但是好像取不到

**Comment by alex8088** [comment]
你的public是的给renderer用的吗？不了解你的项目结构。

如果是脚手架构建的项目，renderer的public资源应该放在src/renderer（electron-vite 中renderer的工作目录）中。

还有直接运行需要加 npx electron-vite build， 不加则可以在 npm scripts 加

**Comment by kekekezi** [comment]
不是给render用的 就src下三个进程都可以访问的

**Comment by alex8088** [comment]
nothing can help

**Comment by ZQun** [comment]
@alex8088

**Comment by ZQun** [comment]
@alex8088 你好，我使用的electron-vite@1.0.9版本，添加静态文件src/renderer/src/assets/public/demo.png，或者src/renderer/src/public/demo.png，执行npm run build之后，在out目录中没有找到public静态资源

**Comment by aidenup** [comment]
> @alex8088 你好，我使用的electron-vite@1.0.9版本，添加静态文件src/renderer/src/assets/public/demo.png，或者src/renderer/src/public/demo.png，执行npm run build之后，在out目录中没有找到public静态资源

构建后的静态资源可能被转换成了base64码，你可以使用`electron-vite preview`命令启动后查看开发者工具。如果页面中没有显示静态资源并且控制台报有安全策略相关错误，可能是因为你index.html 中的meta 配置错误导致。
