### ISSUE TITLE
使用webview标签时试了各种路径始终没办法导入preload

### ISSUE THREAD

**Issue by ForceBoot** [alex8088/electron-vite#140]
### Describe the bug

`    
<webview id="webview" src="https://www.baidu.com" preload="file://./webview.js" />
`
使用webview标签时试了各种路径始终没办法导入preload，webview.js放在和App.vue同级目录，我是一个后端刚接触前端感觉可能放错了也或者写错了，搜索了之前的问题找到 #107 但是试了下并没有解决我的问题，在这里卡住了，望指点

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@ForceBoot 可通过窗口的`webContent` 的 `will-attach-webview` 事件在 给 `webview` 的 `webPreferences` 指定 `preload` 赋值方式 和 `browserWindow` 一样处理，这是最简单的方式，详细看一下electron的相关文档

**Comment by ForceBoot** [comment]
关键我在开发环境，不管是相对路径还是放到public下，打包也不可以打包进去，引用相对路径也不可以引用到文件，求助下

`
    <webview id="webview" src="https://www.baidu.com"
        useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
        preload="file://./webview-preload.js" />
`
也不清楚应该把webview-preload.js文件放在哪里才能访问到

**Comment by alex8088** [comment]
https://cn-evite.netlify.app/guide/dev.html#%E5%A4%9A%E7%AA%97%E5%8F%A3%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F 参考多窗口的

**Comment by ForceBoot** [comment]
最后打扰下吧，不行我就先放弃了，我按照您的方法成功加载了html文件，但是preload还是加载不上(绝对路径可以)，然后打包后的exe文件连html都没有显示，我把完整代码发出来，毕竟不是前端开发人员可能问的问题有点low多有打扰哈
`
//electron.vite.config.js
import { resolve } from 'path'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          webview: resolve(__dirname, 'src/preload/webview.js')
        }
      }
    }
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },
    build: {
      rollupOptions: {
        input: {
          webview: resolve(__dirname, 'src/renderer/webview.html')
        }
      }
    },
    plugins: [vue({
        template: {
            compilerOptions: {
                isCustomElement: tag => tag.startsWith('webview')
            }
        }
    })]
  }
})

`
App.vue文件如下
`
<script setup>
import startUrl from '../webview.html?url'
let webviewUrl = "file://../preload/webview.js"  //这里的路径试了各种路径无效
console.log(webviewUrl)
</script>
<template>
    <webview id="webview" :src="startUrl"
        useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
        :preload="webviewUrl" />
</template>
<style lang="less">
@import './assets/css/styles.less';
</style>

`

**Comment by alex8088** [comment]
在主进程所在的窗口中附加：

```ts
  mainWindow.webContents.on('will-attach-webview', (_, webpreferences) => {
    webpreferences.preload = join(__dirname, '../preload/webview.js')
  })
```
