### ISSUE TITLE
引入了这个monacoEditorPlugin ，打包报错 好像是目录不对 

### ISSUE THREAD

**Issue by NightMingGit** [alex8088/electron-vite#144]
### Describe the bug

![image](https://user-images.githubusercontent.com/92633021/231691588-c849eaa2-c542-4f36-9ce0-301954e7988d.png)

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by NightMingGit** [comment]
![image](https://user-images.githubusercontent.com/92633021/231692037-0c9b4066-c1ae-48f1-8499-b1485510056b.png)

**Comment by NightMingGit** [comment]
帮我看下大佬

**Comment by alex8088** [comment]
[vite-plugin-monaco-editor](https://github.com/vdesjs/vite-plugin-monaco-editor) options 中  `customDistPath`  支持自定义输出目录，将 其输出到 `out/renderer`
