### ISSUE TITLE
统信 桌面20专业版(linux ) 权限问题

### ISSUE THREAD

**Issue by lovecrossyou** [alex8088/electron-vite#15]
### Describe the bug

/tmp/dev-0cf7caba.sh: 1 /tmp/dev-0cf7caba.sh: electron-vite ：Permission denied

### Electron-Vite Version

1.0.7

### Electron Version

19.0.14

### Vite Version

3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by lovecrossyou** [comment]
使用环境： 统信UOS 20 专业版

**Comment by alex8088** [comment]
没有权限，就给它权限，sudo是试一试吧，这应该不是 electron-vite 的问题，我相信执行vite的cli也是一样的结果

**Comment by lovecrossyou** [comment]
好的，我再看看吧，sudo chmod 777 -R /tmp都执行了 ，还是这个权限问题

**Comment by lovecrossyou** [comment]
麻烦问一下 ，这个临时文件在那个脚本写的，我改下写死试试呗

**Comment by alex8088** [comment]
并没有临时文件，建议你删除node_module,然后在用sudo 安装，`sudo npm i`

**Comment by alex8088** [comment]
我也用过 统信 奇怪的问题太多了，你也可能会遇到 打包Electron之后跑不起来的情况，也是没有权限之类的， 统信 魔改太多东西了

**Comment by lovecrossyou** [comment]
> 我也用过 统信 奇怪的问题太多了，你也可能会遇到 打包Electron之后跑不起来的情况，也是没有权限之类的， 统信 魔改太多东西了

谢谢哈 我试试
