### ISSUE TITLE
无法禁用F12快捷键

### ISSUE THREAD

**Issue by Lookforward666** [alex8088/electron-vite#150]
### Describe the bug

在你的模板代码里有这样一段代码
// Default open or close DevTools by F12 in development
  // and ignore CommandOrControl + R in production.
  // see https://github.com/alex8088/electron-toolkit/tree/master/packages/utils
  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })
但是当我点进watchWindowShortcuts发现第二个参数shortcutOptions只有2个可用参数：
export declare type shortcutOptions = {
    /**
     * Use `ESC` key to close window, default `false`.
     */
    escToCloseWindow: boolean;
    /**
     * Zoom in (`Minus + CommandOrControl`) or zoom out(`Equal + Shift + CommandOrControl`), default `false`.
     */
    zoom: boolean;
};
请问要怎么写，才能实现禁用F12快捷键呢？谢谢

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
[@electron-toolkit/utils](https://github.com/alex8088/electron-toolkit/tree/master/packages/utils) `watchWindowShortcuts` 已经考虑到了，在开发模式下可以通过F12快捷打开devtool，但当打包程序后此功能就会禁用屏蔽保护。

**Comment by Lookforward666** [comment]
感谢，如果要添加更多的快捷键屏蔽或者启动，需要在这里怎么做呢?
app.on('browser-window-created', (_, window) => {
optimizer.watchWindowShortcuts(window)
})

**Comment by alex8088** [comment]
`watchWindowShortcuts` 仅支持一些通用的快捷键，如果想要更多，自己实现就好，参考代码 https://github.com/alex8088/electron-toolkit/blob/master/packages/utils/src/optimizer.ts
