### ISSUE TITLE
build:win后，安装后白屏，尝试相关问题解决方案，仍未解决。

### ISSUE THREAD

**Issue by dengwl** [alex8088/electron-vite#151]
### Clear and concise description of the problem

按部就班的搭建好项目后，引了相关框架，使用开发环境运行，没有问题，但一打包后，进入就是空白。求指教！
安装后查看调试，页面框架如图
![image](https://user-images.githubusercontent.com/19411201/233302691-00d7a05d-0841-48b5-9826-96c5e9cbdd4a.png)
实际页面代码
![image](https://user-images.githubusercontent.com/19411201/233303118-8da6201d-f0d8-4e32-be94-8944a09d4864.png)
![image](https://user-images.githubusercontent.com/19411201/233303468-63e4a060-d261-41cd-bb35-42917c81e13d.png)
我增加了个.babelrc文件
![image](https://user-images.githubusercontent.com/19411201/233303796-a2fd44e8-35cc-4267-a3a8-f7facb8e847e.png)

是我打包的时候有什么地方配置有问题么？
这是我的依赖项：
` "dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "@electron-toolkit/preload": "^1.0.3",
    "@electron-toolkit/utils": "^1.0.2",
    "ant-design-vue": "^3.2.17",
    "axios": "^1.3.5",
    "babel-plugin-import": "^1.13.6",
    "electron-updater": "^5.3.0",
    "pinia": "^2.0.34",
    "unplugin-vue-components": "^0.24.1",
    "vue-qrcode-reader": "^3.1.5",
    "vue-router": "^4.1.6",
    "vue3-qr-reader": "^1.0.0",
    "vite": "^4.2.1",
    "vue": "^3.2.47",
    "less": "^4.1.3",
    "typescript": "^4.9.5",
    "vue-tsc": "^1.2.0"
  },
  "devDependencies": {
    "@electron-toolkit/tsconfig": "^1.0.1",
    "@electron/notarize": "^1.2.3",
    "@rushstack/eslint-patch": "^1.2.0",
    "@types/node": "16.18.21",
    "@vitejs/plugin-vue": "^4.1.0",
    "@vue/eslint-config-prettier": "^7.1.0",
    "@vue/eslint-config-typescript": "^11.0.2",
    "electron": "^22.3.4",
    "electron-builder": "^23.6.0",
    "electron-vite": "^1.0.21",
    "eslint": "^8.36.0",
    "eslint-plugin-vue": "^9.10.0",
    "less": "^4.1.3",
    "prettier": "^2.8.7",
    "typescript": "^4.9.5",
    "vite": "^4.2.1",
    "vue": "^3.2.47",
    "vue-tsc": "^1.2.0"
  }`

### Suggested solution

无

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
见 文档 故障排除章节 https://cn-evite.netlify.app/guide/troubleshooting.html#vue-router-%E6%88%96-react-router-dom-%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E6%AD%A3%E5%B8%B8%EF%BC%8C%E4%BD%86%E5%9C%A8%E6%9E%84%E5%BB%BA%E5%90%8E%E6%97%A0%E6%95%88

**Comment by OwEeicebare** [comment]
楼主解决了吗,社区好少啊我也白屏是咋回事啊我连怎么，可以附加参数 --trace-warnings 到应用程序运行，查看错误信息。例如：.\app.exe --trace-warnings（在 Windows 中），都不会大佬可以留个方式沟通下吗

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/troubleshooting#vue-router-%E6%88%96-react-router-dom-%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E6%AD%A3%E5%B8%B8-%E4%BD%86%E5%9C%A8%E6%9E%84%E5%BB%BA%E5%90%8E%E6%97%A0%E6%95%88
