### ISSUE TITLE
发布后VueRouter失效

### ISSUE THREAD

**Issue by SuperLiii** [alex8088/electron-vite#152]
### Describe the bug

使用yarn dev开发的时候一切正常,但是在发布后或者使用yarn start
router-view无法被显示,router-link也无法跳转

使用yarn create @quick-start/electron创建的工程

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by SuperLiii** [comment]
抱歉打扰了
我找到了解决方案 ,在createApp时添加 router.push("/"); 即可

像这样:
`
import router from "./router"
createApp(App).use(router).mount('#app').$nextTick(()=>{
    router.push("/");
})
`


参考  https://stackoverflow.com/questions/53990214/how-to-fix-blank-page-if-i-am-using-vue-router-with-electron-js

**Comment by alex8088** [comment]
这应该是更好的处理方式 https://cn-evite.netlify.app/guide/troubleshooting.html#vue-router-%E6%88%96-react-router-dom-%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E6%AD%A3%E5%B8%B8%EF%BC%8C%E4%BD%86%E5%9C%A8%E6%9E%84%E5%BB%BA%E5%90%8E%E6%97%A0%E6%95%88
