### ISSUE TITLE
V8 字节码 bytecode-loader.js 注入代码打开开发者工具漏洞

### ISSUE THREAD

**Issue by xlsqwg** [alex8088/electron-vite#153]
### Describe the bug

**实现过程，在通过bytecode打包后生产环境主进程文件夹中的 bytecode-loader.js 文件里注入以下代码后运行应用程序，直接拥有开发者工具的权限，从而实现逆向抓包破解等行为**

`const { app } = require('electron');
app.on('web-contents-created', function (event, contents) {contents.openDevTools()});`

**具体实现过程（位于路径dist\win-unpacked\resources\app\out\main\bytecode-loader.js）：**

> "use strict";
**const { contextBridge, app } = require('electron'); // 注入的代码
app.on('web-contents-created', function (event, contents) {contents.openDevTools()}); // 注入的代码**
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const v8 = require("v8");
const Module = require("module");
v8.setFlagsFromString("--no-lazy");
v8.setFlagsFromString("--no-flush-bytecode");

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@xlsqwg 

目前字节码只是保护主进程和预加载脚本，对于渲染进程并不保护，所以控制开发工具能不能打开并无太大意义。因此需要把重要的业务逻辑写在主进程，而不是渲染进程。推荐的做法是主进程实现业务逻辑，而渲染进程实现的UI界面处理，同时，preload脚本不应暴露太大权限的，提高api权限颗粒度。

**Comment by xlsqwg** [comment]
@alex8088 好的，谢谢指导
