### ISSUE TITLE
.node files on windows are not processed correctly

### ISSUE THREAD

**Issue by adminy** [alex8088/electron-vite#155]
### Describe the bug

```
build the electron main process successfully

-----

[vite:node-asset] Could not load Z:/adminy/project/node_modules/registry-js/build/Release/registry.node?commonjs-proxy 
(imported by node_modules/registry-js/dist/lib/registry.js):
The argument 'path' must be a string or Uint8Array without null bytes.
Received '\x00Z:/adminy/project/node_modules/registry-js/build/Release/registry.node'
vite v4.3.4 building for development...

watching for file changes...
```

This works fine if I just import the library by itself in a node repl.

### Electron-Vite Version

1.0.22

### Electron Version

24.2.0

### Vite Version

4.3.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@adminy install `registry-js` in `dependences`.

**Comment by adminy** [comment]
I have no idea how or why this works, but thanks, it works ❤️ 
Also it seems to work only if its a dependency, not a dev-dependency.

**Comment by alex8088** [comment]
https://evite.netlify.app/guide/dev.html#dependencies-vs-devdependencies
