### ISSUE TITLE
resolving package installation warnings

### ISSUE THREAD

**Issue by gustavoalvim41** [alex8088/electron-vite#157]
### Clear and concise description of the problem

After initializing a project with the following command:

```
yarn create @quick-start/electron
```
The following warnings are displayed to us:

![Screenshot_2](https://github.com/alex8088/electron-vite/assets/72044547/42cc8688-ad09-4abc-99fb-a11e59523b75)

These warnings are provided to inform you about possible improvements, updates, or changes in the packages you are using. It is recommended to take these warnings into consideration and update the packages accordingly to ensure the best functionality and compatibility in your project.

### Suggested solution

To resolve these warnings, you can execute the following command:
```
yarn add @electron/osx-sign@latest @electron/asar@latest
```

This will add the latest versions of the @electron/osx-sign and @electron/asar packages to your project. These updated versions will replace the older versions mentioned in the warnings and resolve the issues related to package names.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
`electron-builder 24` will fix these issues, currently electron-builder 24 is in `alpha`.
