### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by wcc1433** [alex8088/electron-vite#16]
### Describe the bug

在 main里面定义一个 xxx.ts模块，在其它地方引入该模块不会打包。实际允许会报 module not found

### Electron-Vite Version

2

### Electron Version

19.0.x

### Vite Version

2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by wcc1433** [comment]
顺便问问大佬一个基础的问题：main里面是 node.js环境的代码，我在里面封装了一个 api。怎么给到 preload里面让 页面能调用呢。

**Comment by alex8088** [comment]
> ![image](https://user-images.githubusercontent.com/37837522/188868822-b61b2f3a-eb32-4103-b178-e8621bde8230.png)

playwright.ts 有被导入，就会被bundle，假如被 main的index.ts 导入，那就会被bundle，bundle并不是按文件，都会被打包的index.js中（你可查看打包后的代码是不是包含playwright的代码，就清楚了），如果有很多文件，会自动分块，就是分成很多文件 ，你可能需要对vite的打包机制要有所了解。

**Comment by alex8088** [comment]
> 顺便问问大佬一个基础的问题：main里面是 node.js环境的代码，我在里面封装了一个 api。怎么给到 preload里面让 页面能调用呢。

一般会在主进程提供IPC，preload定义方法来send或者invoke这些IPC, 很难一句话说清楚，你可看看这里项目：

https://github.com/alex8088/EvPlayer，可以更快理解

**Comment by wcc1433** [comment]
好的，非常感谢大佬
