### ISSUE TITLE
安装robotjs，rebuild之后任然报错

### ISSUE THREAD

**Issue by shiouhoo** [alex8088/electron-vite#160]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/61953211/8253b00c-87df-4403-9e6c-14a0fe0da298)

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
这并不是electron-vite的问题，尝试一下npm

**Comment by shiouhoo** [comment]
请问这是什么引起的呢，实在找不到解决办法，实测rebuild是成功了的，在主进程也可以使用，就是pnpm install的时候就会出现上面的错误

**Comment by alex8088** [comment]
改用npm 试一试，
- https://github.com/pnpm/pnpm/issues/5638
- https://github.com/electron-userland/electron-builder/issues/6933

**Comment by sevenzx** [comment]
请问你解决这个问题了吗

**Comment by ftyszyx** [comment]
Robotjs(https://github.com/octalmage/robotjs) 是使用 V8 API 构建的。所以它必须针对不同的 Node 版本进行重新编译。如果你的电脑没有编译环境，安装这个库会报错。
所以我用 Node API 重写了 Robotjs 的封装api.并进行了预编译。
现在你可以仅用一个命令安装 robotjs：
“npm install robotjs_addon”
并且它与不同的 Node 版本兼容。
代码已开源。如果你感兴趣，可以查看一下。
https://github.com/ftyszyx/robotjs
注意：接口有减少，因为我暂时没用到
