### ISSUE TITLE
 [`@electron-toolkit/preload`] 切换路由跳转，之前页面使用的window.electron.ipcRenderer.on监听的事件仍然会被监听到

### ISSUE THREAD

**Issue by DonXander** [alex8088/electron-vite#161]
### Describe the bug

切换路由跳转，之前页面使用的window.electron.ipcRenderer.on监听的事件在新页面中仍然会被监听到，我的监听事件是使用之前被封装过的 useIpcRendererOn，里面有销毁页面移出监听的逻辑，但实际测试还是会触发
<img width="557" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/43494377-a5be-408d-a509-f3e6c84c237e">

### Electron-Vite Version

1.0.10

### Electron Version

20.3.1

### Vite Version

3.1.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@DonXander 此问题已知，待修复。开启上下文隔离时，事件函数会被electron代理，函数对象在序列化和反序列化后并非同一对象，导致remove失败。可以暂时通过关闭上下文隔离或者使用removeAll处理。

**Comment by DonXander** [comment]
关闭上下文隔离，怎么操作，对现有代码有影响么？有尝试在页面中使用removeAll，不起作用
<img width="438" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/ec4ece10-955b-4615-b5b7-92905d74831d">

**Comment by alex8088** [comment]
removeAllListeners('xxx')

**Comment by DonXander** [comment]
???

**Comment by alex8088** [comment]
具体的事件名

**Comment by DonXander** [comment]
居然可以。我问chatgpt说的是不需要任何参数

**Comment by DonXander** [comment]
还有一点，当跳转路由，新页面有之前的事件监听时，Unmount钩子里面的removeAll可能会异步导致新页面的监听事件被销毁

**Comment by alex8088** [comment]
@electron-toolkit/preload, new ver 2.0.0 is out! more detail: https://github.com/alex8088/electron-toolkit/blob/preload@2.0.0/packages/preload/CHANGELOG.md
