### ISSUE TITLE
app.vue文件添加了router后，热更新失效

### ISSUE THREAD

**Issue by gaofeng222** [alex8088/electron-vite#163]
### Clear and concise description of the problem

app.vue文件添加了router后，修改页面组件的内容，热更新失效，必须重启项目才能看到最新的修改

### Suggested solution

修改页面组件的内容后能及时刷新

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
HMR 是由vite提供完全支持，实践并无此问题，是否使用了vue插件，是否正确使用router，可以逐一排查一下。建议创建一个vue的vite项目测试是否同样有问题。

**Comment by gaofeng222** [comment]
大佬，我的仓库demo。。。https://github.com/gaofeng222/electronapp/tree/master，麻烦看下

**Comment by gaofeng222** [comment]
> HMR 是由vite提供完全支持，实践并无此问题，是否使用了vue插件，是否正确使用router，可以逐一排查一下。建议创建一个vue的vite项目测试是否同样有问题。

大佬，我的仓库demo。。。[https://github.com/gaofeng222/electronapp/tree/master，麻烦看下](https://github.com/gaofeng222/electronapp/tree/master%EF%BC%8C%E9%BA%BB%E7%83%A6%E7%9C%8B%E4%B8%8B)

**Comment by gaofeng222** [comment]
![GIF 2023-5-16 13-44-52](https://github.com/alex8088/electron-vite/assets/18065659/98b7c7d9-3744-4f0e-829c-1b6bc85babfc)

这个演示效果，不知怎么造成的

**Comment by alex8088** [comment]
如还有问题，建议在vue或者vite项目issue中反馈此问题
