### ISSUE TITLE
预加载脚本类型定义中的 Window 无法在vue文件中正常使用，编辑器为：Intellij IDEA 2023.1

### ISSUE THREAD

**Issue by cnJxl** [alex8088/electron-vite#164]
### Describe the bug

目录结构像这样:
```txt
project
└ src
  └ main
    └ ......
  └ preload
    └ index.ts
    └ types.d.ts
    └ xxx.ts
  └ renderer
    └ ......
```

注：未修改 tsconfig 文件

类型定义类似这样（types.d.ts）：
```ts
// 无法在 vue 文件中正常使用, 注：即便是初始的 declare global { interface Window { electron: ElectronAPI, api: any}} 也无法使用
declare interface Window {
  ClientClipboard: {
    copy: (text: string) => void
    read: () => string
  }
}

// 可以使用
type ClientClipboardCopy = (text: string) => void
```

在其它地方使用时：
```vue
<!-- App.vue -->
<template><div>App</div></template>
<srcipt setup lang="ts">
window.ClientClipboard.copy('xxx')
//     ^^^^^^^^^^^^^^^ ~~~~
//     未解析的变量 ClientClipboard
</script>
<style></style>
```

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
将tsconfig中的files字段去掉，重启IDE
