### ISSUE TITLE
Allert CLI

### ISSUE THREAD

**Issue by O-YENA** [alex8088/electron-vite#166]
### Describe the bug

```
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different

> blic-app@1.0.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=23.6.0
  • loaded configuration  file=C:\Work\Project\Blic-App\Frontend\electron-builder.yml

added 423 packages, and audited 424 packages in 51s

58 packages are looking for funding
  run `npm fund` for details

**6 high severity vulnerabilities**

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

After installation, ```6 high severity vulnerabilities``` and ```npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward. There is no API change, just a package name change
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware of the API is slightly different```

### Electron-Vite Version

latest

### Electron Version

latest

### Vite Version

latest

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
dup #157
