### ISSUE TITLE
根目录有个文件夹，怎么在打包之后，能正常引用到

### ISSUE THREAD

**Issue by DonXander** [alex8088/electron-vite#169]
### Describe the bug

dev和preview都可以正常访问，build及builder之后在\dist\win-unpacked中打开访问异常，手动copy到该目录下也不行
文件夹目录：
<img width="140" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/8dedae39-254d-4a0c-bfbc-968f9ef069e1">

项目中引用：
<img width="576" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/faeb5547-7162-4417-bab7-6d05639caffd">

### Electron-Vite Version

1.0.10

### Electron Version

20.3.1

### Vite Version

3.1.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
可以看看看资源处理

**Comment by DonXander** [comment]
“公共目录中的所有资源都不会复制到输出目录。所以在打包 app 的时候，公共目录应该一起打包。”
--
所以这里具体应该怎么操作

**Comment by DonXander** [comment]
想要的结果是将db资源复制到输出目录吧

**Comment by alex8088** [comment]
输出目录是指代码构建输出位置，这和打包无关，不复制是保留资源在原来目录，确保路径不会变化，代码中路径引用才不会出错。electron-builder中没有配置排除目录，就会打包。你的问题在于asar路径问题。这文档中也有说明。你需要理解asar局限性和路径处理问题，还有DB文件必然不能打包到asar中，因为需要读写。

**Comment by alex8088** [comment]
你也可以参故障排除章节，排查技巧，查找打包后不行的原因

**Comment by DonXander** [comment]
我尝试新建resources目录，并将db拷贝进去，build&builder出来的包里没有相关文件。asar配置这里是排除了的。
<img width="229" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/150f2eb8-f4e4-4a12-bb05-8f597b4eb110">

另外打包后的问题排查这里。。我是执行\dist\win-unpacked里面的exe文件，后面添加--trace-warnings，但是并没有任何反应

**Comment by DonXander** [comment]
build&builder出来的包里没有相关文件
--
哦对，node_modules里面有nedb

**Comment by alex8088** [comment]
resources/**，改成两个星

**Comment by DonXander** [comment]
我尝试将db目录排除，可以在这里找到拷贝的db目录

**Comment by DonXander** [comment]
> resources/**，改成两个星

资源拷贝有了，但是运行还不行。是这里的路径有问题么
<img width="392" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/76b4c336-e0da-44e9-829a-7834d761d41d">
<img width="349" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/62738e56-702d-4f62-9a23-503e2aa56598">

**Comment by alex8088** [comment]
https://cn-evite.netlify.app/guide/assets.html#app-asar-unpacked-%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84%E9%97%AE%E9%A2%98

**Comment by DonXander** [comment]
看到了。但文档这里推介的是静态url的情形，我是用的函数拼接，下面这样也是不行
<img width="468" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/3ef413b4-dfa7-480d-ba4b-f85d42a79014">

**Comment by DonXander** [comment]
replace是对的，为何执行安装程序安装完成后又不行呢

**Comment by DonXander** [comment]
resource目录的文件是有的
<img width="332" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/674e9a25-d9c4-427d-b560-1e061fa1f525">
