### ISSUE TITLE
项目创建之后其他组件中无法识别 vue

### ISSUE THREAD

**Issue by moom-en** [alex8088/electron-vite#170]
### Describe the bug

项目创建之后其他组件中无法识别 vue，但不影响运行（我是 WebStorm 2023.1.2）
![image](https://github.com/alex8088/electron-vite/assets/35919845/93af8689-1c6e-450c-b837-2538fb6826bf)

### Electron-Vite Version

1.0.22

### Electron Version

24.3.1

### Vite Version

4.3.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
tsconfig中移除files字段

**Comment by moom-en** [comment]
> tsconfig中移除文件字段

移除了还是这样

**Comment by alex8088** [comment]
IDE是否有vue相关插件，或者手动增加vue类型定义文件
