### ISSUE TITLE
添加pinia报错  无法运行 

### ISSUE THREAD

**Issue by yq5858588** [alex8088/electron-vite#171]
### Clear and concise description of the problem

![image](https://github.com/alex8088/electron-vite/assets/6045826/a006cb2b-d25f-41f2-abf7-7298bb31ec42)

### Suggested solution

就光引入一下  就报错了 

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
根据错误信息处理，依赖兼容问题， 最新pinia要求 vue 3.3 https://github.com/vuejs/pinia/commit/b8fb1653211dbe6dc6aa3a8ac36185bf93bcfa25
