### ISSUE TITLE
怎么在这个项目里单独调试一个和多个ts文件呢？使同样的代码在调试和整体运行时保持一致。

### ISSUE THREAD

**Issue by Sercl** [alex8088/electron-vite#173]
### Describe the bug

怎么在这个项目里单独调试一个和多个ts文件呢？使同样的代码在调试时和整体运行时保持一致。

我通过手动添加了个ts配置文件，使用ts-node调试正常，但是如果文件里包含纯esm的库就会报错，用动态导入后倒是没问题了。

但是在项目整体运行时候又会异常，再改回import导入就又可以了。

这两种状况同时都会有，有什么合适的方案可以同时兼容两种运行方式吗？或者我该怎么修改这个config配置文件呢？
（都在Main主线程内）

ts-node调试时使用的config文件：
`{
  "include": [
    "src/main/**/*"
  ],
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "composite": true
  },
  "exclude": [
    "node_modules"
  ]
}
`

非常感谢

### Electron-Vite Version

1.0.22

### Electron Version

21.4.4

### Vite Version

3.2.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
为什么需要ts-node来调试，electron-vite即支持调试。

**Comment by Sercl** [comment]
> 为什么需要ts-node来调试，electron-vite即支持调试。

每次修改完在运行到修改部分的前置流程太长了，所以想单文件调试好了没问题再接入到主进程里。
electron-vite怎么调试这种单个或多个ts文件呢？查阅文档并没有找到。谢谢

**Comment by alex8088** [comment]
不解你的开发方式，建议你创建一个脚手架项目了解。只要了解了实际是非常简单的，不存在这么麻烦的事情。

**Comment by Sercl** [comment]
好的，谢谢了，我去研究下
