### ISSUE TITLE
当使用vite plugin时，配置项似乎会被更改导致无法正常打包

### ISSUE THREAD

**Issue by TalexDreamSoul** [alex8088/electron-vite#174]
## 问题描述

似乎当使用了其他的vite插件（初步推测可能是 unocss时）可能会导致 vite 中 build.target 项被更改
即 build.cssTarget 继承原有的 target 而 target 被修改为 [ "esnext" ] 导致打包失败

## 建议

通过配置项指定或采用其他的特殊 renderer build target (即chrome**) 来避免

### Electron-Vite Version

1.0.22

### Electron Version

24.3.1

### Vite Version

4.3.5

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
感谢建议，有些包会强制修改target，后续兼容chrome**和>=es2021。

**Comment by alex8088** [comment]
New ver 1.0.23 is out. Supports `es?` build target.
