### ISSUE TITLE
你好，当html里面引入jq这样的库，应该如何打包，开发时没问题，打包时报错

### ISSUE THREAD

**Issue by ezewu** [alex8088/electron-vite#175]
### Describe the bug

<img width="827" alt="image" src="https://github.com/alex8088/electron-vite/assets/22029449/e7cef3a3-6fe5-483c-bdbf-5cfcf5084638">

### Electron-Vite Version

最新版

### Electron Version

最新版

### Vite Version

最新版

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by ezewu** [comment]
<img width="499" alt="image" src="https://github.com/alex8088/electron-vite/assets/22029449/bb4f476a-639f-4e68-8607-38de5eb38ad2">
这里面，有一些库，不支持npm安装，要如何打包，麻解答一下，谢谢

**Comment by alex8088** [comment]
可以放在renderer的公共目录，当做静态资源处理

**Comment by ezewu** [comment]
你好，如何做静态处理，能有一点点示例吗

**Comment by alex8088** [comment]
相关：https://cn.vitejs.dev/guide/assets.html#the-public-directory

在src/renderer下建public目录，把你的static放进去。建议阅读一下vite和electron-vite的文档

**Comment by ezewu** [comment]
谢谢
