### ISSUE TITLE
Unable to build all files in src/renderer

### ISSUE THREAD

**Issue by hackernese** [alex8088/electron-vite#176]
### Describe the bug

So my original problem is i am trying to pop a modal window from the main process, so i was intending to create a second HTML file in src/renderer called "about.html" for my modal window. My current directory is something like this :
```
 src
  └ main
       └ index.js
  └  preload
       └ index.js
  └ renderer
       └ srcabout
            └ // React components relating to about page
       └ src 
           └ // React components relating to the main page
       └ index.html
       └ about.html
``` 
but when i run "npm run build", there is no "about.html" in "out/renderer/about.html", here is an IPC handler which once invoked will create a modal window
```javascript
ipcMain.handle('open:about', () => {
    const child = new BrowserWindow({ parent: win, modal: true, show: false })
    child.loadFile(join(__dirname, '../renderer/about.html'))

    child.on('ready-to-show', () => {
      child.show()
    })
  })
``` 
at first that does not work, but when i tried to manually add about.html to "out/renderer" then change `"build:win": "npm run build && electron-builder --win --config"` to `"build:win": "electron-builder --win --config"` and execute "npm run build:win" afterward, the IPC handler worked and the About page was shown
Can anyone please tell me is there anyway i can include about.html or all files in the src/renderer directory into my build directory ? Am i missing any option in electron-vite-config.js ? Here is my config, it's the same as the default one
```javascript
import { resolve } from 'path'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin()]
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },
    plugins: [react()]
  }
})

``` 

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://evite.netlify.app/guide/dev.html#multiple-windows-app

**Comment by hackernese** [comment]
Sorry, didn't notice that part in the docs, thank it works now

**Comment by hackernese** [comment]
Excuse me, just an extra question from this, currently i am changing my IPC to this 

```javascript
ipcMain.handle('open:about', () => {
    const child = new BrowserWindow({ parent: win, modal: true, show: false })

    if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
      child.loadURL(process.env['ELECTRON_RENDERER_URL'])
    } else {
      child.loadFile(join(__dirname, '../renderer/about.html'))
    }

    child.on('ready-to-show', () => {
      child.show()
    })
  })
``` 

for easier development and hot reloading from vite, but process.env['ELECTRON_RENDERER_URL'] seem to belong to the main process ( index.html ) only. Is it possible to create a seperate URL for about.html ?

**Comment by alex8088** [comment]
https://evite.netlify.app/guide/hmr.html

**Comment by hackernese** [comment]
Ok thanks
