### ISSUE TITLE
如果支持多页面开发，配置文件及main加载路径应该怎么改

### ISSUE THREAD

**Issue by DonXander** [alex8088/electron-vite#177]
### Describe the bug

如果支持多页面开发，配置文件及main加载路径应该怎么改，初步的项目目录如下：
![image](https://github.com/alex8088/electron-vite/assets/25742814/822e7268-9f9f-41de-93ad-ef1ba99f3eef)

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn-evite.netlify.app/guide/dev.html#%E5%A4%9A%E7%AA%97%E5%8F%A3%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F

https://cn-evite.netlify.app/guide/hmr.html
