### ISSUE TITLE
Unable to run the dev server for renderer only

### ISSUE THREAD

**Issue by farhan27555** [alex8088/electron-vite#178]
### Describe the bug

Hello. I am encountering an issue while trying to run the development server for the web app using the `--rendererOnly` option. I have limited experience with Electron, so I might be missing something in my setup.

From what I understand, using the `--rendererOnly` option should only run the dev server for the web app. However, even after following the recommended steps and using the `--rendererOnly` option, the Electron app is still being launched along with the web app dev server. This is not the expected behavior, as I want to run only the web app during development without the Electron app.

Here are the steps I have taken so far:

Made sure that the electron-vite command has been run at least once and that there have been no changes to the main process and preload scripts source code.
Despite following these steps, the Electron app continues to launch when running `npm run dev -- --rendererOnly.`
I do get a warning in the terminal though: `warn: you have skipped the main process and preload scripts building`

I would greatly appreciate any assistance or guidance on how to resolve this issue. If there are additional configurations or steps required to achieve running only the web app in development mode without launching the Electron app, please provide the instructions.

Thank you for your help!

### Electron-Vite Version

electron-vite/1.0.22

### Electron Version

22.3.9

### Vite Version

4.3.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@farhan27555,

The `electron-vite` command is designed for electron development, so it is necessary to start electron app for development and debugging. This is still different from normal web development. The `--rendererOnly` option design is just as the warning prompt says, it conditionally speeds up the build speed and improves the development experience.

If you only use electron as a browser, debugging in electron is no problem. If you still want to develop in the browser, you can create a  `vite.config.js` file for vite with the `renderer` config in `electron-vite.config.js`. e.g.

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
 {
    root: './src/renderer',
    plugins: [vue()]
  }
})
```

And then add scripts to package.json to use vite command to dev. You can get more details from [vite's documentation](https://vitejs.dev/).

**Comment by farhan27555** [comment]
@alex8088 Really appreciate the response. Thanks

**Comment by jvidalgz** [comment]
I was looking a way to run electron-vite in the browser so I can run some tests using cypress.js. This issue was really helpful, here is how I solve this (kind of):
1. new file ```vite.config.js```
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  root: './src/renderer',
  plugins: [vue()],
  build: {
    outDir: './dist-web'
  }
})
```

2. Add to ```package.json```
```
"scripts": {
    "vite:dev": "vite",
    "vite:build": "vite build",
}
```

Unfortunately, I can't use the .env file located in root directory so I have to create a new one under ./src/renderer and all keys preffied with ```VITE_```

**Comment by alex8088** [comment]
https://evite.netlify.app/guide/env-and-mode.html
