### ISSUE TITLE
.d.ts文件提供的类型增强在vue文件中无法获取类型提示

### ISSUE THREAD

**Issue by stormbuf** [alex8088/electron-vite#180]
### Describe the bug

在 preload 的.d.ts 文件中提供了类型增强：
<img width="612" alt="iShot_2023-05-31_00 34 23" src="https://github.com/alex8088/electron-vite/assets/37621593/8dd5472b-fa1c-4a0a-a652-5618f35f0ade">

然后在ts文件中能正常调用并获得类型提示：
<img width="427" alt="iShot_2023-05-31_00 35 11" src="https://github.com/alex8088/electron-vite/assets/37621593/bbd4581d-04f3-4408-9973-780ce891a6e1">

然而在vue文件中使用时，无法获得类型提示，并红线提示报错：
<img width="793" alt="iShot_2023-05-31_00 42 57" src="https://github.com/alex8088/electron-vite/assets/37621593/134dcd32-98ba-4a6b-bcfd-9250c8eb140d">

项目可以正常运行。

tsconfig*.json和 electron.vite.config.ts 等配置文件未做修改。

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
是否安装typescript volar,

检查 tsconfig.web是否包含

```json
{
  "extends": "@electron-toolkit/tsconfig/tsconfig.web.json",
  "include": [
    //...
    "src/preload/*.d.ts"
  ],
  // ...
}
```

**Comment by stormbuf** [comment]
https://github.com/alex8088/electron-vite/issues/180#issuecomment-1569372419

typescript volar 已安装

tsconfig.web 中也包含相关路径
<img width="553" alt="image" src="https://github.com/alex8088/electron-vite/assets/37621593/a831704b-b946-4002-82d2-4b5d85d803e6">

**Comment by alex8088** [comment]
将 tsconfig中files属性去掉重启IDE试一试

**Comment by stormbuf** [comment]
这个方法有在issue中看到并且尝试过，依然没有类型提示。

**Comment by alex8088** [comment]
也可以和IDE有关，也可尝试更新vscode
