### ISSUE TITLE
.env 获取不到

### ISSUE THREAD

**Issue by yixinhm** [alex8088/electron-vite#183]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/77895852/0305a712-9c74-4872-ad3f-1bbcae6ace61)

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn-evite.netlify.app/guide/env-and-mode.html

**Comment by yixinhm** [comment]
谢谢

**Comment by yixinhm** [comment]
我在.env.development  设置了PRELOAD_VITE_SOME_KEY=123   # 预加载脚本可用 在预加载脚本读不到

**Comment by Picktarget** [comment]
@yixinhm 请问是如何解决的呢
