### ISSUE TITLE
How to use require() in the main process?

### ISSUE THREAD

**Issue by cattletruck** [alex8088/electron-vite#185]
### Describe the bug

I am trying out electron-vite and I'm having trouble with require in main/index.js. When using a require statement in main/index.js I am getting a module not found error and the app will not launch.  This issue, https://github.com/alex8088/electron-vite/issues/66 , seems to cover the same topic, but the answer seems to be outdated, I couldn't find the 'externalizePlugin' mentioned in the answer in the vite or electron-vite docs.

to reproduce:
1) make app with scaffolding
yarn create @quick-start/electron my-app --template vue

2) create file to be required: + main/myImport.js

3) require it in the main process (main/index.js):
const myImport = require('./myImport.js')

4) start the project with 'yarn dev'

### Electron-Vite Version

24.4.1

### Electron Version

1.0.23

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
You need to write it in ES syntax(import module).
