### ISSUE TITLE
app.relaunch() does not work properly with dev server

### ISSUE THREAD

**Issue by davbrito** [alex8088/electron-vite#186]
### Describe the bug

When calling app.relaunch(), the electron app restarts but the dev server is gone, so it ends up with a white screen.

### Electron-Vite Version

electron-vite@1.0.22

### Electron Version

electron@25.0.1

### Vite Version

vite@4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Yeah, it's not restart electron-vite command, electron-vite is hard to intercept. It is recommended to use `electron-vite preview` command to test in production mode when you need to test this method.
