### ISSUE TITLE
How to create and access files in the public directory

### ISSUE THREAD

**Issue by Andrew-web-coder** [alex8088/electron-vite#187]
### Describe the bug

All I want to:

1) Dynamically generate some file and store somewhere;
2) Create a link to that file from the HTML file.

I can make it work in dev mode using path `./src/renderer/output.gif`, and then using `/output.gif` for `src` value in my HTML page. But, obviously, it does not work in the build, I have tried many variations, but it always produces 404 error. 

So, how to make it work in the production?

### Electron-Vite Version

latest

### Electron Version

latest

### Vite Version

latest

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
By default, the working directory of renderers are located in `src/renderer`, so the public directory needs to be created in this directory. The default public directory is named `public`, which can also be specified by `renderer.build.publicDir`.

more details: https://vitejs.dev/guide/assets.html#the-public-directory

**Comment by Andrew-web-coder** [comment]
@alex8088 I have already read these docs several times but it just doesn't work.

**Comment by alex8088** [comment]
Your project structure？ How do you use？

**Comment by Andrew-web-coder** [comment]
I have a multiple window app where I have to create a file in one window (after user has done some interaction) and then display it in another one. I think the problem is that there is no `public` folder in the production.

**Comment by alex8088** [comment]
You can set up a custom protocol ->  https://github.com/alex8088/electron-vite/issues/36

**Comment by Andrew-web-coder** [comment]
What a complete nightmare
