### ISSUE TITLE
开发时没有问题 ，打包时报这个错

### ISSUE THREAD

**Issue by ezewu** [alex8088/electron-vite#189]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/22029449/e7ecd239-6e66-4c98-a345-ad23c7d69a8e)

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
故障排除章节 https://cn.electron-vite.org/guide/troubleshooting.html#a-javascript-error-occurred-in-the-main-process-error-cannot-find-module-xxx

**Comment by ezewu** [comment]
谢谢
