### ISSUE TITLE
Multiple Window approach not working

### ISSUE THREAD

**Issue by davbrito** [alex8088/electron-vite#190]
### Describe the bug

I have this renderer config:

```js
{
  renderer: {
      define: {
        ...apiUrlsDefines,
      },
      resolve: {
        alias: {
          "@renderer": resolve("src/renderer/src"),
          "@components": resolve("src/renderer/src/components"),
          ...commonAliases,
        },
      },
      plugins: [react()],
      build: {
        rollupOptions: {
          input: {
            index: resolve(__dirname, "src/renderer/src/index.html"),
            database: resolve(__dirname, "src/renderer/src/database/index.html"),
          },
        },
      },
    },
}
```

I start the server and then navigate to /database.html and i get a 404

### Electron-Vite Version

1.0.23

### Electron Version

24.4.1

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/hmr.html#using-hmr
