### ISSUE TITLE
你好database.db是要放在那个地方，才能打包过后能引用到。试了几个地方，打包过后就用不了了

### ISSUE THREAD

**Issue by ezewu** [alex8088/electron-vite#192]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/22029449/90451218-f5e5-459c-8e64-d264924e4b5b)

### Electron-Vite Version

1.0.23

### Electron Version

24.4.1

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by ezewu** [comment]
const dbPath = path.join(__dirname, "../../resources/database.db").replace("app.asar", "app.asar.unpacked"); 这样可以

**Comment by alex8088** [comment]
> const dbPath = path.join(__dirname, "../../resources/database.db").replace("app.asar", "app.asar.unpacked"); 这样可以

可以看看资源处理章节，可以简洁处理。但需要注意的将数据文件随程序分发时，如果重新安装更新时会丢失。最好的处理方式在程序运行时去创建，并将数据文件放在程序数据目录或者像微信一样放在用户目录。目录可以通过electron的api获得(`app.getPath`)
