### ISSUE TITLE
无法使用 nanoid 或 uuid 包，提示 crypto is not defined

### ISSUE THREAD

**Issue by imziyang** [alex8088/electron-vite#193]
### Describe the bug

![WX20230615-030037@2x](https://github.com/alex8088/electron-vite/assets/3312507/08acd151-da5e-47c7-a6a0-4a49eff8e5b8)
在主进程中使用 nanoid 包，会提示 crypto is not defined。

查看 out/main 文件，发现这个包里面的 crypto 没有被编译。
![WX20230615-030311@2x](https://github.com/alex8088/electron-vite/assets/3312507/88b18f92-f86c-42bd-999e-df673484164b)

### Electron-Vite Version

1.0.17

### Electron Version

21.3.3

### Vite Version

4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
检查是否开启externalizeDepPlugin，且安装在dep中。https://cn.electron-vite.org/guide/dev.html#dependencies-vs-devdependencies

**Comment by imziyang** [comment]
开启了externalizeDepPlugin，nanoid 放在了 dep 中，因为nanoid 只支持 esm，所以把它放进了 externalizeDepPlugin 的 exclude 里面，然后就报错了。
![WX20230615-142706@2x](https://github.com/alex8088/electron-vite/assets/3312507/4dd22ea0-7a2d-4326-82d5-4fa6e5f7095a)
![WX20230615-142853@2x](https://github.com/alex8088/electron-vite/assets/3312507/0cab56ec-9c20-40ec-9d06-d9eb03a95d1e)

**Comment by alex8088** [comment]
@imziyang 你的处理方式没有问题，nanoid 默认支持浏览器模式，两种方式解决

- 使用3版本还有正常维护，支持cjs
- 使用4版本的non-secue分支

```ts
import { nanoid } from 'nanoid/non-secure'

console.log(nanoid())
```

**Comment by imziyang** [comment]
@alex8088 感谢感谢~
