### ISSUE TITLE
安装完成之后，设置自动更新没监听到

### ISSUE THREAD

**Issue by DonXander** [alex8088/electron-vite#194]
### Clear and concise description of the problem

`const { autoUpdater } = require('electron-updater')

 autoUpdater.setFeedURL({
    url: 'http://www.test.com/download'
 })
autoUpdater.on('update-available', () => {
    //logger.info('update-available')
})
autoUpdater.on('update-downloaded', () => {
    //logger.info('update-downloaded')
})

app.whenReady().then(() => {
    autoUpdater.checkForUpdates()
})
`
日志输出显示事件没有监听到，setFeedURL的URL能正常下载，version比本地安装的版本更高

### Suggested solution

如上代码

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
需要把打包后的 `latest.yml` 文件放到服务器

**Comment by DonXander** [comment]
貌似不行。latest.yml和exe文件放的同一目录，是否需要给yml一个可访问地址

**Comment by alex8088** [comment]
确保你的文件服务器可以下载yml文件，可自己手动测试

**Comment by DonXander** [comment]
尝试放开目录 http://www.test.com/download/，http://www.test.com/download/latest.yml，安装文件还是http://www.test.com/download
--
以上测试不行

**Comment by DonXander** [comment]
尝试放开目录 http://www.test.com/download/，http://www.test.com/download/latest.yml，安装文件还是http://www.test.com/download。还是不行

**Comment by DonXander** [comment]
尝试放开目录 [http://www.test.com/download/]，可访问[http://www.test.com/download/latest.yml]，安装文件还是http://www.test.com/download。还是不行

**Comment by DonXander** [comment]
尝试放开目录 [http://www.test.com/download/]，可访问[http://www.test.com/download/latest.yml]，安装文件还是[http://www.test.com/download]。还是不行
