### ISSUE TITLE
如何外置配置文件，修改配置后，重新打开应用后生效

### ISSUE THREAD

**Issue by TeddyQ** [alex8088/electron-vite#195]
### Clear and concise description of the problem

我创建了config.json文件，配置了系统名称、服务IP信息，打包后功能都正常
代码引用方式如下：
import { cName, serverIp } from '../../../../resources/config/config.json'

安装以后配置文件路径如下：
C:\Users\username\AppData\Local\Programs\remote-om-system\resources\app.asar.unpacked\resources\config\config.json

修改安装路径下config.json的系统名称，重新打开应用，没有加载修改以后的名称

请问如何实现该功能？谢谢！

### Suggested solution

无

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
关于资源处理参考 https://cn.electron-vite.org/guide/assets.html#%E5%B0%86%E8%B5%84%E6%BA%90%E5%BC%95%E5%85%A5%E4%B8%BA%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84

此外，推荐你使用electron-store这些库来处理程序配置。

**Comment by TeddyQ** [comment]
import { cName, serverIp } from '../../../../resources/config/config.json??asset&asarUnpack'的方式没有测试成功，
用electron-store可以了，谢谢！

**Comment by islet-recover** [comment]
> import { cName, serverIp } from '../../../../resources/config/config.json??asset&asarUnpack'的方式没有测试成功， 用electron-store可以了，谢谢！

你用electron store 实现了外置配置文件么？
