### ISSUE TITLE
ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by RitchieP** [alex8088/electron-vite#196]
### Describe the bug

I'm trying to use ElectronJS's showOpenDialog to select a directory. However, when I try to do 

```js
import { dialog } from 'electron'
```

My web console gives me the error:

```bash
client.ts:112 ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (index.js:4:28)
    at __require (chunk-DFKQJ226.js?v=618a7a16:8:50)
    at index.js:21:34
```

I have also tried to follow the discussions with [this issue](https://github.com/electron/electron/issues/24005). But because they're mainly discussing VueJS, which probably has a different project structure than this electron-vite.

I have also tried to enable nodeIntegration inside `main/index.js` but no luck.

Appreciate it if anyone can help!

### Electron-Vite Version

1.0.22

### Electron Version

22.3.8

### Vite Version

4.3.5

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
- https://electron-vite.org/guide/dev.html#nodeintegration
- https://electron-vite.org/guide/dev.html#using-preload-scripts

**Comment by RitchieP** [comment]
So I guess I will need to handle the dialog functions in the main process and have preload script to invoke the showDialog function. Please correct me if I'm wrong.

Thanks @alex8088 for the links! Cleared my problem a lot.

**Comment by RitchieP** [comment]
I guess we can also move this issue to discussions since it's not actually a real issue itself in the repository.

**Comment by alex8088** [comment]
> So I guess I will need to handle the dialog functions in the main process and have preload script to invoke the showDialog function. Please correct me if I'm wrong.
> 
> Thanks @alex8088 for the links! Cleared my problem a lot.

yes

```ts
// main
import { dialog, ipcMain } from 'electron'

ipcMain.on('show-dialog', () => {
})
```

```ts
// renderer
window.electron.ipcRenderer.send('show-dialog')
```

**Comment by RitchieP** [comment]
Thanks for the help @alex8088!
