### ISSUE TITLE
mac build执行完成安装后，打开应用报错

### ISSUE THREAD

**Issue by DonXander** [alex8088/electron-vite#199]
### Describe the bug

<img width="372" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/39e2ca86-37bf-4432-8b4e-8dfeefc1cf0b">

打包的dist下面目录如图：
<img width="1032" alt="image" src="https://github.com/alex8088/electron-vite/assets/25742814/0c1342d5-658a-4aac-86c8-aab42bcfa897">

mac目录下只有应用程序，没有其他文件。请问asarUnpack配置对mac是不生效吗

### Electron-Vite Version

1.0.23

### Electron Version

20.3.1

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
看文档故障排除章节

**Comment by DonXander** [comment]
preview正常，打包后异常。使用npm构建有个报错，我使用的是cnpm，这是否会影响

**Comment by DonXander** [comment]
现在执行npm构建也可以

**Comment by alex8088** [comment]
> preview正常，打包后异常。使用npm构建有个报错，我使用的是cnpm，这是否会影响

建议不要使用cnpm

**Comment by DonXander** [comment]
直接用npm会报错。使用cnpm安装，npm来打包会有上面截图的问题，一堆的module找不到
