### ISSUE TITLE
[提问]请问想引入electron addon，该怎么做

### ISSUE THREAD

**Issue by SD-Gaming** [alex8088/electron-vite#2]
### Clear and concise description of the problem

比如有一个 addon.node 文件，我要在preload/index.ts或者renderer/src/main.ts引入，

应该放在那个位置？以及在哪里增加什么配置才可以在开发模式和生产模式下正确引入?

### Suggested solution

对vite不熟悉，希望有一个模板指引由此需求的人🙏

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
- node  addon 最好在主进程（main）中使用，渲染可以通过preload的暴露的ipc去使用
- 外部依赖排除, 举例
```
export default defineConfig({
  main: {
    build: {
      rollupOptions: {
        external: ['@electron-toolkit/utils']
      }
    }
  }
)
```

**Comment by alex8088** [comment]
@SD-Gaming 你的建议不错，对原生插件这一块我会补充指引或者示例

**Comment by caoxiemeihao** [comment]
preload、renderer 这两个属于同一类，vite 没办法重新构建 node-native addon  
可以通过 `require('native-addon') 的方式避开 vite 构建

**Comment by SD-Gaming** [comment]
> preload、renderer 这两个属于同一类，vite 没办法重新构建 node-native addon 可以通过 `require('native-addon')` 的方式避开 vite 构建

是的，放在public文件夹中，直接require('./addon-path')就可以了
