### ISSUE TITLE
设计疑问：.env.development 的变量仅对渲染器可用

### ISSUE THREAD

**Issue by joyexpr** [alex8088/electron-vite#20]
### Clear and concise description of the problem

这两天在做不同环境分别打包的预研工作，包括但不限于开发环境、测试环境 、生产环境，

在阅读关于[环境变量和模式的文档](https://cn-evite.netlify.app/guide/env-and-mode.html)，看到说开发环境，即.env.development 的变量仅对渲染器可用

想请问为什么开发环境不允许对main和preload进行变量替换，这么特殊设计的原因是什么？有没有配置修改这个特性

### Suggested solution

是否可以取消这个特殊性，如果开发环境不需要变量替换，不写进.env.development即可

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@joyexpr 在开发中，实际 main 和 preload scripts 都是基于 vite 的 build（production）方式构建的，所以你可以看见out是有文件输出，而renderer则是开启了一个开发服务即是vite dev（devlopment），我这里没有考虑破坏保持vite的设计，所以会有这种特殊性存在，但实际上是可以打破的，就是通过cli选项 --mode 来指定，则无论底层执行 vite的是开发dev指令还是生产build指令都有效。

你提出的，实际也是值得考虑的（避免理解和使用混乱），即是 dev 指令的默认模式都统一为 devlopment，但可能需要对此产生的副作用考究一下。

目前，可以通过--mode选项来统一应用变量解决问题

**Comment by joyexpr** [comment]
了解了，其实是不是我们可以把 electron-vite dev 中的dev可以看成是对electron-vite而言，而非对vite。

否则根据（实际 main 和 preload scripts 都是基于 vite 的 build（production）方式构建的），那在electron-vite dev时，是否main的preload 要根据 .env.production 来进行变量替换（目前应该没有这么做吧？），而这会引起更大的理解和使用混乱

--mode方式有考虑过，我原来就有计划使用--mode dev 和 .env.dev 来代替development，避免混乱，只是想了解下您目前这样设计的原由。

但顺便再确认下呀，目前使用 --mode developemnt 是否就可以强制 main、preload、renderer 使用.env.development进行变量替换？

**Comment by alex8088** [comment]
上面的问题也存在，确实混乱，待我考究一下，完善这部分能力，--mode会全部生效的

**Comment by joyexpr** [comment]
> 上面的问题也存在，确实混乱，待我考究一下，完善这部分能力，--mode会全部生效的

试了下好像不行呀，我做了以下步骤
1. 工程根目录下放了.env.development（dev和production也试过，一样），内容为MAIN_VITE_SOME_KEY=123develop 等
2. package.json里dev指令改成"dev": "electron-vite dev --mode=development",
3. main/index.ts里打印变量：console.log(import.meta.env.SOME_KEY)
发现打印出来SOME_KEY的值是null

**Comment by alex8088** [comment]
@joyexpr 变量引用不正确 import.meta.env.MAIN_VITE_SOME_KEY，前缀不能是省

**Comment by joyexpr** [comment]
> @joyexpr 变量引用不正确 import.meta.env.MAIN_VITE_SOME_KEY，前缀不能是省

发现了，但又发现在默认模式下（即不设--mode），main进程还是可以从.env.development中提取变量，和文档里写的不一样

**Comment by alex8088** [comment]
> > @joyexpr 变量引用不正确 import.meta.env.MAIN_VITE_SOME_KEY，前缀不能是省
> 
> 发现了，但又发现在默认模式下（即不设--mode），main进程还是可以从.env.development中提取变量，和文档里写的不一样。但和我一开始期望倒变得一致
@joyexpr 
我也发现了，一开始设计就没有问题 ，回看我的测试用例有问题导致误判，待我重整一下文档，感谢

**Comment by alex8088** [comment]
文档已修正

**Comment by keyiis** [comment]
@alex8088 请问如果我想在main/renderer/preload共享一个环境变量，那是不是得像下面这样把这个变量定义三遍？
```
MAIN_VITE_SOME_KEY=123      # 主进程可用
PRELOAD_VITE_SOME_KEY=123   # 预加载脚本可用
RENDERER_VITE_SOME_KEY=123  # 渲染器可用
```
这样感觉很变扭，个人感觉没必要用前缀区分，或者有一种前缀是不限制作用范围的，也就是在main/renderer/preload都可以访问到

**Comment by alex8088** [comment]
@keyiis 前缀是少不了的，这是vite对于安全性的考虑，当然你可以通过`envPrefix`定义成同一个前缀共享 https://cn-evite.netlify.app/guide/env-and-mode.html#%E5%85%A8%E5%B1%80%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by keyiis** [comment]
@alex8088 谢谢解答！如果能保留一个共享前缀那就更好了:)，此外如果我想修改主进程import.meta.env的默认替换操作，该如何入手？我在您的代码里没有找到相关的内容

**Comment by alex8088** [comment]
@keyiis 你可以将它们都设置成同一个前缀，你提的第二点没理解你需求。
