### ISSUE TITLE
在.env中配置了主进程的变量，但是在主进程中并不能获取到对应的值

### ISSUE THREAD

**Issue by bzw1204** [alex8088/electron-vite#202]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/9693637/e11c557f-bcb1-4fef-821a-fa4a96389608)
![image](https://github.com/alex8088/electron-vite/assets/9693637/95c63c5e-c4f5-42ed-801f-3c6db52fa8a1)
![image](https://github.com/alex8088/electron-vite/assets/9693637/b68a0375-a7cf-4ecb-9c02-fd7a276a106f)
问题描述如上图所示

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by 1zilc** [comment]
正好遇到同样的问题，不过我是用cross-env注入的，打包后`process.env`中变量丢失

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/env-and-mode.html

使用 `import.meta.env` 获取

**Comment by DipSyJava** [comment]
遇到同样问题,也以为是通过process.env获取
原来主进程也使用import.meta.env,
只是主进程中import.meta.env获取的是以MAIN_VITE_前缀的
渲染进程获取的是以RENDERER_VITE_为前缀的
感谢!
