### ISSUE TITLE
希望新增一个配置开发环境下的别名

### ISSUE THREAD

**Issue by guibieshubao** [alex8088/electron-vite#203]
### Describe the bug

我不太清楚是不是我自己不会配置，简略的说一下，在electron.vite.confg.js默认配置：                                                             renderer: {  resolve: {
      // 别名[无效]
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },}   ，实际上去组件中使用会发现
import { userStore } from '@/stores/userstore'这样会报错：[vite] Internal server error: this.yerror is not a function
  Plugin: vite:import-analysis 或是其他；我还通过在src/renderer/src单独设置vite.cofing.js，同样报错。  老哥没有别名开发很是苦恼

### Electron-Vite Version

^1.0.23

### Electron Version

^24.4.1

### Vite Version

^4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by guibieshubao** [comment]
好吧这不是一个bug,而是一个问题或需求

**Comment by alex8088** [comment]
@Renderer/stores/userstore
