### ISSUE TITLE
Default resolve condition "node" for preload causes incompatible node versions of modules to be loaded when nodeIntegration is disabled

### ISSUE THREAD

**Issue by shayded-exe** [alex8088/electron-vite#204]
### Describe the bug

Preload should not have "node" set as a resolve condition by default, as there's no way to disable it because vite's `mergeConfig` will merge arrays.

My preload uses the `uuid` module. Because of this condition, it bundles the node version module instead of the browser version, which breaks because it requires the `crypto` module and I have node integration disabled.

### Electron-Vite Version

1.0.24

### Electron Version

22

### Vite Version

4.1.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@shayded-exe I'm also thinking about this. You can externalize it first(`sandbox` needs to be disabled).

**Comment by shayded-exe** [comment]
Disabling sandbox isn't and option for me.

**Comment by alex8088** [comment]
The next version will remove this condition for preload.

**Comment by shayded-exe** [comment]
@alex8088 That doesn't overwrite the value though. Vite's `mergeConfig` concats the arrays.

See here:
https://github.com/vitejs/vite/blob/main/packages/vite/src/node/utils.ts#L1038

**Comment by alex8088** [comment]
new ver 1.0.25 is out!

**Comment by shayded-exe** [comment]
Thank you! 😃
