### ISSUE TITLE
app.asar.unpacked 这个名称是否可以修改

### ISSUE THREAD

**Issue by bzw1204** [alex8088/electron-vite#205]
### Describe the bug

1. 我在项目中的资源存储如下 
![image](https://github.com/alex8088/electron-vite/assets/9693637/5e58a453-ee29-4656-95c1-226b512c8cce)
我想在打包之后保持原样，请问如何配置
2. 我在electron-builder.yml 中 win: 下使用extraFiles 配置打包后并未按照预期进行文件复制
![image](https://github.com/alex8088/electron-vite/assets/9693637/3cbeae4e-b8d0-4a3b-8404-f50c5a7da4d3)

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
脚手架默认 配置electron-builder不将公共资源配置打包到asar，这个目录不可以改动。 

如果想通过electron-builder的extraFiles处理，资源就不一定要放在公共目录处理，打包的时候会按配置拷贝到对于位置。

如果放在公共目录建议阅读[资源处理章节](https://cn.electron-vite.org/guide/assets.html#%E5%B0%86%E8%B5%84%E6%BA%90%E5%BC%95%E5%85%A5%E4%B8%BA%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84)，去处理，也是非常简单的。

**Comment by bzw1204** [comment]
> 

好的，我试试
