### ISSUE TITLE
多窗口开发配置后未编译生成对应页面

### ISSUE THREAD

**Issue by New-Lanke** [alex8088/electron-vite#207]
### Describe the bug

我阅读了文档中 [多窗口应用程序](https://cn-evite.netlify.app/guide/dev.html#%E5%A4%9A%E7%AA%97%E5%8F%A3%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F)这一章节的内容，并按照其内容配置了我的`electron.vite.config.ts`，我配置了一个`Index`页面和一个`Music`页面。

## 疑问

但我在创建新窗口时遇到两个问题：
1. 如何使用开发服务器去访问新页面`Music`（loadURL方式）
2. 渲染进程的入口配置似乎未生效，编译后只生成了一个`index.html`，我无法通过loadFile去加载`music.html`页面

## 配置

`electron.vite.config.ts`

~~~ts
import react from '@vitejs/plugin-react'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import { resolve } from 'path'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()]
  },
  preload: {
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/preload/index.ts'),
          music: resolve(__dirname, 'src/preload/music.ts')
        }
      }
    },
    plugins: [externalizeDepsPlugin()]
  },
  renderer: {
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/renderer/index.html'),
          music: resolve(__dirname, 'src/renderer/music.html')
        }
      }
    },
    plugins: [react()]
  }
})

~~~

`music.html`
~~~html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Electron</title>
    <!-- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP -->
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"
    />
  </head>

  <body>
    <div id="root"></div>
    <script type="module" src="/src/music.tsx"></script>
  </body>
</html>

~~~

`music.tsx`

~~~tsx
import React from 'react'
import ReactDOM from 'react-dom/client'

export function Music() {

  return (
    <div>
      <audio></audio>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <Music />
  </React.StrictMode>
)

~~~

运行`pnpm dev`后`out`文件夹输出
![image](https://github.com/alex8088/electron-vite/assets/51505088/55dbe25d-bc41-4768-96c6-db12f644b8e3)

### Electron-Vite Version

^1.0.21

### Electron Version

^22.3.4

### Vite Version

^4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
参阅: https://electron-vite.org/guide/hmr.html
renderer页面输出需要build的时候才会构建。

**Comment by New-Lanke** [comment]
> 参阅: https://electron-vite.org/guide/hmr.html renderer页面输出需要build的时候才会构建

多页面开发时，有除了`build`外更简便的方式吗，比如类似`Webpack`的`watch`方式

**Comment by alex8088** [comment]
不是要构建出来才能调试开发的。开发模式下，不用build一样可以调试，无需watch，每次都去构建。build是开发完成要打包的时候才需要执行的。你需要了解一下vite的hmr。开发模式下开启dev server，通过loadUrl加载页面。打包即是build时通过loadFile加载实际打包后的页面

```ts
if (!app.isPackaged && process.env['ELECTRON_RENDERER_URL']) {
  mainWindow.loadURL(`${process.env['ELECTRON_RENDERER_URL']}/view.html`)
} else {
  mainWindow.loadFile(path.join(__dirname, '../renderer/view.html'))
}
```

**Comment by New-Lanke** [comment]
> 不是要构建出来才能调试开发的。开发模式下，不用build一样可以调试，无需watch，每次都去构建。build是开发完成要打包的时候才需要执行的。你需要了解一下vite的hmr。开发模式下开启dev server，通过loadUrl加载页面。打包即是build时通过loadFile加载实际打包后的页面
> 
> ```ts
> if (!app.isPackaged && process.env['ELECTRON_RENDERER_URL']) {
>   mainWindow.loadURL(`${process.env['ELECTRON_RENDERER_URL']}/view.html`)
> } else {
>   mainWindow.loadFile(path.join(__dirname, '../renderer/view.html'))
> }
> ```

好的，谢谢
