### ISSUE TITLE
Forge does not work

### ISSUE THREAD

**Issue by Andrew-web-coder** [alex8088/electron-vite#208]
### Describe the bug

I am following these steps - https://electron-vite.org/guide/distribution.html#distributing-apps-with-electron-forge

I am receiving this error message:

```
An unhandled rejection has occurred inside Forge:
Error: The main entry point to your app was not found. Make sure "app\out\main\index.js" exists and does not get ignored by your ignore option
at Object.validateElectronApp (app\node_modules\electron-packager\src\common.js:115:13)
```
But:

1) That file exists
2) I have not touched "ignore" option and I believe that it is not causing an issue

### Electron-Vite Version

latest

### Electron Version

latest

### Vite Version

latest

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/#electron-entry-point

**Comment by Andrew-web-coder** [comment]
@alex8088 Yes, it is like this - `"main": "./out/main/index.js",`

**Comment by alex8088** [comment]
> app\node_modules\electron-packager\src\

**Comment by SaekiRaku** [comment]
Same issue here, not monorepo project. And no difference between using `npm` and `pnpm`.
Here is something I tried to dig in, I found that `out` dir was not copied to the `electron-packager`.

<img width="1440" alt="截屏" src="https://github.com/alex8088/electron-vite/assets/12109558/ca6734f6-f398-4f3b-a3d5-ae424feaf82b">

**Comment by alex8088** [comment]
Forge's default packaging ourdir is `out`, which conflicts with `electron-vite`.  Change `outDir` to `dist`

```json
"main": "./dist/main/index.js",
"scripts": {
  "dev": "electron-vite dev--outDir=dist",
  "package": "electron-vite build  --outDir=dist && electron-forge package",
  "make ": "electron-vite build --outDir=dist && electron-forge make"
},
```

**Comment by alex8088** [comment]
I try this:

```js
// forge.config.cjs
module.exports = {
  packagerConfig: {
    out: 'dist'
  }
}
```

but not work.  It is always output in the `out` directory. I don't know if it is a bug of Forge

**Comment by SaekiRaku** [comment]
> I try this:
> 
> 
> 
> ```js
> 
> // forge.config.cjs
> 
> module.exports = {
> 
>   packagerConfig: {
> 
>     out: 'dist'
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> but not work.  It is always output in the `out` directory. I don't know if it is a bug of Forge

Forge forbid to override the `out` field. see https://www.electronforge.io/config/configuration#electron-packager-config

> You can not override the dir, arch, platform, out or electronVersion options as they are set by Electron Forge internally.

**Comment by alex8088** [comment]
check out https://electron-vite.org/guide/distribution.html#distributing-apps-with-electron-forge
