### ISSUE TITLE
base config for renderer  doesn't work on build process. 

### ISSUE THREAD

**Issue by etorres1193** [alex8088/electron-vite#209]
### Describe the bug

When "base" property is set for renderer config, renderer dist folder doesn't add base path to index.html.

![image](https://github.com/alex8088/electron-vite/assets/21205250/dcb1710f-6ff9-4dfe-8d2d-c1922a54def6)

![image](https://github.com/alex8088/electron-vite/assets/21205250/551f39f5-0709-4fc4-9950-4a106435c137)

This is usefull when you want to deploy renderer dist folder as PWA for testing case on a server without building an app,  
example: http://server.example/myapp/

### Electron-Vite Version

1.0.24

### Electron Version

25.2.0

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@etorres1193 `base` not work with Electron. It is recommended that you add a vite configuration to build for testing.

```ts
import { defineConfig } from 'electron-vite'
import renderer from './vite.config'

export default defineConfig({
  main: {
    // ...
  },
  preload: {
    // ...
  },
  renderer
})
```
