### ISSUE TITLE
[缺陷] 贴边的窗口被 HMR 重置了位置

### ISSUE THREAD

**Issue by grandsong** [alex8088/electron-vite#21]
## 概述

我在windows 10系统里，把electron窗口拖动到最右边，系统会把它贴边——高度变成屏幕高度、宽度为屏幕宽度的一半。

意义：我把代码编辑器贴边到屏幕的另一半。这样就可以同时看到双方。

但，当我修改了 src\renderer\src\main.ts 时，触发了模块热替换的瞬间，electron 窗口会取消贴边——其位置和尺寸会变成贴边操作之前的状态。

## 如何重现？

我是刚刚用 pnpm create @quick-start/electron 创建的全新的项目。

之后我做的修改如下：

1. 把依赖的 electron 版本升级到最新的 20.1.4
2. 开启了主进程的热重载。即，`"dev": "electron-vite dev --watch",`
3. 在 src\renderer\src\main.ts 里，添加了 `console.log(6)` 。 ——修改该数字以触发并确认 HMR 生效。

### Electron-Vite Version

1.0.8

### Electron Version

20.1.4

### Vite Version

3.1.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
理解你的意图，主进程是通过热重载（重启进程）来实现，实际上很难做到无感热重载，从工具本身入手记忆位置实则是难实现的。

但你提的对改善开发体验还是有一定意义的，也值得研究，也许可以通过插件之类的来完善，待研究

Thanks

**Comment by grandsong** [comment]
等等，你好像理解错了……
主进程的热重载 应该跟这个缺陷没有关系；它发生在渲染的 HMR。
窗口**并没有**被重启（那才是热重载，而我也实际尝试过了），而只是在内容变化的同时变化了位置和尺寸。

**Comment by grandsong** [comment]
我之所以详细列出了所有修改，仅仅是为了严谨。实际上我并不认为它们跟这个缺陷有关系。
我有对electron应用的不少开发经验，也有自己的开发框架，而我的HMR并不会导致窗口的属性（贴边与否）发生变化。
从道理上讲，渲染的main.ts修改后，应该只是刷新整个网页，相当于在普通浏览器里按F5，而这不应该影响作为容器的窗口。
我猜想，你并不是仅仅刷新了网页？

**Comment by alex8088** [comment]
> 我之所以详细列出了所有修改，仅仅是为了严谨。实际上我并不认为它们跟这个缺陷有关系。 我有对electron应用的不少开发经验，也有自己的开发框架，而我的HMR并不会导致窗口的属性（贴边与否）发生变化。 从道理上讲，渲染的main.ts修改后，至多不过是刷新整个网页，相当于在普通浏览器里按F5，而这不应该影响作为容器的窗口。 我猜想，你并不是仅仅刷新了网页？

嗯嗯~，我看漏了，如果改动的是renderer的main文件，确实是hmr，待我测试看看，谢谢

**Comment by alex8088** [comment]
![test1](https://user-images.githubusercontent.com/25053004/190885693-2a938811-77bf-4fdd-b3c8-201ed8c8e905.gif)

@grandsong，我测试并没有此问题，你确认改动的是renderer的文件而不主进程代码。

**Comment by alex8088** [comment]
不过我这里的electron是19的版本

**Comment by alex8088** [comment]
在20版本下测试，也未发现此问题

**Comment by grandsong** [comment]
我修改的是 src\renderer\src\main.ts 啊。
我刚刚又试了一下。哪怕我仅仅是保存该文件（而没有修改其内容），都会触发HMR并导致窗口失去贴边……
和你录屏里一样，在vscode终端里显示`[vite] page reload src/main.ts`

--

此外，我还发现，在保存文件、触发HMR时，有以下情况：

- 第一次，vscode不受影响，而在windows底部的任务栏里，electron窗口对应的按钮会闪烁。
- 第二次，electron窗口获得焦点；相应地，vscode编辑器会失去焦点。这也是个小麻烦。

--

我试着修改了packages.json，去掉了主进程热重载的`--watch`参数。然后证实了，热重载跟本缺陷无关。

--

另外，为什么在你的录屏里，electron窗口没有标题栏？贴边应该不会导致隐藏标题栏啊。

--

注：我的操作系统是 win 10。屏幕分辨率为 2560 * 1440 。

**Comment by grandsong** [comment]
修改 App.vue 则没有这个问题。看来 main.ts 是特殊的……

**Comment by grandsong** [comment]
main.ts 不会经常修改，所以这个小缺陷优先级低。你不修复也不要紧。
我只是好奇为什么会如此……

**Comment by alex8088** [comment]
我的录屏软件不能全屏，所以看不到标题栏。在linux和mac下测试都是正常，不知是否和electron本身有关，可能得找个高分windows测试一下，或者看有其他人反馈类似问题。

谢谢的反馈。
