### ISSUE TITLE
build 报错

### ISSUE THREAD

**Issue by hbb520** [alex8088/electron-vite#213]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/22811157/a9e581ef-e566-4fcd-a4ed-18f8e91b5c7f)

### Electron-Vite Version

最新

### Electron Version

最新

### Vite Version

最新

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
本地nodejs版本过低

**Comment by alex8088** [comment]
"node": "^14.18.0 || >=16.0.0"
