### ISSUE TITLE
Cannot destructure property 'ipcRenderer' of 'window.electron' as it is undefined.

### ISSUE THREAD

**Issue by msbadreldin** [alex8088/electron-vite#216]
### Describe the bug

I'm using react template and it works well in electron app, however in browser i got this error message:
Cannot destructure property 'ipcRenderer' of 'window.electron' as it is undefined.

in app.tsx i do import ipcRenderer from window.electron
const { ipcRenderer } = window.electron

and here is my preload script:
if (process.contextIsolated) {
  try {
    contextBridge.exposeInMainWorld('electron', electronAPI)
    contextBridge.exposeInMainWorld('api', api)
  } catch (error) {
    console.error(error)
  }
} else {
  // @ts-ignore (define in dts)
  window.electron = electronAPI
  // @ts-ignore (define in dts)
  window.api = api
}
and main.ts is the same as template with no changes

### Electron-Vite Version

1.0.23

### Electron Version

25.2.0

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
electron module(preload script) cannot  work in a browser.
