### ISSUE TITLE
yarn create @quick-start/electron my-app --template vue-ts error

### ISSUE THREAD

**Issue by li1753846989** [alex8088/electron-vite#217]
### Describe the bug

使用yarn create @quick-start/electron my-app --template vue-ts进行项目的创建，提示报错并创建失败，但npm可以成功创建项目
运行环境：
```
node: 16.17.0
yarn: 1.22.19
window: win11 22621.1992
```
log: 
```
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⠁ waiting...
[-/5] ⠁ waiting...
[3/5] ⠁ nodemon
[-/5] ⠁ waiting...
error C:\Users\xxx\AppData\Local\Yarn\Data\global\node_modules\windows-build-tools: Command failed.
Exit code: 1
Command: node ./dist/index.js
Arguments:
Directory: C:\Users\xxx\AppData\Local\Yarn\Data\global\node_modules\windows-build-tools
Output:
Downloading vs_BuildTools.exe
[============================================>] 100.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\xxx\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
```

### Electron-Vite Version

*

### Electron Version

*

### Vite Version

*

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
这貌似是yarn 问题，yarn 更新 create 模块报错问题

**Comment by li1753846989** [comment]
好的,那就不是脚手架的问题

**Comment by li1753846989** [comment]
原因: 安装windows-build-tools卡住
解决方案: https://github.com/felixrieseberg/windows-build-tools/issues/244#issuecomment-824213136
