### ISSUE TITLE
Is there a way to include extra resources at compile time?

### ISSUE THREAD

**Issue by ryusei-48** [alex8088/electron-vite#218]
### Describe the bug

Hello. I am developing the following offensive
```
project-root
| -- build/
| -- compiled/
| -- dist/
| -- node_modules/
| -- src/
     | -- main/
          | -- extra_resources/ # exe binary, dll, txt, sqlite file and same directory etc ....
          | -- main.ts
     | -- preload/
     | -- renderer/
| --　・・・・・
| -- electron.vite.config.dev.ts
| -- electron.vite.config.prod.ts
| -- 　・・・・・・
```

For example, the contents of `electron.vite.config.prod.ts` are as follows
``` typescript
import { bytecodePlugin, defineConfig, externalizeDepsPlugin } from 'electron-vite';
import React from "@vitejs/plugin-react";
import { resolve } from 'path';
import sass from "vite-plugin-sass-dts";

export default defineConfig({
  main: {
    plugins: [
      externalizeDepsPlugin(),
      bytecodePlugin({ protectedStrings: [ "ready-to-show" ] })
    ],
    build: {
      minify: true,
      outDir: './compiled/main'
    }
  },
  preload: {
    plugins: [
      externalizeDepsPlugin(),
      bytecodePlugin()
    ],
    build: {
      minify: true,
      outDir: './compiled/preload'
    }
  },
  renderer: {
    build: {
      minify: true, chunkSizeWarningLimit: 2000,
      cssCodeSplit: true,
      outDir: resolve(__dirname, 'compiled/renderer'),
      rollupOptions: {
        input: {
          main: resolve(__dirname, './src/renderer/index.html')
        }
      }
    },
    plugins: [ React({ jsxImportSource: '@emotion/react' }), sass() ]
  }
})
```

How can I make the `compiled/main` folder contain a set of `extra_resources/` folders?

### Electron-Vite Version

1.0.24

### Electron Version

25.2.0

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/assets.html

**Comment by ryusei-48** [comment]
Thanks for the answer. I had missed the description in the documentation.

However, the issue is still unresolved. I have tried modifying the relevant part of the configuration file as follows, but the `extra_resources` directory is not copied.

``` typescript
// ・・・・・・
main: {
    publicDir:  join(__dirname, './src/main/extra_resources'),  // added code
    plugins: [
      externalizeDepsPlugin(),
      bytecodePlugin({ protectedStrings: [ "ready-to-show" ] })
    ],
    build: {
      minify: true,
      outDir: './compiled/main',
      copyPublicDir: true   // added code
    }
  }
// ・・・・・・

```

By default, it seems that `<project-root>/public` is automatically detected and copied to `outDir`, but when I tried that, the result was the same.

Is there something I am missing?
Or is it a bug?

**Comment by alex8088** [comment]
https://electron-vite.org/guide/assets.html#importing-asset-as-file-path

**Comment by alex8088** [comment]
- All assets in public directory are not copied to output directory. So when packaging the app, the public directory should be packaged together.
- It is recommended to use the ?asset suffix to import public assets.

**Comment by ryusei-48** [comment]
I guess I was mistaken. My apologies.

The app I am currently working on required Python to run on Electron. That is why I wanted to include the Python itself and an external package.

I thought about the `main/extra_resources` directory as a place to bundle them, but I guess that wasn't appropriate.

The Python related components should be set as `extra resources` when packaging with `electron-builder` and included in the installer.

Thank you for your time.
