### ISSUE TITLE
[help]为什么我在main文件夹下面创建的js文件没有被打包到out文件夹下，导致找不到文件。

### ISSUE THREAD

**Issue by QuiteAlive** [alex8088/electron-vite#22]
### Describe the bug

为什么我在main文件夹下面创建的js文件没有被打包到out文件夹下，导致找不到文件。
![image](https://user-images.githubusercontent.com/36289522/190861883-7d57278c-ca7c-4c64-88b2-7a1616d4731f.png)
![image](https://user-images.githubusercontent.com/36289522/190861946-144ab2b2-f35d-4c1e-a19c-1f96e532e965.png)

### Electron-Vite Version

1.0.8

### Electron Version

19.0.14

### Vite Version

3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@QuiteAlive  websocket.js 是如何导入到 index.js中的？

**Comment by QuiteAlive** [comment]
@alex8088 const myChildProccess = require('child_process')
myChildProccess.fork(path.join(__dirname, './websocket.js'))

**Comment by alex8088** [comment]
> @alex8088 const myChildProccess = require('child_process') myChildProccess.fork(path.join(__dirname, './websocket.js'))

实际是将websocket.js当成插件使用，构建工具无法识别其为依赖，可以向下面一样处理：

```
├──plugins/
│  └── websocket.js
├──src/
│  ├──main 
│  ├──preload  
│  └──renderer
└──package.json
```
然后正确处理调用路径，就可以了

ps：调用一些可执行程序也是这样处理的

**Comment by QuiteAlive** [comment]
完美，谢谢解答！

> > @alex8088 const myChildProccess = require('child_process') myChildProccess.fork(path.join(__dirname, './websocket.js'))
> 
> 实际是将websocket.js当成插件使用，构建工具无法识别其为依赖，可以向下面一样处理：
> 
> ```
> ├──plugins/
> │  └── websocket.js
> ├──src/
> │  ├──main 
> │  ├──preload  
> │  └──renderer
> └──package.json
> ```
> 
> 然后正确处理调用路径，就可以了
> 
> ps：调用一些可执行程序也是这样处理的

**Comment by alex8088** [comment]
good job!

**Comment by jx-zyf** [comment]
> 完美，谢谢解答！
> 
> > > @alex8088 const myChildProccess = require('child_process') myChildProccess.fork(path.join(__dirname, './websocket.js'))
> > 
> > 
> > 实际是将websocket.js当成插件使用，构建工具无法识别其为依赖，可以向下面一样处理：
> > ```
> > ├──plugins/
> > │  └── websocket.js
> > ├──src/
> > │  ├──main 
> > │  ├──preload  
> > │  └──renderer
> > └──package.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后正确处理调用路径，就可以了
> > ps：调用一些可执行程序也是这样处理的

请问plugins中的js，在主进程中的调用路径怎么处理？

**Comment by alex8088** [comment]
> > 完美，谢谢解答！
> > > > @alex8088 const myChildProccess = require('child_process') myChildProccess.fork(path.join(__dirname, './websocket.js'))
> > > 
> > > 
> > > 实际是将websocket.js当成插件使用，构建工具无法识别其为依赖，可以向下面一样处理：
> > > ```
> > > ├──plugins/
> > > │  └── websocket.js
> > > ├──src/
> > > │  ├──main 
> > > │  ├──preload  
> > > │  └──renderer
> > > └──package.json
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 然后正确处理调用路径，就可以了
> > > ps：调用一些可执行程序也是这样处理的
> 
> 请问plugins中的js，在主进程中的调用路径怎么处理？ @QuiteAlive @alex8088

https://cn.electron-vite.org/guide/assets#将资源引入为文件路径

**Comment by jx-zyf** [comment]
> > > 完美，谢谢解答！
> > > > > @alex8088 const myChildProccess = require('child_process') myChildProccess.fork(path.join(__dirname, './websocket.js'))
> > > > 
> > > > 
> > > > 实际是将websocket.js当成插件使用，构建工具无法识别其为依赖，可以向下面一样处理：
> > > > ```
> > > > ├──plugins/
> > > > │  └── websocket.js
> > > > ├──src/
> > > > │  ├──main 
> > > > │  ├──preload  
> > > > │  └──renderer
> > > > └──package.json
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 然后正确处理调用路径，就可以了
> > > > ps：调用一些可执行程序也是这样处理的
> > 
> > 
> > 请问plugins中的js，在主进程中的调用路径怎么处理？ @QuiteAlive @alex8088
> 
> [https://cn.electron-vite.org/guide/assets#将资源引入为文件路径](https://cn.electron-vite.org/guide/assets#%E5%B0%86%E8%B5%84%E6%BA%90%E5%BC%95%E5%85%A5%E4%B8%BA%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84)

好的，我试试，感谢解答
