### ISSUE TITLE
Configure Jest with Path Alias

### ISSUE THREAD

**Issue by dw-acc** [alex8088/electron-vite#222]
### Describe the bug

For the life of me I can't get Jest to work with `@renderer` path alias

My tsconfig.web.json
![image](https://github.com/alex8088/electron-vite/assets/136799983/c6ca85e1-e4d9-4fcd-916c-e91c91ea657e)

My jest.config.ts
![image](https://github.com/alex8088/electron-vite/assets/136799983/81ab39a8-cbb1-4839-9b3f-b1fb4b0091de)

### Electron-Vite Version

1.0.22

### Electron Version

24.6.2

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
```js
moduleNameMapper: {
   "^@renderer/(.*)$": "<rootDir>/src/renderer/src/$1",
},
```

**Comment by dw-acc** [comment]
@alex8088  thank you for the quick reply, but that does not appear to work. I still get the following errors when running the tests

`Cannot find module '@renderer/store/hooks' or its corresponding type declarations.`

**Comment by hoangvu12** [comment]
Have you found the solution?

**Comment by yun77op** [comment]
add this snippet to your configuration. it's working on my local environment.

```
transform: {
    "^.+\\.(ts|tsx)$": [`ts-jest`, { tsconfig: 'tsconfig.web.json' }]
},
```

make sure ts-jest consuming the correct tsconfig file
