### ISSUE TITLE
开发状态下访问本地文件

### ISSUE THREAD

**Issue by H-xie** [alex8088/electron-vite#223]
### Clear and concise description of the problem

electron-vite 为桌面程序开发提供了便利的开始。但是开发的时候也遇到了一些问题。

在 `npm run dev` 启动的开发模式下，无法直接载入本地文件。从开发工具看，本地文件的地址被加上了 `http://127.0.0.0:xxx/C:/xxx` 的形式。尝试在地址前加上 `file:///C:/xxx` 也会报错

`Not allowed to load local resource`

但是使用原始的 Electron 没有这个情况。

在 npm start 启动的程序，没有这个问题。可以访问本地文件。但是每次修改就要重新打包，就有点麻烦了。

所以，希望能够增加，开发状态下 （`npm run dev`）的本地访问功能。

### Suggested solution

None

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
对于本地资源文件(比如，主进程传递给渲染进程的文件地址)必须以file协议处理。高版本electron默认启用webSecurity。处理方式两种:
- 禁用窗口属性 webSecurity，支持file协议
- 自定义协议处理，这是推荐的做法，如 app://icon.png 参考 #36 

对于renderer本身的资源和web开发一致无需特殊处理，比如public资源或者通过 `?url` 导入的资源，都会正常处理。
