### ISSUE TITLE
Can not run packaged macos dmg 

### ISSUE THREAD

**Issue by geohuz** [alex8088/electron-vite#224]
### Describe the bug

The application window shows the following error:
```
Unexpected Application Error!
404 Not Found
```

The app runs without any problem in development mode,  set ```export CSC_IDENTITY_AUTO_DISCOVERY=false``` to skip the code sign to build the dmg.

### Electron-Vite Version

 "electron-vite": "^1.0.25",

### Electron Version

"electron": "^25.3.1",   "electron-builder": "^23.6.0",

### Vite Version

 "vite": "^4.4.2"

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by geohuz** [comment]
Running in preview mode I saw the following error: ```Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.```

**Comment by alex8088** [comment]
How to load your html file?

**Comment by geohuz** [comment]
I'm using the vitejs react scaffolder to develop then moved to vite-electron, create a project then copy the filed from old project over into render, I'm not sure if the index.html has any problem:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Tree Org</title>
    <!-- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP -->
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self'; img-src 'self' data:; font-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'"
    />
  </head>

  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
```

slightly changes in the content security rules for loading fonts and images.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/hmr.html#using-hmr

**Comment by alex8088** [comment]
recommend https://electron-vite.org/guide/#scaffolding-your-first-electron-vite-project

**Comment by geohuz** [comment]
yeah I'm using ``yarn create @quick-start/electron`` to create the project, then moved my original vitejs source code into ``src/renderer``,  running nicely in development. here is the project structure:

<img width="234" alt="Screenshot 2023-07-21 at 12 03 36" src="https://github.com/alex8088/electron-vite/assets/730770/10e13c37-0fa4-4c54-8add-cbbb2e695bcd">

the hmr part in main/index.js is unchanged:

```
 // HMR for renderer base on electron-vite cli.
  // Load the remote URL for development or the local html file for production.
  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
...
```

**Comment by alex8088** [comment]
what is the preview mode?

**Comment by geohuz** [comment]
Sorry it is in the package.json:

```
"start": "electron-vite preview",
```

I suspect the issue is with react-router, still trying to figure out...

**Comment by geohuz** [comment]
My issue is with the react-router, change the router to hashrouter fix the issue. 

Thanks!
