### ISSUE TITLE
Unable to bind breakpoints in VSCode

### ISSUE THREAD

**Issue by mtoso** [alex8088/electron-vite#226]
### Describe the bug

When a breakpoint is set doesn't get bound. When the debugger start it doesn't stop on the breakpoint.

### Electron-Vite Version

1.0.25

### Electron Version

25.3.1

### Vite Version

4.4.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
What does your `launch.json` configuration look like? Does your console have any other information?

Docs: https://electron-vite.org/guide/debugging.html#vscode

**Comment by mtoso** [comment]
Sorry I should I have provided more info. My bad.
The content of `launch.json` is the same as in the link you provided. I created the base project using
`npm create @quick-start/electron my-app -- --template react`
The only change I made is switching to Forge following the docs here https://electron-vite.org/guide/distribution.html#distributing-apps-with-electron-forge
Now I have a new `--outDir=build` and I think the issue with the debugger is that the source maps are not created anymore or at least I don't see them in the `build` dir.

**Comment by alex8088** [comment]
Whether to set the `main` field of package.json to `./build/main/index.js`?

**Comment by mtoso** [comment]
Yes I did that... it is set to `"main": "./build/main/index.js"` .
And these are the scripts I have"
```
        "dev": "electron-vite dev --outDir=build",
        "format": "prettier --write .",
        "lint": "eslint . --ext .js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix",
        "make": "electron-vite build --outDir=build && electron-forge make",
        "package": "electron-vite build --outDir=build && electron-forge package",
        "start": "electron-vite preview --outDir=build",
```
I would expect to have a `./build/main/index.js.map` but I don't and I think that is the issue. I am not sure how to force that

**Comment by mtoso** [comment]
I fixed it. I had to add the same value of `outDir` option to the `launch.json` runtimeArgs:

` "runtimeArgs": ["--sourcemap", "--outDir=build"],`

Maybe it should be mentioned on the docs here: https://electron-vite.org/guide/debugging.html#vscode

**Comment by mtoso** [comment]
I fixed it. I had to add the same value of `outDir` option to the `launch.json` runtimeArgs:

` "runtimeArgs": ["--sourcemap", "--outDir=build"],`

Maybe it should be mentioned on the docs here: https://electron-vite.org/guide/debugging.html#vscode

**Comment by alex8088** [comment]
@mtoso , Thank you, i will add prompts in the debugging guide.
