### ISSUE TITLE
node_modules/app-builder-bin/linux/arm64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE Exit code:

### ISSUE THREAD

**Issue by learncodingforweb** [alex8088/electron-vite#228]
### Describe the bug

Steps followed

1. npm create @quick-start/electron, create myapp with react typescript
2. cd myapp && npm i
3. npm build:linux

on raspberrypi 4 getting error
**node_modules/app-builder-bin/linux/arm64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE Exit code:**

How to resolve issue?

### Electron-Vite Version

1.0.25

### Electron Version

24.6.2

### Vite Version

4.4.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Network problem, try again, or reinstal.

**Comment by learncodingforweb** [comment]
I tried multiple times, getting same issue again.
```
 electron-builder  version=23.6.0 os=6.1.21-v8+
  • loaded configuration  file=/home/camera/dev/desktop/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=arm64 electron=24.6.4 appOutDir=dist/linux-arm64-unpacked
  • building        target=AppImage arch=arm64 file=dist/desktop-1.0.0.AppImage
  • building        target=snap arch=arm64 file=dist/desktop_1.0.0_arm64.snap
  ⨯ snapcraft is not installed, please: sudo snap install snapcraft --classic  
  ⨯ /home/camera/dev/desktop/node_modules/app-builder-bin/linux/arm64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: /home/camera/dev/desktop/node_modules/app-builder-bin/linux/arm64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/camera/dev/desktop/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```
```
camera@camera:~/dev/desktop $ uname -a
Linux camera 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

```
camera@camera:~/dev/desktop $ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
**Does it support raspberry pi os and arm64 bit**

**Comment by alex8088** [comment]
You can try to check out the [electron-builder issue tracker](https://github.com/electron-userland/electron-builder/issues) to see.
