### ISSUE TITLE
使用@quick-start/electron，选择vanilla就没有vite吗？

### ISSUE THREAD

**Issue by like0413** [alex8088/electron-vite#229]
### Clear and concise description of the problem

我本想用HMR的

### Suggested solution

-

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
vanilla 下选择  js，推荐使用cjs 语法编写，也就无需vite构建，ts 下，则会加入 electron-vite.
