### ISSUE TITLE
文档网站的搜索功能不能用

### ISSUE THREAD

**Issue by joyexpr** [alex8088/electron-vite#23]
### Clear and concise description of the problem

发现[文档网站](https://cn-evite.netlify.app/guide/)的搜索功能不能用，不知道是还没空弄还是没注意到？

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/4078122/190957853-53c1cb80-95dc-4f26-bb3d-974b371fe4b9.png">

### Suggested solution

支持搜索

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
知道的，正在申请

**Comment by alex8088** [comment]
it works now!
