### ISSUE TITLE
debugging without IDEs e.g. Chrome DevTools

### ISSUE THREAD

**Issue by mtoso** [alex8088/electron-vite#231]
### Describe the bug

In electron, the `--inspect` can be used according to the docs https://www.electronjs.org/docs/latest/tutorial/debugging-main-process to open the chrome devtools.
Maybe this functionality is already present, but it is unclear how I can pass that option since all the commands run through the `electron-vite` package.
In my case, the reason why I would like to have the devtools is that my render process is not doin any direct request to the API, but it talks to the main process through IPC and the main process issues the calls to the API. In this case It would be useful to be able to see the Network tab of the devtools.

### Electron-Vite Version

1.0.25

### Electron Version

25.3.1

### Vite Version

4.4.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@mtoso ,
- It is recommended to debug with IDEs like VSCode. It's very easy. Check out https://electron-vite.org/guide/debugging.html for more details.
-  If you still want to debug without IDEs and use the Electron CLI args, you can follow  this now. https://electron-vite.org/guide/dev.html#passing-cli-arguments-to-electron-app
- electron-vite will supports `--inspect` and ` --inspect-brk` args.

**Comment by mtoso** [comment]
Hi,
yes I agree that using the IDE is more convenient but that is for using the debugger. As I mentioned I want to see the network requests and AFIK the debugger view in VSCode does not allow that. 
I guess I can try passing `--inspect` using  https://electron-vite.org/guide/dev.html#passing-cli-arguments-to-electron-app.
When you say `electron-vite will supports --inspect and  --inspect-brk args.` do you mean that you will add something specific? 

Thanks

**Comment by alex8088** [comment]
@mtoso Yes, it should be supported in the next version.

**Comment by mtoso** [comment]
@alex8088 Thank you, appreciate it.

**Comment by alex8088** [comment]
new ver 1.0.26 is out :tada:, 

check out

-  https://electron-vite.org/guide/cli.html#dev-options
-  https://electron-vite.org/guide/debugging.html#v8-inspector-e-g-chrome-devtools


https://github.com/alex8088/electron-vite/assets/25053004/54b963f1-49f6-4380-bcae-e1dba53c4c54
