### ISSUE TITLE
Still able to see source code inside dist/linux-unpacked/resources/, how to enable code protection against read

### ISSUE THREAD

**Issue by learncodingforweb** [alex8088/electron-vite#235]
### Describe the bug

Steps followed
    npm create @quick-start/electron, create myapp with react typescript
    cd myapp && npm i
    npm build:linux

**Still able to see source code inside dist/linux-unpacked/resources/, how to enable code protection against read.**

As mention in docs
**Compile to v8 bytecode to protect source code.**

To to make sure code protection against read.

### Electron-Vite Version

1.0.25

### Electron Version

24.6.2

### Vite Version

4.4.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Protect source code, but not your resources. 

- Public Directory: https://electron-vite.org/guide/assets.html#public-directory
- electron-builder unpack resourcesfrom asar archives by default，the reason: https://electron-vite.org/guide/distribution.html#limitations-of-asar-archives

**Comment by learncodingforweb** [comment]
How to make react app content secure by using Uglify / Obfuscator or encryption technique as you have provided provision  for code protection against read for node source code not render process, which include frontend ui code like reactjs.

```
import { defineConfig, bytecodePlugin } from 'electron-vite'

export default defineConfig({
  main: {
    plugins: [bytecodePlugin()]
  },
  preload: {
    plugins: [bytecodePlugin()]
  },
  renderer: {
    // ...
  }
})
```

**Comment by alex8088** [comment]
I think obfuscation don't have much protection, you can minify(`build.minify`) your code.

**Comment by xzifan** [comment]
Haven't tried it myself but I guess you could put the sensitive part of the logic into main process (Nodejs) instead of react frontend and use bytecode plugin.
