### ISSUE TITLE
electron-log transported console output with no styles

### ISSUE THREAD

**Issue by xzifan** [alex8088/electron-vite#236]
### Describe the bug

As i tried to start the electron instance with electron-vite, the console could not transport the output with colors. 
![image](https://github.com/alex8088/electron-vite/assets/34232484/a63b0b5c-da0a-4df7-aaa8-3fa648012837)

I did a bit research about it and I guess the styles were lost when converted from  `startElectron` [src/electron.ts#L139](https://github.com/alex8088/electron-vite/blob/master/src/electron.ts#L139).

It would work as I expected if I make this change.
```diff
-  const ps = spawn(electronPath, ['.'].concat(args))
+  const ps = spawn(electronPath, ['.'].concat(args), {stdio: 'inherit'})
-  ps.stdout.on('data', chunk => {
-  !inspect && chunk.toString().trim() && logger.info(chunk.toString())
-  })
-  ps.stderr.on('data', chunk => {
-    !inspect && chunk.toString().trim() && logger.error(chunk.toString())
-  })
+  // !inspect && chunk.toString().trim() && logger.info(chunk.toString())
+  // })
+  // ps.stderr.on('data', chunk => {
+  //  !inspect && chunk.toString().trim() && logger.error(chunk.toString())
+  //})
```

### Electron-Vite Version

1.0.22

### Electron Version

19.0.0

### Vite Version

4.0.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
new ver 1.0.26 is out :tada: 

fixed now
