### ISSUE TITLE
Uncaught TypeError: path.join is not a function

### ISSUE THREAD

**Issue by moxun33** [alex8088/electron-vite#24]
### Describe the bug

运行 `pnpm dev` 命令启动后报错
```js
browser-external:path:9 Module "path" has been externalized for browser compatibility. Cannot access "path.join" in client code.

get @ browser-external:path:9

index.js:4 Uncaught TypeError: path.join is not a function
    at node_modules/.pnpm/electron@19.0.17/node_modules/electron/index.js (index.js:4:23)
    at __require (chunk-FZ7BPVOU.js?v=697db4fb:12:50)
    at dep:electron:1:16
```
文件`node_modules/.pnpm/electron@19.0.17/node_modules/electron/index.js`的错误行

![image](https://user-images.githubusercontent.com/5940883/191399529-82488fbf-7fb6-43db-aa88-c1eba4edcd25.png)

### Electron-Vite Version

1.0.9

### Electron Version

19.0.17

### Vite Version

3.1.3

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
what is browser-external ?

**Comment by alex8088** [comment]
提供更多信息，可能可以帮助到

**Comment by moxun33** [comment]
> what is browser-external ?

我也不知。应该是在Electron+Vite中无法在渲染进程内import Node的内置模块，如果强行import的话Vite会报这个错。

**Comment by moxun33** [comment]
> 提供更多信息，可能可以帮助到，`配置信息`

1、配置是 `npm create @quick-start/electron`默认的，没改动。
2、只在 `App.tsx`引入`import path from 'path'`，然后就报上述的错误。

**Comment by alex8088** [comment]
@moxun33 在不开启nodeIntegration的情况下渲染进程是不能使用node模块的，如果开启了，也应该在配置中 external 排除node模块，但是不建议这样的开发方式，这是不安全，electorn 已经默认nodeIntegration集成功能关闭，也移除remote模块， 所以不应该包含node

**Comment by moxun33** [comment]
> @moxun33 在不开启nodeIntegration的情况下渲染进程是不能使用node模块的，如果开启了，也应该在配置中 external 排除node模块，但是不建议这样的开发方式，这是不安全，electorn 已经默认nodeIntegration集成功能关闭，也移除remote模块， 所以不应该包含node

OK。明白了。

**Comment by donglinkai** [comment]
> @moxun33 在不开启nodeIntegration的情况下渲染进程是不能使用node模块的，如果开启了，也应该在配置中 external 排除node模块，但是不建议这样的开发方式，这是不安全，electorn 已经默认nodeIntegration集成功能关闭，也移除remote模块， 所以不应该包含node

那我想使用node模块怎么办

**Comment by NotYoojun** [comment]
我们的项目都是打开 nodeIntegration 的，但是还是访问不了。如何在配置文件中排除 node 模块？
