### ISSUE TITLE
Unocss icon显示不出来

### ISSUE THREAD

**Issue by djkloop** [alex8088/electron-vite#240]
### Describe the bug

Unocss icon显示不出来

![image](https://github.com/alex8088/electron-vite/assets/21050914/5e53c0c4-a526-4567-9ad6-350a0cb3ed6e)

#### unocss.config.ts
```ts 
import { defineConfig, presetAttributify, presetIcons, presetUno, transformerDirectives, transformerVariantGroup } from 'unocss'

export default defineConfig({
  shortcuts: {
    'border-base': 'border-#aaa3',
    'border-box': 'border border-base rounded',
    'bg-main': 'bg-gray-400',
    'bg-base': 'bg-white dark:bg-hex-1a1a1a',
  },
  rules: [
    ['ydg', { '-webkit-user-select': 'none', 'user-select': 'none', '-webkit-app-region': 'drag' }],
    ['ndg', { '-webkit-app-region': 'no-drag' }],
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
  ],
  theme: {
    colors: {
      primary: '#1668dc',
    },
  },
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})

```

### Electron-Vite Version

1.0.25

### Electron Version

24.6.5

### Vite Version

4.4.7

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
csp 文件， index.html 文件头配置

**Comment by djkloop** [comment]
@alex8088  去掉可以了，谢谢。
