### ISSUE TITLE
Template with SvelteKit and electron-vite

### ISSUE THREAD

**Issue by burguela** [alex8088/electron-vite#242]
### Clear and concise description of the problem

Hello everyone! 

### I would like to propose a possibility to create a sveltekit app with electron-vite.

It appears to me that when sveltekit was officialy lauched the svelte community started to only adopts sveltekit instead of only svelte. The reason is that sveltekit can do everthing and more than just svelte. And with [adapter-static](https://github.com/sveltejs/kit/tree/master/packages/adapter-static) it is possible to easily create a SPA.

An example of the community only(mostly) adopting sveltekit is the library [Skeleton UI](https://github.com/skeletonlabs/skeleton/discussions/721).

### Problems with electron-vite and sveltekit

I tried to integrate sveltekit with electron-vite but i encountered the following problems and can't resolve them:

1. sveltekit uses "type": "module" in the package.json and electron adopts commonjs;
2. sveltekit build for "client" and "server" even with adapter-static. The renderer only accepts build.target = "chrome" or "es", and for the server sveltekit overwrite the target to "node";

### Suggested solution

As for now, i dont have a suggested solution.

Here is [my attempt to integrate electron-vite and sveltekit](https://github.com/burguela/electron-vite-sveltekit).

Thanks!

### Validations

- [x] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
#145
