### ISSUE TITLE
Integrate Sequelize

### ISSUE THREAD

**Issue by gi30-justin** [alex8088/electron-vite#246]
### Describe the bug

Hi I want to integrate sequelize using this repo but having issues shown here on `npm run dev` 

![image](https://github.com/alex8088/electron-vite/assets/93763175/955f5559-178a-4fe9-a0d8-fa7daf54d0d3)

everythings fresh i just added few codes for the sequelize setup 

attaching here: 
main.ts 
![image](https://github.com/alex8088/electron-vite/assets/93763175/18f07028-0188-485d-8742-2e82ac462baf)

here's the getdb.ts file 

![image](https://github.com/alex8088/electron-vite/assets/93763175/efcc9823-f3cf-48d5-ac13-a2830a3d54a4)
![image](https://github.com/alex8088/electron-vite/assets/93763175/ccb35d7f-45e3-4696-8b52-dcf93e220355)

### Electron-Vite Version

1.0.25

### Electron Version

24.6.2

### Vite Version

4.4.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
`sequelize`  can only be used in the main process

**Comment by gi30-justin** [comment]
> `sequelize` can only be used in the main process

any code sample on how i can apply this please? thank you so much if you can help me with this issue.

**Comment by alex8088** [comment]
https://github.com/alex8088/electron-vite-decorator-example

**Comment by gi30-justin** [comment]
Hi @alex8088  thanks for the reference but is there a way i can auto inject this to the renderer and be used to the app itself?  
 right now i'm trying to use is on my Vue - App.vue file 

![image](https://github.com/alex8088/electron-vite/assets/93763175/4575e9d3-9ff1-486c-9e27-0c68e9ce17a6)


but error shows here
![image](https://github.com/alex8088/electron-vite/assets/93763175/ce2086df-bc6f-4a73-b04c-ba0d6c1c1b2e)

**Comment by alex8088** [comment]
It is recommended to use preload scripts to develop

https://electron-vite.org/guide/dev.html#using-preload-scripts

**Comment by gi30-justin** [comment]
Hi @alex8088  do you have a sample with vue js applying sequelize? . Thanks in advance.

**Comment by alex8088** [comment]
> Hi @alex8088 do you have a sample with vue js applying sequelize? . Thanks in advance.

https://github.com/alex8088/electron-vite-decorator-example
