### ISSUE TITLE
请问这个脚手架怎么跟eggjs结合使用呢 

### ISSUE THREAD

**Issue by yq5858588** [alex8088/electron-vite#247]
### Clear and concise description of the problem

请问这个脚手架怎么跟eggjs结合使用呢 

### Suggested solution

请问这个脚手架怎么跟eggjs结合使用呢 

### Alternative

请问这个脚手架怎么跟eggjs结合使用呢 

### Additional context

请问这个脚手架怎么跟eggjs结合使用呢 

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
可以在主进程中使用
