### ISSUE TITLE
能否添加 nodemon 以支持自动重启?

### ISSUE THREAD

**Issue by Maxiaochuan123** [alex8088/electron-vite#249]
### Clear and concise description of the problem

在修改 electron main.js 时, 窗口无法得到实时响应, 需要重启.

### Suggested solution

能否添加  nodemon 以支持自动重启?

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/hot-reloading.html
