### ISSUE TITLE
其他库中使用了wasm，加载不到

### ISSUE THREAD

**Issue by king514jy** [alex8088/electron-vite#25]
### Describe the bug

使用[https://github.com/rubickCenter/rubick-base](https://github.com/rubickCenter/rubick-base)这个库时，库中使用了wasm，加载不到
![image](https://user-images.githubusercontent.com/5669543/192308652-d32b8c39-4892-4cb9-a45c-de884bb095d2.png)
![image](https://user-images.githubusercontent.com/5669543/192308736-e99706bd-7ef2-4c5b-b94f-faafe78fdd1f.png)
![image](https://user-images.githubusercontent.com/5669543/192308905-06ab4ddc-cb34-49f1-b2db-68c4394ba11f.png)

### Electron-Vite Version

1.0.9

### Electron Version

20.2.0

### Vite Version

3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@king514jy 

1.  排除 `dependencies` 打包，只打包自己的代码，node addon 通常也是这么处理，可以参考下面配置

```
export default defineConfig({
  main: {
    build: {
      rollupOptions: {
        external: ['@silvia-odwyer/photon-node']
      }
    }
  },
  // ...
})
```

- 如果依赖的dependencies都支持commonjs，实则都可以排除不打包，当然也可以自己选择。

2.  打包依赖情况下可以使用 [vite-plugin-wasm](https://github.com/Menci/vite-plugin-wasm) 或者 [@rollup/plugin-wasm](https://github.com/rollup/plugins/tree/master/packages/wasm) 插件

- 如果都将依赖一起打包，那也必须处理了好chunk文件的大小分割，因为太大的chunk对模块加载也是不利地

3.  如果是自己开发地 wasm 以文件形式引入，同样也需要上述的类似的插件来处理

**Comment by king514jy** [comment]
@alex8088 可以了
