### ISSUE TITLE
webview preload is not use

### ISSUE THREAD

**Issue by xiaozhanghui** [alex8088/electron-vite#253]
### Describe the bug

将预加载脚本附加到 webview 的最简单方法是通过 webContents 的 will-attach-webview 事件处理。
mainWindow.webContents.on('will-attach-webview', (e, webPreferences) => {
  webPreferences.preload = join(__dirname, '../preload/index.js')
})
报错了
16 sandbox_bundle:2 Unable to load preload script: D:\workspace\study\electron-app\out\preload\index.js
(anonymous) @ VM16 sandbox_bundle:2
VM16 sandbox_bundle:2 Error: module not found: @electron-toolkit/preload
    at preloadRequire (VM16 sandbox_bundle:2:82225)
    at <anonymous>:4:17
    at runPreloadScript (VM16 sandbox_bundle:2:82977)
    at VM16 sandbox_bundle:2:83236
    at VM16 sandbox_bundle:2:83391
    at ___electron_webpack_init__ (VM16 sandbox_bundle:2:83395)
    at VM16 sandbox_bundle:2:83518
(

### Electron-Vite Version

1.0.25(vite@4.4.2)

### Electron Version

24.6.2

### Vite Version

 4.4.2(@types/node@18.16.19)(less@4.1.3)

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by xiaozhanghui** [comment]
渲染进程是正常的，webview中就报错

**Comment by alex8088** [comment]
webPreferences.sandbox = false

**Comment by xiaozhanghui** [comment]
> webPreferences.sandbox = false

感谢，我一直以为这个只要加到mainWindow上的，没想到webview上也要
