### ISSUE TITLE
大佬大佬，要是脚手架能提供构建angular框架的项目就好了

### ISSUE THREAD

**Issue by Fangfang2468** [alex8088/electron-vite#257]
### Describe the bug

自己尝试用angluar cli构建项目后自己配electron环境，开发环境没问题，但是打包的问题太多了。求大佬能不能出个构建angular的功能

### Electron-Vite Version

1.0.26

### Electron Version

26

### Vite Version

3

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
用 [create-electron](https://electron-vite.org/guide/#scaffolding-your-first-electron-vite-project) 创建项目，参考 https://github.com/hiepxanh/angular-vite-example 改造一下renderer，试一试
