### ISSUE TITLE
多窗口时报Failed to resolve module specifier "fs"，但是我并没有用fs

### ISSUE THREAD

**Issue by PorygonCN** [alex8088/electron-vite#26]
### Describe the bug

打开子窗口只报了这个错 没法定位

![image](https://user-images.githubusercontent.com/31176914/192590625-dea92ecf-db37-4b43-828c-dd3e3d0345a9.png)

![image](https://user-images.githubusercontent.com/31176914/192589049-0caec3eb-bcd8-400e-bf41-b002ac380db3.png)
刚接触`electron-vite` 希望能帮忙解惑

### Electron-Vite Version

1.0.9

### Electron Version

20.1.4

### Vite Version

3.1.3

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by PorygonCN** [comment]
我发现是我使用的pdfjs中import了fs 但是我不知道要怎么来修改....

**Comment by alex8088** [comment]
@PorygonCN pdfjs 是基于nodejs实现，应该在主进程中使用，不能在renderer中使用。

**Comment by alex8088** [comment]
@PorygonCN 在主进程使用也更合理，renderer通过ipc去做处理

**Comment by PorygonCN** [comment]
@alex8088 找到解决方法了, 在preload中`contextBridge.exposeInMainWorld()` 使用了node内置模块的包 然后在原本要使用的位置从`import xxxx`改为 `window.xxxx`

**Comment by alex8088** [comment]
@PorygonCN 看到你的回复，在preload中expose是对的，但最好的方式还是应该将相关的业务处理放在main中处理，再在preload中通过ipc调用主进程进行处理，并expose相关方法给渲染进程使用。这样做是因为不推荐在preload中使用node，这也是官方推荐的，在electron 20 后默认都会开启沙箱（也是可以关闭的），node功能在preload会不可用（因为不安全），当然这个建议不是绝对，可以根据自己的需要来处理

**Comment by PorygonCN** [comment]
@alex8088 嗯 已经解决了 昨晚考虑的不够  今天是通过preload中引用 然后 render进程中调用 然后还得关闭上下文隔离和启用node模块 因为做的是自己的内容 并非加载网络内容 所以安全问题反而不重要了
