### ISSUE TITLE
构建时ts检查不通过

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#261]
### Describe the bug

build:win 报错如下图，ts检查不通过，删除 build 命令中的 “npm run typecheck && ” 就可以正常打包；

基础模板使用 npm create @quick-start/electron 创建

![image](https://github.com/alex8088/electron-vite/assets/39619390/df231ce5-3176-4c1f-9cd0-e9cafa40b9fa)

### Electron-Vite Version

1.0.26

### Electron Version

24.6.2

### Vite Version

4.4.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
缺少 preload 类型定义
// tsconfig.web.json
```json
{
  "extends": "@electron-toolkit/tsconfig/tsconfig.web.json",
  "include": [
    "src/renderer/src/env.d.ts",
    "src/renderer/src/**/*",
    "src/renderer/src/**/*.vue",
    "src/preload/*.d.ts"
  ],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@renderer/*": [
        "src/renderer/src/*"
      ]
    }
  }
}
```
