### ISSUE TITLE
build 后能带自带右键和工发者工具吗？

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#263]
### Clear and concise description of the problem

如题，build 后能带带上右键菜单和chrome工发者工具吗？

### Suggested solution

如题，build 后能带带上右键菜单和chrome工发者工具吗？

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
可以，这和electron-vite没有关系，请参阅 electron 文档。
