### ISSUE TITLE
Example on importing node_module files directly

### ISSUE THREAD

**Issue by EricRohlfs** [alex8088/electron-vite#264]
### Clear and concise description of the problem

In my case, I could not get a specific node_module file to import.  I was trying to import node_modules/bootstrap/dist/js/bootstrap.esm.js.  

Bootstrap 5.x has good examples on importing scss and JavaScript for vite. Unfortunately the JavaScript import doesn't work in vite-electron. Fyi, the scss import works fine. 

I tried the following individually and they did not work for me.
```
import * as bootstrap from 'bootstrap'
import * as bootstrap from 'bootstrap/dist/js/bootstrap.esm.js'
import { Collapse } from '../../../../../node_modules/bootstrap/dist/js/bootstrap.esm.js'
import { Collapse } from 'bootstrap'
import {Collapse} from 'bootstrap/dist/js/bootstrap.esm.js'
import * as bootstrap from  'bootstrap/dist/js/bootstrap.esm.ts?asset'
import * as bootstrap from 'bootstrap?asset'
```

I worked around the issue by copying the bootstrap.esm.js file contents into a bootstrap.ts file in the src folder and imported that right into the  renderer/index.html file.  Not the ideal solution. 

```
  <script type="module">
      import './src/bootstrap.ts'
    </script>
```

### Suggested solution

I do not have a suggested solution.

### Alternative

I tried the following individually and they did not work for me.
```
import * as bootstrap from 'bootstrap'
import * as bootstrap from 'bootstrap/dist/js/bootstrap.esm.js'
import { Collapse } from '../../../../../node_modules/bootstrap/dist/js/bootstrap.esm.js'
import { Collapse } from 'bootstrap'
import {Collapse} from 'bootstrap/dist/js/bootstrap.esm.js'
import * as bootstrap from  'bootstrap/dist/js/bootstrap.esm.ts?asset'
import * as bootstrap from 'bootstrap?asset'
```

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
`?asset` suffix only work in main process
