### ISSUE TITLE
"throw er; // Unhandled 'error' event" on yarn dev with starter project

### ISSUE THREAD

**Issue by Champitoad** [alex8088/electron-vite#266]
### Describe the bug

I am trying to scaffold the basic electron-vite project with the vanilla template, following instructions [here](https://electron-vite.org/guide/#scaffolding-your-first-electron-vite-project). But when I run either `npm run dev` or `yarn dev` I get the following error:
```sh
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn {PATH_TO_APPDIR}/my-app-vanilla/node_modules/electron/dist/electron ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn {PATH_TO_APPDIR}/my-app-vanilla/node_modules/electron/dist/electron',
  path: '{PATH_TO_APPDIR}/my-app-vanilla/node_modules/electron/dist/electron',
  spawnargs: [ '.' ]
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Already tried with various other versions of Node (14, 16, 20) with no success. Also I run NixOS.

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
I think this is a compatibility issue between `Electron `and `NixOS`.
