### ISSUE TITLE
mac M1和Intel打包都是同一个吗?

### ISSUE THREAD

**Issue by zscorpio** [alex8088/electron-vite#268]
### Describe the bug

mac M1和Intel打包都是同一个吗?我看打包命令只有一个, github action也是, 理论上是不是应该2个包?

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
electron-builder --mac --x64 --arm64

**Comment by zscorpio** [comment]
哦哦原来是不一样的, 谢谢, 那我尝试着加一个命令试试

**Comment by alex8088** [comment]
github 要打包 arm64架构，需要做配置，详细看github action相关文档，github action 默认应该打的是 x64

**Comment by zscorpio** [comment]
嗯, 我以为都是一样的, 所以文档才没写, 我还没测试 到时候试试
