### ISSUE TITLE
Invalid or incompatible cached data (cachedDataRejected)

### ISSUE THREAD

**Issue by liqz2009** [alex8088/electron-vite#269]
### Describe the bug

在苹果电脑上bytecode不能用，其他平台可以

### Electron-Vite Version

1.0.27

### Electron Version

23.0.0

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/troubleshooting.html#a-javascript-error-occurred-in-the-main-process-error-invaild-or-incompatible-cached-data-cacheddatarejected
