### ISSUE TITLE
electron-vite dev 多窗口下，其他页面404

### ISSUE THREAD

**Issue by king514jy** [alex8088/electron-vite#27]
### Describe the bug

![image](https://user-images.githubusercontent.com/5669543/192749839-5717f3d5-15cc-400a-9cd7-6745e7fd994d.png)
![image](https://user-images.githubusercontent.com/5669543/192750587-0c436486-c556-44a5-b42c-f17e533243e1.png)
使用 electron-vite preview  下正常。。但是调试很麻烦。每次都要重启

### Electron-Vite Version

1.0.9

### Electron Version

20.2.0

### Vite Version

3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@king514jy 加载入口页面方式不正确，多窗口下, 可以参考下面配置，在主进程

```
function createWindow(): void {
  let url = ''
  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    url = `${process.env['ELECTRON_RENDERER_URL']}/update.html`
  } else {
    url = path.join(__dirname, '../renderer/update.html')
  }
 //...
}
```
根据你具体的页面修改

**Comment by king514jy** [comment]
getUrl(name){
    return is.dev && process.env['ELECTRON_RENDERER_URL']?process.env['ELECTRON_RENDERER_URL']+"/"+name+".html":
      path.join(__dirname, '../renderer/'+name+"/"+name+".html");
  }
入口方法我是从模板中复制过来方法。应该没有问题

**Comment by alex8088** [comment]
@king514jy 问题是否解决了，可以多打点日志看看，貌似你的upload和login是有多一层目录

**Comment by king514jy** [comment]
@alex8088 好的，我再看看，应该是我的问题。谢谢

**Comment by king514jy** [comment]
@alex8088 已解决

**Comment by alex8088** [comment]
If you have any questions, you can submit a new issue at any time
