### ISSUE TITLE
Allow dynamic specification of `"main"` field in `package.json`

### ISSUE THREAD

**Issue by undergroundwires** [alex8088/electron-vite#270]
### Clear and concise description of the problem

As a developer using `electron-vite`, I would like the ability to dynamically set the `"main"` field in `package.json` or have `electron-vite` handle this automatically. This will make the build process more flexible and centralized.

Take `electron-builder` for instance, which allows us to dynamically set the `"main"` field:

```js
// electron-builder.cjs
module.exports {
  ...
  extraMetadata: {
    main: join(dynamicLogicToGetDistPath(), 'main/index.cjs')
```

This functionality allows for centralized management of distribution directories, which is crucial for complex projects. In contrast, `package.json` forces us to hardcode this information, which limits flexibility.

### Suggested solution

**Alternative 1**:

`electron-vite` already knows the main entry file's location and where to copy it.  Can it patch `package.json` or implement a similar mechanism to point to the main file from the distribution directory? This would enable a zero-config approach.

**Alternative 2**:

Allow developers to specify the main file path in one of the configuration files. This could even be an additional feature on top of Alternative 1.

### Additional context

First of all, thank you for this excellent plugin. The TypeScript configuration files are a great help, and the support for ESM modules is impressive. The documentation is clear and comprehensive; I never had to look at the code. This project now empowers desktop builds of [privacy.sexy](https://github.com/undergroundwires/privacy.sexy).

**What I'm trying to solve:**

This need arose when I attempted to centralize all distribution directory configurations into a single [`dist-dirs.json`](https://github.com/undergroundwires/privacy.sexy/blob/master/dist-dirs.json) file. The goal is to eliminate hardcoded paths that lead to unstable builds. While I can easily manage this in [`electron.vite.config.ts`](https://github.com/undergroundwires/privacy.sexy/blob/master/electron.vite.config.ts#L11), [`electron-builder.cjs`](https://github.com/undergroundwires/privacy.sexy/blob/master/electron-builder.cjs#L16-L18), [`vite.config.ts`](https://github.com/undergroundwires/privacy.sexy/blob/master/vite.config.ts#L19), or in CI/CD pipelines/other commands through a utility I build ([`scripts/print-dist-dir.js`](https://github.com/undergroundwires/privacy.sexy/blob/master/scripts/print-dist-dir.js)), I cannot do so in [`package.json`](https://github.com/undergroundwires/privacy.sexy/blob/master/package.json#L9). This issue aims to bridge that gap.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
@undergroundwires 

Maybe adding a `cli` option to dynamically specify the electron entry file would be a good way, e.g.

```sh
electron-vite dev --entry out/main/xxx.js
```

**Comment by undergroundwires** [comment]
Thanks for the quick response @alex8088 .

Config file option would simplify my setup with power of TypeScript but this can be only specific to me. CLI option would still solve it for me but I will need to build some cross-platform command wrappers so I can read distribution directory from JSON file. Even though I prefer config file option if I had the choice, CLI option would be much appreciated (it should work with `electron-vite build` too).

<details>
  <summary>Out-of-topic appreciation/feedback</summary>
  
I really like how clean your code is here.

I also see perfect balance of the project where it just does enough "magic" that eliminates common problems without abstracting too much.

I decided on this when I was doing deep dive through [lack of ESM support in electron](electron/electron/issues/21457#issuecomment-1537136292) and got it working with completely [different and much simpler config](https://github.com/undergroundwires/privacy.sexy/blob/0a2a1a026b0efb29624be82b06536c518c1ea439/electron.vite.config.ts#L39-L65) than provided there. I recommend the plugin to all `vue-cli-plugin-electron-builder` refugees, nklayman/vue-cli-plugin-electron-builder#1982.

I know how much effort it takes to maintain open-source, often with little to no gains. Your efforts are appreciated 👍️.
</details>

**Comment by alex8088** [comment]
@undergroundwires 

This feature should be added in the next version, and of course it will support all CLI commands.

Thank you for your appreciation and recommendation for this project. Providing faster and cleaner DX for Electron was the motivation behind this project. It's great to help Electron developers solve some difficult problems.

**Comment by undergroundwires** [comment]
Works great, environment variable was a life saver, thank you for listening, your efforts and quick action @alex8088 👍️
