### ISSUE TITLE
构建 mac --ia32时候，没有代理的情况下 git地址报错404

### ISSUE THREAD

**Issue by hengtar** [alex8088/electron-vite#271]
### Describe the bug

<img width="1122" alt="image" src="https://github.com/alex8088/electron-vite/assets/20667901/93d7ffa8-81f3-440a-9fbb-7728ed7cdbd2">

### Electron-Vite Version

max

### Electron Version

max

### Vite Version

max

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
网络问题

**Comment by alex8088** [comment]
你可以添加一个 `.npmrc` 文件内容

```
ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/
```
