### ISSUE TITLE
缺少 vite-web单独启动命令，electron-vite不支持自定义process.argv传递参数给electron

### ISSUE THREAD

**Issue by impohcom** [alex8088/electron-vite#277]
### Clear and concise description of the problem

缺少 vite-web单独启动命令，electron-vite不支持自定义process.argv传递参给electron

### Suggested solution

建议给electron 支持自定义的process.argv传递参
新增vite-web单独启动 

### Validations

- [ ] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [ ] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [ ] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
- [ 传递 CLI 参数给 Electron 应用程序](https://cn.electron-vite.org/guide/dev.html#%E4%BC%A0%E9%80%92-cli-%E5%8F%82%E6%95%B0%E7%BB%99-electron-%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F)
- 单独调试web，可以新增vite配置使用vite命令单独去调试，

此外，可以使用--rendererOnly 选项（仅用于 dev 命令）以跳过主进程和预加载脚本构建，并仅为渲染器启动开发服务。此选项将大大提高 dev 命令速度，但也会启动electron进程。

**Comment by impohcom** [comment]
function startElectron(root) {
    ensureElectronEntryFile(root);
    const electronPath = getElectronPath();
    const isDev = process.env.NODE_ENV_ELECTRON_VITE === 'development';
    const args = [];
    if (!!process.env.REMOTE_DEBUGGING_PORT && isDev) {
        args.push(`--remote-debugging-port=${process.env.REMOTE_DEBUGGING_PORT}`);
    }
    if (!!process.env.V8_INSPECTOR_PORT && isDev) {
        args.push(`--inspect=${process.env.V8_INSPECTOR_PORT}`);
    }
    if (!!process.env.V8_INSPECTOR_BRK_PORT && isDev) {
        args.push(`--inspect-brk=${process.env.V8_INSPECTOR_BRK_PORT}`);
    }
    const ps = node_child_process.spawn(electronPath, ['.'].concat(args), { stdio: 'inherit' });
    ps.on('close', process.exit);
    return ps;
}

源码并没有可以在后面拼接自定义参数的

**Comment by alex8088** [comment]
请看文档https://cn.electron-vite.org/guide/dev.html#%E4%BC%A0%E9%80%92-cli-%E5%8F%82%E6%95%B0%E7%BB%99-electron-%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F
