### ISSUE TITLE
electron-vite集成了puppeteer，打包后使用puppeteer报错http_proxy_agent不能使用

### ISSUE THREAD

**Issue by northFlyX** [alex8088/electron-vite#280]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/116325855/15c7e89e-f0ce-4afc-bf51-6b463348e08b)
开发时不会出现此错误，开发时可以正常使用puppeteer，打包后会再启动puppeteer就会报此错误
![image](https://github.com/alex8088/electron-vite/assets/116325855/657e4740-2488-4557-a0a6-161bcb6dad0f)
这是打开的代码，此段代码运行在主进程的worker线程中
![image](https://github.com/alex8088/electron-vite/assets/116325855/ad8ff603-68ce-4637-962c-c546c2e118bf)

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
preview 模式下是否正常

**Comment by iamzuijiasunyou** [comment]
碰到了同样的问题，有解决方案吗？

**Comment by wumingluren** [comment]
我也是一样的问题使用puppeteer-core又说路径错误

**Comment by arronf2e** [comment]
请问这个问题是否已解决 @northFlyX ?

**Comment by arronf2e** [comment]
大家别用 pnpm 装包，我用的 yarn，没问题了
