### ISSUE TITLE
这个能增量打包和更新吗？

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#281]
### Clear and concise description of the problem

如题，这个脚手架支持增量打包和更新吗？

### Suggested solution

如果没有话，可有好的解决方案？

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
增量更新需要根据自己的需求场景实现，目前没有成熟的解决方案。
