### ISSUE TITLE
Error in electron-vite: Unable to load preload script because of "missing file" in chunks folder.

### ISSUE THREAD

**Issue by Uncasted** [alex8088/electron-vite#282]
### Describe the bug

http://prntscr.com/WvyfJ-x97k4S

Any idea why this could be happening? The chunks folder is there and it contains the module but it says it's missing for some reason.

### Electron-Vite Version

1.0.25

### Electron Version

24.6.2

### Vite Version

4.4.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/dev.html#limitations-of-sandboxing for more details.

Because the `require` function is a polyfill with limited functionality, you will not be able to use `CommonJS` modules to separate your preload script into `multiple` files, unless `sandbox: false` is specified.

**Comment by Uncasted** [comment]
Is there a way I could fix this without disabling sandbox? Would it work if they were ES modules instead?

**Comment by stefmedjo** [comment]
I am trying to build a project created accordingly with what is described in the docs but I am getting a white screen and these logs about some index.css and index.js files not found.
Do you have a solution to this ? I started getting these problems when using node 18.

![mlkju](https://github.com/alex8088/electron-vite/assets/24573833/1c4e1f49-b14f-427b-959a-8a73306473af)

**Comment by alex8088** [comment]
Whether a router is used?  Maybe this problem: https://electron-vite.org/guide/troubleshooting.html#vue-router-or-react-router-dom-works-in-development-but-not-production

**Comment by matthme** [comment]
I'm actually having the same issue when using multiple windows with independent preload scripts that both depend on shared dependencies. In that case there's no way to configure `electron.vite.config.ts` in a way to not generate chunks (see the corresponding issue in [rollup](https://github.com/rollup/rollup/issues/2756)). I think it's worth re-opening this issue as I think electron-vite should make sure preload scripts get bundled as independent single files.
