### ISSUE TITLE
有exe程序更新的配置吗

### ISSUE THREAD

**Issue by hbb520** [alex8088/electron-vite#283]
### Clear and concise description of the problem

有exe程序更新的配置吗

### Suggested solution

有exe程序更新的配置吗

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
通过过electron-builder打包，可以搭配electron-updater实现升级，具体查阅electron-builder文档
