### ISSUE TITLE
 Could not dynamically require "sqlite3".

### ISSUE THREAD

**Issue by 027xiguapi** [alex8088/electron-vite#287]
### Describe the bug

在项目中引入sqlite3时， 
![image](https://github.com/alex8088/electron-vite/assets/31228055/d6c2bbd1-d75e-4871-8101-99909b2245dc)

### Electron-Vite Version

1.0.27

### Electron Version

23.2.0

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
How did you import it?
