### ISSUE TITLE
Resolve custom alias

### ISSUE THREAD

**Issue by lukasbrzobohaty** [alex8088/electron-vite#288]
Hi, I try to specify custom resolve aliases and I get always error `Failed to resolve import ...`.

tsconfig.json
```
{
  "compilerOptions": {
    ...
    "paths": {
      "@/*": ["./src/renderer/src/*"],
      "@config/*": ["./src/renderer/config/*"],
    },
  }
}
```

electron.vite.config.ts
```
const alias = {
  '@': resolve(__dirname, 'src/renderer/src'),
  '@config': resolve(__dirname, 'src/renderer/config'),
};

export default ({ mode }) => {
  return defineConfig({
    main: {
      resolve: {
        alias,
      },
      plugins: [externalizeDepsPlugin()],
    },
    preload: {
      plugins: [externalizeDepsPlugin()],
    },
    renderer: {
      resolve: {
        alias,
      },
      ...
    },
  });
};
```
When I run `electron-vite dev` then I got errors:
```
Failed to resolve import "@config/config" from "src/renderer/src/App.vue". Does the file exist?
Failed to resolve import "@/App" from "src/renderer/src/main.ts". Does the file exist?

etc.
```

What am I doing wrong?

### Electron-Vite Version

1.0.27

### Electron Version

26.2.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by BruceAndyLee** [comment]
Have just run into this issue myself.

this sample (inserted into every object under keys main/build/renderer) works for me just fine
```jsx
resolve: {
      alias: {
        '@frontend': resolve(__dirname, "./src/"),
        '@electron': resolve(__dirname, "./electron/"),
        '@common': resolve(__dirname, "./common/"),
      },
    },
```

so, probably the `./` at the start of the second argument of `resolve`?

**Comment by lukasbrzobohaty** [comment]
I try to add `./` to resolve paths and nothing changed. I got the same errors. It's mystery.

**Comment by shb3014** [comment]
I run into the same issue and adding ./ won't solve the problem. Is there a code sandbox project or template including how to do this?

**Comment by shb3014** [comment]
it turns out that the tsconfig path settings should be put in tsconfig.web.json or tsconfig.node.json. putting in tsconfig.json directly won't work.
