### ISSUE TITLE
 electro-vite vue-ts template     install vue-router error

### ISSUE THREAD

**Issue by pq-code** [alex8088/electron-vite#289]
### Describe the bug

router.push()        trigger

 ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (index.js:4:28)
    at __require (chunk-UXIASGQL.js?v=c4380bfc:8:50)
    at index.js:21:34

 webPreferences: {
      nodeIntegration: true,
    }
The problem persists

### Electron-Vite Version

^1.0.27

### Electron Version

^25.6.0

### Vite Version

^4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by pq-code** [comment]
The problem arises from


const fs = require('fs');
const path = require('path');

const pathFile = path.join(**__dirname**, 'path.txt');

function getElectronPath () {
  let executablePath;
  if (fs.existsSync(pathFile)) {
    executablePath = fs.readFileSync(pathFile, 'utf-8');
  }
  if (process.env.ELECTRON_OVERRIDE_DIST_PATH) {
    return path.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, executablePath || 'electron');
  }
  if (executablePath) {
    return path.join(__dirname, 'dist', executablePath);
  } else {
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
  }
}

module.exports = getElectronPath();

**Comment by alex8088** [comment]
This is not a vue-router problem. 

Don't use `nodejs` and `electron main` modules in renderer

more detail: https://electron-vite.org/guide/dev.html#nodeintegration
