### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by kekekezi** [alex8088/electron-vite#29]
### Clear and concise description of the problem

1 、我打包以后体积超级大 有没有什么优化的办法 
2、 我需要在项目里面启动chorme 我把chrome也打包里面了 这个有没有好办法呀 

### Suggested solution

球球了 看看我吧

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@kekekezi ，你是将整个chrome打包进去吗？chrome本身多大？

**Comment by kekekezi** [comment]
@alex8088 对的 但是即使不把chorme打进去 也有100多m

**Comment by kekekezi** [comment]
@alex8088 chrome大概有600m

**Comment by alex8088** [comment]
@kekekezi   electron-builder打包，window安装包一般在60多M，mac和linux一般是80多M，一般太大的原因：

- 把不必要的依赖打包了，一些开发需要的依赖是非常大的，比如esbuild，tsc等，所以要正确安装开发依赖包，要分清是开发需要还是程序自身需要（即dependencies和 devDependencies），因为打包工具正常这会分析打包dependencies的包，所以如果把一些构建工具安装到dependencies也可能造成最终打包的文件大。

除了正确安装依赖外，还可以通过打包配置去除一些必要的文件，以electron-builder为例，可以通过file属性来配置

```
files:
  - '!**/.vscode/*'
  - '!**/{README.md,RELEASE.md}'
```

就如上面，会把vscode配置文件，node_module下所有readme文件去掉，当然这些要自己分析，那些可以去掉

- 如果构建代码中没有将dependencies相关模块在externals排除，那么构建工具也会将你依赖一并打包，这种情况下也应该排除打包node_module下dependencies包。但打包工具是不会做这个识别，需要人工干预。

这里建议在externals中排除dependencies相关包依赖，如果不排除，处理方式和第一种类似

至于你要把chrome打包进去，那必然是大的，这是无法逃避的（那是不是应该考虑其他实现手段）
