### ISSUE TITLE
Blank HTML Generated in Production Build with vite build

### ISSUE THREAD

**Issue by samarthasthan** [alex8088/electron-vite#295]
### Describe the bug

I am encountering an issue when using the `npm run build:mac` command to generate a production build for my application. The problem is that the resulting HTML file is blank, causing the application not to load correctly in production. This issue does not occur during development when using `npm run dev`, where the application runs as expected.

<h2>with npm run dev- </h2>

![Screenshot 2023-09-27 at 2 38 19 AM](https://github.com/alex8088/electron-vite/assets/97031010/de2acda3-b41b-4cdd-b4c9-62ca980f2b63)

<h2>with npm run build:mac- </h2>

![Screenshot 2023-09-27 at 2 38 38 AM](https://github.com/alex8088/electron-vite/assets/97031010/c300d2d9-b77f-413f-92db-dc333073f827)

<h2>electron.vite.config.js</h2>

![carbon](https://github.com/alex8088/electron-vite/assets/97031010/8f30098d-7a66-458a-918c-1ac962214867)

<h2>package.json</h2>

![carbon (1)](https://github.com/alex8088/electron-vite/assets/97031010/be85ac55-86f5-4c53-b826-5bcfd05c1486)

<h2>electron-builder.yml</h2>

![carbon (2)](https://github.com/alex8088/electron-vite/assets/97031010/e783999c-585d-4ba1-8f42-e17cb5f0bef1)

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
check out https://electron-vite.org/guide/troubleshooting.html#vue-router-or-react-router-dom-works-in-development-but-not-production for more details

**Comment by samarthasthan** [comment]
Thanks got it 👍🏻
