### ISSUE TITLE
Sveltekit support

### ISSUE THREAD

**Issue by adminy** [alex8088/electron-vite#296]
### Clear and concise description of the problem

My understanding is that at the moment this only supports svelte, but now sveltekit, as when I tried doing that I get a bunch of errors and even if I try fixing them via a direct import hack I got:
```javascript
import { sveltekit } from './node_modules/@sveltejs/kit/src/exports/vite/index.js'
```
```bash
✘ [ERROR] Top-level await is currently not supported with the "cjs" output format

    node_modules/@sveltejs/kit/src/core/sync/ts.js:5:7:
      5 │   ts = (await import('typescript')).default;
        ╵         ~~~~~

failed to load config from /Users/adminy/project/electron.vite.config.js
error during start dev server and electron app:
Error: Build failed with 1 error:
node_modules/@sveltejs/kit/src/core/sync/ts.js:5:7: ERROR: Top-level await is currently not supported with the "cjs" output format
    at failureErrorWithLog (/Users/adminy/project/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/adminy/project/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/adminy/project/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/Users/adminy/project/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/adminy/project/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/Users/adminy/project/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/adminy/project/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/adminy/project/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
```

### Suggested solution

This might be tied to the ESM support bug I opened earlier where one fixes the other. But I'm not certain here what the best way to go about this is.

### Alternative

you could just host sveltekit somewhere and put in the url in electron there, but I'd much prefer it if electron itself did the building and routing.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
@adminy  rename `electron.vite.config.js` -> `electron.vite.config.mjs`

**Comment by adminy** [comment]
Done that, but its parsing an index.html file inside my src/renderer folder instead of the sveltekit app.html default.

**Comment by adminy** [comment]
my understanding is that 
```javascript
import { sveltekit } from '@sveltejs/kit/vite'
```
is made of 
```javascript
import { svelte } from '@sveltejs/vite-plugin-svelte'
```
and a kit component which is the dynamic router that electron-vite does not support as its also trying to control outputs and formats just like the kit does.

**Comment by alex8088** [comment]
> Done that, but its parsing an index.html file inside my src/renderer folder instead of the sveltekit app.html default.

https://electron-vite.org/guide/dev.html#project-structure

**Comment by alex8088** [comment]
#145
