### ISSUE TITLE
Throw error when there is vite.config.ts file in root

### ISSUE THREAD

**Issue by ccforeverd** [alex8088/electron-vite#3]
### Describe the bug

1. Throw error when there is vite.config.ts file in root

    ``` text
      The symbol "prevRefreshReg" has already been declared
      1  |  import RefreshRuntime from "/@react-refresh";let prevRefreshReg;let prevRefreshSig;if (import.meta.hot) {  if (!window.__vite_plugin_react_preamble_installed__) {    throw new Error(      "@vitejs/plugin-react can't detect preamble. Something is wrong. " +      "See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201"    );  }  prevRefreshReg = window.$RefreshReg$;  prevRefreshSig = window.$RefreshSig$;  window.$RefreshReg$ = (type, id) => {    RefreshRuntime.register(type, "/Users/zhangshuyao/Sites/electron-vite-quick-start/electron-app/src/renderer/src/App.tsx" + " " + id)  };  window.$RefreshSig$ = RefreshRuntime.createSignatureFunctionForTransform;}import RefreshRuntime from "/@react-refresh";
      2  |  let prevRefreshReg;
         |      ^
      3  |  let prevRefreshSig;
      4  | 
    ```

2. Type error in electron.vite.config.ts when imports vite.config.ts

    ``` ts
      // electron.vite.config.ts
      import webViteConfig from './web.vite.config'
      export default {
        // type error: 不能将类型“UserConfigExport”分配给类型“UserConfig | undefined”。
        // 类型“Promise<UserConfig>”与类型“UserConfig”不具有相同的属性。ts(2322)
        renderer: webViteConfig
      }

      // web.vite.config.ts
      import { defineConfig } from 'vite'
      export default defineConfig(...)
    ```

### Electron-Vite Version

1.0.2

### Electron Version

18.2.0

### Vite Version

2.9.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
hi, @ccforeverd

first problem,

`electron-vite` base on `vite`, and vite will be automatically resolved the file named `vite.congfig.{ts,js,mjs.cjs}`. so the electron-vite requires the config file that cannot be named `vite.config.*`. You not need to use vite config file after you use electron-vite. You just need to configure in `electron.vite.config.ts`. I recommend you scaffold a react project  using `create-electron` to learn how to configure . 

```
npm create @quick-start/electron my-app --template react-ts
```

second problem,

it‘s a bug and i will fix it soon

Thx

**Comment by alex8088** [comment]
@ccforeverd new ver 1.0.3

**Comment by ccforeverd** [comment]
Resolved! Thank you so much!
I will keep using the eletron-vite
