### ISSUE TITLE
最新版本 Electron 不被支持

### ISSUE THREAD

**Issue by grandsong** [alex8088/electron-vite#30]
### Describe the bug

当我把electron升级到最新版（"21.0.1"）之后，执行`pnpm dev`时出现错误：

```
vite v3.1.4 building for development...

watching for file changes...

build started...
✓ 1 modules transformed.
[vite:esbuild-transpile] Transform failed with 1 error:
error: Invalid version: "undefined"

Invalid version: "undefined"
```

经过一番折腾，我发现问题出在

```js
function getElectronNodeTarget(electronVer) {
  const nodeVer = {
    '20': '16.15',
    '19': '16.14',
    ...
  }
}
```

增加一行`'21': '16.15',`即可“骗过”程序。

---

如果你总能在第一时间更新这个`nodeVer`，当然好。但这不太现实。

所以，我建议，增加一个“就近”机制：

当`nodeVer`中没有准确对应版本号的键（21）时，取数字最大的那个键（'20'）。

同理，`getElectronChromeTarget()` 也应当如此。

### Electron-Vite Version

1.0.9

### Electron Version

21.0.1

### Vite Version

3.1.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@grandsong 最新的commit已经增加支持，待新版发布。你提地建议也合理，后面优化。

我对于electron的版本更新策略的建议，是跟随vscode的版本演进，不建议最新地，最新版本的稳定性并不可靠，而且每次更新最好是阅读其官方的blog，知晓其重要变更，对于大型项目而言，这种更新策略，我觉得是相对合理的，毕竟vscode会做更多的测试。当然这是经验之谈，对练手项目也不需要考虑这个。

**Comment by grandsong** [comment]
那么，你可以在版本就近的同时，显示警告，并提出你的这个建议。

**Comment by alex8088** [comment]
new ver is out!
