### ISSUE TITLE
bytecode在Mac下打包后还是不能用

### ISSUE THREAD

**Issue by liqz2009** [alex8088/electron-vite#302]
### Describe the bug

Uncaught Exception:
Error: Invalid or incompatible cached data (cachedDataRejected)
at Module._extensions..jsc (/Users/mr.li/Desktop/ldrm/sharp-knife/dist/mas-dev-universal/GcodeSql.app/Contents/Resources/app.asar/out/main/bytecode-loader.js:50:11)

// specify `electron.universal.vite.config.ts` for building x64 Electron app
import { defineConfig } from 'electron-vite'

export default defineConfig(() => {
  process.env.ELECTRON_EXEC_PATH = '/dist/mas-dev-universal/GcodeSql.app'

  return {
    // electron-vite config
  }
})

### Electron-Vite Version

1.0.28

### Electron Version

26.2.4

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
字节码与系统架构相关，需要分架构打包(即要分别打包x64和arm64)，不支持universal混合打包模式，也不建议才用这种模式打包。详细参考文档https://cn.electron-vite.org/guide/source-code-protection.html#%E5%A4%9A%E5%B9%B3%E5%8F%B0%E6%9E%84%E5%BB%BA

**Comment by alex8088** [comment]
universal 仅将x64和arm64两种架构的electron同时打包，在安装时根据系统架构选择安装，但它不会处理代码。尽管你指定了x64 Electron app，但最终打包出来的的bytecode就只是支持x64的，在amr64中安装运行就会有问题。

**Comment by liqz2009** [comment]
谢谢您的回复。
bytecode不是依据chromium的版本号来生成的吗？chromium不是平台无关的吗？为什么会存在不兼容问题呢？
或者可不可以打出2个bytecode代码，不同平台会选择不同的代码呢？
打包这块没有仔细看，您研究的应该比较深，希望您考虑。

**Comment by alex8088** [comment]
和chromium的版本而是系统架构，详细请阅读文档，支持不同架构都没有问题，只是universal打包方式无法支持安架构处理打包问题，需要拆分安不同架构打包处理

**Comment by liqz2009** [comment]
chromium是浏览器内核，不管在什么架构上，或者平台上，他执行的js代码或者是bytecode代码都应该是相同的。
