### ISSUE TITLE
多入口配置不生效和路径引用

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#308]
### Describe the bug

有2个问题不知如何解决：
1、如下配置 out 目录不能产生 loader.html 文件；
2、 loader.html 文件里面样式引用图片资源路径应该怎么处理？

renderer: {
    build: {
      rollupOptions: {
        input: {
          loader: resolve(__dirname, 'src/renderer/loader.html')
        }
      }
    },
  }

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
是否有build，唯build是不会生成的，对于渲染进程静态资源引入参考 vite 的静态资源处理

**Comment by tom-style** [comment]
@alex8088 

> 是否有build，唯build是不会生成的，对于渲染进程静态资源引入参考 vite 的静态资源处理

没有build，这样的html文件不是自动的吗，那后续每次修改HTML都要重新build 一下测试？
