### ISSUE TITLE
bytecodePlugin not working in renderer

### ISSUE THREAD

**Issue by jovey-zheng** [alex8088/electron-vite#311]
### Describe the bug

Used `bytecodePlugin` in renderer, not working. Is there have anyway to fixed this? Or not support now?

![image](https://github.com/alex8088/electron-vite/assets/9565245/c820b16b-0a3a-42a4-8fca-347ca52081be)

build result as below:
![image](https://github.com/alex8088/electron-vite/assets/9565245/78250a0f-68ec-454b-8b6e-6148912bd008)

### Electron-Vite Version

1.0.28

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
bytecodePlugin not supoort renderer

**Comment by alex8088** [comment]
https://electron-vite.org/guide/source-code-protection.html

**Comment by jovey-zheng** [comment]
> bytecodePlugin not supoort renderer

Okay, understood. But I still want to understand why bytecodePlugin does not support renderer.

**Comment by alex8088** [comment]
The bytecode is implemented based on the nodejs vm module and cannot be supported in the renderer environment.

**Comment by alex8088** [comment]
Important code implementation should be in the main process and handled via ipc exchange
