### ISSUE TITLE
开发时可以正常访问，build后文件访问文件失败

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#313]
### Describe the bug

开发时通过 .loadURL(url)可以正访问， build 后以文件方式访问 .loadFile(path) 失效（见下图），是要本地再启服务然后以loadURL方式访问？

![image](https://github.com/alex8088/electron-vite/assets/39619390/9d747d9e-011e-45dc-800c-5c5b91a04b60)

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/troubleshooting.html#vue-router-%E6%88%96-react-router-dom-%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E6%AD%A3%E5%B8%B8%EF%BC%8C%E4%BD%86%E5%9C%A8%E6%9E%84%E5%BB%BA%E5%90%8E%E6%97%A0%E6%95%88
