### ISSUE TITLE
能定义全局图标（包括任务栏、窗口标题栏等）吗？

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#314]
### Describe the bug

通过 new BrowserWindow 创建的窗口，里面的链接打开的新窗口图标还是electron默认的；

![image](https://github.com/alex8088/electron-vite/assets/39619390/8fe69c24-28b9-40d8-b60e-0ad63c60700c)

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
更新build下的icon即可，打包后即会使用新icon。

**Comment by StreenJiang** [comment]
> 更新build下的icon即可，打包后即会使用新icon。

我这边尝试修改了 resource 下的 icon.png，也尝试修改了 build 下的 icon.png & icon.ico & icon.icns，依旧没用。npm run build/build:win 都没用，依旧是 electron 的默认图标

**Comment by XiaoSong-CPE** [comment]
> > 更新build下的icon即可，打包后即会使用新icon。
> 
> 我这边尝试修改了 resource 下的 icon.png，也尝试修改了 build 下的 icon.png & icon.ico & icon.icns，依旧没用。npm run build/build:win 都没用，依旧是 electron 的默认图标

替换图标后，还需要修改的应该是主进程里的代码。需要把这个

```ts
function createWindow(): void {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 720,
    show: false,
    autoHideMenuBar: true,
    ...(process.platform === 'linux' ? { icon } : {}),
    webPreferences: {
      preload: path.join(__dirname, '../preload/index.mjs'),
      sandbox: false

    }
  })
```

改为这样：
```ts
function createWindow(): void {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 720,
    show: false,
    autoHideMenuBar: true,
    icon,
    webPreferences: {
      preload: path.join(__dirname, '../preload/index.mjs'),
      sandbox: false

    }
  })
```

默认情况下只有Linux会使用icon，但是我的windows也可以正常显示图标。请问作者 @alex8088 为什么只设置了Linux的图标，是有什么兼容性问题吗？

**Comment by alex8088** [comment]
对的
