### ISSUE TITLE
Internal server error: Failed to resolve import "@/stores/user.js" from "src\renderer\src\views\index\index.vue". Does the file exist?

### ISSUE THREAD

**Issue by muchenkezhan** [alex8088/electron-vite#318]
### Describe the bug

  1  |  import { ref, reactive } from 'vue'
  2  |  import { useRouter, useRoute } from "vue-router";
  3  |  import { useUserStore } from '@/stores/user.js'
     |                                  ^
  4  |
  5  |  const _sfc_main = {
      at formatError (file:///G:/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/%E9%BB%91%E9%A9%AC%E4%B8%80%E4%B8%AA%E5%B0%8F%E6%97%B6%E7%9A%84/electron-app/node_modules/.store/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-

vite.config.js:
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    vue(),
   
  ],
  resolve: {

    alias: {
      '@': fileURLToPath(new URL('/src/renderer/src', import.meta.url))
    }
  },

})

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
不能单独使用@定义别名
