### ISSUE TITLE
dev 模式无错，打包报错； 

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#319]
### Describe the bug

安装完 electron-store 后，使用的pnpm dev 可以，build 报错；删除所有依赖用yarn重装问题解决，晕死；

![QQ图片20231020223807](https://github.com/alex8088/electron-vite/assets/39619390/0783f595-7fcc-4b3c-8b73-348b613df94e)

### Electron-Vite Version

1.0.28

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/troubleshooting.html#%E5%88%86%E5%8F%91

**Comment by alex8088** [comment]
建议看你下故障排除章节
