### ISSUE TITLE
使用Nedb报错

### ISSUE THREAD

**Issue by DonXander** [alex8088/electron-vite#32]
### Describe the bug

![image](https://user-images.githubusercontent.com/25742814/195321034-18f9553e-32d6-4b8f-a228-98063b9ad007.png)

![image](https://user-images.githubusercontent.com/25742814/195321440-2f6769d8-5d35-4db5-80cd-e9ec4d40e5a5.png)

### Electron-Vite Version

1.0.8

### Electron Version

19.0.14

### Vite Version

3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
不建议在渲染进程使用，建议在主进程使用，同时在主进程配置中的external选项排除；如果非要在渲染进程使用，需要开启nodeIntegration，这是不安全做法，还用 remote模块已经被Electron移除，需要也要另外安装

**Comment by alex8088** [comment]
你需要先看electron文档，知道electron大致架构，关于electron-vite的配置的和功能特性也可以阅读一下文档

**Comment by DonXander** [comment]
我在主进程中引入datastore，现在启动报下面的错误
![image](https://user-images.githubusercontent.com/25742814/195331728-cff59c5d-727c-4f53-81f7-cb11df5527bc.png)

**Comment by alex8088** [comment]
你的源代码怎么写

**Comment by alex8088** [comment]
修改一下配置
```
 main: {
    build: {
      rollupOptions: {
        external: ['@electron-toolkit/utils','nedb']
      }
    }
  },
```

**Comment by DonXander** [comment]
![image](https://user-images.githubusercontent.com/25742814/195341002-eb3afc33-1ff1-4ba4-9752-0d114802b405.png)
配置改过了的，还是报错
![image](https://user-images.githubusercontent.com/25742814/195341927-1b66788a-9b02-46b6-afad-3df26c00cf73.png)


datastore.js
![image](https://user-images.githubusercontent.com/25742814/195341134-d3c7d908-c424-419e-8bcb-c053ee9fff01.png)

index.js只是简单引入
![image](https://user-images.githubusercontent.com/25742814/195341672-4a3c9793-8052-4f6e-9e6a-3ad9c52c351b.png)

**Comment by alex8088** [comment]
@DonXander 你的用法错误，不能在主进程中使用@electron/remote，这个模块不建议使用的，它为了将就以前不好开发模式，并且只能再渲染进程中使用，用来和主进程交互的。

```
import { app } from 'electron'
import nedb from 'nedb'
import * as path from 'path'

//...
app.whenReady().then(() => {
  // ....

  const db = new nedb({
    autoload: true,
    filename: path.join(app.getAppPath('userData'), 'db.db')
  })

  db.loadDatabase(function (err) {
    console.log(err)
  })

  //...
})
```

**Comment by alex8088** [comment]
@DonXander 问题是否解决？

**Comment by DonXander** [comment]
Thanks，its OK.
