### ISSUE TITLE
can't debug in webstorm

### ISSUE THREAD

**Issue by tiantao433** [alex8088/electron-vite#321]
### Describe the bug

add debug configuratin in webstorm by docs. but debug can't work in both main and render process.
vue:  3.3.6

### Electron-Vite Version

1.0.28

### Electron Version

25.9.2

### Vite Version

4.5.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
more detail and check your npm version

**Comment by tiantao433** [comment]
node v18.18.2, npm v9.8.1
can run debug mode, but breakpoint can't work

**Comment by tiantao433** [comment]
链接：https://pan.baidu.com/s/1UPnd0-C_dmEHkVhGIjBB_g?pwd=90b5 
提取码：90b5 
this is my project

**Comment by alex8088** [comment]
watch #130 video

**Comment by tiantao433** [comment]
my config is same with the video

<img width="536" alt="1" src="https://github.com/alex8088/electron-vite/assets/6522598/47c0d334-4182-4151-997c-747b372e912e">
<img width="538" alt="2" src="https://github.com/alex8088/electron-vite/assets/6522598/8619fa46-94ed-4dda-b1c1-06439ea675cd">

**Comment by alex8088** [comment]
add double-dash to retry  `-- --sourcemap --remote-debugging-port=9222`

**Comment by tiantao433** [comment]
add double-dash  works.  debug is ok now
