### ISSUE TITLE
环境变量无法读取变量

### ISSUE THREAD

**Issue by Z1oftheKill** [alex8088/electron-vite#325]
### Describe the bug

环境变量声明了之后无效
// package.json:    "dev": "electron-vite dev --mode development --watch ",
// .env.development: VITE_BASE_URL='http://192.168.1.10:8081' 

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/env-and-mode

**Comment by Z1oftheKill** [comment]
谢谢 我没有注意看内容抱歉
