### ISSUE TITLE
装饰器/反射 在 electron-vite 内预期不一致

### ISSUE THREAD

**Issue by Kenhuey** [alex8088/electron-vite#326]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/57590797/beb33289-70ae-408e-8464-c2fbbae342d3)

上图路径是 ./src/main/index.ts
已经在文件头部引用 
功能内容描述：给字段注入默认数据
```
import "reflect-metadata";
```
使用 electron-vite(yarn dev) 执行，结果不正常，无法正常赋值或反射操作
实际输出：
```
test - undefined
```

预期输出
```
test - 8088
```

### Electron-Vite Version

^1.0.27

### Electron Version

^25.6.0

### Vite Version

^4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [x] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/typescript-decorator

**Comment by Kenhuey** [comment]
> https://cn.electron-vite.org/guide/typescript-decorator

![image](https://github.com/alex8088/electron-vite/assets/57590797/81d0b840-17d0-48b4-a87b-45926b4c66cb)

是已经加上了的，但是不行😭

**Comment by alex8088** [comment]
请使用 electron-vite 而不是 ts-node

**Comment by Kenhuey** [comment]
> 请使用 electron-vite 而不是 ts-node

ts-node 是外部测试用的，内部使用 electron-vite  无法正常给 target 赋值

**Comment by alex8088** [comment]
不理解，这是两个不同的工具，ts-node 只是一个 TypeScript 执行器和node.js的 REPL而已，他不是构建工具不会支持装饰器。使用electron-vite去测试

**Comment by Kenhuey** [comment]
> 不理解，这是两个不同的工具，ts-node 只是一个 TypeScript 执行器和node.js的 REPL而已，他不是构建工具不会支持装饰器。使用electron-vite去测试

抱歉，可能是我没说明白意思，我用 ts-node 执行，或者使用 node 编译成 js 再运行之后上面一模一样的代码后，预期结果也是正确的
而用 electron-vite 去测试的话预期结果是不正确的，研究了一下午，目前尚不知道什么原因

issue 描述的内容是 两套一样的代码，在 electron-vite 内无法正常执行

**Comment by alex8088** [comment]
为否 有引入 reflect-metadata，你可以参考示例 ：https://github.com/alex8088/electron-vite-decorator-example

**Comment by Kenhuey** [comment]
> 为否 有引入 reflect-metadata，你可以参考示例 ：https://github.com/alex8088/electron-vite-decorator-example

在文件顶部已经引入了 reflect-metadata 的，参考示例也是看过，没有关于 PropertyDescriptor 的相关操作

**Comment by Kenhuey** [comment]
测试代码已上传在 main 分支  https://github.com/Kenhuey/com.mythsart.tbt4w
希望作者大大有空的话能抽空测试一下！

**Comment by Kenhuey** [comment]
研究了许久，找不到方法解决，放弃了，采用其他实现方式
