### ISSUE TITLE
打包后不能运行

### ISSUE THREAD

**Issue by king514jy** [alex8088/electron-vite#33]
### Describe the bug

删除lock 重新安装，都不行。
![image](https://user-images.githubusercontent.com/5669543/195517811-661fd179-441c-4340-9bd6-44c5d2b1fd1d.png)
`{
  "name": "resource-plaza",
  "version": "1.0.0",
  "description": "An Electron application with Vue",
  "main": "./out/main/index.js",
  "author": "",
  "homepage": "http://www.ledfin.cn",
  "scripts": {
    "format": "prettier --write .",
    "lint": "eslint . --ext .js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix",
    "start": "electron-vite preview",
    "dev": "electron-vite dev",
    "build": "electron-vite build",
    "postinstall": "electron-builder install-app-deps",
    "build:win": "npm run build && electron-builder --win --config",
    "build:mac": "npm run build && electron-builder --mac --config",
    "build:linux": "npm run build && electron-builder --linux --config"
  },
  "dependencies": {
    "@electron-toolkit/preload": "^1.0.2",
    "@electron-toolkit/utils": "^1.0.2",
    "axios": "^0.27.2",
    "crypto-js": "^4.1.1",
    "electron-log": "^4.4.8",
    "electron-store": "^8.1.0",
    "electron-updater": "^4.6.5",
    "element-plus": "^2.2.17",
    "form-data": "^4.0.0",
    "fs-extra": "^10.1.0",
    "gsap": "^3.11.2",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.1.4",
    "@vitejs/plugin-vue": "^3.0.3",
    "@vue/eslint-config-prettier": "^7.0.0",
    "electron": "20.2.0",
    "electron-builder": "23.3.3",
    "electron-notarize": "^1.2.1",
    "electron-vite": "^1.0.9",
    "eslint": "^8.24.0",
    "eslint-plugin-vue": "^9.4.0",
    "less": "^4.1.3",
    "prettier": "^2.7.1",
    "unplugin-auto-import": "^0.11.2",
    "unplugin-vue-components": "^0.22.7",
    "vite": "^3.0.9"
  }
}
`

### Electron-Vite Version

1.0.10

### Electron Version

20.2.0

### Vite Version

3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@king514jy  分清那些模块是渲染进程使用的，通常渲染进程会完全打包（将依赖一并打包），所以依赖模块最好安装为devDep(有效减少安装包体积)，而主进程需要的模块（deps）可以在配置文件中排除依赖，只需要打包自己的代码即可

```
  main: {
    build: {
      rollupOptions: {
        external: ['@electron-toolkit/utils', 'axios',...]
      }
    }
  },
```

下一个版本会优化增加插件来自动处理依赖

**Comment by alex8088** [comment]
你的报错貌似也不是依赖问题，而是找不到入口文件，有无更具体的信息

**Comment by king514jy** [comment]
@alex8088 
![image](https://user-images.githubusercontent.com/5669543/195528360-7fe9bb2d-78f4-4e4e-8260-e346a7057d9c.png)
![image](https://user-images.githubusercontent.com/5669543/195528411-3e8d8c73-59dd-4746-8ad0-a1db8464ce0b.png)
该问题并不是依赖的问题，不过我按你的建议从新安装了模块。入口，我都是保持的默认结构，没有修改过。测试环境下都是正常，但是打包以后，就找不到入口文件了

**Comment by king514jy** [comment]
@alex8088 
![image](https://user-images.githubusercontent.com/5669543/195528903-f1c701bb-e078-4081-a333-d96d65b7102a.png)

**Comment by alex8088** [comment]
@king514jy 旧脚手架上electron-builder配置有问题

**Comment by alex8088** [comment]
```
files:
  - '!**/.vscode/*'
  - '!src/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
```

**Comment by alex8088** [comment]
@king514jy 问题是否可以解决？

**Comment by king514jy** [comment]
@alex8088 可以了

**Comment by alex8088** [comment]
合理配置electron-builder 的 files 属性，是优化安装包体积的重要方法
