### ISSUE TITLE
Installer integrity check has failed. common causes includeincomplete download and damaged media. contact theinstaller's author to obtain a new copy More information at.http://nsis.sfnet/NSIS Error

### ISSUE THREAD

**Issue by chougaigai** [alex8088/electron-vite#334]
### Describe the bug

Installer integrity check has failed. common causes includeincomplete download and damaged media. contact theinstaller's author to obtain a new copy
More information at.http://nsis.sfnet/NSIS Error
<img width="893" alt="image" src="https://github.com/alex8088/electron-vite/assets/32348909/7ef91e0e-61cb-4f88-97dc-0c32259a47fa">

当我覆盖安装 或者 卸载时 报错。

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
electron-builder 问题 
https://github.com/electron-userland/electron-builder/issues/4875

**Comment by chougaigai** [comment]
> 电子生成器问题 [电子用户区/电子生成器#4875](https://github.com/electron-userland/electron-builder/issues/4875)

Thank you
