### ISSUE TITLE
Support Vite 5

### ISSUE THREAD

**Issue by undergroundwires** [alex8088/electron-vite#335]
### Clear and concise description of the problem

Vite 5 is [released](https://vitejs.dev/guide/migration.html) but this package requires maximum of Vite 4.x as peer-dependency, blocking migrations to Vite 5.

### Suggested solution

Support usage with Vite 5.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
Thanks for the reminder, it's under testing

**Comment by alex8088** [comment]
electron-vite 2 beta is out, welcome to test and report issues.

**Comment by shayded-exe** [comment]
After updating, rollup is no longer bundling dependencies for the main process. They're all being externalized.

I'm using the split vendor chunk plugin.

**Comment by alex8088** [comment]
@shayded-exe You can set `ssr.noExternal` to `true` to make externalizeDepsPlugin work

I will fix this issue.

**Comment by SvetBorislavov** [comment]
Fixed with v2.0.0

**Comment by alex8088** [comment]
electron-vite 2.0 is out! 🎉,check out [Announcement Blog Post](https://electron-vite.org/blog/) for details.
