### ISSUE TITLE
Support --no-sanbox Dev Options

### ISSUE THREAD

**Issue by khoetran** [alex8088/electron-vite#336]
### Clear and concise description of the problem

I got the following error message when running "npm run dev" command in linux OS.

**The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.**

### Suggested solution

It should be great if there is a way to pass "--no-sandbox" option to "electron" process.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
@khoetran This option(`--noSandbox`) will be supported in the next version soon. https://github.com/alex8088/electron-vite/commit/7369960b998cfb13cc7a46aa2d540956c28a379e

**Comment by alex8088** [comment]
new ver 1.0.29 is out 🎉
