### ISSUE TITLE
开发阶段vite热更只更新.vue内容，不会更新pinia的.ts文件内容。

### ISSUE THREAD

**Issue by 826327700** [alex8088/electron-vite#338]
### Describe the bug

例如，在pinia中写一个方法test(){console.log(1)}，在.vue中某个按钮调用这个方法，输出1，然后去改console.log(2)，再去调用方法，还是输出1。

### Electron-Vite Version

1.0.28

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
使用最新版本的pinia测试，并未发现有此问题，如果你确认你的代码没有问题，你可以在pinia或者vite反馈此问题。
