### ISSUE TITLE
渲染进程使用ipcRenderer报错

### ISSUE THREAD

**Issue by DonXander** [alex8088/electron-vite#34]
### Describe the bug

![image](https://user-images.githubusercontent.com/25742814/195972428-06899f5b-7237-4403-9d06-75e47988b82e.png)

引用代码：
![image](https://user-images.githubusercontent.com/25742814/195972456-f8e138cf-30c3-4768-9127-0d2de7e63fa2.png)

### Electron-Vite Version

1.0.8

### Electron Version

19.0.14

### Vite Version

3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
和你提的上一个issue一样的道理，不开启node集成的情况下，在渲染进程不可以使用任何node的能力，ipc调用也是通过preload暴露给渲染进程调用，脚手架集成了@electron-toolkit/preload 库， 可以直接使用  window.electron.ipcRenderer。

而渲染进程IPC监听可以参考 https://github.com/alex8088/EvPlayer/blob/master/src/renderer/src/hook/useIpcRendererOn.ts 这个hook。

你也可以一下研究上面的项目，有助于你快速深入。

**Comment by DonXander** [comment]
![image](https://user-images.githubusercontent.com/25742814/195974415-bc5a51d4-de83-4462-b5a8-ac045040d66d.png)
这样吗，会报错reading undefined

另外我在preload中这样引入，window.ipcRenderer也是reading undefined
![image](https://user-images.githubusercontent.com/25742814/195974476-33dbc8bb-1a26-448c-9d12-d824cadfb89f.png)

**Comment by alex8088** [comment]
具体地报错是什么

**Comment by DonXander** [comment]
![image](https://user-images.githubusercontent.com/25742814/195974890-cef08a5c-680a-4d67-be2a-4777d6845f18.png)

**Comment by alex8088** [comment]
window.electron.ipcRenderer.send('dd', ‘’)

**Comment by alex8088** [comment]
文档都有; https://github.com/alex8088/electron-toolkit/tree/master/packages/preload

**Comment by DonXander** [comment]
忘加send，不过还是上面报错
![image](https://user-images.githubusercontent.com/25742814/195975614-50fb36f6-e281-4501-bda6-d9c4f6bc6656.png)

按文档改成globals还是

**Comment by alex8088** [comment]
electronAPI

**Comment by DonXander** [comment]
不行呢

**Comment by DonXander** [comment]
![image](https://user-images.githubusercontent.com/25742814/195976118-554313f1-6ed8-49db-ab7d-f0845ab4d6fc.png)
这里加了这个配置会不会影响

**Comment by alex8088** [comment]
错误是什么

**Comment by DonXander** [comment]
![image](https://user-images.githubusercontent.com/25742814/195976472-4b1b22df-d11d-4f93-a399-0b6af8716d93.png)
还是这个

**Comment by alex8088** [comment]
如果没有使用热重载，重新运行编译一下，是否给对应的渲染进程加载了preload脚本，自己打印多点日志排逐步排查吧

**Comment by DonXander** [comment]
![image](https://user-images.githubusercontent.com/25742814/195980836-0b2d4b04-cac3-4bc5-baab-d5f3ef298364.png)
是这里加载的preload吧

我从0重新创建了一个ev应用，如下使用还是会报错
![image](https://user-images.githubusercontent.com/25742814/195980892-033c9e39-4cf0-4d56-a8ea-43f4e2f91fda.png)

**Comment by alex8088** [comment]
错误和日志？能输出下面
![深度截图_选择区域_20221015203224](https://user-images.githubusercontent.com/25053004/195986589-edfc8902-545b-4f97-bd03-92473ef62abc.png)

**Comment by alex8088** [comment]
或者提供你的源码看看

**Comment by DonXander** [comment]
![image](https://user-images.githubusercontent.com/25742814/195987510-9f27baca-aefb-424d-b1da-c36285b8b260.png)

[electron-app-new.zip](https://github.com/alex8088/electron-vite/files/9792106/electron-app-new.zip)

**Comment by alex8088** [comment]
![2022-10-15 21-47](https://user-images.githubusercontent.com/25053004/195990030-a1134b10-e03a-4a39-bb75-dfa11fa0528c.gif)

**Comment by DonXander** [comment]
??你有改什么吗

**Comment by DonXander** [comment]
哦明白了，涉及主进程是只能在electron容器里面调试，我之前是浏览器打开的
