### ISSUE TITLE
I got an error to building the app using pnpm

### ISSUE THREAD

**Issue by imnash21** [alex8088/electron-vite#343]
### Describe the bug

I use pnpm to install the app then I tried to build the app using this command "**pnpm build:win**" then I got an error, so I check the **scripts** at the **package.json** and it use the "**npm run...**" then I replace it all to "**pnpm...**" and I try to run this command "**pnpm build:win**" again and it's working with no errors or warnings.

### Electron-Vite Version

1.0.29

### Electron Version

27.0.0

### Vite Version

4.4.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
You should check your pnpm version, and more error details. It's mostly a network issue or dependencies installation issue.

**Comment by imnash21** [comment]
If this command "**pnpm build** it's working normally, but if "**pnpm build:win**" command I got an error, so I need to replace the "**npm run...**" to "**pnpm...**" in **package.json** -> **scripts**.
