### ISSUE TITLE
UOS+Kunpeng 920 无法安装依赖

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#345]
### Describe the bug

UOS+Kunpeng 920 无法安装依赖;

![QQ图片20231207092925](https://github.com/alex8088/electron-vite/assets/39619390/33e7167c-b7fa-4e2f-a71e-627a77d5f02b)

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
升级你的nodejs

**Comment by tom-style** [comment]
> 升级你的nodejs

node 版本是 16.20.2，还要升？

**Comment by tom-style** [comment]
> 升级你的nodejs

![image](https://github.com/alex8088/electron-vite/assets/39619390/f6a5f30a-54d5-4604-bec8-4d9d3fdb5557)

![image](https://github.com/alex8088/electron-vite/assets/39619390/995a2a64-526a-49ae-bfa3-ccfc1998ac4e)
