### ISSUE TITLE
Unexpected files included in final build

### ISSUE THREAD

**Issue by clintonblackmore** [alex8088/electron-vite#349]
Summary:
===

Folders in the root directory of an electron vite project end up in the .asar file of the build application.

How I Discovered This Issue:
===

_(Proper 'steps to reproduce' are below)._

I created a new project on 2023-12-02 using the command:

```
npm create @quick-start/electron <project_name> -- --template svelte-ts
```

and I must first say, electron-vite is very impressive. Thank you for this.

Anyways, today I was trying to figure out how to make mac builds for Intel and Apple Silicon architectures. I renamed my 'dist' folder so that I could diff the results against my original results. Then I renamed that folder, too, as it hadn't worked. After doing this several times, I noticed that my app sizes had ballooned from, say, 200 mb to 5.76 GB, and then it wouldn't build. The error in the terminal said "app.asar: file size cannot be larger than 4.2GB".

That got me suspicious. After I figured out how to extract an asar file, I was able to confirm that, yes, the latest builds contains all the random 'dist-XXXX' folders.

This was surprising to me. I would expect that only a whitelist of folders would be included in the final Electron application. I can't see why I might desire to create a folder in the root of my project and have it automatically included in the final application unless I expressly want it there.

------------

I suppose I should write this step-by-step as a bug.

Steps To Reproduce
===

Note that I'm using a Mac, but these instructions should be straightforward to adjust for other platforms.

1. Create a new project: `npm create @quick-start/electron unexpected-growth -- --template svelte-ts`

2. Install and build: ` cd unexpected-growth && npm install && npm run build:mac`

3. Preserve the dist folder: `mv dist dist-original`

4. Build again. (You could pretend that you changed the build configuration file and want to see what differs.) `npm run build:mac`

Expected Result
===

The output in `dist-original` and `dist` should be identical.

Actual Result
===

The `unexpected-growth` app in the `dist` folder is 598 mb, whereas the one in the `dist-original` folder is 213 mb.

`dist-original/mac-arm64/unexpected-growth.app/Contents/Resources/app.asar` is 45 kb.
`dist/mac-arm64/unexpected-growth.app/Contents/Resources/app.asar` is 367 mb.

To see what is in the second asar file, run:

`npx @electron/asar extract dist/mac-arm64/unexpected-growth.app/Contents/Resources/app.asar ExtractedASAR`

Looking through the output folder, the reason is obvious: it (unexpectedly!) includes the `dist-original` folder.

### Electron-Vite Version

^1.0.27

### Electron Version

v25.9.8

### Vite Version

^4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@clintonblackmore 

You need to use electron-builder to exclude folders that do not need to be published.

https://electron-vite.org/guide/distribution#distributing-apps-with-electron-builder.

use `file` filed to exclude folder

```yml
files:
  - '!dist-XXXX/*
```
