### ISSUE TITLE
uos 20sp1 可以运行起来，但是控制台报错；

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#350]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/39619390/ff50974a-a747-402d-8066-7b3f0643345d)

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
此问题不在electron-vite层面，建议你去electron反馈此问题
