### ISSUE TITLE
uos 20sp1 build 失败

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#351]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/39619390/35c97657-ec6f-4c41-a9a2-5e3d565077e6)

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
此问题不在electron-vite层面，可能是平台兼容问题，建议你去electron-builder检索是否有有相关问题或者反馈问题
