### ISSUE TITLE
Config output format must be "cjs" supportESM() or "es"' but it does not support "es"

### ISSUE THREAD

**Issue by Konglomneshued** [alex8088/electron-vite#352]
### Describe the bug

I'm trying the beta version and getting issues when building.

Here is my main section in `electron.vite.config.ts`:

```
...
main: {
      plugins: [ externalizeDepsPlugin() ],
      build: {
         rollupOptions: {
            output: {
               format: 'esm',
               entryFileNames: '[name.mjs]',
            },
         },
      },
   },
...
```

I get this error when `npm run dev`
```
throw new Error(`The electron vite main config output format must be "cjs"${supportESM() ? ' or "es"' : ''}.`);
```

So I change my config:

```
...
main: {
      plugins: [ externalizeDepsPlugin() ],
      build: {
         rollupOptions: {
            output: {
               // Changed from esm to es
               // because of above error.
               format: 'es',
               entryFileNames: '[name.mjs]',
            },
         },
      },
   },
...
```

I get this error:
```
throw new Error('The electron vite main config output format does not support "es", ' +
```

The error messages provide conflicting information.

### Electron-Vite Version

2.0.0-beta.0

### Electron Version

^27.1.3

### Vite Version

^4.2.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Should be electron 28, or you will get this error.

There are two ways to enable esm in electron:

- add " type": " module"  in package.json 
- set the ` build. rollupOptions.output.format` to `es`.

otherwise, you should rewrite your preload path in code with `.mjs` suffix.

if your electron version less then 28, it must be always cjs format.

**Comment by alex8088** [comment]
Need to make error messages more user friendly

**Comment by Konglomneshued** [comment]
> Should be electron 28, or you will get this error.
> 
> There are two ways to enable esm in electron:
> 
>     * add " type": " module"  in package.json
> 
>     * set the ` build. rollupOptions.output.format` to `es`.
> 
> 
> otherwise, you should rewrite your preload path in code with `.mjs` suffix.
> 
> if your electron version less then 28, it must be always cjs format.

Thank you, it's working now.
