### ISSUE TITLE
判断is.dev错误，is是一个 object，应该是 is.is.dev 才能获取到

### ISSUE THREAD

**Issue by mx623303468** [alex8088/electron-vite#355]
### Describe the bug

src/mian/index.ts:32   
```js
// 这个地方is是一个Object，需要is.is.dev 获取才是正确的
if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
````
![is](https://github.com/alex8088/electron-vite/assets/36760861/e158df04-0157-4417-ac20-e65cc4f03af6)

### Electron-Vite Version

1.0.27

### Electron Version

22.3.9

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
这个取决于你如何导入 utils 库，如使用具名导入`import { is } form @electron-toolkit/utils` 是 is.dev，如果你改为默认导入 `import utils form @electron-toolkit/utils` 则是 utils.is.dev.

**Comment by mx623303468** [comment]
> 这个取决于你如何导入 utils 库，如使用具名导入`import { is } form @electron-toolkit/utils` 是 is.dev，如果你改为默认导入 `import utils form @electron-toolkit/utils` 则是 utils.is.dev.

 是这样导入的，`import { electronApp, optimizer, is } from '@electron-toolkit/utils'` 脚手架生成后，没有改动。。。 有时是好的，我再看看，谢谢大佬的回复，比心~
