### ISSUE TITLE
使用electron-vite创建vue模板，多窗口不知道如何配置多个预加载脚本

### ISSUE THREAD

**Issue by 1361176289** [alex8088/electron-vite#358]
### Describe the bug

我使用了electron-vite vue的模板，然后我想创建多窗口的同时使用新的预加载脚本，我在preload文件夹内新建一个ts文件想要通过这个方式去创建新的预加载脚本，但是我发现在out文件夹内没有生成对用的js文件，我看了官网文档没有太明白使用vue的方式是怎样创建的

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/dev#%E5%A4%9A%E7%AA%97%E5%8F%A3%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F
