### ISSUE TITLE
父窗口给子窗口通信

### ISSUE THREAD

**Issue by 1361176289** [alex8088/electron-vite#361]
### Describe the bug

我新建窗口后想给子窗口发送消息，报错
![image](https://github.com/alex8088/electron-vite/assets/58896251/8bbe7067-9acd-43a5-a6ae-af26bf5185fe)
子窗口接收：
![image](https://github.com/alex8088/electron-vite/assets/58896251/55aef7e2-4bd2-48db-91c6-6e074615bc32)
控制台报错：
![image](https://github.com/alex8088/electron-vite/assets/58896251/9e00a084-c0ce-49ae-a25a-2365ad24d71f)

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
这是代码逻辑错误，你可以在开发者群中向其他开发者探讨请教。
