### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module 配置 exclude后，依然报错

### ISSUE THREAD

**Issue by huangxh1** [alex8088/electron-vite#363]
### Describe the bug

1. 使用`npm i`安装  `pdfjs-dist`库
2. 使用 `npm run dev`命令，启动项目，出现` require() of ES Module`错误
3. 根据`electron-vite`文档，添加`plugins: [externalizeDepsPlugin({ exclude: ['pdfjs-dist'] })]`配置
4. 再次使用第2步的命令启动项目，出现` Rollup failed to resolve import "canvas" from "/Users/hang/Documents/MyWork/template/node_modules/pdfjs-dist/legacy/build/pdf.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external`
5. 根据提示，在`electron.vite.config.ts`文件中的`main`添加如下代码：
 ```ts
    build: {
      rollupOptions: {
        external: ['canvas']
      }
    }
 ```
6. 再次启动出现以下错误：

<img width="1394" alt="image" src="https://github.com/alex8088/electron-vite/assets/30429312/f7c1ea0b-4621-4316-84e6-6fc92a5ad386">

---
`pdfjs-dist`版本：`4.0.269`
`系统平台`：`Mac M1CPU`
`node`版本：`v16.20.2`
---
本人后端仔（会vue），才接触electron项目，实在找不出原因，所以来此求助，望大佬抽空帮忙看一下，感谢

### Electron-Vite Version

1.0.29

### Electron Version

22.3.27

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
确认你自己是否修改了构建输出目录配置，对应修改package. json main 的入口文件地址，按错误提示去排查

**Comment by huangxh1** [comment]
> 确认你自己是否修改了构建输出目录配置，对应修改package. json main 的入口文件地址，按错误提示去排查

已经找到问题了，配置那些都是对的，问题是处在`pdfjs`这个工具里，里面使用了一些html相关的，就不能在主线程里使用，智能去渲染线程里用。感谢大佬
