### ISSUE TITLE
BrowserView无效

### ISSUE THREAD

**Issue by king514jy** [alex8088/electron-vite#37]
### Describe the bug

![image](https://user-images.githubusercontent.com/5669543/197229139-a04e5019-6de0-4aef-bfe3-f006d2dabaed.png)
默认示例项目，改用BrowserView加载页面，窗口无任何显示
![image](https://user-images.githubusercontent.com/5669543/197229715-f17a00d0-1b2c-40f5-af76-4156a4ee5360.png)

### Electron-Vite Version

1.0.10

### Electron Version

20.3.1

### Vite Version

3.1.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
主窗口必须有加载页面，且view最好是在主窗口ready to show 后创建。可以参考 https://github.com/alex8088/electron-micro-app

**Comment by king514jy** [comment]
@alex8088 原始我记得是不用必须主窗口有内容，这是你插件的设定吗？之前有遇到新开窗口并打开别人的网页，他的网页内有个跳转，直接使用窗口不会自动跳转，得使用BrowserView。如果主窗口必须加载页面，感觉挺奇怪得。

**Comment by alex8088** [comment]
@king514jy electron-vite 仅仅是构建工具而已，不会对electron本身有任何设定。你提到的情况我没有验证了解，但你要知道electron不同版本之间也有差异。尤其是20之后的版本，安全要求更高，沙盒模式默认开启等等。多做些尝试以了解原因。
