### ISSUE TITLE
build:win，构建windows应用程序时 {{version}}解析失败

### ISSUE THREAD

**Issue by ZHJ0413** [alex8088/electron-vite#371]
### Describe the bug

![screenshot_2024-01-03_17-19-06](https://github.com/alex8088/electron-vite/assets/128804549/dae89e0c-d857-4817-8f2a-50fb9aa9e732)

麻烦看一下，谢谢
### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
确保electron-builder正确安装，或者重新安装依赖

**Comment by ZHJ0413** [comment]
> 确定 Electron-builder 正确安装，或者重新依赖安装

![screenshot_2024-01-03_18-48-42](https://github.com/alex8088/electron-vite/assets/128804549/36d8b815-b83c-41f9-911c-56ef8f22c59a)

确定正确安装后仍然没法解析{{version}}

**Comment by alex8088** [comment]
从截图来看，貌似并不是正常的安装过程，你可以删除lock文件和node_modules，再重新安装 `npm run install` 或  `pnpm I`

**Comment by ZHJ0413** [comment]
已经解决，环境变量的问题，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月06日 11:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alex8088/electron-vite] build:win，构建windows应用程序时 {{version}}解析失败 (Issue #371) |

从截图来看，貌似并不是正常的安装过程，你可以删除lock文件和node_modules，再重新安装 npm run install 或 pnpm I
