### ISSUE TITLE
desktopCapturer.getSources 方法 types: ['window'] ，获取不到应用自身的窗口截图

### ISSUE THREAD

**Issue by blcyzycc** [alex8088/electron-vite#373]
### Describe the bug

我想要获取应用的截图，但是使用此方法获取窗口的截图，只能获取到其它窗口的，应用自身的截图获取不到。我试着用原来的开发模板 vue3+electron13 可以获取到，这个能解决嘛，不然只能使用老版本开发了。

if (process.platform === 'win32') {
    desktopCapturer.getSources({
      types: ['window'],
      thumbnailSize: { width: 1920, height: 1080}
    }).then(async sources => {
      console.log(sources);
    })
  }

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
请先确认正确使用api，推荐你使用preload开发，在preload中使用desktopCapturer

**Comment by blcyzycc** [comment]
试过了，在 preload 中使用 desktopCapturer.getSources 会直接报错
![微信图片_20240108125121](https://github.com/alex8088/electron-vite/assets/36541261/4c106991-c877-4e08-b98f-87d74a7e813a)

**Comment by alex8088** [comment]
desktopCapturer 从 electorn 17 开始只能在主进程中使用，https://www.electronjs.org/blog/electron-17-0#highlighted-features

**Comment by blcyzycc** [comment]
我把electron降低到 17.4.11 版本，已经可以获取到当前应用的截图。这个功能问题应该electron更新导致的，或者是有什么新特性，但是文档里面没有给任何参数或说明

**Comment by alex8088** [comment]
参数一样，就是为了安全只能在主进程使用而已

**Comment by blcyzycc** [comment]
就是在主进程用的，能获取到其它应用的截图，但是获取不到electron应用本身的，我在electron Issues看到不止我一个人遇到这种问题，回退到v17.4.11版本就正常了



在 2024-01-08 15:47:59，"alex.wei" ***@***.***> 写道：

参数一样，就是为了安全只能在主进程使用而已
