### ISSUE TITLE
Worker arent working on build mac

### ISSUE THREAD

**Issue by Makio64** [alex8088/electron-vite#375]
### Describe the bug

Following the current documentation, Worker works well on build windows but not on build mac ( the file isnt unpack ).
```
{
	//...
	"directories": {
		"buildResources": "build"
	},
	"files": [
		"!src/*",
		//...
	],
	"asarUnpack": [
		"resources/**",
		"out/main/worker.mjs",
		"out/main/worker.js",
		"out/main/worker.jsc",
		"out/main/bytecode-loader.cjs"
	],
	"nsis": {
		//...
	},
	"win": {
		//...
	},
	"mac": {
		"identity": null,
		"extendInfo": {
			"NSCameraUsageDescription": "Application requests access to the device's camera.",
			"NSMicrophoneUsageDescription": "Application requests access to the device's microphone.",
			"NSDocumentsFolderUsageDescription": "Application requests access to the user's Documents folder.",
			"NSDownloadsFolderUsageDescription": "Application requests access to the user's Downloads folder."
		},
		"notarize": false
	},
	"dmg": {
		"artifactName": "${name}-${version}.${ext}"
	},
	"linux": {
		//...
	},
	//...
}
```

And. 

```
import //...

export default defineConfig({
	main: {
		plugins: [externalizeDepsPlugin(), bytecodePlugin()],
		build: {
			rollupOptions: {
				input: {
					index: resolve(__dirname, 'src/main/index.js'),
					worker: resolve(__dirname, 'src/main/worker.mjs'),
				},
			},
		},
	},
	preload: {
		plugins: [externalizeDepsPlugin(), bytecodePlugin()],
	},
	//..
})


### Electron-Vite Version

beta4

### Electron Version

28.1.1

### Vite Version

5.0.11

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
正常构建行为是一致的，请确保代码是一致的，或者提供更详细的错误信息

**Comment by alex8088** [comment]
more details

**Comment by Makio64** [comment]
I try both way to integrate workers documented here : https://electron-vite.org/guide/assets#importing-worker-threads

When `pnpm dev` : no problem on mac / windows - the worker answer
When `build:win` : compile, no problem the worker answer 
When `build:mac`: compile, but when the worker is call nothing happen, the worker don't answer to the postMessage.

Its like it try to create the worker from the wrong place or from an empty file

I logged the createWorker function compiled : 
```
function createWorker(options) { return new node_worker_threads.Worker(new URL("./chunks/worker-bYROrqmS.js", require("url").pathToFileURL(__filename).href), options); }
```

On the example its hard to see if it works as there is nothing on the front size : https://github.com/alex8088/electron-vite-worker-example/tree/1bd39ad4a65f7441515a9daa5a55f8e636adc7cb/src/main

**Comment by alex8088** [comment]
Usually workers will not have cross-platform problems, you can add some logs to troubleshoot.

**Comment by alex8088** [comment]
> Any suggestions on the logs I could add ? Its a bit hard to debug as the worker didnt pop or throw any error, it just not answering anything when built on mac only ( `Macbookpro M3 pro Max` )

print some console logs to track

**Comment by Makio64** [comment]
I just did a test by forking your electron-vite-worker-example : https://github.com/Makio64/electron-vite-worker-example
and it works ! =)

So I investigate more the worker in my app and the error was from `sharp` lib, on compile and on mac only it need this : 
```
    "asarUnpack": [
      "**/node_modules/sharp/**/*",
      "**/node_modules/@img/**/*"
    ]
```
Else the worker crash silently on sharp import..

**Comment by tsekiguchi** [comment]
I'm running into a similar, but different problem with bytecode and workers. 

When using bytecode, one of my main workers didn't function anymore. When I disabled the bytecode plugin, it would work again. This worker has a few specific packages that its importing like `ffmpeg`, `sharp`, and `exiftool` that are included in the `app.asar.unpack`.

The specific error that was throwing when bytecode was enabled was that there was no handler for the request in my worker.

As a potential solution, I tried to compile `index.ts` to bytecode, as referenced in the source code protection documentation: https://electron-vite.org/guide/source-code-protection#customizing-protection. However, this did not fix the problem in prod.

The current solution that I've come up with was to take the `worker.js` file, and place it in the resources directory, and point to it as a public asset (https://electron-vite.org/guide/assets#importing-asset-as-file-path). I also had to remove `require("../out/main/index.js");` which was serving no purpose, but was placed there when transpiling from `.ts` to `.js`.

I hope that this information can help someone else in the future, or help lead to a potential fix! Please let me know if I can provide any other information.
