### ISSUE TITLE
client side errors are always uncaught and sent to preload.js

### ISSUE THREAD

**Issue by benzmuircroft** [alex8088/electron-vite#377]
### Describe the bug

I need to trace the errors but it wont let me! it's ignoring the window.onerror function completely!

### Electron-Vite Version

latest

### Electron Version

latest

### Vite Version

latest

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
``` js
window.addEventListener('error', (event) => {
});
window.addEventListener('unhandledrejection', (event) => {
});
```

**Comment by alex8088** [comment]
Can't understand your thoughts. Please proivde some examples.
