### ISSUE TITLE
File Watcher Configurations Not Working

### ISSUE THREAD

**Issue by ElsevarAsadov** [alex8088/electron-vite#379]
### Describe the bug

My application uses sqlite and the db file in located in resources folder.the problem is that I use vite file watcher in development but when ever something changes in db of course vite catch this change and restart app.The problem is I try everything in electron.vite.config.js to ignore the db file using ```ignored``` paramaterer in server.watch but nothing changes.even i give empty object and false parameter to make sure this params is working but still no effect.

I tried every possibility.

```js

import { resolve } from 'path'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  server:{
    watch:false
  },
  main: {
    server:{
      watch:false
    },
    plugins: [externalizeDepsPlugin()]
  },
  renderer: {
    server:{
      watch:false
    },
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },
    plugins: [react()]
  }
})```


### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
electron-vite does not enable `watch` by default。If you enable [hot reloading](https://electron-vite.org/guide/hot-reloading), only dependent files will be watched. Please provide more details or a simple repo to reproduce.

You can check out [hot reloading](https://electron-vite.org/guide/hot-reloading) for more details.

**Comment by ElsevarAsadov** [comment]
> electron-vite does not enable `watch` by default。If you enable [hot reloading](https://electron-vite.org/guide/hot-reloading), only dependent files will be watched. Please provide more details or a simple repo to reproduce.
> 
> You can check out [hot reloading](https://electron-vite.org/guide/hot-reloading) for more details.

Hi, sorry I forgot to specify that I use --watch flag and I wanna ignore dB file

**Comment by ElsevarAsadov** [comment]
my configuration is wrong.watch configuration should be ```build.watch.exclude``` thanks
