### ISSUE TITLE
在 preload 使用 ESM 报错

### ISSUE THREAD

**Issue by Lingyan000** [alex8088/electron-vite#382]
### Describe the bug

在 preload 如果编译为 ESM 使用 __dirname 会报错，原因是 electron-vite 兼容 cjs 时使用了 import.meta.url，这似乎在 preload 中无法使用
```
sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
```

### Electron-Vite Version

2.0.0

### Electron Version

28.1.3

### Vite Version

5.0.11

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
这个错误和esm无法，没有正确使用ipc，可能在窗口关闭或者ipc已被注销等其他情况下仍然调用ipc导致

**Comment by Lingyan000** [comment]
![image](https://github.com/alex8088/electron-vite/assets/34851056/6c1b2b04-babb-438c-820b-7ac115f0327a)
好像和 contextIsolation 有关，我把 contextIsolation 设置为 true 就正常了

**Comment by Lingyan000** [comment]
同时我发现 bytecodePlugin 无法在 esm 模式下生效

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/dev#electron-的-esm-支持

**Comment by Lingyan000** [comment]
> [https://cn.electron-vite.org/guide/dev#electron-的-esm-支持](https://cn.electron-vite.org/guide/dev#electron-%E7%9A%84-esm-%E6%94%AF%E6%8C%81)

这种情况将无法打开渲染进程，错误确实和 esm 无关，这应该是 electron 的问题

```typescript
// main
const mainWindow = new BrowserWindow({
    width: 900,
    height: 670,
    show: false,
    autoHideMenuBar: true,
    ...process.platform === "linux" ? { icon } : {},
    webPreferences: {
      preload: join$1(__dirname, "../preload/index.mjs"),
      sandbox: false,
      contextIsolation: false,
      webSecurity: false
    }
  });
```

```typescript
// preload

console.log(import.meta.url)
// ...
```
