### ISSUE TITLE
cliui dependency error

### ISSUE THREAD

**Issue by nijinekoyo** [alex8088/electron-vite#383]
### Describe the bug

`require() of ES Module` error when trying to build the project, caused by dependency on `cliui`
Use the solution in the [documentation](https://cn-evite.netlify.app/guide/troubleshooting.html#%E6%9E%84%E5%BB%BA) to fix it but it fails.

Log
```
$ electron-builder install-app-deps

project\node_modules\cliui\build\index.cjs:291
const stringWidth = require('string-width');
                    ^
Error [ERR_REQUIRE_ESM]: require() of ES Module project\node_modules\string-width\index.js from project\node_modules\cliui\build\index.cjs not supported.
Instead change the require of index.js in project\node_modules\cliui\build\index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (project\node_modules\cliui\build\index.cjs:291:21)
    at Object.<anonymous> (project\node_modules\yargs\build\index.cjs:1:60678)
    at Object.<anonymous> (project\node_modules\yargs\index.cjs:5:30)
    at Object.<anonymous> (project\node_modules\electron-builder\out\builder.js:7:15)
    at Object.<anonymous> (project\node_modules\electron-builder\out\cli\cli.js:11:19)
    at Object.<anonymous> (project\node_modules\electron-builder\cli.js:4:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Electron-Vite Version

^2.0.0

### Electron Version

^28.1.1

### Vite Version

^5.0.11

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by nijinekoyo** [comment]
cliui issues about this issue
https://github.com/yargs/cliui/issues/138

**Comment by nijinekoyo** [comment]
This problem seems to be caused by tailwindcss. It will return to normal after removing the relevant dependencies.

**Comment by nijinekoyo** [comment]
This problem occurred when trying to install `vue-router@4`. After testing, it seems that this error will occur as long as `vue-router@4` is installed.

**Comment by nijinekoyo** [comment]
[electron-app.zip](https://github.com/alex8088/electron-vite/files/13945202/electron-app.zip)
This problem was successfully reproduced in this blank project

**Comment by nijinekoyo** [comment]
Very strange, it seems that as long as tailwindcss is introduced first, and then vue-router is introduced, this problem will be triggered.

**Comment by alex8088** [comment]
[cliui](https://github.com/yargs/cliui/tree/master) only supports esm, so you need to exclude it in externalizeDevPlugin or install in devDependencies.

**Comment by nijinekoyo** [comment]
I developed it in an esm environment, and this bug still appears, and this bug is also related to the dependent installation order, which is very confusing.

**Comment by alex8088** [comment]
failed when executing `electron-builder install-app-deps` command?

**Comment by nijinekoyo** [comment]
Yes, direct `yarn install` will also fail

**Comment by nijinekoyo** [comment]
You can try the blank project I posted above

**Comment by alex8088** [comment]
It may be that [cliui](https://github.com/yargs/cliui/tree/master) does not correctly handle the relationship between dependent packages(esm or cjs). You  can remove `postinstall` script in your `package.json`.  `electron-builder install-app-deps` command use to rebuild native node module, you can skip it first. If you cannot use it normally, it is recommended to replace it with other packages.

**Comment by nijinekoyo** [comment]
ok
