### ISSUE TITLE
Can't import types declared in main/index.ts outside of svelte files

### ISSUE THREAD

**Issue by Sahasrara** [alex8088/electron-vite#384]
### Describe the bug

I'm trying to import types declared in main/index.ts from a file called settings.ts that's used by the renderer. It can't find the types.

By contrast, I am able to import the same type within all .Svelte files.

### Electron-Vite Version

^2.0.0

### Electron Version

^28.1.1

### Vite Version

^5.0.11

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Sahasrara** [comment]
I've also noticed that some files can't resolve aliases defined in tsconfig.json. I'm not sure if that's related.

```
{
  "extends": "@electron-toolkit/tsconfig/tsconfig.json",
  "include": [
    "src/renderer/src/env.d.ts",
    "src/renderer/src/**/*",
    "src/renderer/src/**/*.svelte",
    "src/renderer/src/**/*.ts",
    "src/preload/*.d.ts"
  ],
  "exclude": [
    "src/renderer/lib/vendor/**"
  ],
  "compilerOptions": {
    "verbatimModuleSyntax": true,
    "useDefineForClassFields": true,
    "strict": false,
    "allowJs": true,
    "checkJs": true,
    "lib": ["ESNext", "DOM", "DOM.Iterable"],
    "baseUrl": "./src",
    "paths": {
      "@lib/*": ["renderer/lib/*"]
    },
    "types": ["vitest/globals"]
  },
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

**Comment by Sahasrara** [comment]
I've also noticed that it's not resolving aliases defined in tsconfig.json. I'm not sure if that's related or not:

```
{
  "extends": "@electron-toolkit/tsconfig/tsconfig.json",
  "include": [
    "src/renderer/src/env.d.ts",
    "src/renderer/src/**/*",
    "src/renderer/src/**/*.svelte",
    "src/renderer/src/**/*.ts",
    "src/preload/*.d.ts"
  ],
  "exclude": [
    "src/renderer/lib/vendor/**"
  ],
  "compilerOptions": {
    "verbatimModuleSyntax": true,
    "useDefineForClassFields": true,
    "strict": false,
    "allowJs": true,
    "checkJs": true,
    "lib": ["ESNext", "DOM", "DOM.Iterable"],
    "baseUrl": "./src",
    "paths": {
      "@lib/*": ["renderer/lib/*"]
    },
    "types": ["vitest/globals"]
  },
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

**Comment by Sahasrara** [comment]
Moving the "lib" folder into renderer/src/ seemed to resolve both issues. I'm not sure what's going on.

**Comment by alex8088** [comment]
Sometimes it may be an IDE problem, just restart it. Recommended sharing types example: https://github.com/alex8088/EvPlayer

**Comment by Sahasrara** [comment]
Thanks for the tip! It seems to work having moved the lib directory under src/renderer/src. I couldn't get it to work otherwise.

Also, I'm still not able to see any of the renderer/.d.ts types in renderer/*.ts files. I can see the window.api in .Svelte files, but not .ts files. 

Any idea what could cause that? Kind of a similar problem to what I was experiencing with the lib folder .ts files importing types, except this time, the .ts files are already in the src/renderer/src folder.

**Comment by Sahasrara** [comment]
Ah! I tracked it down to tsconfig.node.json. This include:

`"src/preload/*"`

It seems that by commenting that out, the preload .d.ts started working.
