### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Z1oftheKill** [alex8088/electron-vite#385]
### Describe the bug

![1705567022051](https://github.com/alex8088/electron-vite/assets/86594107/78e3da00-69ba-409f-a1be-c7ae90bc2a87)
在打包完了 运行exe安装文件的时候报错了

### Electron-Vite Version

"^1.0.27"

### Electron Version

"^25.6.0"

### Vite Version

"^4.4.9"

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/troubleshooting#a-javascript-error-occurred-in-the-main-process-error-cannot-find-module-xxx

**Comment by Z1oftheKill** [comment]
> https://cn.electron-vite.org/guide/troubleshooting#a-javascript-error-occurred-in-the-main-process-error-cannot-find-module-xxx
谢谢 我解决了  用yarn就行  但是打出来的包双击运行之后没有反应 , 请问打包的配置项是在哪里配置?

**Comment by Z1oftheKill** [comment]
> electron-builder中配置，如果是安装后无法运行， 尝试 https://cn.electron-vite.org/guide/troubleshooting#%E6%8A%80%E5%B7%A7 去排错

(node:17316) electron: Failed to load URL: file:///E:/Product/ykw/dzkj-static2/out/renderer/index.html/%23/newsKCharts with error: ERR_FILE_NOT_FOUND
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:17316) electron: Failed to load URL: file:///E:/Product/ykw/dzkj-static2/out/renderer/index.html/%23/login with error: ERR_FILE_NOT_FOUND
(node:17316) electron: Failed to load URL: file:///E:/Product/ykw/dzkj-static2/out/renderer/index.html/%23/home with error: ERR_FILE_NOT_FOUND 
 我使用cmd运行exe文件抛出了这样的错误 请问哪里有文档可以解决关于这个错误的?

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/troubleshooting#vue-router-%E6%88%96-react-router-dom-%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E6%AD%A3%E5%B8%B8-%E4%BD%86%E5%9C%A8%E6%9E%84%E5%BB%BA%E5%90%8E%E6%97%A0%E6%95%88
