### ISSUE TITLE
Support for Utility Processes

### ISSUE THREAD

**Issue by Sahasrara** [alex8088/electron-vite#386]
### Clear and concise description of the problem

It'd be great to be able to support Utility processes. Or if it's already possible, to document how they can be used. Right now, it's not clear how to use them with typescript.

### Suggested solution

I don't have any ideas.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
@Sahasrara, You can refer to nodejs worker
https://electron-vite.org/guide/assets#import-with-constructors

PS: UtilityProcesses tutorials will be added to the docs

**Comment by alex8088** [comment]
new ver 2.1.0 is out 🎉. Easy way to use Electron UtilityProcess API.

https://electron-vite.org/guide/dev#utility-process-and-child-process
