### ISSUE TITLE
模板文件里面引用js文件打包的时候打包不进去

### ISSUE THREAD

**Issue by Z1oftheKill** [alex8088/electron-vite#387]
### Describe the bug

<script src="/src/TweenMax.min.js"> in "/index.html" can't be bundled without type="module" attribute

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
通过 import 导入静态脚本或者通过vite的静态资源处理，静态资源可在 src/renderer下新增 public 目录 https://cn.vitejs.dev/guide/assets.html#the-public-directory
https://cn.electron-vite.org/guide/assets
