### ISSUE TITLE
After upgrading to Vite 5, decorators are no longer functioning as expected

### ISSUE THREAD

**Issue by dcristafovici** [alex8088/electron-vite#388]
### Describe the bug

Previously, I was using Vite version 4.5.2, and everything was running smoothly, except for the issue I encountered when trying to use MobX decorators. I received an error indicating that the decorators feature was not enabled. To address this, I went to the electron.vite.config file and added a new configuration, which resolved the problem:

```
plugins: [
  react({
    babel: {
      parserOpts: {
        plugins: ['decorators', 'classProperties']
      }
    }
  })
]

```

However, upon discovering that new versions of Vite and Vite Electron were released, I decided to update both to their latest versions. After the update, everything seemed to be working fine, except for the decorators feature, which caused errors with unexpected tokens on pages where decorators were used. I suspect there might be an issue with the Babel options.

### Electron-Vite Version

2.0

### Electron Version

28.1.4

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@dcristafovici checkout https://vitejs.dev/guide/migration.html#update-experimentaldecorators-and-usedefineforclassfields-typescript-behaviour

**Comment by dcristafovici** [comment]
Thank u @alex8088. It helped, i've spent a plenty of hours on Friday thinking  and trying resolve vite's issue, without trying to adjust my .tsconfig file
