### ISSUE TITLE
Public assets not showing up.

### ISSUE THREAD

**Issue by Android789515** [alex8088/electron-vite#390]
### Out dir in VS Code

![VS Code](https://github.com/alex8088/electron-vite/assets/90219092/20d610a0-3573-425b-b6ea-688a007b868e)

### In App
![App](https://github.com/alex8088/electron-vite/assets/90219092/9c7d854e-d211-4bc2-b647-0305261744c7)

![App Expanded](https://github.com/alex8088/electron-vite/assets/90219092/3be1a905-7276-4b42-8ece-d0db9e874b2c)

### Console
![Console](https://github.com/alex8088/electron-vite/assets/90219092/bb563c06-66f3-4571-951e-477b45c7c752)

### My public folder
![Public Dir](https://github.com/alex8088/electron-vite/assets/90219092/5a02a486-3c56-4064-b1fc-e672dc715de8)

I'm very likely handling my static assets incorrectly.  I'm trying to use these theme files in a link tag using an absolute path instead of relative.

### Electron-Vite Version

2.0.0-beta.2

### Electron Version

28.1.0

### Vite Version

4.0.5

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://vitejs.dev/guide/assets.html#the-public-directory pubic dir apply to static assets but not compile-time assets like scss, less.

**Comment by Android789515** [comment]
> https://vitejs.dev/guide/assets.html#the-public-directory pubic dir apply to static assets but not compile-time assets like scss, less.

Right, I changed it to CSS and I still have the issue.

**Comment by alex8088** [comment]
> > https://vitejs.dev/guide/assets.html#the-public-directory pubic dir apply to static assets but not compile-time assets like scss, less.
> 
> Right, I changed it to CSS and I still have the issue. Or is CSS also included?

Use them in html header?

**Comment by Android789515** [comment]
The problem is they aren't in the app sources when I open the dev tools.

**Comment by Android789515** [comment]
> > > https://vitejs.dev/guide/assets.html#the-public-directory pubic dir apply to static assets but not compile-time assets like scss, less.
> > 
> > 
> > Right, I changed it to CSS and I still have the issue. Or is CSS also included?
> 
> Use them in html header?

I can't, they are not available in the chrome app, despite being in the out folder.  See the images I posted.

**Comment by alex8088** [comment]
https://vitejs.dev/guide/assets.html#the-public-directory Note that:

- Assets in public cannot be imported from JavaScript.

So you want to make it work, you need to link your public css file in the html header. Why must it be placed in public dir but not import them.

**Comment by Android789515** [comment]
This is the problem:
![VS Code](https://github.com/alex8088/electron-vite/assets/90219092/10551f88-4c51-403e-90bf-8a8ee7ae9616)
![App](https://github.com/alex8088/electron-vite/assets/90219092/b53c7e08-b1df-4773-a97a-846f0fe2ff62)

Linking them doesn't work because they don't show up when I launch my app.  I get the same error.

**Comment by alex8088** [comment]
@Android789515  All css files will be merged into one(check you asset ccs file). If you don't want to be merged, you should put them into the public  directory as static assets.

**Comment by Android789515** [comment]
I already have them in the public directory.  I'll repost the image here (it's also posted above in my original post).

![image](https://github.com/alex8088/electron-vite/assets/90219092/4cb5354c-4227-47bc-8c2d-6e168d6a9126)

**Comment by Android789515** [comment]
I figured it out.

[Apparently must use new URL() to use static assets with Vite](https://stackoverflow.com/a/73211477)
