### ISSUE TITLE
PNPM failed to run dev script

### ISSUE THREAD

**Issue by brifiction** [alex8088/electron-vite#392]
### Describe the bug

I have received the error below (see screenshot), after I ran `pnpm i` and then `pnpm dev`. Strangely enough, if it was `npm` or `yarn`, when executing the `dev` script, everything is running fine and dandy.

## Steps to replicate

To replicate, I first ran:

```bash
pnpm create @quick-start/electron
```

Then, chose `react` with `typescript`, with all yes except to 'download mirror proxy` question.

<img width="859" alt="image" src="https://github.com/alex8088/electron-vite/assets/9148451/769016bd-3e29-4750-bf4c-a3d0bf02e512">

Any assistance or clues to the understanding of this error, will be greatly appreciated 🙏 

### Electron-Vite Version

2.0.0(vite@5.0.12)

### Electron Version

28.1.4

### Vite Version

5.0.12(@types/node@18.19.9)

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
The installation was not successful and you need to clear the pnpm cache. Enable mirror proxy if you are in Chin and reinstall.

**Comment by brifiction** [comment]
> The installation was not successful and you need to clear the pnpm cache. Enable mirror proxy if you are in China and reinstall.

Thanks Alex, I've attempted your suggestion to run `pnpm store prune`.

The complete solution with your suggestion, are as described below steps:

1. `pnpm store prune`.
2. Next, (this is required step) run `rm -rf node_modules` to delete `node_modules` folder.
3. Perform fresh `pnpm i`.
4. Lastly, run `pnpm dev` to expect successful dev env launched.

Thank you @alex8088 !  🙌 

FYI, for those who ran into this issue like mine, below are the versions of `node` & `pnpm`:
1. `pnpm` = `8.14.3`
2. `node` = `21.5.0`

<img width="861" alt="image" src="https://github.com/alex8088/electron-vite/assets/9148451/3da8b093-a443-41a1-b46b-8700b246ee8f">
