### ISSUE TITLE
Asset imports in ESM mode are generated with __dirname variable

### ISSUE THREAD

**Issue by nerdynomadd** [alex8088/electron-vite#397]
### Describe the bug

When importing an asset path (in this case, it's a Tray icon that'll be used with the Tray class from electron), electron-vite will generate a path using the __dirname variable, which is not available in a full ESM context.

Here's my TS import:
```js
import trayIconPath from '../../../assets/logoTemplate.png?asset';
```

And here's the generated code in main.js:
```js
const trayIconPath = join(__dirname, "./chunks/logoTemplate-IqcVkt31.png");
```

Which leads to the following error at runtime:
```
App threw an error during load
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/**/Desktop/**/**/application-desktop/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/**/Desktop/**/**/application-desktop/dist/main/main.js:32:27
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Here's my electron.vite.config.ts:
```js
export default defineConfig({
  main: {
    build: {
      rollupOptions: {
        input: {
          main: resolve(__dirname, "src/main.ts"),
          pipeline_process: resolve(__dirname, "src/pipeline_process.ts"),
        },
        output: {
          format: "es"
        }
      },
      outDir: 'dist/main',
      publicDir: 'assets',
    },
  },
  preload: {
    build: {
      rollupOptions: {
        input: {
          preload: resolve(__dirname, "src/preload.ts"),
        },
        output: {
          format: "es"
        }
      },
      outDir: 'dist/preload',
    },
  },
});
```

### Electron-Vite Version

2.0.0

### Electron Version

28.0.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@nerdynomadd It seems that electron-vite 2 is not used. When esm is enabled in this way, the file suffix will be `.mjs`. In addition, your config file is wrong, it should be `main.publicDir`. Upgrade your electron-vite or use `npm create @quick-start/electron@latest` to create a project to test.

**Comment by alex8088** [comment]
Is there any more problem？

**Comment by undergroundwires** [comment]
Hi @alex8088, regarding the statement `When esm is enabled in this way, the file suffix will be .mjs`.

I also enable the ESM same way: using  `build > output > format > 'es'` and I have `type="module"` in my `package.json` but I get `.js` as file extension instead of `.mjs` for main process, but I get `.mjs` for preloader process.

Is this intended? And is this best-practice to enable native ESM this way?

**Comment by theogravity** [comment]
I have the same problem as @undergroundwires. The preload is `.mjs` and uses imports, which isn't currently allowed in a preload. Not sure what settings to use to have it build a cjs for preload.
