### ISSUE TITLE
使用64位windows系统打包32位程序

### ISSUE THREAD

**Issue by xzghting** [alex8088/electron-vite#399]
### Clear and concise description of the problem

如何使用64位windows系统打包32位程序

### Suggested solution

RT，
有没有详细教程呀，建议做到文档内。但是确实现在32位系统不多，但是我就遇上了

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
增加架构指令 --ia32，相关请查阅electron-builder的文档

**Comment by xzghting** [comment]
> 增加架构指令--ia32，相关请查阅 Electron-builder 的文档

我在package.json内scripts里增加了一条：
<img width="905" alt="image" src="https://github.com/alex8088/electron-vite/assets/13431205/22a8e295-40b8-4fae-a0d4-d212c55cd5bd">
这里还需要带上这个--config吗

**Comment by xzghting** [comment]
> 增加架构指令--ia32，相关请查阅Electron-builder的文档

<img width="804" alt="image" src="https://github.com/alex8088/electron-vite/assets/13431205/e15a3b4b-4998-4816-a149-1c5f7d7b5037">
或者是这样？

**Comment by alex8088** [comment]
> > 增加架构指令--ia32，相关请查阅Electron-builder的文档
> 
> <img alt="image" width="804" src="https://private-user-images.githubusercontent.com/13431205/301706495-e15a3b4b-4998-4816-a149-1c5f7d7b5037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDEzMTMsIm5iZiI6MTcwNjg0MTAxMywicGF0aCI6Ii8xMzQzMTIwNS8zMDE3MDY0OTUtZTE1YTNiNGItNDk5OC00ODE2LWExNDktMWM1ZjdkN2I1MDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAyMzAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OWRlYjdlYjRjNmYxZmMwNzQyYTBjMzJjZTdiM2RkYTc4MDA5MGYzMDU4MmJiZTQyNzFmNThlYjU2MDM2NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2d0V6zLWENk4cbIO-QCVKTPH_7qWZm3wa8qiro7xVXQ"> 或者是这样？

对

**Comment by xzghting** [comment]
> > > 增加架构指令--ia32，相关请查阅Electron-builder的文档
> > 
> > 
> > <img alt="图像" width="804" src="https://private-user-images.githubusercontent.com/13431205/301706495-e15a3b4b-4998-4816-a149-1c5f7d7b5037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDEzMTMsIm5iZiI6MTcwNjg0MTAxMywicGF0aCI6Ii8xMzQzMTIwNS8zMDE3MDY0OTUtZTE1YTNiNGItNDk5OC00ODE2LWExNDktMWM1ZjdkN2I1MDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAyMzAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OWRlYjdlYjRjNmYxZmMwNzQyYTBjMzJjZTdiM2RkYTc4MDA5MGYzMDU4MmJiZTQyNzFmNThlYjU2MDM2NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2d0V6zLWENk4cbIO-QCVKTPH_7qWZm3wa8qiro7xVXQ">或者是这样？
> 
> 对

在问一下，如果是macos arm系统，有没有可以解决打包exe程序的方案呀，我目前是macos arm，打包windows exe的时候都是换了一台电脑打包的，非常麻烦 0.0

**Comment by alex8088** [comment]
不使用原生模块可以，详细看electron-builder文档，或自行检索。如果使用electron-vite字节码代码保护，详细参考文档。

**Comment by xzghting** [comment]
> 不使用原生模块可以，详细看electron-builder文档，或自行检索。如果使用electron-vite字节码代码保护，详细参考文档。

使用了原生的，比如选文件那些。但是arm mac打包x64的windows感觉行不通呢
