### ISSUE TITLE
Error using sqlite3 in electron-vite

### ISSUE THREAD

**Issue by lfpei** [alex8088/electron-vite#4]
### Describe the bug

![image](https://user-images.githubusercontent.com/40376166/171644321-3c186260-ad80-4288-af43-5cf7aeaa493f.png)

electron-builder.yml
asarUnpack:
  - '**/*.{node,dll}'
  - node_modules/sqlite3
The above configuration is invalid

### Electron-Vite Version

^1.0.2

### Electron Version

^18.2.0

### Vite Version

^2.9.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by lfpei** [comment]
![image](https://user-images.githubusercontent.com/40376166/171645654-d7aac17b-e00a-4f21-af9a-15de9ded128c.png)
yarn add sqlite3 has no error;
Running in electron does not report any errors

**Comment by lfpei** [comment]
According to the above configuration, it still reports an error；
In renderer
const sqlite3 = require('sqlite3')
const { open } = require('sqlite')
commonjs spelling can be used normally;
import { open } from 'sqlite'
import sqlite3 from 'sqlite3'
ES6 will still report the above error；

I also added plugin according to configuration `@rollup/plugin-commonjs` and `@rollup/plugin-node-resolve`
![image](https://user-images.githubusercontent.com/40376166/172052403-23413049-a34c-47f1-8fbd-e2ec3c58e225.png)

![image](https://user-images.githubusercontent.com/40376166/172052365-e9a58fbe-f960-4d7a-a3b4-712a9a793614.png)

**Comment by alex8088** [comment]
@lfpei the renderer build module base on `iife` mode but not `commonjs` . The `sqlite3`  is only for `nodejs`, so usually `sqlite3` is used in the main process. The renderer process calls sqlite through IPC.

**Comment by lfpei** [comment]
![image](https://user-images.githubusercontent.com/40376166/172053394-275a3425-dd0d-42f6-8151-4e7694e1610a.png)

In main process，this is nomal. In renderer process , Can't use this way? 
only used in the main process?

**Comment by alex8088** [comment]
@lfpei

Not impossible, but complicated to configure. This is unsafe and unreasonable. I don't recommend you do this.

**Comment by alex8088** [comment]
@lfpei The renderer process development, like web development, is browser-based.

**Comment by lfpei** [comment]
OK, thanks
