### ISSUE TITLE
"lib.entry" not working in the config file

### ISSUE THREAD

**Issue by petdomaa100** [alex8088/electron-vite#40]
### Describe the bug

As specified [in the docs](https://evite.netlify.app/config/#build-options-for-main), I should be able to modify the entry file for main file with "lib.entry". However, it doesn't seem to be working. "lib" is not even a part of the type definitions for the config object. Am I missing something?

```ts
const config: UserConfigSchema = {
	main: {
		lib: {
			entry: '/src/main.ts'
		},
		plugins: [ externalizeDepsPlugin() ]
	},
	preload: {
		plugins: [ externalizeDepsPlugin() ]
	},
	renderer: {
		resolve: {
			alias: {
				'@renderer': resolve('src/renderer/src')
			}
		},
		plugins: [ react() ]
	}
};
```

### Electron-Vite Version

1.0.11

### Electron Version

20.3.3

### Vite Version

3.1.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
should be `build.lib`

**Comment by alex8088** [comment]
use `defineConfig` get type intellisense

**Comment by petdomaa100** [comment]
Git it, thank you :)
