### ISSUE TITLE
Electron 29 beta Cannot Find Packages when using ESM

### ISSUE THREAD

**Issue by johnlindquist** [alex8088/electron-vite#401]
## Reproduce

You can use this repo to reproduce (it just followed the steps below): https://github.com/johnlindquist/electron-29

- `npm create @quick-start/electron`
- Follow `esm` guide
- install `electron-log` and use it in main/index.ts: https://github.com/johnlindquist/electron-29/blob/main/src/main/index.ts#L5
- install Electron 29 `npm i electron@beta` (29.0.0-beta.5 as of today)

### `npm run dev`

Works fine

### `npm run build:mac`

- Successfully builds
- open `./dist/mac-arm64/foo.app`

Your run into a `Cannot find package`, "electron-log" error.

```
Uncaught Exception:
Error: Cannot find package '/Users/johnlindquist/dev/electron-29/dist/mac-arm64/electron-29.app/Contents/Resources/app.asar/node_modules/electron-log/package.json' imported from /Users/johnlindquist/dev/electron-29/dist/mac-arm64/electron-29.app/Contents/Resources/app.asar/out/main/index.mjs
Did you mean to import electron-log/src/index.js?
at legacyMainResolve (node:internal/modules/esm/resolve:189:26)
at packageResolve (node:internal/modules/esm/resolve:783:14)
at moduleResolve (node:internal/modules/esm/resolve:845:20)
at defaultResolve (node:internal/modules/esm/resolve:1050:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
at link (node:internal/modules/esm/module_job:84:36)
```
![CleanShot 2024-02-03 at 09 41 14](https://github.com/alex8088/electron-vite/assets/36073/aeebc0e3-f817-4391-99f3-5f9e23cb51ce)

## Fix
Downgrade to Electron 28, build works fine again.

### Electron-Vite Version

2.0.0

### Electron Version

29.0.0-beta.5

### Vite Version

5.0.11

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by 1zilc** [comment]
我前几天也遇到过，当时以为是external的问题，结果`asar:false` 后node_modules 都在里面，并且能正常运行 ,这个应该是electron 29的问题，建议反馈到electron issue

**Comment by undergroundwires** [comment]
I still reproduce this with latest `electron-vite` (2.1.0), `electron-builder` (24.13.3), `electron-log` (v5.1.2) and `electron`  (v29.1.4). What was your solution how did you solve this?

**Comment by undergroundwires** [comment]
I still reproduce this with latest `electron-vite` (2.1.0), `electron-builder` (24.13.3), `electron-log` (v5.1.2) and `electron`  (v29.1.4 same with latest v28, i.e. v28.2.7). Downgrading Electron to v28 did not solve my issue, the same error latest v28 (v28.2.7).

How did you solve this?

**Comment by 1zilc** [comment]
> I still reproduce this with latest `electron-vite` (2.1.0), `electron-builder` (24.13.3), `electron-log` (v5.1.2) and `electron`  (v29.1.4 same with latest v28, i.e. v28.2.7).
> 
> 
> 
> The suggested solutions did not work for me:
> 
> 
> 
> - Downgrading Electron to v28 did not solve my issue, the same error latest v28 (v28.2.7).
> 
> - Setting `asar: false` had no affect.
> 
> 
> 
> Error is there when running `electron-vite dev` and `electron-vite preview`.
> 
> 
> 
> How did you solve this?

try 29.1.1

**Comment by undergroundwires** [comment]
I got same error running after clean install of Electron 29.1.1. I run `electron-vite build` before running `dev` just in case.

Error:

```
Uncaught Exception:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/bob/user/dev/undergroundwires/privacy.sexy/node_modules/electron-log/main' imported from /home/bob/user/dev/undergroundwires/privacy.sexy/dist-electron-unbundled/main/index.mjs
Did you mean to import electron-log/main.js?
    at new NodeError (node:internal/errors:406:5)
    ...
```
    
I realize that I'm only getting this error if I import  electron-log from /main alias such as:
    
```mjs
import log from "electron-log/main";
```
    
Importing only from `electron-log` does not yield this error.

However importing it as `/main` is recommended in its [README](https://github.com/megahertz/electron-log?tab=readme-ov-file#usage) as it's best practice to get right context.

Can it be something with dependency externalization? @alex8088

**Comment by undergroundwires** [comment]
I got same error running after clean install of Electron 29.1.1. I run `electron-vite build` before running `dev` just in case.

Error:

```
Uncaught Exception:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/bob/user/dev/undergroundwires/privacy.sexy/node_modules/electron-log/main' imported from /home/bob/user/dev/undergroundwires/privacy.sexy/dist-electron-unbundled/main/index.mjs
Did you mean to import electron-log/main.js?
    at new NodeError (node:internal/errors:406:5)
    ...
```
    
I realize that I'm only getting this error if I import  electron-log from /main alias such as:
    
```mjs
import log from "electron-log/main";
```

Importing only from `electron-log` does not yield this error:
    
```mjs
import log from "electron-log";
```

However importing it as `/main` is recommended in its [README](https://github.com/megahertz/electron-log?tab=readme-ov-file#usage) as it's best practice to get right context.

I'm unsure if this has anything to do with `electron-vite` or electron/electron#41241.

**Comment by alex8088** [comment]
electron-vite only builds the code and does not affect the runtime. This problem may be a problem with electron-builder or electron. There is no problem with subpath under `cjs`, so it is more likely to be an electron issue. The PR https://github.com/electron/electron/issues/41241. does not seem to solve all the problems. This looks like an asar problem, electron esm loader cannot correctly resolve subpath modules.

**Comment by alex8088** [comment]
Don't externalize the module yet and let electron-vite bundle it. This is also a way to avoid this problem.

**Comment by undergroundwires** [comment]
The suggested workaround worked for me. Thank you for the capability, sticking around and supporting the community @alex8088 ❤️. 

This fixes it:

```js
externalizeDepsPlugin({
      exclude: [ electron-log' ]
})]
```

**Comment by theogravity** [comment]
I was able to get around this with `import log from "electron-log/main.js";`
