### ISSUE TITLE
主进程使用了setInterval，热重载会开启多个窗口

### ISSUE THREAD

**Issue by weiminghaoo** [alex8088/electron-vite#403]
### Describe the bug

主进程使用了setInterval，热重载watchHook中ps.kill()杀不死，是否可以修改为ps.kill('SIGKILL')？

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@weiminghaoo 未能重现此问题，setInterval 是否有特殊逻辑，提供相关复现示例或更详尽的信息。

**Comment by weiminghaoo** [comment]
> @weiminghaoo 未能重现此问题，setInterval 是否有特殊逻辑，提供相关复现示例或更详尽的信息。

import { usb } from 'usb'
usb.on('attach', (device) => {
})
usb.on('detach', (device) => {
})
使用了usb，内部应该是有使用setInterval来监听usb设备的插拔，我的开发环境是mac
