### ISSUE TITLE
es语法的加密

### ISSUE THREAD

**Issue by 2514765066** [alex8088/electron-vite#413]
### Clear and concise description of the problem

现在electron28版本开始支持es语法，我相信在未来electron也会逐步更加完善对es语法的支持，但是现在electron-vite它对es语法并不能加密，只能加密commonjs语法，因为我做的是一些单机的软件，不希望我的源码泄露，我也不想变成commonjs语法

### Suggested solution

所以我希望你们能加上对es语法的源码保护功能

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
@2514765066 对于代码编写上，使用es语法是没有问题的，electron-vite对es语法和comomnjs语法做了一定兼容处理，区别在于最终的构建目标是esm还是cjs。例如使用es语法编写，构建目标为cjs，那么最终会构建成cjs。没有 electron 28 之前 electron-vite 也是同样支持 es 的，这是构建工具的作用。 electron 支持esm 使得 electron-vite的构建目标多了一个选择，并且在两种语法间做了一定的兼容，使得两种语法可以自由切换。对于esm的字节码加密支持，还有一些问题有待解决，你可以关注后续的版本。
