### ISSUE TITLE
是否应该考虑转换为字节码的模块可能有导出？

### ISSUE THREAD

**Issue by Eleg-i** [alex8088/electron-vite#415]
### Clear and concise description of the problem

我的应用在构建时使用了多个入口。部分入口被视作动态模块进行导入。如果转换为字节码，需要获取模块的导出成员。字节码的转换本身是没有问题的，但是引入字节码的js文件丢弃了这部分信息。查看源码后个人认为需要根据chunk的信息区分哪些成员需要导出，并按原始形式导出。

### Suggested solution

举个栗子：

[electron-vite/src/plugins/bytecode.ts line 316](https://github.com/alex8088/electron-vite/blob/7f13ea2a845b2759f89a483cc72bfab941cfda9f/src/plugins/bytecode.ts#L316C23-L316C42)
```javascript
const bytecodeModuleBlock = `module.exports = require("./${path.basename(name) + 'c'}");`
```

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
是否可以提供相关的repo
