### ISSUE TITLE
String protection not working when build.minify is set to true

### ISSUE THREAD

**Issue by therealartti** [alex8088/electron-vite#417]
### Describe the bug

The protectedStrings option fails to find the wanted strings when build.minify is true. Removing minify: true fixes it.

Here's my electron.vite.config.js:
```
export default defineConfig({
  main: {
    plugins: [
      externalizeDepsPlugin(),
      bytecodePlugin({ protectedStrings: ['ABCDE', 'FGHIJ'] }),
    ],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.js'),
          index2: resolve(__dirname, 'src/main/index2.js'),
          index3: resolve(__dirname, 'src/main/index3.js')
        }
      },
      minify: true //works without this
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin()],
    build: {
      minify: true
    }
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },
    plugins: [react()],
    build: {
      minify: true
    }
  }
})
```

[Enforcing the plugin ordering](https://vitejs.dev/guide/using-plugins.html#enforcing-plugin-ordering) does not seem to help either:
```
plugins: [
      {
        ...bytecodePlugin({
          protectedStrings: ['ABCDE', 'FGHIJ']
        }),
        enforce: 'pre'
      },
      externalizeDepsPlugin()
    ],
```

### Electron-Vite Version

2.0.0

### Electron Version

28.2.4

### Vite Version

5.1.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@therealartti Thank you for your feedback. When minification is enabled, string protection has no effect. This is because string protection is based on character codes. However, modern minification tools, whether `esbuild` or `terser`, will restore the converted character codes, causing the protection to fail. electron-vite will throw a warning. In fact, minification has little effect on reducing bytecode size, so it is recommended not to enable minification when protecting strings.
