### ISSUE TITLE
vm module of Node.js is deprecated while using bytecodePlugin.

### ISSUE THREAD

**Issue by 0x5374656c6c6172** [alex8088/electron-vite#419]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/127069617/12f0b123-bb05-41ab-b77b-7e4eb6f4fe60)

Everything seems to be working fine.
But, does it affect how the plugin works?

### Electron-Vite Version

2.0.0

### Electron Version

29.0.1

### Vite Version

5.1.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
`sandbox: false` or disable bytecode plugin

**Comment by 0x5374656c6c6172** [comment]
> `sandbox: false` or disable bytecode plugin

`sandbox: false` was set. This is common project created with `@quick-start/electron`.
