### ISSUE TITLE
node-serialport is not working

### ISSUE THREAD

**Issue by stalkercn** [alex8088/electron-vite#42]
### Describe the bug

When node-serialport lib is imported, error occurred.

Node Version: 16.18.0
Node-SerialPort Version: 10.4.0
Electron Version: 20.3.3
Vite Version: 3.1.8
Electron-Vite Version: 1.0.11

**Reproduction:**

1. install node-serialport
`npm i serialport`

2. code in main/index.ts:
`import { SerialPort } from serialport;
console.log(SerialPort)`

3. run electron-vite

> Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=107 uv=1 libc=glibc node=16.15.0 electron=20.3.3

### Electron-Vite Version

1.0.11

### Electron Version

20.3.3

### Vite Version

3.1.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
need to  externalize `serialport`, edit your config:

```js
import { resolve } from 'path'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin()]
  },
 //...
})
```
use `externalizeDepsPlugin `  to automatically externalize package.json dependencies.

Learm more about https://evite.netlify.app/guide/build.html#externals

**Comment by stalkercn** [comment]
app can be launched now, but when `npm i` is ran, there's still an error.

> > electron-builder install-app-deps

  • electron-builder  version=23.6.0
  • loaded configuration  file=C:\git\electron-app\electron-builder.yml
  • rebuilding native dependencies  dependencies=@serialport/bindings-cpp@10.7.0 platform=win32 arch=x64
  ⨯ cannot execute  cause=fork/exec C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\bin\pnpm.cjs: %1 is not a valid Win32 application.
                    command='C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\bin\pnpm.cjs' rebuild @serialport/bindings-cpp@10.7.0
                    workingDir=
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Taqibrian** [comment]
Pada tanggal Sel, 25 Okt 2022 08.25, stalkercn ***@***.***>
menulis:

**Comment by alex8088** [comment]
@stalkercn
Remove `"postinstall": "electron-builder install-app-deps"` in `package.json` after successfully installing `serialport` . 

May be some problem in `electron-builder install-app-deps`  rebuilding  `serialport`. https://github.com/serialport/node-serialport/issues/2463

**Comment by stalkercn** [comment]
> @stalkercn Remove `"postinstall": "electron-builder install-app-deps"` in `package.json` after successfully installing `serialport` .
> 
> May be some problem in `electron-builder install-app-deps` rebuilding `serialport`. [serialport/node-serialport#2463](https://github.com/serialport/node-serialport/issues/2463)

this works.
