### ISSUE TITLE
Can not use assets in renderer/public directory with build mode

### ISSUE THREAD

**Issue by frangte** [alex8088/electron-vite#422]
### Describe the bug

Hi owner, first of all thank for creating this repo, very helpful to start a new electron project.

But I have some problem when using assets in the public directory, already read some github issue related to this problem but no luck for me. 

Here is code of react component

```jsx
export const Test = () => {
  return (
    <div>
      Test
      <img src="/image.png" />
    </div>
  )
}
```

Here is run dev mode
<img width="1208" alt="image" src="https://github.com/alex8088/electron-vite/assets/19859575/001a65f0-c887-4994-b18a-80e828827831">

Here is build verison
<img width="1107" alt="image" src="https://github.com/alex8088/electron-vite/assets/19859575/1f042130-6d9d-4922-b7bf-9322430f08e7">

Here is the project structure
<img width="274" alt="image" src="https://github.com/alex8088/electron-vite/assets/19859575/596ce68a-9b2a-4d7a-b8c9-27d6b9525e81">

Here is vite.config
```js
import { resolve } from 'path'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import react from '@vitejs/plugin-react'
import AutoImport from 'unplugin-auto-import/vite'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin()]
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src'),
      }
    },
    plugins: [
      react(),
      AutoImport({
        imports: ['react', 'react-router-dom'],
        dts: './src/auto-imports.d.ts',
        dirs: ['src/**/*.ts', 'src/**/*.tsx', 'src/store/*.ts'],
        eslintrc: {
          enabled: true
        },
        defaultExportByFilename: true
      })
    ]
  }
})
```

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
you can run start command to preview your app and check the out/renderer dir.

**Comment by frangte** [comment]
<img width="224" alt="image" src="https://github.com/alex8088/electron-vite/assets/19859575/cae41b4e-feb1-439a-bf9c-91a0783efa0d">
here is out/renderer dir, i see it included all file in public but maybe smt wrong in bundle step

**Comment by ralyodio** [comment]
has anyone found a solution? I'm trying to load an svg icon on a map and it can't find it.

**Comment by Harley-xk** [comment]
> has anyone found a solution? I'm trying to load an svg icon on a map and it can't find it. What path do I use in the html?

I've found the solution, the `out/renderer` folder is the working directory in html, so you should use a relative path to load public files, like: `./Test.jpeg`,
