### ISSUE TITLE
Make electron-toolkit/preload optional on package install

### ISSUE THREAD

**Issue by mdruuu** [alex8088/electron-vite#425]
### Clear and concise description of the problem

electron-toolkit/preload is a neat package that simplifies IPC code, but to use it, sandbox is required to be disabled because sandboxed preload scripts can only load polyfilled api.

### Suggested solution

Would it be possible to make the preload package install optional, when you first initialize the project using npm create @quick-start? With an explanation as to why sandbox needs to be disabled if used? Would make for a nicer UX, especially for beginners like me. 

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
Not only the electron-toolkit/preload module requires sandbox. All third-party modules require it. You can disable externalizeDep plugin (in preload config) to support sandbox and also you can use electron-toolkit/preload module and other  third-party modules. For developers, they need to have knowledge about `sandbox` before they can make a decision. It is inappropriate to choose in scaffolding.

**Comment by mdruuu** [comment]
I understand sandbox needs to be disabled to use any external modules. I
guess my thinking is that it's better to have it most secure by default,
and let people choose to disable sandbox if they want to, vs having it
disabled by default. And as far as I can see, preload is the only 3rd party
module loaded?

I also think it's a good thing to make developers think about sandbox
explicitly during scaffolding, as it involves application security, but I
understand where you are coming from and will not push this matter any
further.

Thanks for the response and thanks for building and maintaining the repo!
It's extremely useful.

**Comment by alex8088** [comment]
@mdruuu Thanks for the suggestion, security practices are very important and I will improve this in the future including scaffolding and documentation.
