### ISSUE TITLE
WebStorm can't resolve tsconfig.json struct

### ISSUE THREAD

**Issue by d-o0o-b** [alex8088/electron-vite#426]
### Describe the bug

模板:  `@quick-start/electron my-app -- --template vue-ts`
直接使用这个模板，webstorm无法正确的识别路径别名配置，以及一些相关的配置。
当我将tsconfig.web.json和tsconfig.node.json中的compilerOptions和inclue拷贝到tsconfig.json中后，神奇的是，IDE就识别了；我不知道这种处理方式是否会造成潜在的影响，但就目前测试来看，一切都可以正常工作

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by d-o0o-b** [comment]
应该是webstorm的问题，期望出一个webstorm的模板，vscode不是很熟练。

**Comment by alex8088** [comment]
@d-o0o-b 移除 tsconfig.json 中的 files 字段重启IDE 即可

**Comment by d-o0o-b** [comment]
不，这个方式不行，我已经找到完美的解决方案了，在 Settings -> Editor -> FileType 中的Typescript Config中配置tsconfig.web.config以及tsconfig.node.json即可

希望能将这个说明加到文档中，对我这种第一次接触到多个配置文件的新手会很有帮助。


> @d-o0o-b 移除 tsconfig.json 中的 files 字段重启IDE 即可

**Comment by SerOleMar** [comment]
> 不，这个方式不行，我已经找到完美的解决方案了，在 Settings -> Editor -> FileType 中的Typescript Config中配置tsconfig.web.config以及tsconfig.node.json即可

@d-o0o-b 它对我不起作用。你能告诉我更多吗？

**Comment by zjc19982** [comment]
> 不，这个方式不行，我已经找到完美的解决方案了，在 Settings -> Editor -> FileType 中的Typescript Config中配置tsconfig.web.config以及tsconfig.node.json即可
> 
> 希望能将这个说明加到文档中，对我这种第一次接触到多个配置文件的新手会很有帮助。
> 
> > @d-o0o-b 移除 tsconfig.json 中的 files 字段重启IDE 即可

I'm using IDEA 2023.3.6, and It works for me.
