### ISSUE TITLE
The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.

### ISSUE THREAD

**Issue by yaoshengli** [alex8088/electron-vite#427]
### Describe the bug

babel v8字节保护的时候会提示这个，我应该怎么处理！

### Electron-Vite Version

last

### Electron Version

27

### Vite Version

5

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
具体的信息

**Comment by yaoshengli** [comment]
我试图在 https://github.com/electron-vite/vite-plugin-electron 中使用v8字节保护功能。
虽然结果没有什么影响，可它提示error
![1709108334278](https://github.com/alex8088/electron-vite/assets/13297623/e51ce5ea-2d15-4864-8a74-e70c425583ef)

![11](https://github.com/alex8088/electron-vite/assets/13297623/42b3f516-b0a6-4836-b536-002f5b2eb54a)

**Comment by yaoshengli** [comment]
最后可以保护成功，就是会提示这个错误。
![22](https://github.com/alex8088/electron-vite/assets/13297623/9aa81fdc-f17d-4ebd-a6cd-185619d405a4)

**Comment by alex8088** [comment]
这个是babel的提示，需要自己配置(external)排除掉一些第三方库构建加密。而在electron-vite中这些都会自行处理的

**Comment by yaoshengli** [comment]
我想应该处理好了~，感谢大神。
![33](https://github.com/alex8088/electron-vite/assets/13297623/be7a1ed6-015f-4600-a3b0-8eef24eceb72)
