### ISSUE TITLE
Api availability in Renderer

### ISSUE THREAD

**Issue by latinusveridas** [alex8088/electron-vite#43]
### Describe the bug

Hello Alex and community,

I'm struggling to put available my custom API in my Vue app with contextBridge (preload).

In the mount() function in the script of App.vue, when I print the window object, I can see the ElectronAPI and myApi, with its properties attached. That's fine on that. 

But if I try to print only the myApi object or myString property of myApi, results is undefined in the console => and that's my problem. Actually I'm not able to access to my custom api variables / functions.
<a href="https://freeimage.host/i/DrtHqx"><img src="https://iili.io/DrtHqx.md.png" alt="DrtHqx.md.png" border="0"></a>

Now if we open the window object, we can see that ElectronAPI and myApi are correctly imported
<a href="https://freeimage.host/i/DrtiQa"><img src="https://iili.io/DrtiQa.md.png" alt="DrtiQa.md.png" border="0"></a>

You will find attached (archive.zip):

preload_index.d.ts (originally src/preload/index.d.ts)
preload_index.ts (originally src/preload/index.ts)
renderer_App.vue (originally src/renderer/src/App.vue)

main_index.ts (originally src/main/index.ts)

electron.vite.config.ts (originally project folder)
tsconfig.json (originally project folder)
tsconfig.node.json (originally project folder)
tsconfig.web.json (originally project folder)

Last info that could be helpful, as you can see in the main/index.ts, the contextIsolation is set to true, in order to leverage on ContextBridge, as recommend in Electron doc. 

Many thanks for your work and your help Alex,
Latinus

### Electron-Vite Version

1.0.11

### Electron Version

20.3.2

### Vite Version

3.1.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.
[Archive.zip](https://github.com/alex8088/electron-vite/files/9869240/Archive.zip)

**Comment by alex8088** [comment]
Hi, @latinusveridas 

you expose the preload api named `myApi`, but use `myAPI` in renderer.

**Comment by alex8088** [comment]
you can  also remove `files` field in `tsconfig.json` to make preload type intellisense work in your IDE(not vscode)

**Comment by latinusveridas** [comment]
> Hi, @latinusveridas
> 
> you expose the preload api named `myApi`, but use `myAPI` in renderer.

Thanks for your quick reply, good shot. Problem solved. 



> you can also remove `files` field in `tsconfig.json` to make preload type intellisense work in your IDE(not vscode)

Well actually i'm using vscode, and if I remove the preload declaration file from `files`, Intellisense is not able to fund my API declarations anymore. Should I move it to another place ? 

Thanks again for your support Alex, much appreciated .
Latinus

**Comment by alex8088** [comment]
:handshake: 

 try to remove `files` and relaunch vscode, see if it works.

**Comment by alex8088** [comment]
But it works for my vscode and don't need to do anything

**Comment by latinusveridas** [comment]
> 🤝
> 
> try to remove `files` and relaunch vscode, see if it works.

Doesn't work. As well I tried to put the declaration file in the include array of ts.config.node.json and ts.config.web.json and no result. 

Two observations:
1. Vscode seems to leverage only on tsconfig.json (and does not consider ts.config.node.json and ts.config.web.json)
2. When I check Intellisense propositions, there is two definitions proposed, but they are pointing actually to the same one: 
<a href="https://freeimage.host/i/DPUZqN"><img src="https://iili.io/DPUZqN.md.png" alt="DPUZqN.md.png" border="0"></a>

Thanks
Latinus

**Comment by alex8088** [comment]
![0](https://user-images.githubusercontent.com/25053004/198087601-ff261858-2e9a-4d01-8fdc-9ef1f693e9b3.png)
In vscode, you can know whether tsconfig is valid for the file.

**Comment by latinusveridas** [comment]
It's actually tsconfig.web.json as well which is mentioned by vscode. But strangely, the only way to avoid Intellisense error is to include the d.ts in `files` tsconfig.json.

**Comment by alex8088** [comment]
Is the vscode plugin for Vue installed?

 Vue Language Features (Volar) + TypeScript Vue Plugin (Volar)

**Comment by latinusveridas** [comment]
Yes:

Volar 1.0.9 for Vue Language Features + Typescript Vue plugin
Vetur 0.36.0

Maybe Vetur cause issues (collisions etc.) ? I can try to disable it. 
I keep you posted
Latinus

**Comment by alex8088** [comment]
Thanks, close this issue first, and I will continue to pay attention.
