### ISSUE TITLE
使用typeorm，在window打包运行，TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by weiminghaoo** [alex8088/electron-vite#430]
### Describe the bug

```typescript
import { Entity, Column, OneToOne, PrimaryGeneratedColumn, JoinColumn } from 'typeorm'

@Entity('message')
export class MessageModel {
  @PrimaryGeneratedColumn({ type: 'int' })
  id: number | undefined

  @Column({ type: 'int8', nullable: false })
  roomId: number | undefined

  @Column({ type: 'text', nullable: false })
  content: string | undefined

  @Column({ type: 'text', nullable: false })
  type: string | undefined
}
```

window环境中，在主进程中导入MessageModel，开发时没问题，打包后运行报错

```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (D:\workspaces\500_electron\electron-app\dist\win-unpacked\resources\app.asar\node_modules\path-scurry\dist\cjs\index.js:131:40)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (D:\workspaces\500_electron\electron-app\dist\win-unpacked\resources\app.asar\node_modules\glob\dist\commonjs\glob.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
```

### Electron-Vite Version

2.0.0

### Electron Version

^28.2.0

### Vite Version

^5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
是否启用 swcPlugin

查阅文档：https://electron-vite.org/guide/typescript-decorator

参考示例： https://github.com/alex8088/electron-vite-decorator-example

**Comment by weiminghaoo** [comment]
> 是否启用 swcPlugin
> 
> 查阅文档：https://electron-vite.org/guide/typescript-decorator
> 
> 参考示例： https://github.com/alex8088/electron-vite-decorator-example

已启用

**Comment by alex8088** [comment]
preview 是否正常

**Comment by alex8088** [comment]
故障排查 https://cn.electron-vite.org/guide/troubleshooting#%E6%8A%80%E5%B7%A7

**Comment by weiminghaoo** [comment]
> preview 是否正常

preview 正常，参考示例项目，测试是正常的

我尝试新建项目,在main/index.ts加入以下代码，其他未做任何更改，打包后还是报错

```typescript
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm'

@Entity()
export class AccountTags {
  @PrimaryGeneratedColumn()
  id!: string

  @Column({ type: 'text' })
  title!: string

  @Column({ type: 'text' })
  color!: string

  @Column({ type: 'integer' })
  createdAt!: number
}
```

<img width="662" alt="image" src="https://github.com/alex8088/electron-vite/assets/29938792/918b0819-66ad-4ffe-b1e0-01ab6ae86b37">
<img width="632" alt="image" src="https://github.com/alex8088/electron-vite/assets/29938792/53c94194-33b6-4a77-9d1c-8678661e1658">
<img width="555" alt="image" src="https://github.com/alex8088/electron-vite/assets/29938792/577387ef-b673-4f82-9750-3220fa35e004">

**Comment by alex8088** [comment]
使用什么包管理器，preview正常，问题就出在打包

**Comment by alex8088** [comment]
还用你需要安装 reflect-metadata

**Comment by weiminghaoo** [comment]
> reflect-metadata

用的pnpm，reflect-metadata装了 还是不行

**Comment by alex8088** [comment]
改用npm吧

**Comment by weiminghaoo** [comment]
> 改用npm吧

npm也不行

**Comment by alex8088** [comment]
如果preview没有问题，通常就是打包问题，问题是否出现在其他地方，比如你的sqlite生成文件位置等，你可以尝试unpack打包，执行程序验证，或者提供复现repo

**Comment by alex8088** [comment]
问题是否解决

**Comment by weiminghaoo** [comment]
> 问题是否解决

没有😫

**Comment by weiminghaoo** [comment]
> 问题是否解决

解决了！开启swcPlugin、reflect-metadata、使用npm、关闭bytecodePlugin

**Comment by Undefined100** [comment]
> > 问题是否解决
> 
> 解决了！开启swcPlugin、reflect-metadata、使用npm、关闭bytecodePlugin

bytecodePlugin开启就不行吗
