### ISSUE TITLE
Electron run dev blank window on Ubuntu 22.04

### ISSUE THREAD

**Issue by TheRedfoox** [alex8088/electron-vite#433]
### Describe the bug

On Ubuntu 22.04 when I run dev: "electron-vite dev --watch" I get the error electron: Failed to load URL: http://localhost:5173/ with error: ERR_SOCKET_NOT_CONNECTED

![image](https://github.com/alex8088/electron-vite/assets/19651327/851c2ea6-3ba3-4c57-a070-0086cf3b5438)

I have no problems when I run start: "electron-vite preview" or on Windows (run dev or start)

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Are you using WSL2?

**Comment by TheRedfoox** [comment]
No, it's just that I develop on both a Windows and an Ubuntu PC.

**Comment by alex8088** [comment]
try 
```
renderer: {
    server: {
      hmr: {
        host: 'localhost'
      }
    }
  }
```
Not sure if it's because of this:
https://vitejs.dev/guide/troubleshooting.html#dev-server

**Comment by TheRedfoox** [comment]
Same result

**Comment by alex8088** [comment]
I think this is not a problem with vite and works when setting host to 127.0.0.1. I guess setting the host to 127.0.0.1 will force it to IPv4 .
