### ISSUE TITLE
Upgrade to electron 29

### ISSUE THREAD

**Issue by galangel** [alex8088/electron-vite#434]
### Clear and concise description of the problem

should support latest version

### Suggested solution

update the code

### Additional context

https://releases.electronjs.org/

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
always support latest version
