### ISSUE TITLE
在window 7下面build 时开启字符码保护，运行报错是不支持吗？

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#436]
### Describe the bug

使用的是如下的依赖，是依赖版本问题还是window7 不支持？看了官方文档没太明白；
"electron": "^22.3.27",
"electron-builder": "^22.14.13",
"electron-vite": "^1.0.29",

### Electron-Vite Version

1.0.29

### Electron Version

22.3.7

### Vite Version

4.5.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by tom-style** [comment]
> 支持Win7，和操作系统架构相关，缺乏具体的信息。

在WMware安装的虚机机window7 sp1版本，安装的node16.20.2（强行设置不检查版本，不然装不上），客户端dev模式正常，安装后，start 后报如下提示：
![image](https://github.com/alex8088/electron-vite/assets/39619390/e0582ee5-ac20-4468-a360-bc8ac0020be5)

**Comment by alex8088** [comment]
貌似没有正确使用字节码插件，请按故障排除章节技巧去排除问题

**Comment by tom-style** [comment]
> 貌似没有正确使用字节码插件，请按故障排除章节技巧去排除问题

打包到其win11或macos等都是正常的，win7不行。故障排除章节倒是看，没看出要怎么解决；
