### ISSUE TITLE
only web start error

### ISSUE THREAD

**Issue by byunghyun** [alex8088/electron-vite#438]
### Describe the bug

If you try to run it through the web without running Electron, an error will occur.

success
"start": "concurrently \"yarn dev:electron\" \"yarn dev:web\"",

error
"dev:web": "vite",

Can't I just run the web alone?

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
You should add a separate configuration file for vite.

**Comment by byunghyun** [comment]
Hello, thank you for your response.

Could you please let me know the link if the docs say what setting to do?


-----Original Message-----

**Comment by alex8088** [comment]
https://vitejs.dev/config/
