### ISSUE TITLE
在主进程的webPreferences.preload只能加载名称为index或者preload的js，不支持其他名称的js文件

### ISSUE THREAD

**Issue by duoduoele** [alex8088/electron-vite#444]
### Describe the bug

在主进程的webPreferences.preload只能加载名称为index或者preload的js，不支持其他名称的js文件

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
当然支持，取决你自己的命名，参考
- https://cn.electron-vite.org/guide/dev#%E9%A1%B9%E7%9B%AE%E7%BB%93%E6%9E%84
- https://cn.electron-vite.org/guide/dev#%E5%A4%9A%E7%AA%97%E5%8F%A3%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F

**Comment by duoduoele** [comment]
经过测试，依旧不可行。
//electron.vite.config.mjs
export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin(),bytecodePlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin(),bytecodePlugin()],
    build: {
      rollupOptions: {
        input: {
          preload: resolve(__dirname, 'src/preload/test.js')
        }
      }
    }
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },
    plugins: [vue()]
  }
})
这样的配置，dev运行的时候会在out目录生成正确的代码，但是页面并不会运行这个out/preload里面的js，打包之后也不会运行。
或者是主进程
// src/main/index.js
const mainWindow = new BrowserWindow({
    width: 300,
    height: 500,
    show: false,
    autoHideMenuBar: false,
    resizable:false,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: true, 
      sandbox: false,
      preload: join(__dirname, './../preload/test.js'),//已经在src/preload新建了test.js文件
    }
  });
  程序运行时渲染页面会报错 Unable to load preload script: C:\Users\xx\Desktop\electron-vite\wm\out\preload\test.js
  还有个问题，我发现fs模块在主进程也不能识别相对路径，__dirname总是指向out/main这个目录
  我是通过npm create @quick-start/electron@latest方式创建的项目，刚才重新创建项目测试了一下，依旧不行

**Comment by alex8088** [comment]
引用的相对路径错误

**Comment by duoduoele** [comment]
已解决，名称为index.js或preload.js的文件可以直接使用，其他名称的js文件需要配合build.lib.entry使用。谢了。
