### ISSUE TITLE
打包后报错第三方依赖包丢失，但是在开发环境是可以的

### ISSUE THREAD

**Issue by gongjianOnline** [alex8088/electron-vite#446]
### Describe the bug

排查报错是 依赖中的依赖丢失，大家有遇到过吗
"scripts": {
    "format": "prettier --write .",
    "lint": "eslint . --ext .js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts,.vue --fix",
    "typecheck:node": "tsc --noEmit -p tsconfig.node.json --composite false",
    "typecheck:web": "vue-tsc --noEmit -p tsconfig.web.json --composite false",
    "typecheck": "npm run typecheck:node && npm run typecheck:web",
    "start": "electron-vite preview",
    "dev": "electron-vite dev",
    "build": "npm run typecheck && electron-vite build",
    "postinstall": "electron-builder install-app-deps",
    "build:unpack": "npm run build && electron-builder --dir",
    "build:win": "npm run build && electron-builder --win",
    "build:mac": "npm run build && electron-builder --mac",
    "build:linux": "npm run build && electron-builder --linux"
  },
  "dependencies": {
    "@ant-design/icons-vue": "^7.0.1",
    "@electron-toolkit/preload": "^2.0.0",
    "@electron-toolkit/utils": "^2.0.0",
    "ant-design-vue": "4.1.0",
    "axios": "^1.6.5",
    "basic-ftp": "^5.0.4",
    "colorette": "^2.0.20",
    "combined-stream": "^1.0.8",
    "dayjs": "^1.11.10",
    "debug": "^4.3.4",
    "electron-store": "^8.1.0",
    "electron-updater": "^6.1.1",
    "form-data": "^4.0.0",
    "get-installed-apps": "^1.1.0",
    "knex": "^3.1.0",
    "lodash": "^4.17.21",
    "ms": "^2.1.3",
    "node-gyp": "^10.0.1",
    "pg-connection-string": "^2.6.2",
    "pinia": "^2.1.7",
    "rebuild": "^0.1.2",
    "spark-md5": "^3.0.2",
    "sqlite3": "^5.1.7",
    "tarn": "^3.0.2",
    "uuid": "^9.0.1",
    "vue-router": "4"
  },
  "devDependencies": {
    "@electron-toolkit/eslint-config": "^1.0.1",
    "@electron-toolkit/eslint-config-ts": "^1.0.0",
    "@electron-toolkit/tsconfig": "^1.0.1",
    "@rushstack/eslint-patch": "^1.3.3",
    "@types/node": "^18.17.5",
    "@vitejs/plugin-vue": "^4.3.1",
    "@vue/eslint-config-prettier": "^8.0.0",
    "@vue/eslint-config-typescript": "^11.0.3",
    "electron": "^25.6.0",
    "electron-builder": "^24.6.3",
    "electron-vite": "^1.0.27",
    "eslint": "^8.47.0",
    "eslint-plugin-vue": "^9.17.0",
    "less": "^4.2.0",
    "prettier": "^3.0.2",
    "typescript": "^5.1.6",
    "vite": "^4.4.9",
    "vue": "^3.3.4",
    "vue-tsc": "^1.8.8"
  }

### Electron-Vite Version

2.1.0

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/troubleshooting#a-javascript-error-occurred-in-the-main-process-error-cannot-find-module-xxx

**Comment by gongjianOnline** [comment]
> https://cn.electron-vite.org/guide/troubleshooting#a-javascript-error-occurred-in-the-main-process-error-cannot-find-module-xxx
按照顾文档中的删除了lock文件重新使用 cnpm 构建后,仍然会有相同的问题, 排查是第三方包的依赖包没有被打包,不知到怎么解决一下

**Comment by alex8088** [comment]
不能使用cnpm，改用其他包管理器
