### ISSUE TITLE
请问项目运行启动时终端输出中文乱码怎么解决呀？

### ISSUE THREAD

**Issue by guitars123** [alex8088/electron-vite#447]
### Describe the bug

依赖下载完成之后，开发时调试输出中文乱码，调试体验不太好
![image](https://github.com/alex8088/electron-vite/assets/62170779/374ae1ec-3f40-4ddc-8ba9-f9a9626bcea9)

### Electron-Vite Version

2.0.0

### Electron Version

electron28

### Vite Version

5

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
IDE字符集不支持中文，自行检索解决
