### ISSUE TITLE
`electron-vite dev` serves WASM files in a wrong format

### ISSUE THREAD

**Issue by pwbh** [alex8088/electron-vite#449]
### Describe the bug

I am migrating my project from a regular web to electron app because I am in need of native functionality, and I wanted to migrate to electron-vite because vite is what I was using and everything worked wonderfully until now.

However the same setup seem to fail recognize the wasm binary as wasm file format. 
It works correctly in `electron-vite preview` and everything mounts as expected, but it seem to fail in `electron-vite dev`.  My wasm module is written in Rust.

I am guessing it has something to do with Vite's hot reloading server and how it serves files, wonder if there is something that I am missing here. In regular Vite powered web app hot reloading works as expected without any special handling.

This is my `main.ts` from the renderer folder.  

```ts
import init from 'wgpu-wasm'

import './styles/app.css'

import App from './App.svelte'
import globalInitializator from './globalInitializator'

const start = async () => {
  globalInitializator()

  const { memory } = await init()

  return new App({
    target: document.getElementById('app'),
    props: { memory }
  })
}

const app = start()

export default app
```

Logs from the console:

```
`WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
 ```

This one just means that the type with which we served is wrong
```
Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
```

Thanks for any input on this.

### Electron-Vite Version

2.1.0 (Also tried 2.0.0)

### Electron Version

28.2.0

### Vite Version

5.1.0 (Also tried 5.0.12)

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://vitejs.dev/guide/features.html#webassembly

**Comment by pwbh** [comment]
Instantiating seems not the way to go, is there any difference between electron-vite and vite hot reload servers?

**Comment by alex8088** [comment]
> Instantiating seems not the way to go, is there any difference between electron-vite and vite hot reload servers?
> 
> Edit: The way I initialize it, is already using Instantiating, so its either the HMR or something related to that.

There is no difference, electron-vite‘s HMR is powered by vite.

**Comment by alex8088** [comment]
Did you use wasm-pack to generate the wasm?  https://github.com/nshen/vite-plugin-wasm-pack

**Comment by pwbh** [comment]
Thanks I'll try that
