### ISSUE TITLE
针对addon模块，是否有最佳实践？

### ISSUE THREAD

**Issue by keyiis** [alex8088/electron-vite#45]
### Clear and concise description of the problem

在文档中没有发现关于sqlite3/serialport这类模块的打包指引

### Suggested solution

能否在文档中具体描述下或者哪里可以找到

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
duplicate #42 

https://cn-evite.netlify.app/guide/build.html#%E5%A4%96%E9%83%A8%E4%BE%9D%E8%B5%96

**Comment by alex8088** [comment]
@keyiis 最新的脚手架默认就支持

**Comment by keyiis** [comment]
我安装了Sequelize，并在代码中使用，但是npm run dev后提示如下错误
```
TypeError: browser.Sequelize is not a constructor
    at Object.<anonymous> (D:\project\vite-electron-test\electron-app\out\main\index.js:181:22)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
```

**Comment by alex8088** [comment]
这貌似没有正确使用Sequelize，`browser.Sequelize` ?

提供更详细的使用细节

**Comment by keyiis** [comment]
@alex8088 sequelize是在主进程里调用的，使用方法和后端使用时一样，这里有什么特别的要求吗？

**Comment by alex8088** [comment]
你使用的装饰器版本，目前对装饰器还没有支持，计划后续版本支持。

**Comment by alex8088** [comment]
最新版本已支持
