### ISSUE TITLE
After I ran npx electron-vite, shows Cannot find module 'electron/package.json'

### ISSUE THREAD

**Issue by aScHEABL** [alex8088/electron-vite#451]
### Describe the bug

As title, I'm trying to start a new project with this package, followed exactly what the [docs](https://electron-vite.org/guide/) says.
I installed electron-vite with command `npm i electron-vite -D`, installed successfully.
Next, I ran the command `npx electron-vite` in my project directory,
then it shows
```
ERROR  Cannot find module 'electron/package.json'
Require stack:
- /home/saturagi/repos/electron-marco/node_modules/electron-vite/dist/chunks/lib-E9FdlsIF.mjs
```
Upon checking project/node_modules/electron-vite/dist/chunks/lib-E9FdlsIF.mjs,
The file is indeed there even with the same name, the path is correct too.

Then I edited the package.json exactly like the docs says
```
{
  "scripts": {
    "start": "electron-vite preview",
    "dev": "electron-vite dev",
    "prebuild": "electron-vite build"
  }
}
```
And then ran `yarn run dev` still pops the same error as above.
Is this a bug?
My OS is Linux mint 21
node version 20.10.0
yarn version 1.22.21

### Electron-Vite Version

2.1.0

### Electron Version

latest

### Vite Version

5.1.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
You need to install electron in your project. It is recommended to use scaffolding to create projects .

```bash
 npm create @quick-start/electron@latest
```

**Comment by aScHEABL** [comment]
> You need to install electron in your project. It is recommended to use scaffolding to create projects .
> 
> ```shell
>  npm create @quick-start/electron@latest
> ```

Yes, thank you, the issue is resolved. However may I suggest that the docs should be written from top to bottom?
It'll cause confusion because people will think they're supposed to do it from top to bottom order.
