### ISSUE TITLE
ProtectedStrings don't work for template literals

### ISSUE THREAD

**Issue by axelstudios** [alex8088/electron-vite#455]
### Describe the bug

When using the bytecode plugin with `protectedStrings`, the protection fails if the string is a template literal. It could be something as simple as:
```TypeScript
const secret = `MY SECRET`
```
or a multi-line string:
```TypeScript
export const privateKey = `-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
`
```

It can be fixed by updating [this line](https://github.com/alex8088/electron-vite/blob/f42a9d370f5965f43a49a55be6d0c3d2637118cd/src/plugins/bytecode.ts#L213) to:
```TypeScript
const re = new RegExp(`\\u0027${escapedStr}\\u0027|\\u0022${escapedStr}\\u0022|\\u0060${escapedStr}\\u0060`, 'g')
```

### Electron-Vite Version

2.10.0

### Electron Version

29.1.5

### Vite Version

5.1.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Template literals are different from strings and cannot be violently replaced. For example:

```js
const d = 'a'
const key= `ABC${d}`
```
It is recommended to handle it this way:

```js
const privateKey = '-----BEGIN PRIVATE KEY-----' + '\n' + '.....'
```
