### ISSUE TITLE
应用程序在打包 --ia32时打开应用会报错无法读取缓存数据，而64位的应用则可以正常运行，请问这是什么原因导致的呢？

### ISSUE THREAD

**Issue by guitars123** [alex8088/electron-vite#457]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/62170779/fb77e3e9-582a-43f8-8488-8b11bd8e0d8f)

### Electron-Vite Version

2.1.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by guitars123** [comment]
使用了bytecodePlugin()的原因，移除了就好了

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/source-code-protection#%E5%A4%9A%E5%B9%B3%E5%8F%B0%E6%9E%84%E5%BB%BA

@guitars123

**Comment by guitars123** [comment]
感谢，问题解决了，以后多看文档
