### ISSUE TITLE
新建一个worker_threads 线程，子线程文件里引入了其他文件 无法编译运行

### ISSUE THREAD

**Issue by gakkiox** [alex8088/electron-vite#458]
### Describe the bug

新建一个worker_threads 线程，子线程文件里引入了其他文件 无法编译运行 
由于依赖都打包到main.js里面导致子线程无法引用

![微信截图_20240326210920](https://github.com/alex8088/electron-vite/assets/54433489/82635a41-fb74-466e-a5c4-45a424a0fa2b)
![微信截图_20240326211017](https://github.com/alex8088/electron-vite/assets/54433489/0db73bdb-0a60-4321-882d-e1936055e934)

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/dev#worker-threads

**Comment by gakkiox** [comment]
感谢大佬指示
