### ISSUE TITLE
增加对worker的支持

### ISSUE THREAD

**Issue by liuyike98** [alex8088/electron-vite#46]
### Clear and concise description of the problem

插件配置文件貌似只有preload，main，renderer，除此之外通常worker也是需要一个文件夹的，希望能够增加支持

### Suggested solution

none

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@liuyike98 

- 对于渲染进程的 Worker 可以在 `renderer.worker` 进行配置
- 对于主进程的nodejs worker处理有两种方式:
  
1. 插件形式(不构建)：

```
.
├──plugins /
│  ├──worker.js     # written in `commonjs`
│  └──...
├──src
│  ├──main /
│  │  ├──index.ts # 
│  │  └──...
│  ├──preload
│  └──renderer
├──electron.vite.config.ts
├──package.json
└──...
```

2. 需要构建

```
export default {
  main: {
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.ts'),
          worker: resolve(__dirname, 'src/main/worker.ts')
        }
      }
    }
  },
  preload: {},
  // ...
}
```
**这两种形式都需要在代码中正确引用路径**

目前，这样的处理方式基本可以解决问题。增加一个选项并无法减轻配置负担，而更加关切的问题是使用中的路径问题，是否可以智能解析，如果能够做到，那可能需要增加一个选项或者一个插件来处理，但目前我并没有找到很好的处理办法。

**Comment by alex8088** [comment]
#51 new solution

**Comment by liuyike98** [comment]
> #51 new solution

ok，下午我试一下哈，还有个问题，给你提了个issue，帮忙看下吧，感谢

**Comment by alex8088** [comment]
新解决方案还没发布，要下一个版本，着急可以先通过上面的方案处理

**Comment by alex8088** [comment]
new ver `1.0.13` is out! You can learn more by playing with the [example](https://github.com/alex8088/electron-vite-worker-example).
