### ISSUE TITLE
Windows production build blank renderer page

### ISSUE THREAD

**Issue by KillerCodeMonkey** [alex8088/electron-vite#460]
If i build my project for production on windows everything is bundled and all necessary files are produced for the renderer (js, css and index.html).

But the index.html does not contain the script or css. 
It is just a blank page.

e.g. my config:

```JS
export default {
  main: {
    plugins: [externalizeDepsPlugin()],
    build: {
      lib: {
        entry: 'src/launcher/main/main.ts'
      },
      outDir: 'dist/launcher/main'
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
    build: {
      lib: {
        entry: 'src/launcher/preload/preload.ts'
      },
      outDir: 'dist/launcher/preload'
    },
    define: envs
  },
  renderer: {
    root: 'src/launcher',
    build: {
      rollupOptions: {
        input: 'src/launcher/index.html'
      },
      outDir: 'dist/launcher/renderer'
    }
  }
}
```

source index.html
```HTML
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
  </head>
  <body>
    <script type="module" src="./renderer/index.tsx"></script>
  </body>
</html>
```

dist index.html
```HTML
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
  </head>
  <body>
  </body>
</html>
```

It is working fine for mac and linux builds.

### Electron-Vite Version

2.1.0

### Electron Version

26.6.10

### Vite Version

5.2.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/troubleshooting#vue-router-or-react-router-dom-works-in-development-but-not-production

**Comment by KillerCodeMonkey** [comment]
Can you please explain the connection between that router thing and my problem?

since it is working on other platforms how is this connected?

**Comment by alex8088** [comment]
bad script path
```ts
 <script type="module" src="./renderer/index.tsx"></script>
```

Where is your renderer working directory?

https://electron-vite.org/guide/dev#customizing

**Comment by KillerCodeMonkey** [comment]
check my renderer config

```
renderer: {
    root: 'src/launcher',
    build: {
      rollupOptions: {
        input: 'src/launcher/index.html'
      },
      outDir: 'dist/launcher/renderer'
    }
  }
```

- src
  - launcher
    - main/
      - main.ts
    - preload/
      - preload.ts 
    - renderer/
      - index.tsx  
    - index.html

i guess the config is correct, since it is working as i said on linux and mac.
and vite finds the html and bundles the index and css correctly. but the script and css bundles are not added to the dist index.html only in windows

**Comment by KillerCodeMonkey** [comment]
btw: thanks for you fast responses... again and again

**Comment by alex8088** [comment]
Vite build should not depend on platform.  I think there are other reasons. Maybe you can provide a reproducible example to make it easier to find the problem.

**Comment by KillerCodeMonkey** [comment]
@alex8088  i tried it with your helpful create app.

if i change the config for the renderer to this:

```TS
renderer: {
  root: 'src/renderer',
  build: {
    rollupOptions: {
      input: 'src/renderer/index.html'
    }
  },
  ... // default renderer config
}

```

there is no error during build, but the index is empty

**Comment by KillerCodeMonkey** [comment]
got it working.

seems like when setting root/build.rollupOptions.input we need to pass paths os specific.
strange it builds without an error and finds all files but only the replacement in the index is not working.

when using join/resolve in the vite.config so / or \ is used it is working.

@alex8088 you can decide if you wan to add some info to the docs, or check if you can get it working.

For me it is working as long as i know now that i have to pass some paths that way.
