### ISSUE TITLE
能支持Mobile吗？

### ISSUE THREAD

**Issue by yingapp** [alex8088/electron-vite#464]
### Clear and concise description of the problem

ELectron 能运行在移动手机上吗？Android webview有很多限制，比如不能缓存PWA

### Suggested solution

如果能实现就不需要编写原生代码了

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by yingapp** [comment]
而且可以保证运行环境的一致性

**Comment by alex8088** [comment]
electron 不支持移动端仅支持 PC 端
