### ISSUE TITLE
Error: Cannot bind an API on top of an existing property on the window object

### ISSUE THREAD

**Issue by chalapathi-ct** [alex8088/electron-vite#468]
### Describe the bug

I have a preloader that exposes the wow variable to the window.  I am getting this error in electron-vite dev and electron-vite preview, after building I am not getting this error. 
![image](https://github.com/alex8088/electron-vite/assets/139749782/448da759-3cd8-4091-8979-9606bbdb9986)

I am freezing my wow object in my website script for business purposes (which will not happen if the website is opened in the electron app).  The preload scripts should be loaded before the website is rendered right, so the error shouldn't come. 

![Screenshot from 2024-04-10 10-02-29](https://github.com/alex8088/electron-vite/assets/139749782/d0ff226d-0900-407a-8df4-9f5f8ff9982a)

### Electron-Vite Version

2.1.0

### Electron Version

29.2.0

### Vite Version

5.2.7

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Where is your error message?

**Comment by chalapathi-ct** [comment]
> Where is your error message?

sorry!. I have attached the error.

**Comment by alex8088** [comment]
it should be unsandboxed.

**Comment by alex8088** [comment]
Maybe it's your preload script problem.
