### ISSUE TITLE
After packaging, the reload shortcut does not take effect

### ISSUE THREAD

**Issue by shunjinchan** [alex8088/electron-vite#472]
### Describe the bug

After packaging, the reload shortcut does not take effect. but the development environment is fine.

**sample**

```js
{ role: 'reload' }
```
 or
```js
{
    label: 'Reload',
    accelerator: 'CommandOrControl + R',
    click: () => {
      mainWindow.webContents.reload()
    }
  }
```

### Electron-Vite Version

2.1.0

### Electron Version

 platform=darwin arch=arm64 electron=28.2.5 

### Vite Version

5.1.5

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
// main.js
```ts
// Default open or close DevTools by F12 in development
// and ignore CommandOrControl + R in production. 
// see https://github.com/alex8088/electron-toolkit/tree/master/packages/utils
app.on('browser-window-created', (_, window) => {
  optimizer.watchWindowShortcuts(window)
})
```
Remove it yourself when not needed. It is recommended not to allow users to refresh or to let the app control when to refresh.
