### ISSUE TITLE
renderer not found in Output Dir

### ISSUE THREAD

**Issue by weiguic2w** [alex8088/electron-vite#473]
### Describe the bug

在使用`npm create @quick-start/electron my-app --template vue`构建项目并执行`npm run dev`时，发现out目录下找不到renderer。
![image](https://github.com/alex8088/electron-vite/assets/124777699/d7cd8b40-fc9d-4c1a-b15f-ffacec9d6152)

这在开发模式下可以正常运行，但当我根据https://electron-vite.org/guide/distribution#distributing-apps-with-electron-forge 指引用electron forge打包时会找不到index.html。
![image](https://github.com/alex8088/electron-vite/assets/124777699/cc28277b-f4f4-450e-a66d-792be6ef6ed6)
后续通过`renderer: {
    build: {
      outDir: 'dist/renderer'
    }
  }`指定输出目录也未能生效。我不知道这是否是正常的设计，如果是正常设计我该如何解决打包后index.html not found的问题

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by weiguic2w** [comment]
在app.asar的解压文件app-unpacked中也未能找到index.html
![image](https://github.com/alex8088/electron-vite/assets/124777699/41e5b8b9-f5d1-42ae-b5cb-a25022125c13)
![image](https://github.com/alex8088/electron-vite/assets/124777699/48bbe45c-8d24-48ab-a8f1-d2bad6a3a005)

**Comment by alex8088** [comment]
打包前先build，https://cn.electron-vite.org/guide/distribution#%E4%BD%BF%E7%94%A8-electron-forge-%E5%88%86%E5%8F%91%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F

```sh
 "make ": "electron-vite build --outDir=dist && electron-forge make"
```

**Comment by weiguic2w** [comment]
感谢，已解决。
