### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by redisviewer** [alex8088/electron-vite#474]
### Describe the bug
![image](https://github.com/alex8088/electron-vite/assets/12822830/bc0cbbd4-bf1b-49a2-b629-84de429ab1a9)

index.js:1 Uncaught ReferenceError: process is not defined
    at Object.<anonymous> (index.js:1:8188)
    at n2 (index.js:1:489)
    at Object.<anonymous> (index.js:1:609)
    at n2 (index.js:1:489)
    at index.js:1:576
    at index.js:1:580
    at index.js:1:81
    at node_modules/node-machine-id/dist/index.js (index.js:1:356)
    at __require (chunk-ROME4SDB.js?v=1c968ba8:11:50)
    at index.js:1:18859

App.vue中使用了node-machine-id库生成设备id，node-machine-id内部应该是用了process，导致报错，
请问这种情况该怎么处理

### Electron-Vite Version

2.1.0

### Electron Version

28.2

### Vite Version

4.5.3

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
渲染进程不支持使用node模块，推荐使用preload开发。https://cn.electron-vite.org/guide/dev#%E4%BD%BF%E7%94%A8%E9%A2%84%E5%8A%A0%E8%BD%BD%E8%84%9A%E6%9C%AC

**Comment by redisviewer** [comment]
<img width="1068" alt="image" src="https://github.com/alex8088/electron-vite/assets/12822830/6d1d4164-8c19-443a-8a3d-05343c6d57ad">
我使用preload把它导入过去这样使

感谢作者
