### ISSUE TITLE
使用 vue-router  无法生效

### ISSUE THREAD

**Issue by inkn** [alex8088/electron-vite#475]
### Describe the bug

使用 vue-router  无法生效；
创建一个新项目
npm i  vue-router@4  添加 vue-router,
配置好路由后，路由不生效；控制台报错：
```
vue-router.js?v=40c392b4:2659 ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (electron.js?v=40c392b4:36:30)
    at __require (chunk-ZS7NZCD4.js?v=40c392b4:8:50)
    at electron.js?v=40c392b4:54:16
```

src\renderer\src\router\index.ts:
```
import { createRouter, createWebHashHistory } from 'vue-router';

const routes = [
  {
    path: '/',
    redirect: '/main'  // 当访问根路径时自动重定向到 /main
  },
  {
    path: '/main',
    name: 'Main',
    component: () => import('../components/Main.vue')
  },
  {
    path: '/child',
    name: 'Child',
    component: () => import('../components/Child.vue')
  },
  // 更多路由...
];

const router = createRouter({
  history: createWebHashHistory(),
  routes
});

export default router;
```

src\renderer\src\main.ts:

```
import './assets/main.css'

import { createApp } from 'vue'
import App from './App.vue'
import naive from 'naive-ui'

import router from '@renderer/route'

const app = createApp(App)
app.use(naive)
app.use(router)
app.mount('#app')

```

都是很简单配置；很基础的用法；不能在 render 渲染进程里 import vue-router ? 

### Electron-Vite Version

2.0.0

### Electron Version

^28.2.0

### Vite Version

^5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
这和router无关，这是因为你在渲染进程使用了electron模块，仔细看你的错误信息， 推荐使用preload开发。

**Comment by inkn** [comment]
> 这和router无关，这是因为你在渲染进程使用了electron模块，仔细看你的错误信息， 推荐使用preload开发。

但是，我不用 router 就没有报错，就是用模板创建的空工程，什么都没有，也没有使用 electron 模块。

**Comment by alex8088** [comment]
错误信息非常明确，从代码错误的位置找到源代码使用位置

**Comment by inkn** [comment]
> 错误信息非常明确，从代码错误的位置找到源代码使用位置
确实是用了electron ,  ipcRenderer ，感谢大佬
