### ISSUE TITLE
在vue文件中，声明的window全局变量提示Unresolved variable，不可解析变量

### ISSUE THREAD

**Issue by kongbair** [alex8088/electron-vite#477]
### Describe the bug

```vue
<script setup lang="ts">
import { reactive } from 'vue'

const versions = reactive({ ... window.electron.process.versions })
</script>

<template>
  <ul class="versions">
    <li class="electron-version">Electron v{{ versions.electron }}</li>
    <li class="chrome-version">Chromium v{{ versions.chrome }}</li>
    <li class="node-version">Node v{{ versions.node }}</li>
  </ul>
</template>
```

上面是原始文件的版本组件，安装环境后，我尝试用webstorm打开它后，提示window.electron无法解析。如图所示：

![image](https://github.com/alex8088/electron-vite/assets/93134550/9bd96262-bdf6-4d02-83af-a5b5f41f8809)

但在ts文件中，它可以正常解析，不会提示任何错误，还有智能提示;

我试着把文件tsconfig.json 中的  "files": [],   这一行删除，重启ide，依然不行。

### Electron-Vite Version

^2.0.0

### Electron Version

^28.2.0

### Vite Version

^5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
将tsconfig中的files去除，重启ide
