### ISSUE TITLE
官方项目导下来后运行打包exe，安装完成后打开失败

### ISSUE THREAD

**Issue by wwwmomo** [alex8088/electron-vite#492]
### Clear and concise description of the problem

"build:win": "npm run build && electron-builder --win"
运行命令，打包成功
使用的是m1 mac环境
nodejs 20.12.2
在电脑安装完之后打开失败
![企业微信20240429-141251](https://github.com/alex8088/electron-vite/assets/32353382/ceb516d9-71d0-44f7-b061-12bcda1e9ab8)
![企业微信截图_17143604474838](https://github.com/alex8088/electron-vite/assets/32353382/4fe0e576-4098-4d25-b678-ac56cccbf753)

### Suggested solution

希望能够正常安装运行

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
请阅读electron-builder的相关文档，arm64怎么能在window64上运行呢，你需要打包x64的windows安装包，还需要注意不同平台打包的问题。可以自行检索了解electron-builder跨平台架构如何打包

**Comment by wwwmomo** [comment]
"build:win": "npm run build && electron-builder --win --x64"
加上了 --x64成功解决，感谢大佬的提示
