### ISSUE TITLE
build:win 打包之后，把所有源码都在app,asar里面。使用 asar 解包可以看到源码文件

### ISSUE THREAD

**Issue by zhezhizhuo** [alex8088/electron-vite#495]
### Describe the bug

源代码打包到asar里面去了 
。使用 asar 解包可以看到源码文件

### Electron-Vite Version

^2.0.0

### Electron Version

^28.2.0

### Vite Version

5.2.10

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by zhezhizhuo** [comment]
使用的js 去解包
![image](https://github.com/alex8088/electron-vite/assets/74035484/577d632c-cd3f-4a7b-ab11-c0bc7f41be13)
解出来之后 居然是全部的代码out是打包之后的加密源码文件，而electro目录和src的目录是源代码全部被打包在app.asar中
![image](https://github.com/alex8088/electron-vite/assets/74035484/a6d51219-be11-46b6-9ffe-7a2770c2310a)

**Comment by zhizhuo0325** [comment]
好的谢谢你可以关闭该Issuser了
