### ISSUE TITLE
main下index.js用require引入了同目录下另一个js，但是在out目录里面没有该js，只有index.js

### ISSUE THREAD

**Issue by jipfqf** [alex8088/electron-vite#497]
### Describe the bug

我把ipcMain.handle这些接口全部放到api.js里面和index.js同目录
然后在最后一行加上require('api')，运行时api.js没有复制到out目录里面，导致运行不起来
应该怎么配置或者有什么其他方法

### Electron-Vite Version

2.2.0

### Electron Version

28.3.1

### Vite Version

5.2.10

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
请使用esm语法

**Comment by wumingluren** [comment]
> > 请使用esm语法
> 
> 原来如此，感谢

可以给下完整的示例代码吗？

**Comment by jipfqf** [comment]
> > > 请使用esm语法
> > 
> > 
> > 原来如此，感谢
> 
> 可以给下完整的示例代码吗？

![image](https://github.com/alex8088/electron-vite/assets/22951659/135e07bb-e8aa-4c5d-bd7c-e4cb95fec6f9)
![image](https://github.com/alex8088/electron-vite/assets/22951659/04bbb457-d763-4871-a54c-02a8d40c5745)
大概就长这样
