### ISSUE TITLE
Defaults for define in main are causing esbuild error due to process.env not being a valid value

### ISSUE THREAD

**Issue by kskalski** [alex8088/electron-vite#5]
### Describe the bug

I'm getting error 

```
> error: Invalid define value (must be valid JSON syntax or a single identifier): process.env

 > error: Invalid define value (must be valid JSON syntax or a single identifier): global.process.env

 > error: Invalid define value (must be valid JSON syntax or a single identifier): globalThis.process.env
```

which can be bypassed by adding ``define``, that replaces those keys with something else like single identifier or ``{}``. However for main process I do actually want to use ``process.env``, which appears to be not possible to do now (I suspect newest esbuild introduced some stricter checks that the value is single identifier or valid JSON, but ``process.env`` is neither, see https://github.com/evanw/esbuild/issues/2292).

I think for ``main`` section we shouldn't actually use the define at all, since we are replacing ``process.env`` with ``process.env``, which doesn't make a lot of sense and those references could be left as they are in the emitted code.

### Electron-Vite Version

1.0.3

### Electron Version

18

### Vite Version

v3.0.0-alpha.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@kskalski 

I can't reproduce this bug (`esbuild` ver: `0.14.42`). Can you provide more detailed info on this?

In Vite, the string replacement is done by itself, the `define` config should not be used in  `esbuild`. see [vite define plugin](https://github.com/vitejs/vite/blob/v2.9.9/packages/vite/src/node/plugins/define.ts)

**Comment by kskalski** [comment]
Ok, seems like this error happens only when I remove
```
 external: ['@electron-toolkit/utils']
```
line in the config. I was building without this external declaration, because I wasn't sure for its need, but possibly it shouldn't be ever removed.

**Comment by alex8088** [comment]
use vite@3 now
