### ISSUE TITLE
渲染进程打包之后找不到图片资源，开发的时候可以看到图片渲染，请问是需要配置什么么

### ISSUE THREAD

**Issue by zhezhizhuo** [alex8088/electron-vite#500]
### Describe the bug

我代码里面是这样写的
 //map循环遍历 返回Img  如何 模板字符串动态获取图片
 <img className={styles.rightImg} src={`/img/maps/${item.icon}.png`}/>
开发的时候配置了
  renderer: {
    publicDir: resolve('src/renderer/src/assets'」
//配置了静态资源图片
但是打包之后图片加载不出来

![Uploading image.png…]()

### Electron-Vite Version

^2.0.0

### Electron Version

^28.2.0

### Vite Version

5.2.10

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by zhezhizhuo** [comment]
控制报错 
 file:///D:/img/play/tabs/4.png         net::ERR_FILE_NOT_FOUND

**Comment by zhezhizhuo** [comment]
@alex8088  可以加个微信吗 这里太卡了图片上传不了

**Comment by zhezhizhuo** [comment]
![image](https://github.com/alex8088/electron-vite/assets/74035484/f6858283-d21d-49b3-852d-32163e95fe3b)

**Comment by zhezhizhuo** [comment]
![image](https://github.com/alex8088/electron-vite/assets/74035484/99c9eabd-6493-41ea-9189-86077acd1601)

**Comment by zhezhizhuo** [comment]
开发过程中是可以正常返回的 ，
![image](https://github.com/alex8088/electron-vite/assets/74035484/1601a79c-f904-40e9-8991-936de424fea1)

**Comment by zhezhizhuo** [comment]
可能是开发通过端口 /img   \src\renderer\src\assets 里面的静态资源，打包之后就无法请求到了

**Comment by alex8088** [comment]
> @alex8088 可以加个微信吗 这里太卡了图片上传不了

issue 头部栏有交流群信息

**Comment by zhezhizhuo** [comment]
![image](https://github.com/alex8088/electron-vite/assets/74035484/8f02ef9c-52ba-4df0-9627-3b3888e3f756)

**Comment by alex8088** [comment]
> ![image](https://private-user-images.githubusercontent.com/74035484/328865135-f6858283-d21d-49b3-852d-32163e95fe3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjY3NjQsIm5iZiI6MTcxNTE2NjQ2NCwicGF0aCI6Ii83NDAzNTQ4NC8zMjg4NjUxMzUtZjY4NTgyODMtZDIxZC00OWIzLTg1MmQtMzIxNjNlOTVmZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDExMDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNmNjYjhjNGEzMGJiZjVjZTUwMjgyYWRiZTQwNDAxMWMyODdiN2MzMDRmYTc2YjczZjU0MTFiYjlhOGFlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._KHuNswudtjL3_JOpkNk_egp69XVBbJCntB6AwK_HUM)

这是代码上使用了绝对地址
renderer的静态资源处理可以参考vite静态资源章节

**Comment by zhezhizhuo** [comment]
> > ![image](https://private-user-images.githubusercontent.com/74035484/328865135-f6858283-d21d-49b3-852d-32163e95fe3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjY3NjQsIm5iZiI6MTcxNTE2NjQ2NCwicGF0aCI6Ii83NDAzNTQ4NC8zMjg4NjUxMzUtZjY4NTgyODMtZDIxZC00OWIzLTg1MmQtMzIxNjNlOTVmZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDExMDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNmNjYjhjNGEzMGJiZjVjZTUwMjgyYWRiZTQwNDAxMWMyODdiN2MzMDRmYTc2YjczZjU0MTFiYjlhOGFlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._KHuNswudtjL3_JOpkNk_egp69XVBbJCntB6AwK_HUM)
> 
> 这是代码上使用了绝对地址 renderer的静态资源处理可以参考vite静态资源章节

没有看懂 vite的文档，  有案例提供吗 ，我需要如何修改，还请麻烦您，点拨一下

**Comment by alex8088** [comment]
脚手架创建的项目就有呀

**Comment by zhezhizhuo** [comment]
![image](https://github.com/alex8088/electron-vite/assets/74035484/89e527ad-ac26-498a-a165-d2a223491a4d)
我是要遍历的时候去渲染图片，能直接通过src去设置地址吗 
![image](https://github.com/alex8088/electron-vite/assets/74035484/cc14ce17-40d7-43b9-8020-030997dcf661)
有没有办法直接动态获取呢
