### ISSUE TITLE
主进程里面使用log打印出来不是简体字。

### ISSUE THREAD

**Issue by wumingluren** [alex8088/electron-vite#502]
### Describe the bug

![image](https://github.com/alex8088/electron-vite/assets/41581133/847e7d43-bf89-457a-8964-d90de5358db3)
发现也不是繁体字，不知道为啥会这样。
顺便问一下主进程里面index.js怎么引用其他的js文件

### Electron-Vite Version

最新

### Electron Version

最新

### Vite Version

最新

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
IDE问题，自行检索解决，js文件可以使用esm语法导入

**Comment by Kaidesuyoo** [comment]
![image](https://github.com/alex8088/electron-vite/assets/164149205/144cefe4-b5f3-4eb8-a84f-8881c71ec16d)
然后重启系统即可。

或者fork一份，按照[https://github.com/electron-vite/vite-plugin-electron/issues/116#issuecomment-1346066737](这个)修改对应源码。

**Comment by alex8088** [comment]
这个并不能解决此问题，这不是构建工具问题，而是输出终端字符编码问题？https://zhuanlan.zhihu.com/p/354940478

**Comment by wumingluren** [comment]
> 这个并不能解决此问题，这不是构建工具问题，而是输出终端字符编码问题？https://zhuanlan.zhihu.com/p/354940478

试了这个方法，打印出来还是乱码字。

**Comment by favour1025** [comment]
chcp 65001

**Comment by favour1025** [comment]
chcp 65001

**Comment by Taoister39** [comment]
如果你使用的是 powershell，可以设置输出编码 utf-8。

```powershell

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

```

> > 这个并不能解决此问题，这不是构建工具问题，而是输出终端字符编码问题？https://zhuanlan.zhihu.com/p/354940478
> 
> 试了这个方法，打印出来还是乱码字。
