### ISSUE TITLE
build之后的exe启动很慢

### ISSUE THREAD

**Issue by Reeyc** [alex8088/electron-vite#505]
### Clear and concise description of the problem

双击打开exe，启动时间 >5s，应该不是业务代码问题，我们代码量很少，就几个小的.vue文件

### Suggested solution

有没有好的优化方案

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
你可以使用脚手架创建初始化项目比对时间，排除是否代码问题，这个启动时间显然是不正常的。也有可能是杀毒软件这些导致的。
