### ISSUE TITLE
本地模块包含 dll 文件，怎么 在运行npm run dev 一起复制获取到 out/main目录内呢

### ISSUE THREAD

**Issue by RayCssjmt** [alex8088/electron-vite#509]
### Clear and concise description of the problem

目前我在 main 编写了一个模块 使用 dll扩展，然后我运行 npm run dev，代码文件被 转为 out/main/index.js，但是dll文件没被复制过去 导致找不到 ，请问需要怎么配置呢

### Suggested solution

需要将 dll 文件 在执行 npm run dev 一起复制 /out/main目录下面去

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/assets 按资源处理章节处理

**Comment by RayCssjmt** [comment]
> https://cn.electron-vite.org/guide/assets 按资源处理章节处理

好呢，感谢
