### ISSUE TITLE
在vue img标签中，vite总是在尝试解析以.png结尾的请求

### ISSUE THREAD

**Issue by summerset-zz** [alex8088/electron-vite#511]
### Describe the bug

组件里有一个img标签是这样的：
```
// vite报错
 <img src="renderer://res/rosearchive-title.png" />
```
我在main线程设置了拦截renderer协议的功能来返回已打包的本地文件，但是这个请求就没有到达main线程。

vite报错如下：
```
[plugin:vite:import-analysis] Failed to resolve import "/rosearchive-title.png" from "src/renderer/src/pages/Init.vue". Does the file exist?
```
大概是vite认为这是一个静态资源所以自行import了。

# 临时的解决方案（可用）
我修改成了动态属性时工作正常：
```
// 正常
     <img :src="`renderer://res/rosearchive-title.png`" />
```

# 已尝试的解决方法（无效）
electron.vite.config.ts，`renderer`节点增加如下信息：
```
     build: {
            assetsInlineLimit: 0,
        },
        assetsInclude: ['renderer://**/*', 'renderer://**/*.*'],
```
结果无效。

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
vite目前不支持自定义协议，已有相关pr https://github.com/vitejs/vite/issues/13540
目前只能通过变量处理
