### ISSUE TITLE
在.vue文件中，利用iframe来加载一个本地的html文件不被允许

### ISSUE THREAD

**Issue by duoduoele** [alex8088/electron-vite#514]
### Clear and concise description of the problem

利用iframe来加载一个本地的html文件不被允许

### Suggested solution

利用iframe来加载一个本地的html文件不被允许

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
无相信错误信息，大致是CSP问题，自行检索解决。
