### ISSUE TITLE
Problems loading resources into the client that are not in use in the DOM

### ISSUE THREAD

**Issue by LexDevelp** [alex8088/electron-vite#516]
### Describe the bug

Hello, very good day, afternoon or night!, as the title says, I have a problem loading resources that are not being used in the DOM of the renderer, well, it happens that I need to load a json by and some images by javascript, but when I executed ` ``npm run dev``` the image does not exist in the project if it is loaded by javascript, but on the contrary if it is loaded in html it loads it correctly but due to the functionality of the system I must load it by javascript, the solution I found was to convert the images to base64 but now I have the problem with the .json and .bin files, since I do not only need their content, I need the file as such, and I cannot upload it to the dom so that it recognizes it and I cannot in any way be able to load these files in the client, I would greatly appreciate your help in solving my problem, thank you very much in advance

### Electron-Vite Version

28.2.0

### Electron Version

2.0.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
- For assets handling in the renderers, please refer to the [vite guide](https://vitejs.dev/guide/assets.html). 
- For assets handling in main process, please refer to the [electron-vite guide](https://electron-vite.org/guide/assets). 
- For localized resource processing, it is recommended that you read the relevant content of Electron custom protocol

**Comment by LexDevelp** [comment]
> * For assets handling in the renderers, please refer to the [vite guide](https://vitejs.dev/guide/assets.html).
> * For assets handling in main process, please refer to the [electron-vite guide](https://electron-vite.org/guide/assets).
> * For localized resource processing, it is recommended that you read the relevant content of Electron custom protocol

Hola! muchisimas gracias por responder!, me tomó varios días llegar al resultado por eso tarde en responder, no soy muy bueno en JS, pero pude cargarlo tal como necesitaba
