### ISSUE TITLE
不支持渲染进程中调用内置模块（ipcRenderer）

### ISSUE THREAD

**Issue by liuyike98** [alex8088/electron-vite#52]
### Describe the bug

创建新项目,在vite config中配置了：
```
renderer: {
    build: {
      rollupOptions: {
        external: ['path', 'fs', 'electron'],
      },
    },
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src'),
      },
    },
    plugins: [vue()],
  },
```

在创建窗口时，开启过了node支持，关闭了sandbox，
```
webPreferences: {
      preload: path.join(__dirname, '../preload/index.js'),
      sandbox: false,
      nodeIntegration: true,
      contextIsolation: false,
      webSecurity: false,
      webviewTag: true,
    },
```

在渲染进程中调用ipcrenderer
```
import { ipcRenderer } from 'electron';
ipcRenderer.send('test');
```

报错:
![image](https://user-images.githubusercontent.com/87092276/200477947-d40d25d8-384a-4d44-98e8-90f6d401c5b3.png)

如果出于安全原因，就不应该启用nodeIntegration，而如果启用了nodeIntegration，再通过preload加载，觉得也是没有意义的，安全系数只有0和1，0.9和0.1我觉得是没有什么区别的，而且有些工具项目根本不在乎这些，而是开发效率优先，所以有必要支持（别人可以不用，但不能没有哈哈哈）

查了下资料，不知道是否和这个原因相同，对vite用的也不多：https://zhuanlan.zhihu.com/p/540056695

看到之前有人提这个相同问题issue，解决方案就是你让他用preload，不过我还是觉得是有必要支持

### Electron-Vite Version

latest

### Electron Version

latest

### Vite Version

latest

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JangTaewan** [comment]
同样的问题欸。。

**Comment by liuyike98** [comment]
> 同样的问题欸。。

没得办法，等作者回复一下

**Comment by alex8088** [comment]
不去支持渲染进程使用node模块，除了不安全（当然很多人不在意）之外，另外还有几点原因：

1. 保持良好的开发习惯，这一点需要开发者对electron的架构有清晰的了解，electron 同时存在两种环境，node和browser，主进程和渲染进程运行在node环境（构建标准是cjs），而渲染进程则是browser环境（构建标准是iife或者umd）。开启node集成下，在渲染进程开发中，进行混合式的开发（即夹杂着web开发的代码又有node的代码），我想这并不是很好的习惯。我认为渲染进程开发应该和我们普通的web开发一样，而使用node的能力，就像平时调接口一样，而在electron中调的是ipc。即使最终抛离electron，渲染进程的代码仍然可以使用。并且混合开发也不利于代码逻辑的优化，这要求开发者对node和web开发具备相当能力，才能避免各种奇怪的问题。
2. 对于开发效率问题，我认为在了解electron架构原理下，开发效率比混合式更好。同时，我在脚手架下内置了[@electron-toolkit/preload](https://github.com/alex8088/electron-toolkit/tree/master/packages/preload), 来暴露electron渲染进程中常用的api，也很好的解决开发者使用ipc的问题，开发者没有任何使用负担，当然这也是牺牲一定安全性的权衡。
3. 我认为一个好的构建工具，除了开发体验上的努力外，帮助开发者更好了解electron架构，养成好的开发方式也是很有必要的

产生现在很多开发者有这样的开发方式，也是早期electron实践带来的问题，到目前electron想纠正回来地，都很困难。

当然要支持渲染进程使用node模块也不是做不到，就像你贴出来的链接一样，通过插件将相关node模块进行重新导出处理。

不知道我解析是否清楚，或者有什么想法可以进一步交流

我推荐了解一下库[@electron-toolkit/preload](https://github.com/alex8088/electron-toolkit/tree/master/packages/preload),应该可以解决一些问题。

**Comment by liuyike98** [comment]
> 1. ，而渲染进程则是browser环境（

我仍然认为作为样板工程不能限制开发者使用electron本身具备的能力，应该给出选择的方式，两者如何抉择应该取决于开发者本身，而不是强制要求不允许在渲染进程中使用node

其次我认为之前官网提到的
```
rollupOptions: {
        external: ['path', 'fs', 'electron'],
      },
```
不能解决问题，既然已经提到了，所以我认为这是一个bug

**Comment by alex8088** [comment]
并不是不能使用，而是使用方式

**Comment by liuyike98** [comment]
> 并不是不能使用，而是使用方式的改变

有些窗口并不需要做这么多限制，自由就好，本身electron也是给出了开关选择的，
所以不使用preload的情况下，是不行的对吧？有计划支持吗？没办法的话只能先用草鞋的脚手架，过阵子再来了哈哈

**Comment by liuyike98** [comment]
> 并不是不能使用，而是使用方式的改变

其次，通过
```
const ipcRenderer = require('electron').ipcRenderer;
```
是可以直接使用的，也就是说这明明就是vite打包的问题，而不是...

**Comment by alex8088** [comment]
preload不是必须，也可以多窗口共用。如果渲染进程全程用cjs标准开发，也就不用构建工具了，这本身也在于你是用esm来开发，还是两者混合，而后两者都需要构建工具解析，增加插件或者内置解析，这是构建标准的问题而不是打包问题。目前没有打算支持这种开发方式，待后续有时间可以增加插件支持。

**Comment by liuyike98** [comment]
> preload不是必须，也可以多窗口共用。如果渲染进程全程用cjs标准开发，也就不用构建工具了，这本身也在于你是用esm来开发，还是两者混合，而后两者都需要构建工具解析，增加插件或者内置解析，这是构建标准的问题而不是打包问题。目前没有打算支持这种开发方式，待后续有时间可以增加插件支持。

通过一个插件（https://www.npmjs.com/package/vite-plugin-commonjs-externals）解决了，感谢作者回复，也希望有可能大佬以后内置一个插件

**Comment by alex8088** [comment]
@liuyike98 :handshake: 我也学习一下，这个插件看起来是靠谱的，后续也可以参考，谢谢
