### ISSUE TITLE
Multiple issues building project

### ISSUE THREAD

**Issue by krystianotto** [alex8088/electron-vite#524]
### Describe the bug

I have a few issues moving from webpack to vite.
First, one of my dependencies has a dynamic import defined like this:

```jsx
function getNativeNode(){
  return require("./build/package/module.node");
}
```

I then import it as follows:

```jsx
import { getNativeNode } from 'test-module';
```

When I run `electron-vite build` I get an error:

```
[vite:node-asset] Could not load C:/Users/krystian/Desktop/test/main/node_modules/test-module/build/package/module.node?commonjs-proxy (imported by main/node_modules/test-module/index.js): The argument 'path' must be a string or Uint8Array without null bytes. Received '\\x00C:/Users/krystian/Desktop/test/main/node_modules/test-module/build/package/module.node'
TypeError [PLUGIN_ERROR]: Could not load C:/Users/krystian/Desktop/test/main/node_modules/test-module/build/package/module.node?commonjs-proxy (imported by main/node_modules/test-module/index.js): The argument 'path' must be a string or Uint8Array without null bytes. Received '\\x00C:/Users/krystian/Desktop/test/main/node_modules/test-module/build/package/module.node'
    at open (node:internal/fs/promises:586:10)
    at Object.readFile (node:internal/fs/promises:1025:20)
    at Object.load (file:///C:/Users/krystian/Desktop/test/node_modules/electron-vite/dist/chunks/lib-iT7MOERj.mjs:634:47)
    at Object.handler (file:///C:/Users/krystian/Desktop/test/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:68900:19)
    at file:///C:/Users/krystian/Desktop/test/node_modules/rollup/dist/es/shared/node-entry.js:19774:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Users/krystian/Desktop/test/node_modules/rollup/dist/es/shared/node-entry.js:19674:28)
    at async file:///C:/Users/krystian/Desktop/test/node_modules/rollup/dist/es/shared/node-entry.js:18845:33
    at async Queue.work (file:///C:/Users/krystian/Desktop/test/node_modules/rollup/dist/es/shared/node-entry.js:19884:32)

```

Since I'm able to maintain this dependency I can actually change it to:

```jsx
const path = require('path');

function getNativeNode(){
  return require(path.resolve(__dirname, "./build/package/module.node"));
}

```

It works, but only because I can change the code, which is not pleasant.
Unfortunately, there is now another error regarding dynamic import.
<img width="374" alt="Screenshot 2024-06-03 140229" src="https://github.com/alex8088/electron-vite/assets/47112115/773ecb24-e215-4b89-b727-89dbcabba01d">

I was able to fix this by moving this dependency to the root package.json, but again this is not desirable.
After fixing these two dependencies manually, another problem appeared after packaging the application with electron-builder:
<img width="372" alt="Screenshot 2024-06-03 140507" src="https://github.com/alex8088/electron-vite/assets/47112115/132da147-eb41-4c42-835a-6f71ac2e3f91">

Here is [repo](https://github.com/krystianotto/test-electron-vite) to reproduce the issues.

### Electron-Vite Version

2.2.0

### Electron Version

25.9.8

### Vite Version

5.12.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Since you installed the module through the github address, the module is not recognized by the `externalizeDep` plugin. You can externalize `test-module` by specifying it via the `include` option of the `externalizeDeps` plugin.

https://electron-vite.org/guide/dev#dependencies-vs-devdependencies

**Comment by krystianotto** [comment]
@alex8088 it still shows `module not found` after I pack the application using electron-builder. Any idea why that is?

**Comment by alex8088** [comment]
How did you configure it?

**Comment by krystianotto** [comment]
Here: https://github.com/krystianotto/test-electron-vite/blob/master/main/electron-builder.config.js

**Comment by alex8088** [comment]
Your electron-vite config

**Comment by alex8088** [comment]
```js
export default defineConfig(() => {
  return {
    main: {
      plugins: [
        externalizeDepsPlugin({ include: ['test-module'] }),
      ],
      ...
    },
    ...
});
```

**Comment by krystianotto** [comment]
@alex8088  Yes - I have already done it, but after `npm package` when I run the application I get the error from the last screenshot attached in the description :/ I wonder if that's an issue with Vite or electron-builder.

**Comment by alex8088** [comment]
You should move your electron-builder config file to project root dir.

**Comment by krystianotto** [comment]
I was able to make it work by adding this code to electron-builder:
`files: ["node_modules/test-module/**/*"]`
To be fair I'm not too fond of this approach and don't get why it is necessary to move this dependency manually with electron-builder
