### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by NWYLZW** [alex8088/electron-vite#528]
### Describe the bug

```text
failed to load config from /Users/yijie/codes/projects/spirit/electron.vite.config.ts
error during start dev server and electron app:
/Users/yijie/codes/projects/spirit/node_modules/.pnpm/vite-plugin-glob-accept@0.1.0_@types+node@18.19.33_sass@1.77.2/node_modules/vite-plugin-glob-accept/dist/index.esm.js:1
import { posix, isAbsolute } from 'node:path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

https://github.com/alex8088/electron-vite/blob/1838bdbf3ee91e5a0cd39840190ad2506edfd583/src/utils.ts#L78
```
 if (/\.m[jt]s$/.test(filePath)) {
```

Remove ts extension check, it can't be load esm when use ts extension.

### Electron-Vite Version

2.2.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
`vite-plugin-glob-accept` plugin problem, `"type": "module"` is not specified in package.json or name `index.esm.js` into `index.esm.mjs`.

**Comment by NWYLZW** [comment]
> `vite-plugin-glob-accept` plugin problem, `"type": "module"` is not specified in package.json or name `index.esm.js` into `index.esm.mjs`.

I feel there's a bit of an issue. Why is it that even after setting up `exports` and `module`, it still continues to load as CommonJS (CJS), resulting in the outside module problem?

I'll take another look at the specific standards and behavior. I feel that directly assuming a file with a `.ts` extension to be ESM seems a bit strange.

**Comment by NWYLZW** [comment]
https://github.com/NWYLZW/recurrent-vite-config-load-ts/blob/0a7564a7bdc5febf38c857983829dacd158662c6/vite.config.ts#L1-L8

Directly using vite.config.ts seems to be fine, but as for the loading mechanism, I still think it is inappropriate to assume that ts is esm.

<img width="1223" alt="image" src="https://github.com/alex8088/electron-vite/assets/51358815/224a38a0-86cd-419f-8aeb-fdc5abe404f0">

**Comment by NWYLZW** [comment]
Directly using vite.config.ts seems to be fine.

https://github.com/NWYLZW/recurrent-vite-config-load-ts/blob/239ab1c7ca7e80fc3b690250a70e0c78f571ecfc/vite.config.ts#L1-L8

<img width="1212" alt="image" src="https://github.com/alex8088/electron-vite/assets/51358815/28040feb-82af-46e7-a02d-733a0864b5cf">

**Comment by alex8088** [comment]
> Directly using vite.config.ts seems to be fine.
> 
> https://github.com/NWYLZW/recurrent-vite-config-load-ts/blob/239ab1c7ca7e80fc3b690250a70e0c78f571ecfc/vite.config.ts#L1-L8
> 
> <img alt="image" width="1212" src="https://private-user-images.githubusercontent.com/51358815/337960086-28040feb-82af-46e7-a02d-733a0864b5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzUzNTgsIm5iZiI6MTcxNzkzNTA1OCwicGF0aCI6Ii81MTM1ODgxNS8zMzc5NjAwODYtMjgwNDBmZWItODJhZi00NmU3LWEwMmQtNzMzYTA4NjRiNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEyMTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NTk3ZGVhMTdiZjRlYmE2OGY5MDdiZjc4MmE2OGQzOWY2MTk4MzBhMjA3ZWRkYzMwYTZiNTJkMmZiNjA1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uLO9OBj0BvKhVZMcbpj6HJsQtBS9ll_Y9IHtsJZcAMY">

this way will use `commonjs` module. Try to add `"type": "module"` to your `package.json` will get the error.

**Comment by NWYLZW** [comment]
You are right.
