### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by fy5220** [alex8088/electron-vite#53]
### Describe the bug

您好,请教下,我在使用您的框架学习开发桌面端.有个导入excel的功能.我是使用了xlsx在主进程读取.然后再mac windows上 dev preview都可以正常运行.但是windows打包后.报错cannot find module 'xlsx'我也搜了相似的问题,也写了排除依赖配置,但是还是一样的报错.也提前执行了build命令后再打包.感激不尽.
![Snipaste_2022-11-10_16-55-20](https://user-images.githubusercontent.com/7485564/201047069-737e647e-7829-4b71-a57e-bc6fcb0cc6b2.png)
![Snipaste_2022-11-10_16-54-47](https://user-images.githubusercontent.com/7485564/201047092-64f417be-9051-482a-9674-0c64f201adb9.png)

### Electron-Vite Version

1.0.12

### Electron Version

21.2.0

### Vite Version

3.1.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by fy5220** [comment]
另外我在渲染进程中也需要xlsx去导出excel

**Comment by alex8088** [comment]
你将xlsx安装成devDep？electron-builder的配置？

**Comment by fy5220** [comment]
是安装成devDep 然后electron-build的配置只改了一个
`extraResources: [
    # Server
    { from: 'server', to: '../server' }
  ]`这个 其他都是自动生成的那些

**Comment by alex8088** [comment]
安装成deps，这样electron-builder 才能打包进去

**Comment by alex8088** [comment]
支持browser环境就可以

**Comment by fy5220** [comment]
再次感谢大佬
