### ISSUE TITLE
Setting the mode in the configuration file does not work

### ISSUE THREAD

**Issue by krystianotto** [alex8088/electron-vite#531]
### Describe the bug

I would like to set the vite mode in the configuration file as follows, but it seems that this does not work for electron-vite

```javascript
export default defineConfig(() => {
  main: {
    mode: 'sandbox' <-- this doesn't work, it starts the app with development mode
  }
}
```

### Electron-Vite Version

2.1.0

### Electron Version

25.9.8

### Vite Version

5.2.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by krystianotto** [comment]
Hi @alex8088, any update on this?

**Comment by alex8088** [comment]
https://electron-vite.org/guide/cli 

```sh
electron-vite dev --mode sandbox
```

**Comment by krystianotto** [comment]
@alex8088 I realize this, but shouldn't it also work from the configuration file if vite allows you to manually override the mode?
I would like to set the mode based on variables, for example, as follows:

```javascript
export default defineConfig(() => {
  main: {
    mode: process.env.MODE <-- this doesn't work, it starts the app with development mode
  }
}
```

**Comment by krystianotto** [comment]
@alex8088 I tested this on Vite and it works as expected. `import.meta.env.MODE` returns the value I set in the `mode` field in the configuration file.

**Comment by krystianotto** [comment]
Hi @alex8088, can I expect my fix to be reviewed soon? It's a blocker for me at the moment. Thanks!

**Comment by alex8088** [comment]
@krystianotto release soon

**Comment by scottcorgan** [comment]
@alex8088 When can we expect a release for this? Thanks!
