### ISSUE TITLE
external: ['puppeteer']没有效果

### ISSUE THREAD

**Issue by wumingluren** [alex8088/electron-vite#537]
### Describe the bug

使用puppeteer打包后运行软件报错，搜到一些方法说打包的时候进行排除。
但是添加了这个配置打包的时候还是没有效果。
使用的pnpm 安装到 dependencies
```
main: {
    build: {
      rollupOptions: {
        external: ['puppeteer']
      }
    },
  }
```

### Electron-Vite Version

最新

### Electron Version

最新

### Vite Version

最新

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
此功能为外化模块，无具体错误信息。
