### ISSUE TITLE
How to Pass --owepm-packages-url Argument to electron-vite with ow-electron Fork

### ISSUE THREAD

**Issue by santiarr** [alex8088/electron-vite#538]
### Describe the bug

I'm currently working on an Electron app using the ow-electron fork and electron-vite. ow-electron is a fork of electron specifically designed for Overwolf applications. I need to pass the --owepm-packages-url=https://electronapi-qa.overwolf.com/packages argument to electron-vite.

I followed the documentation but keep encountering the following error:

```
(node:1484)` UnhandledPromiseRejectionWarning: game 21640 not supported
(Use `electron --trace-warnings ...` to show where the warning was created)
```

I have verified that the sample app works correctly with this URL. You can find the sample app [here](https://github.com/overwolf/ow-electron-packages-sample).

Steps to Reproduce:

Clone my repository.
Update package.json to include the following start script:

```
"scripts": {
  "start": "electron-vite dev --owepm-packages-url=https://electronapi-qa.overwolf.com/packages"
}
```
Run the application using yarn start.

Expected Behavior:
The application should start without errors, and the --owepm-packages-url argument should be correctly passed to electron-vite.

Actual Behavior:
The application fails with the error:

```
(node:1484) UnhandledPromiseRejectionWarning: game 21640 not supported
(Use `electron --trace-warnings ...` to show where the warning was created)
```

Additional Context:

This issue is not a bug but more of a question about how to use electron-vite with a fork and pass arguments correctly.
I have tested the URL with the sample app provided by Overwolf, and it works correctly there.

Here is the link to the sample app: [ow-electron-packages-sample](https://github.com/overwolf/ow-electron-packages-sample).
Environment:

electron-vite version:  2.2.0
ow-electron version: 28.3.2
Operating System: Windows 11
package manage: yarn

### Electron-Vite Version

2.2.0

### Electron Version

n/a

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/dev#passing-arguments-to-electron-app

**Comment by santiarr** [comment]
> https://electron-vite.org/guide/dev#passing-arguments-to-electron-app

I tried this but I guess it's more of an overwolf issue, anyway to use @overwolf/ow-electron instead of electron? Right now I am using a yarn patch.
