### ISSUE TITLE
electron-vite dev redirects

### ISSUE THREAD

**Issue by logan064** [alex8088/electron-vite#543]
### Describe the bug

Whenever I run npm run dev it works initially, but once I update a file it then redirects the http address to the development server to https. This causes the HMR update to fail, so how can I disable the http -> https redirect?

My application does reach put to some https backend endpoints, which I think is why it fails when reaching out to an http endpoint after it begins trusting my systems CAs.

### Electron-Vite Version

2.0.0

### Electron Version

28.3.3

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://vitejs.dev/config/server-options.html#server-https

A plugin [@vitejs/plugin-basic-ssl](https://github.com/vitejs/vite-plugin-basic-ssl) may be able to help you.

**Comment by logan064** [comment]
I was able to get this to work
