### ISSUE TITLE
undefind is not a function

### ISSUE THREAD

**Issue by HAnshu47** [alex8088/electron-vite#548]
### Describe the bug

electron-vite.config中使用import {  bytecodePlugin } from 'electron-vite'方式引入bytecodePlugin做源代码加密，在electron打包window低版本时需要将electron降级到23以下，我们选择了21版本，报错如下，bytecode-loader.cjs加载报错，如果注释掉全文引用的bytecodePlugin就可以正常打包使用，是electron-vite版本不兼容吗
<img width="560" alt="image" src="https://github.com/alex8088/electron-vite/assets/53853575/ea97b8e8-2e0f-482e-b05d-8af9e25a8cb0">

<img width="260" alt="image" src="https://github.com/alex8088/electron-vite/assets/53853575/b96c64c2-3271-4bb5-aa50-09605fb469d2">

### Electron-Vite Version

2.3.0

### Electron Version

21.4.4

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
这是代码错误，取消加密保护，找到代码错误位置
