### ISSUE TITLE
main use nestjs is error，how can i use nestjs in electron-vite

### ISSUE THREAD

**Issue by LiFuHai1106** [alex8088/electron-vite#55]
### Describe the bug

![e3c113df68c225587e7937458640310](https://user-images.githubusercontent.com/57932634/201529068-eb514fe2-baf7-47bc-b2fe-191e424928d2.png)

 "dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "@electron-toolkit/preload": "^1.0.2",
    "@electron-toolkit/utils": "^1.0.2",
    "ant-design-vue": "^3.2.15",
    "@nestjs/axios": "^1.0.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "axios": "^1.1.3",
    "dayjs": "^1.11.6"
  },
  "devDependencies": {
    "@electron-toolkit/tsconfig": "^1.0.1",
    "@rushstack/eslint-patch": "^1.2.0",
    "@types/node": "16.11.22",
    "@vitejs/plugin-vue": "^3.1.2",
    "@vue/eslint-config-typescript": "^11.0.2",
    "electron": "^20.3.1",
    "electron-builder": "^22.14.13",
    "electron-notarize": "^1.2.1",
    "electron-vite": "^1.0.10",
    "eslint": "^8.24.0",
    "eslint-plugin-vue": "^9.6.0",
    "less": "^4.1.3",
    "typescript": "^4.7.4",
    "vite": "^3.1.6",
    "vue": "^3.2.40",
    "vue-tsc": "^0.40.13"
  }

### Electron-Vite Version

 "electron-vite": "^1.0.10",

### Electron Version

 "electron": "^20.3.1",

### Vite Version

"vite": "^3.1.6",

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
your config ?

**Comment by alex8088** [comment]
you can update to ver 1.0.14, use `externalizeDepPlugin` to externalize deps and support for `TypeScript decorators`.

**Comment by alex8088** [comment]
@LiFuHai1106 You need to install `@nestjs/websockets` which  is the peer deps for `@nestjs/core`

**Comment by LiFuHai1106** [comment]
> externalizeDepPlugin

感谢大佬，加了externalizeDepPlugin就好了。不过还有个小问题
![9b93e218b0d57cf2123636727a005ce](https://user-images.githubusercontent.com/57932634/201530545-7c6659f7-1a61-42e1-9229-06e853ccce91.png)

**Comment by LiFuHai1106** [comment]
(method) AppController.getHello(): string
对修饰器的实验支持功能在将来的版本中可能更改。在 "tsconfig" 或 "jsconfig" 中设置 "experimentalDecorators" 选项以删除此警告。ts(1219)

**Comment by alex8088** [comment]
因为你写的并不是ts, 所以这样地配置没有用，但jsconfig我了解。关于装饰器你可以阅读一下文档 https://cn-evite.netlify.app/guide/typescript-decorator.html

**Comment by LiFuHai1106** [comment]
> 因为你写的并不是ts, 所以这样地配置没有用，但jsconfig我不了解。关于装饰器你可以阅读一下文档 https://cn-evite.netlify.app/guide/typescript-decorator.html

加swcPlugin可以了！！感谢感谢

**Comment by alex8088** [comment]
如果你感兴趣可以加入群聊参与交流
