### ISSUE TITLE
Building with worker threads results in error from the worker, 'cannot find electron'

### ISSUE THREAD

**Issue by stuartambient** [alex8088/electron-vite#556]
### Describe the bug

I've been running these in development for a while and they run correct.  In my packaged app I get `MODULE_NOT_FOUND` when attempting to run the scripts.

```
requireStack: Array(2), name: 'Error', message: "Cannot find module 'electron'\nRequire stack:\n- C:\\…s\\app.asar\\out\\main\\updateFilesWorker.b4a10f6f.js'
code "MODULE_NOT_FOUND".....
```

**In my main/index.js this is a snippet of how I kick off the worker -** 

```
ipcMain.handle('update-files', async (event) => {
  runWorker(createUpdateFilesWorker)
    .then((result) => {
      console.log('Worker completed successfully:', result);
      console.log('Running subsequent code after worker completion.');
      return mainWindow.webContents.send(
        'file-update-complete',
        getObjectWithLengths(result.result)
      );
    })
    .catch((error) => {
      console.error('Worker encountered an error:', error);
      console.log('Handling subsequent code after worker error.');
    });
});
```

**The runWorker.js I use in various handlers to send (right now 2) different scripts to the worker -** 

```
import createUpdateTagsWorker from './updateTagsWorker?nodeWorker';
import createUpdateFilesWorker from './updateFilesWorker?nodeWorker';

const runWorker = (createWorkerFn, msg) => {
  return new Promise((resolve, reject) => {
    const worker = createWorkerFn(msg);

    // Handle messages from the worker
    worker.on('message', (result) => {
      console.log('Result, result);
      if (result.error) {
        reject(new Error(result.error));
      } else {
        resolve(result);
      }
    });

    // Handle errors from the worker
    worker.on('error', (err) => {
      console.error('Worker error:', err);
      reject(err);
    });

    // Handle worker exit
    worker.on('exit', (code) => {
      if (code !== 0) {
        const errorMessage = `Worker stopped with exit code ${code}`;
        console.error(errorMessage);
        reject(new Error(errorMessage));
      }
    });

    // Start the worker
    worker.postMessage(msg);
  });
};

export default runWorker;
```

**to save space I'll just post the relevant part of a script -**

```
parentPort.on('message', async (/* message */) => {
  try {
    const result = await processFiles();
    parentPort.postMessage({ result });
  } catch (error) {
    parentPort.postMessage({ error: error.message });
  }
});
```

I've gone through the worker example and outside of me not using typescript I'm not finding anything different. 

I posted this as a question in the discussions area but it seems there hasn't been any discussion there as of late I needed to raise this issue here.

### Electron-Vite Version

1.0.29

### Electron Version

20.3.2

### Vite Version

3.1.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
This doesn't seem to be a worker problem. You should not use the Electron module in worker and your can only use the nodejs module.

**Comment by stuartambient** [comment]
Not sure where I'm using the Electron module,  you referring to the 'mainWindow.webContents.send' ?

**Comment by stuartambient** [comment]
Different error - 'the path argument must be of type string. Received undefined. 
I cloned the worker example and went over it repeatedly.  Not seeing where my error could be , maybe a bug in Vite ?

**Comment by alex8088** [comment]
I think it is still necessary to check whether the electron module is referenced. You can try upgrading electron-vite to enjoy a better way of using work. 
- https://electron-vite.org/guide/dev#worker-threads
- https://github.com/alex8088/electron-vite-worker-example

**Comment by stuartambient** [comment]
Thank you! I finally figured the problem just not the solution.  The script I'm passing has 1/2 dozen imports, a few npm packages and some scripts.  I'm guessing I need some additional lines in editor-builder.yml / electron-vite.config.

Anyway, yes, I scaffold the latest into another project.  Once I get passed this issue I'll consider upgrading this project.  Electron always concerns me more when upgrading.

If you don't mind I'll close this out once I fix things.

**Comment by stuartambient** [comment]
So in my worker script I have these imports - 

```
import { parentPort, workerData, isMainThread } from 'worker_threads';
import fg from 'fast-glob';
import { parseMeta } from './utility/index.js';
import { v4 as uuidv4 } from 'uuid';
import {
  roots,
  playlistExtensions,
  audioExtensions,
  fileExtensions
} from '../constant/constants.js';

import { getFiles, insertFiles, deleteFiles } from './sql.js';
```

Including 1 or all throw errors and the worker exits.

I commented them out and just created a simple function for the worker to perform.  It worked.  So my question if anyone knows how to get those imports working ? The imports are in the out/build/chunk files so it must be worker_thread related. I tried adding those packages to asarUnpack but that didn't help.  

I put the worker itself in ```
rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.js'),
          updateFilesWorker: resolve(__dirname, 'src/main/updateFilesWorker.js')
        }
      }
```
I don't think the file needs that though as it shows up in the chunks dir anyway.
