### ISSUE TITLE
Why main build config must it be build.lib but not rollupOptions.input?

### ISSUE THREAD

**Issue by WhiteMinds** [alex8088/electron-vite#56]
### Clear and concise description of the problem

preload build config can use rollupOptions.input, why not main?

I can't use build.lib, because it cannot be used together for [build.assetsInlineLimit](https://vitejs.dev/config/build-options.html#build-assetsinlinelimit ).

### Suggested solution

remove this limit.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
what is your electron -vite ver ?  You can use `rollupOptions.input`. e.g. https://github.com/alex8088/electron-vite-worker-example/blob/master/electron.vite.config.ts

**Comment by WhiteMinds** [comment]
> what is your electron -vite ver ? You can use `rollupOptions.input`. e.g. https://github.com/alex8088/electron-vite-worker-example/blob/master/electron.vite.config.ts

Just now I was using 1.0.12, and now I have upgraded to 1.0.14 and no longer have this problem 😆
