### ISSUE TITLE
集成puppeteer-core后，打包后运行报错

### ISSUE THREAD

**Issue by zmm2tysu** [alex8088/electron-vite#563]
### Describe the bug

仅安装puppeteer-core在dependencies中可以正常运行，放开在主进程中相关puppeteer代码，打包运行就报错

![image](https://github.com/user-attachments/assets/5aff0a9e-0fe7-499c-994f-5da2c8374938)

![image](https://github.com/user-attachments/assets/8fc9a215-2e7a-4688-8e9a-0bbf630bca40)
![image](https://github.com/user-attachments/assets/f8e75713-dbe4-4cdd-9d61-10b50d72337b)

### Electron-Vite Version

^2.2.0

### Electron Version

^28.3.1

### Vite Version

^5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
```yml
asarUnpack:
  - resources/**
  - node_modules/puppeteer/**
  - node_modules/puppeteer-core/**
```

尝试不asar puppeteer-core

**Comment by zmm2tysu** [comment]
> ```yaml
> asarUnpack:
>   - resources/**
>   - node_modules/puppeteer/**
>   - node_modules/puppeteer-core/**
> ```
> 
> 尝试不asar puppeteer-core

尝试过这个的

**Comment by zmm2tysu** [comment]
https://github.com/zmm2tysu/electron-p-demo.git
建了个最小复现的项目，quick-start后集成了puppeteer-core和相关代码

**Comment by alex8088** [comment]
安装到 devDeps 让 electron-vite 重新构建它

**Comment by zmm2tysu** [comment]
开启bytecodePlugin后，安装到devDeps会报错
![image](https://github.com/user-attachments/assets/fd96c1e7-1d1d-4e1a-9567-ef627830ec09)

**Comment by alex8088** [comment]
自定义该模块不字节码不加密

**Comment by zmm2tysu** [comment]
我先去掉了字节码加密打包成功，也能运行起来。但是相关puppeteer功能没有生效，我在node_modules里也没看到这个包了

**Comment by axssbug** [comment]
请教一下，咋解决的，同意的问题，devDeps加了，也没有效果

**Comment by wumingluren** [comment]
怎么解决的？我之前也有一样的问题

**Comment by zmm2tysu** [comment]
@wumingluren @axssbug 降puppeteer-core版本到19.11.1解决的

**Comment by axssbug** [comment]
> @wumingluren @axssbug 降puppeteer-core版本到19.11.1解决的
感谢
