### ISSUE TITLE
Can't `main.build.outDir` support the  '-' character?

### ISSUE THREAD

**Issue by newproplus** [alex8088/electron-vite#564]
### Describe the bug

```ts
// electron.vite.config.ts
import { defineConfig } from 'electron-vite'

export default defineConfig(({ command, mode }) => {
	return {
		main: {
			build: {
				outDir: 'dist-electron', // dist-electron not works, but distelectron or dist_electron works
				lib: {
					entry: 'src-electron/main.ts',
					formats: ['es'],
				},
			},
		},
		preload: {
			build: {
				outDir: 'dist-electron', // dist-electron works, distelectron and dist_electron also works
				lib: {
					entry: 'src-electron/preload.ts',
					formats: ['es'],
				},
			},
		},
	}
})
```
In this configuration file, `main.build.outDir` cannot be set to 'dist-electron' as it does not work, but it can be set to 'distelectron' or 'dist_electron'. Additionally, the value of 'preload.build.outDir' can accept all three: 'dist-electron', 'distelectron', and 'dist_electron'.

Can't `main.build.outDir` support the  '-' character?

### Electron-Vite Version

2.3.0

### Electron Version

31.2.0

### Vite Version

5.3.3

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
dist-electron/main dist-electron/preload
