### ISSUE TITLE
使用bytecodePlugin组件混淆代码后，打包出来的asar资源包，解包之后out\renderer\assets还是包含js源代码 

### ISSUE THREAD

**Issue by haolibote** [alex8088/electron-vite#567]
### Describe the bug

![图片](https://github.com/user-attachments/assets/e220810c-2b88-40a2-aa10-4dd064381449)
electron.vite.config.js
![图片](https://github.com/user-attachments/assets/b31320bf-70d9-40da-a7b8-b2ef3a71c603)

这个useCounterStore是在 src/main/stores/counter.js下的

### Electron-Vite Version

2.3.0

### Electron Version

31.0.2

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
渲染进程不支持字节码保护，字节码保护当前只支持主进程和预加载脚本，相关请阅读文档 [(https://electron-vite.org/guide/source-code-protection)

**Comment by NotYoojun** [comment]
有考虑后续添加对渲染进程的字节码添加支持吗？
