### ISSUE TITLE
react-ts 模板  playwright 无法选取到元素

### ISSUE THREAD

**Issue by sunyongming** [alex8088/electron-vite#569]
### Describe the bug

react-ts 模板  playwright 无法选取到元素

```ts
const api = {
  async test(): Promise<void> {
    const browser = await chromium.launch({
      headless: false
    })
    const context = await browser.newContext({
      viewport: { width: 1500, height: 1080 }
    })
    const page = await context.newPage()
    await page.goto('https://www.baidu.com/')
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(500)
    await page.fill('#kw', '1212')
  }
}
```
![image](https://github.com/user-attachments/assets/892fc2f2-5c5b-451e-b2b3-f45e69285636)

这里是最小复现：https://github.com/sunyongming/electron-app.git

electron-forge vite-typescript 模板项目内，playwright可以成功选取到元素

### Electron-Vite Version

2.3.0

### Electron Version

31.0.2

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
无相关代码
