### ISSUE TITLE
引入nestjs带参数声明报错

### ISSUE THREAD

**Issue by LiFuHai1106** [alex8088/electron-vite#57]
### Describe the bug

(@Res() res: Response, @Req() req: Request)报错，(@Res() res, @Req() req)正常[](url)[](url)
![image](https://user-images.githubusercontent.com/57932634/201685162-f0199bbf-b1b9-4c45-9efe-42960571db4d.png)

[electron-app.zip](https://github.com/alex8088/electron-vite/files/10003857/electron-app.zip)

### Electron-Vite Version

"electron-vite": "^1.0.14",

### Electron Version

"electron": "^20.3.1",

### Vite Version

"vite": "^3.1.6",

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
:x:   `import { Response, Request } from 'express'; `

此处 Response, Request 不是类型

-> install `@types/express`

`import type { Response, Request } from 'express'; `
