### ISSUE TITLE
360误杀

### ISSUE THREAD

**Issue by MasterWWW** [alex8088/electron-vite#571]
### Describe the bug

每次安装都会被360 软件误杀，这个怎么处理

### Electron-Vite Version

2.3.0

### Electron Version

31.0.2

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
对于流氓软件无解，设置白名单或者提交给360认证。最好的方式就是卸载360。

**Comment by MasterWWW** [comment]
eletron 目前都会这样吗？感觉这个东西难顶

**Comment by alex8088** [comment]
我想这与electron无关，而是360流氓
