### ISSUE TITLE
使用electron版本为31.1.0时打开选择文件或者是选择文件夹的时候使用默认地址无效

### ISSUE THREAD

**Issue by Devil-AL** [alex8088/electron-vite#572]
### Describe the bug

使用electron版本为31.1.0时打开选择文件或者是选择文件夹的时候使用默认地址无效

### Electron-Vite Version

2.0.0

### Electron Version

31.1.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
此问题应该在electron项目反馈
