### ISSUE TITLE
关于 webstorm 调试命令的问题.

### ISSUE THREAD

**Issue by semanticDao** [alex8088/electron-vite#579]
### Describe the bug

关于调试文档部分.
直接使用 --sourcemap --remote-debugging-port=9222  
webstorm会忽略掉整个参数.
需要使用 -- --sourcemap --remote-debugging-port=9222

### Electron-Vite Version

V2.3.0

### Electron Version

v31.3.1

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Documentation updated.
