### ISSUE TITLE
打包成windows安装包一直报错，这个应该怎么解决

### ISSUE THREAD

**Issue by sunlight-lg** [alex8088/electron-vite#583]
### Describe the bug

![image](https://github.com/user-attachments/assets/b262fff7-db82-4805-8bd1-b1fb6d157d45)
![image](https://github.com/user-attachments/assets/ddf444bf-da67-4b9a-b841-a0fab5b7b384)
bu不管是怎么修改和更换镜像地址一直还是这个错误无法解决，麻烦帮忙看看这个怎么解决

### Electron-Vite Version

electron-vite-vue

### Electron Version

31.3.1

### Vite Version

5.4.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
与配置无关，确保你的账户有权限，尝试关闭杀毒软件。

**Comment by cyrna** [comment]
请问你解决了吗？我也遇到同样的问题
