### ISSUE TITLE
Invailed or incompatible cached data (cachedDataRejected)

### ISSUE THREAD

**Issue by alicestoneprod** [alex8088/electron-vite#586]
### Describe the bug

![image](https://github.com/user-attachments/assets/fb334d50-7fcc-4c71-b4e2-a2679b280f7c)
import { defineConfig, externalizeDepsPlugin, bytecodePlugin } from "electron-vite"

main: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin()],
  },
  
  
node 20.10.0

### Electron-Vite Version

^2.3.0

### Electron Version

^31.0.2",

### Vite Version

^5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/troubleshooting#a-javascript-error-occurred-in-the-main-process-error-invaild-or-incompatible-cached-data-cacheddatarejected

**Comment by alicestoneprod** [comment]
I changed electron version, also changed node.js version and it got good compile.
