### ISSUE TITLE
react-router-dom works in development but it  doesn't work for window compiled.

### ISSUE THREAD

**Issue by ivanandresdiaz** [alex8088/electron-vite#59]
### Describe the bug

` "react-router-dom": "^6.4.3"`

I want to use react-router-dom for the routes of my app. in development works well, it switches pages. However, when I am going to compile for the window it doesn't work. 

_renderer/src/main.tsx_
```
  <BrowserRouter>
    <App />
  </BrowserRouter>
```
_renderer/src/App.tsx_
```
import { Route, Routes } from 'react-router-dom'
import Page1 from './pages/page1'
import Page2 from './pages/page2'

function App(): JSX.Element {
  return (
    <Routes>
      <Route index path="/" element={<Page1 />} />
      <Route index path="/page2" element={<Page2 />} />
    </Routes>
  )
}

export default App
```

they work in the development, it doesn't work when I compile

I add this repository if you want to see it closer.
https://github.com/ivanandresdiaz/electron-vite-react-ts.git 

### Electron-Vite Version

1.0.11

### Electron Version

20.3.2

### Vite Version

3.1.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by ivanandresdiaz** [comment]
Sorry, I  for posting this issue, it was my mistake. Later I found that the problem is because I need to use HashRouter instead of BrowserRouter. 
I will leave a comment. Maybe in the future, someone has the same problem 

_renderer/src/main.tsx_
**WRONG**
```
  <BrowserRouter>
    <App />
  </BrowserRouter>
```
**CORRECT**
```
import { HashRouter } from 'react-router-dom'

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <HashRouter>
    <App />
  </HashRouter>
)

**Comment by alex8088** [comment]
yes , Electron does not handle history and works with the synchronized URL, so `BrowserRouter` does not work with Electron. Use `HashRouter` instead of `BrowserRouter`  to sync URL with UI (windows.location.hash).
