### ISSUE TITLE
执行asar extract app.asar时会报错

### ISSUE THREAD

**Issue by Codevers** [alex8088/electron-vite#590]
### Describe the bug

报错信息： 未找到/app.asar.unpacked/resources/icon.png。
临时解决：在electron-builder配置中，去掉asarUnpack中的resources/**，重新打包即可恢复正常，尝试给icon加入?asset&asarUnpack，但依然无效。

### Electron-Vite Version

2.3.0

### Electron Version

22.3

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
asarUnpack 在很多情况下是必须的。详细阅读： https://cn.electron-vite.org/guide/distribution#asar-%E5%AD%98%E6%A1%A3%E5%B1%80%E9%99%90%E6%80%A7

这种情况是正常的，要正常解压需要将app.asar.unpacked目录与app.asar放在一起。
