### ISSUE TITLE
Missing shortcut when installing built app for Windows

### ISSUE THREAD

**Issue by charlesanim** [alex8088/electron-vite#592]
Hello! I'm new to Electron development, and haven't been able to figure out this problem when I build my app for distribution.
I don't get any errors in development nor production preview environments, and when running the `npm run build:win` command I didn't get any errors either.

I'm able to run the installer from _myApp/dist/myApp-1.0.0-setup.exe_ without any problems, but as soon as the installation is completed, the desktop shortcut appears without the proper icon and when I try to launch my app I get an error saying that it is missing a shortcut. When I choose to locate the shortcut I am presented with "_..Appdata/Local/Programs/myApp_" folder that only has the uninstaller file in it.

Anyone have any clue where I might have gone wrong? Apologies if I have not provided enough info, but as said: I'm new to this and don't really know which files to show or discuss.
(Note: I used myApp name here just for the sake of simplicity)

Package.json:
<img width="627" alt="packageJSON" src="https://github.com/alex8088/electron-vite/assets/78928366/4731dbc5-8974-4e76-a955-0669e5c9cb59">

electron-builder.yml:
<img width="882" alt="electron-builder" src="https://github.com/alex8088/electron-vite/assets/78928366/30db1672-f412-47d1-b70c-6aed48e1cb41">

_Originally posted by @byOppes in https://github.com/alex8088/electron-vite/discussions/357_

**Comment by byOppes** [comment]
Hello,

Which OS are you on? My problem was as simple as just trying to build Windows installer on a Mac. Creating the .exe requires the operating system to run the installer while building it, and as Mac can't do that, it just really didn't finish the build. I was just surprised that there were no error messages that hinted towards this even tho the build process is failing at least on some level.

If you are on a Windows machine, I'm afraid I can't be of help. I'll try and skim my notes once I get to office today and see if I find anything helpful that I might have forgotten since.

**Comment by charlesanim** [comment]
@byOppes thanks for the response. Yes, i built the exe on my mac, then copied it over to my ASUS Rog Ally which is running Windows 11. It seems you may be hinting at running the build (in this case the project) on the windows machine, then installing the output exe. Will that work? I can try doing that.

**Comment by byOppes** [comment]
I would recommend trying that. There may be some other solutions to the problem but for me building the .exe on my Windows machine was the easiest solution.

Some sites also hint installing Wine with Homebrew but I couldn't get it working. I'm also a total noob and have very limited knowledge of this topic so someone wiser might still aid you more.

I hope you are able to get the problem solved and continue you project!

**Comment by charlesanim** [comment]
It works! 

For future folks: I copied my project to a windows machine, built and distributed the .exe file by running `npm or yarn build:win` and it works. So seems like building windows app on Mac is not possible at least when using electron-vite. 

Thanks for the insight @byOppes

**Comment by byOppes** [comment]
Good to head. Glad I could be of help.

> So seems like building windows app on Mac is not possible at least when using electron-vite.

^at least out of the box ;)

**Comment by Geuni620** [comment]
@charlesanim 

I stumble across it and leave a comment.
In my case, specifying target when creating the window file solved it.


cc. [Electron Application Built on macOS for windows is not working on installation](https://stackoverflow.com/questions/74060787/electron-application-built-on-macos-for-windows-is-not-working-on-installation)
