### ISSUE TITLE
Question,not bug,about bytecodePlugin

### ISSUE THREAD

**Issue by xiatian12345** [alex8088/electron-vite#594]
### Describe the bug

1. build windows platform application
2. use asar extract app.asar,unzip the resources
3. find this codes `├── main
│   ├── bytecode-loader.cjs
│   ├── index.js
│   └── index.jsc
├── preload
│   ├── bytecode-loader.cjs
│   ├── index.js
│   └── index.jsc
`
4. i found bytecode-loader.cjs is plaintext，is other people can decode my index.cjs?

### Electron-Vite Version

2.3.0

### Electron Version

v31.2.1

### Vite Version

5.4.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
No, your source code is in the jsc file.
