### ISSUE TITLE
使用bytecodePlugin插件构建报错

### ISSUE THREAD

**Issue by uchief** [alex8088/electron-vite#60]
### Describe the bug

![image](https://user-images.githubusercontent.com/94058904/202650073-a8240b07-5d9e-4962-8383-c1bcd837cd1e.png)

[vite:bytecode] unknown file: Unable to transform arrow inside class property
  3057 |     return fs__default.default.pathExistsSync(path2);
  3058 |   }
> 3059 |   downloadSuccess = async (path2) => {
       |                     ^
  3060 |     if (process.platform === "darwin") {
  3061 |       await this.macUpdate(path2);
  3062 |     }

### Electron-Vite Version

1.0.14

### Electron Version

21.2.2

### Vite Version

3.2.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@uchief 你的package.json是咋样的，应该是一些程序需要的包没有安装成deps

**Comment by uchief** [comment]
> @uchief 你的package.json是咋样的，应该是一些程序需要的包没有安装成deps

@alex8088 这个是依赖的截图，看着没啥异常的，把bytecodePlugin关掉就正常
![image](https://user-images.githubusercontent.com/94058904/202665677-22b53e41-a337-45b0-a6fd-dc4fb174136b.png)

**Comment by alex8088** [comment]
@uchief 看一下配置

**Comment by uchief** [comment]
> @uchief 看一下配置

@alex8088 这个是配置
![image](https://user-images.githubusercontent.com/94058904/202668271-40d21ce2-425a-406b-8feb-a21e78e04e7f.png)

**Comment by alex8088** [comment]
```js
export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin({ chunkAlias: ['index'] })],
    build: {
      rollupOptions: {
        output: {
          manualChunks(id): string | void {
            if (id.includes('execa')) {
              return 'execa'
            }
            if (id.includes('node-fetch')) {
              return 'node-fetch'
            }
          }
        }
      }
    }
  },
  // ...
})
```
参考上面配置，将`execa`，`node-fetch`单独生成`chunk`，`chunkAlias`指定`index`只保护自己的代码

**Comment by uchief** [comment]
> ```js
> export default defineConfig({
>   main: {
>     plugins: [externalizeDepsPlugin(), bytecodePlugin({ chunkAlias: ['index'] })],
>     build: {
>       rollupOptions: {
>         output: {
>           manualChunks(id): string | void {
>             if (id.includes('execa')) {
>               return 'execa'
>             }
>             if (id.includes('node-fetch')) {
>               return 'node-fetch'
>             }
>           }
>         }
>       }
>     }
>   },
>   // ...
> })
> ```
> 
> 参考上面配置，将`execa`，`node-fetch`单独生成`chunk`，`chunkAlias`指定`index`只保护自己的代码

@alex8088 仍然报错，红色报错部分是我自己的代码，不是包里的

**Comment by alex8088** [comment]
@uchief 

字节码保护是需要将箭头函数转换成普通函数，而Class下：

```js
class A {
  handle = (x = 0) => {
    console.log(x);
  };
}
```

这种写法转换上有问题，这是babel的相关bug，解决方法改用普通函数即是 function 或者 如下面一样：

```js
class A {
  async handle(x = 0) {
    console.log(x);
  };
}
````

**Comment by alex8088** [comment]
@uchief  问题是否已解决？

**Comment by onesianinflaredguard** [comment]
Hello

**Comment by uchief** [comment]
> Hello

@alex8088 修改后已解决

**Comment by uchief** [comment]
> > Hello
> 
> @alex8088 修改后已解决

@alex8088 十分感谢
