### ISSUE TITLE
安装的 serialport 模块在打包之后生成的 exe 文件报错，找不到模块

### ISSUE THREAD

**Issue by AyaKumo** [alex8088/electron-vite#606]
### Describe the bug

安装的 serialport 模块在打包之后生成的 exe 文件报错，找不到相关的模块
使用electron-vite打包的

![image](https://github.com/user-attachments/assets/f0920e21-f0e6-4b1d-a9d6-6d2c63c136dd)

### Electron-Vite Version

2.3.0

### Electron Version

31.0.2

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/troubleshooting#distribution
