### ISSUE TITLE
main.build.publicDir support mutlit point

### ISSUE THREAD

**Issue by frankie-zeng** [alex8088/electron-vite#609]
### Clear and concise description of the problem

some use case, we can't combine all resource into one place..

### Suggested solution

string[]

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
This is an unreasonable requirement and Vite will not support it.
