### ISSUE TITLE
Unable to "un-extern" native node modules from renderer

### ISSUE THREAD

**Issue by ykrasik** [alex8088/electron-vite#61]
### Describe the bug

I'm porting a project from webpack to `electron-vite`. Webpack was previously bundling this as an IIFE.

I ran into a case where one of my dependencies used in the renderer, not sure which one, was using the "utils" nodejs module transitively. I think it was pulling "utils" in through [make-error-cause](https://www.npmjs.com/package/make-error-cause).

This would result in the following error from renderer, even though `nodeIntegration: true` and `contextIsolation: false`:
`index.html:1 Uncaught TypeError: Failed to resolve module specifier "util". Relative references must start with either "/", "./", or "../".`

I don't understand why this was happening, as from what I understand, turning on `nodeIntegration: true` should've given renderer access to "utils". Or was webpack bundling "utils" in the renderer before? Anyway, as I couldn't find a solution, I decided to polyfill it instead. What I found out is - you can't polyfill any node native modules, because they are [marked as externals](https://github.com/alex8088/electron-vite/blob/e72e1ea05625cf8020590cd4741ef3f4a34db567/src/plugins/electron.ts#L255).

I was trying to polyfill them through an alias:
```typescript
export default defineConfig({
  renderer: {
    resolve: {
      alias: {
        util: 'rollup-plugin-node-polyfills/polyfills/util',
      },
    },
  }
})
```

Also, the following had no effect - I was unable to override the default `extern` config for rollup:
```typescript
import { IsExternal } from 'rollup'

const isExternal: IsExternal = id => {
  console.log(`Resolving: ${id}`)
  return false
}

export default defineConfig({
  renderer: {
    build: {
      rollupOpitions: {
        external: isExternal,
      },
    },
  }
})
```

I think that having an ability to un-extern node native modules, or replace the extern block with a function, is useful and currently missing.

P.S. If you could explain why this error appears with `vite-electron` but not with `webpack`, that would help a lot.

### Electron-Vite Version

1.0.14

### Electron Version

21.2.2

### Vite Version

3.2.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by ykrasik** [comment]
About `make-error` - it's not my direct dependency, another lib that I use pulls it in.
So... the problem is that nodejs native modules must be `require`d and not `import`ed from renderer? That would at least explain it. That plugin didn't work for me, but I'm ok with a polyfill as its only the "util" module.

It would be nice to be able to disable the default externing of node builts in renderer. Currently I solved it by applying a patch as part of yarn install:

**package.json**
```json 
"resolutions": {
  "electron-vite": "patch:electron-vite@1.0.14#.yarn/patches/electron-vite-1.0.14.patch"
},
```

**.yarn/patches/electron-vite-1.0.14.patch**
```patch
diff --git a/dist/chunks/lib-d0e65f8e.js b/dist/chunks/lib-d0e65f8e.js
index e0211a8ce..f2bdc0c14 100644
--- a/dist/chunks/lib-d0e65f8e.js
+++ b/dist/chunks/lib-d0e65f8e.js
@@ -361,1 +361,1 @@
-                            external: [...node_module.builtinModules.flatMap(m => [m, `node:${m}`])]
+                            // external: [...node_module.builtinModules.flatMap(m => [m, `node:${m}`])]

```

**Comment by alex8088** [comment]
@ykrasik Thanks. I didn't understand your idea correctly. This requirement seems reasonable, I will fix it.

**Comment by alex8088** [comment]
new ver 1.0.15 is out!
