### ISSUE TITLE
想在程序的【关于】对话框里面显示执行npm run build:win的时间，有方法实现吗

### ISSUE THREAD

**Issue by wjx0912** [alex8088/electron-vite#617]
### Clear and concise description of the problem

感谢~

### Suggested solution

RT

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
你应该在electron反馈你的需求，electron-vite仅仅是electron的构建工具。
