### ISSUE TITLE
"electron": "^32.1.1" 启动失败

### ISSUE THREAD

**Issue by MyDataHouse** [alex8088/electron-vite#619]
### Describe the bug

![image](https://github.com/user-attachments/assets/3d68678d-ffd0-4dce-8869-935f3c775a93)

"electron": "^32.1.1" 启动失败
我换回 31 就正常

### Electron-Vite Version

2.3.0

### Electron Version

32.1.1

### Vite Version

5.4.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
未成功安装electron，脚手架创建时最后的选项选择代理下载，会自动添加electron下载npm代理配置。或者自行收到配置。

**Comment by MyDataHouse** [comment]
![image](https://github.com/user-attachments/assets/b85556aa-cc2f-44e2-ba98-8fc37913a475)
我在node_modules 里找到了 electron 32.1.1。
并且我尝试了 32.0.0 是可以正常运行的的

**Comment by alex8088** [comment]
有安装包不等于安装成功，安装完后需等待electron下载程序包，常见问题，按上述方法解决

**Comment by alex8088** [comment]
成功标志，安装目录下有个dist目录，你的截图显然是没有的
