### ISSUE TITLE
electron-vite build --mode $env不生效

### ISSUE THREAD

**Issue by flying-leaves** [alex8088/electron-vite#62]
### Clear and concise description of the problem

打包时候执行 electron-vite build --mode pre

根目录下创建 .env.pre

`
MAIN_VITE_BUILD_ENV=pre      # 主进程可用
`

主程序中

import.meta.env.MAIN_VITE_BUILD_ENV 打印为undefined

### Suggested solution

像vite一样，可加载正确的全局变量

Electron-Vite Version
1.0.14

Electron Version
20.3.5

Vite Version
3.2.3

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@flying-leaves 在build的状态下是不能打印的，这是构建，构建时这些变量都会被替换，这不是运行程序。

```js
// env.pre
MAIN_VITE_TEST=true
```

```js
//main.ts
console.log(import.meta.env.MAIN_VITE_TEST)
```
执行 `electron-vite dev --mode pre` 打包后就是

```js
//main.js
console.log("true");
```

你可以在 `electron-vite dev --mode pre` 或者  `electron-vite preview --mode pre` 下看到真正的运行状态

**Comment by flying-leaves** [comment]
`
// .env
MAIN_VITE_BUILD_ENV=production

`

`
// .env.pre

#环境变量
MAIN_VITE_BUILD_ENV=pre      # 主进程可用
`

`
// build时候执行
electron-vite build --mode pre
`

`
// main.js

// app.whenReady().then()中执行

dialog
    .showMessageBox(mainWindow, {
      type: 'info',
      title: '提示',
      message: `当前环境为${import.meta.env.MAIN_VITE_BUILD_ENV}, 域名为${apiDomain}`,
      buttons: ['确认'] // 选择按钮，点击确认则下面的idx为0，取消为1
    })
    .then(() => {})

`

这时候显示出来的是
<img width="257" alt="image" src="https://user-images.githubusercontent.com/23043986/203467271-637dfb17-18b6-47d2-8dcb-5a7a59505161.png">

**Comment by alex8088** [comment]
我测试的情况是正常的，检测一下两个配置文件变量命名是否一致，是否有空格，electron-vite并未对变量进行特殊处理，最终也是交由vite来加载。

**Comment by alex8088** [comment]
> 这时候显示出来的是 <img alt="image" width="257" src="https://user-images.githubusercontent.com/23043986/203467271-637dfb17-18b6-47d2-8dcb-5a7a59505161.png">

这个是在什么指令下运行的， dev 还是 preview，如果在在build打包之后，也要确保执行electron-builder前执行build带上mode，例如：
```json
 "build": "npm run typecheck && electron-vite build --mode pre",
 "build:win": "npm run build && electron-builder --win --config",
```
