### ISSUE TITLE
ipcRenderer gets ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by a-x-** [alex8088/electron-vite#63]
### Describe the bug

Or ReferenceError: path is not defined / path.join in not a function

1. `git clone https://github.com/alex8088/electron-vite-boilerplate.git bug && cd bug`
2. `npm i`
3. `import { ipcRenderer } from "electron";`
4. use `ipcRenderer.send("foo", {bar:1})` or just mention it! `ipcRenderer`
5. npm run dev

that place: https://github.com/alex8088/electron-vite/blob/97a62b75f2b1f2ac814af66d90ae5f2d8e56165c/src/electron.ts#L43

### Electron-Vite Version

1.0.14

### Electron Version

21.3.0

### Vite Version

3.2.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@a-x- Maybe lost something.

recommend `npm init @quick-start/electron` to scaffold your project and select react template. 

check out https://evite.netlify.app/guide/ for more detail

**Comment by a-x-** [comment]
did you mean: npm create @quick-start/electron --template react-ts? (I prefer yarn as a significant faster; the command is the same except replacement npm to yarn)

I tried it too.

when I add my dependencies, for example 
```
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
```

it causes the same error

**Comment by a-x-** [comment]
looks like problem is `ipcRenderer`

**Comment by alex8088** [comment]
@a-x- Currently, `node integration` is not supported, because it is not the best way. It is recommended to use `preload` to use the node's ability, and the [@electron-toolkit/preload](https://github.com/alex8088/electron-toolkit/tree/master/packages/preload) package is added to improve the development experience.

**Comment by alex8088** [comment]
@a-x-  If you insist on `node integration`, you need to enable node integration and use the `require` to import the `electron` or `node module`, which is not very elegant.

**Comment by a-x-** [comment]
good, I see boilerplate already use it.

Could you add this explanation into README. Like this: Don't use `import ipcRenderer from "electron"` directly due to <reasons>. electron-vite provides `window.electron.ipcRenderer` instead.

**Comment by alex8088** [comment]
@a-x- Thanks. That's a good suggestion.
