### ISSUE TITLE
mac自动更新

### ISSUE THREAD

**Issue by xuyifeiOnly** [alex8088/electron-vite#638]
### Describe the bug

使用 electron-updater在mac上实现自动更新，下载完成之后报错
<img width="1332" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/7f6a981e-580a-42c9-bd59-561c0df6d0f3">

### Electron-Vite Version

2.3.0

### Electron Version

31.3.1

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
签名问题，可以查阅electron-builder的文档相关i和ssue解决问题
