### ISSUE TITLE
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

### ISSUE THREAD

**Issue by New-Lanke** [alex8088/electron-vite#64]
### Describe the bug

![image](https://user-images.githubusercontent.com/51505088/204501475-4a6bed19-8161-4807-8e56-0fb3aca97950.png)

当我尝试通过`yarn dev`命令启动时，命令行弹出了该错误。
在阅读了文档后，我在`electron.vite.config.ts`中添加了如下配置，但未起作用。
`
renderer: {
        ...
        build: {
            target: 'chrome102'
        }
    },
`

### Electron-Vite Version

^1.0.14

### Electron Version

^21.3.0

### Vite Version

^3.2.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@New-Lanke 

First, this error happens. So you need to change `optimizeDeps.esbuildOptions.target` to avoid transpiling.

```js
    optimizeDeps: {
      esbuildOptions: {
        target: 'esnext'
      }
    }
```

Second, these module just for node, but not browser. if you want to use it, you need to add polyfill for` node:util`.

**Comment by alex8088** [comment]
@New-Lanke 问题是否解决

**Comment by New-Lanke** [comment]
非常感谢，问题已完美解决。
