### ISSUE TITLE
添加配置以控制构建后的语言包

### ISSUE THREAD

**Issue by xaios** [alex8088/electron-vite#654]
### Clear and concise description of the problem

locales 目录中一般可能就用到 en-US、zh-CN，也可能有 zh-TW，其余基本上不会被使用的语言包占用了近 40MB 的体积，有不小的体积优化空间

### Suggested solution

electron-vite 模块导出语言配置插件，默认情况下裁剪至英繁简三语，可通过配置添加语言

```javascript
import { LangPlugin } from 'electron-vite'

LangPlugin()       // en-US zh-CN zh-TW
LangPlugin(['ja']) // en-US zh-CN zh-TW ja
```

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that requests the same feature to avoid creating a duplicate.

**Comment by alex8088** [comment]
electron-vite 仅作为代码构建工具，而非打包工具，相关需求 electron-builder 本身就支持，详细查阅其文档配置既可以。
