### ISSUE TITLE
Use require() in electron main / preload

### ISSUE THREAD

**Issue by kkerti** [alex8088/electron-vite#66]
### Describe the bug

I have refactored my app to use electron-vite, using svelte on the frontend. I like the streamlined configuration available through `electron.vite.config.js`.

My electron main and preload scripts currently use commonjs syntax, files have `module.exports = {}` and the main uses `require()` to load them.

It seems to me that electron-vite supports ESM style imports only.
I have set the outDir to `dist/*` and in `dist/main/index.js` only the main entry file can be found, without it's required files. I tried to add the `vite-plugin-commonjs` to `main`, but no success.

When in `package.json` the main is set to the built outDir index.js, the project fails to start as it can't find modules.

If possible, I would avoid refactoring to ESM now, as we have couple dependencies having cjs exports only.

### Electron-Vite Version

1.0.14

### Electron Version

18.3.15

### Vite Version

3.1.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@kkerti `electron-vite` supports pure CJS dependencies, the `externalizePlugins` will externalize all CJS dependencies that do not need to be bundled. For pure esm  dependencies, they will be bundled into CJS to support Electron. So you can write code in ESM syntax. But it also works if you use CJS syntax. In fact, there is no need to build for CJS.

For outDir,  check out https://evite.netlify.app/guide/build.html#output-dir

**Comment by alex8088** [comment]
@kkerti This issue will be closed as there is nothing to do. If you have any other questions, please feel free to submit an issue.
