### ISSUE TITLE
 字节码解决方案 Credit 以及外发文章涉嫌洗稿的问题

### ISSUE THREAD

**Issue by Nihiue** [alex8088/electron-vite#67]
### Clear and concise description of the problem

我是 [little-byte](https://github.com/Nihiue/little-byte) 的作者, 也写过两篇关于字节码的文章

- [通过字节码保护Node.js源码之原理篇](https://zhuanlan.zhihu.com/p/359235114)
- [Node.js 字节码源码相关问题补完](https://zhuanlan.zhihu.com/p/419591875)

注意以上文章都是21年发布的，第一篇大概是4月份。

### 1.Repo中字节码相关功能代码原创度问题

loader相关的代码存在高度一致性

https://github.com/alex8088/electron-vite/blob/master/src/plugins/bytecode.ts

https://github.com/Nihiue/little-byte/blob/main/src/loader/utils.ts

https://github.com/Nihiue/little-byte/blob/main/src/loader/index.ts

虽然这个功能也不复杂，写出类似的代码无可厚非，但是inject-loader部分连工具函数实现都一致，并且命名习惯相似。
显然不是独立写出来的。

至于 compile 的部分因为本质上很简单，所以我不发表意见。

### 2.外部发表文章洗稿嫌疑的问题

外发文章 [electron-vite：轻松保护你的 Electron 源代码](https://zhuanlan.zhihu.com/p/566262319)

里面多个关键点和我的文章重复

* bytecode的基本原理
* 箭头函数导致崩溃的问题
* 对代码组织的影响里 Function.toString 的部分
* 性能：没有影响，略有提升的结论
* 对于 bytenode 的借鉴

bytecode作为一个v8的基础能力，不同的人对它有相似的利用是正常的。但是最奇怪的是 箭头函数 这个问题，这个问题最早是我提给 bytenode 的 issue https://github.com/bytenode/bytenode/issues/157

 bytenode的作者认为这个问题不值得修复。后来我在 little-byte 里解决了这个问题。electron-vite 声称解决了这个问题，但我没有看到实现。

这个是个很小的细节，而且不太具有通用性，再加上 Function.toString  和其它相似性，我有理由怀疑整篇文章都是洗稿的。

结合代码来看，这个功能从一开始就直接借鉴自我的文章和 little-byte，而非 bytenode。

### Suggested solution

# 总结

这个解决方案从代码层面是很简单的，但是主要的工作量在于深入 V8 以及通过各种 trick 解决小问题。这一部分的工作量比我在文章中提到的大得多。如果你在这样一个功能上使用了别人的产出，我认为应该给予原作者 Credit。

我的代码是 MIT License，意味着你使用是 OK 的，但是有意避开信息来源是不 OK 的，洗稿也是不 OK 的。

如果作者认为我的指控是子虚乌有，我希望看到证据。

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Nihiue** [comment]
bytenode
```
// TODO: rewrite this function
const fixBytecode = function (bytecodeBuffer) {
  if (!Buffer.isBuffer(bytecodeBuffer)) {
    throw new Error('bytecodeBuffer must be a buffer object.');
  }

  const dummyBytecode = compileCode('"ಠ_ಠ"');

  if (process.version.startsWith('v8.8') || process.version.startsWith('v8.9')) {
    // Node is v8.8.x or v8.9.x
    dummyBytecode.slice(16, 20).copy(bytecodeBuffer, 16);
    dummyBytecode.slice(20, 24).copy(bytecodeBuffer, 20);
  } else if (process.version.startsWith('v12') ||
    process.version.startsWith('v13') ||
    process.version.startsWith('v14') ||
    process.version.startsWith('v15') ||
    process.version.startsWith('v16') ||
    process.version.startsWith('v17') ||
    process.version.startsWith('v18') ||
    process.version.startsWith('v19')) {
    dummyBytecode.slice(12, 16).copy(bytecodeBuffer, 12);
  } else {
    dummyBytecode.slice(12, 16).copy(bytecodeBuffer, 12);
    dummyBytecode.slice(16, 20).copy(bytecodeBuffer, 16);
  }
};

```

little-byte
```
const HeaderOffsetMap = {
  'magic': 0,
  'version_hash': 4,
  'source_hash': 8,
  'flag_hash': 12
};

type headerType = keyof (typeof HeaderOffsetMap);

export const headerUtils = {
  set(targetBuffer: Buffer, type: headerType, sourceBuffer: Buffer) {
    sourceBuffer.copy(targetBuffer, HeaderOffsetMap[type]);
  },
  get(buffer: Buffer, type: headerType) {
    const offset = HeaderOffsetMap[type];
    return buffer.slice(offset, offset + 4);
  },
  buf2num(buf: Buffer) {
    // 注意字节序问题
    let ret = 0;
    ret |= buf[3] << 24;
    ret |= buf[2] << 16;
    ret |= buf[1] << 8;
    ret |= buf[0];
    return ret;
  }
};

let _flag_buf: Buffer | undefined;

export function getReferenceFlagHash() {
  if (!_flag_buf) {
    const script = new vm.Script('');
    _flag_buf = headerUtils.get(script.createCachedData(), 'flag_hash');
  }
  return _flag_buf;
}

```
你的实现
```
 `function setFlagHashHeader(bytecodeBuffer) {`,
  `  if (!dummyBytecode) {`,
  `    const script = new vm.Script("", {`,
  `      produceCachedData: true`,
  `    });`,
  `    dummyBytecode = script.createCachedData();`,
  `  }`,
  `  dummyBytecode.slice(FLAG_HASH_OFFSET, FLAG_HASH_OFFSET + 4).copy(bytecodeBuffer, FLAG_HASH_OFFSET);`,
  `};`,

 `function getSourceHashHeader(bytecodeBuffer) {`,
  `  return bytecodeBuffer.slice(SOURCE_HASH_OFFSET, SOURCE_HASH_OFFSET + 4);`,
  `};`,
  `function buffer2Number(buffer) {`,
  `  let ret = 0;`,
  `  ret |= buffer[3] << 24;`,
  `  ret |= buffer[2] << 16;`,
  `  ret |= buffer[1] << 8;`,
  `  ret |= buffer[0];`,
  `  return ret;`,
  `};`,
  `Module._extensions[".jsc"] = function (module, filename) {`,
  `  const bytecodeBuffer = fs.readFileSync(filename);`,
  `  if (!Buffer.isBuffer(bytecodeBuffer)) {`,
  `    throw new Error("BytecodeBuffer must be a buffer object.");`,
  `  }`,
  `  setFlagHashHeader(bytecodeBuffer);`,
  `  const length = buffer2Number(getSourceHashHeader(bytecodeBuffer));`,
```

请你大声告诉我， 是不是巧合

**Comment by Nihiue** [comment]
另外，我没有什么从bytecode借鉴的代码，我从bytecode那里拿到的是一个idea，就是使用字节码来保护源代码本身。你可以自己去对比一下。另外我的所有代码的实现及其背后的设计，都在文章中体现了。

而且当我在我的实现中遇到问题时，我在 bytenode上复现了，去和 bytecode 作者讨论，这是我表达对 bytenode 项目的敬意，以及我对bytenode项目的贡献。

**Comment by Nihiue** [comment]
Ok，这个讨论到此为止了，我来总结一下。

- 代码的相似性是因为整个世界都是我的
- 箭头函数是恰好看了我的issue，但是没看我的文章和代码。尽管这个issue只在 21年 open 了一周。

祝你生活愉快

**Comment by Nihiue** [comment]
你如果视力正常，你就会看到上面这篇Electron的文章里有我的文章的link

**Comment by Nihiue** [comment]
你是不是在搞笑啊，你的文章和字节前端的那篇文章前几百个字是一模一样的。字节前端你的文章里有我的链接。

**Comment by Nihiue** [comment]
参考文章等于前几百个字照抄是吧，有点拙劣了兄弟

**Comment by alex8088** [comment]
那我首先检索收集到就是这篇文章 ，大哥，我首先写的英文版

**Comment by Nihiue** [comment]
我不懂你的逻辑。你能展开讲讲吗

**Comment by alex8088** [comment]
我也对出处做了标准，保持对原作者的尊重，你无法告诉这也是这篇文章的作者，我如何相信。

**Comment by alex8088** [comment]
我参考的起点是英文版的， 我也做了标注，你为什么始终不告诉我这篇文章是不是你的

**Comment by alex8088** [comment]
我在文章中特意标注出处，就是保持对原作者的尊重，这一点很清楚，没有说就是我的，我只是引入，阐述自己的解决方案。这个我反而希望你回答到底你是不是原作者，如果是我就需要修正过来

**Comment by Nihiue** [comment]
你参考什么英文版啊，那个明显是机翻的字节文章。这个先不论。

你的中文文章和字节的中文文章前几百个字一模一样，怎么参考的英文文章可以写出一样的中文？

更不用说我和字节的文章都是你常用的知乎平台的了。

我不和你讨论了，你也千万别加我的链接。

祝你生活愉快。

**Comment by snkeyt** [comment]
> bytenode
> 
> ```
> // TODO: rewrite this function
> const fixBytecode = function (bytecodeBuffer) {
>   if (!Buffer.isBuffer(bytecodeBuffer)) {
>     throw new Error('bytecodeBuffer must be a buffer object.');
>   }
> 
>   const dummyBytecode = compileCode('"ಠ_ಠ"');
> 
>   if (process.version.startsWith('v8.8') || process.version.startsWith('v8.9')) {
>     // Node is v8.8.x or v8.9.x
>     dummyBytecode.slice(16, 20).copy(bytecodeBuffer, 16);
>     dummyBytecode.slice(20, 24).copy(bytecodeBuffer, 20);
>   } else if (process.version.startsWith('v12') ||
>     process.version.startsWith('v13') ||
>     process.version.startsWith('v14') ||
>     process.version.startsWith('v15') ||
>     process.version.startsWith('v16') ||
>     process.version.startsWith('v17') ||
>     process.version.startsWith('v18') ||
>     process.version.startsWith('v19')) {
>     dummyBytecode.slice(12, 16).copy(bytecodeBuffer, 12);
>   } else {
>     dummyBytecode.slice(12, 16).copy(bytecodeBuffer, 12);
>     dummyBytecode.slice(16, 20).copy(bytecodeBuffer, 16);
>   }
> };
> ```
> 
> little-byte
> 
> ```
> const HeaderOffsetMap = {
>   'magic': 0,
>   'version_hash': 4,
>   'source_hash': 8,
>   'flag_hash': 12
> };
> 
> type headerType = keyof (typeof HeaderOffsetMap);
> 
> export const headerUtils = {
>   set(targetBuffer: Buffer, type: headerType, sourceBuffer: Buffer) {
>     sourceBuffer.copy(targetBuffer, HeaderOffsetMap[type]);
>   },
>   get(buffer: Buffer, type: headerType) {
>     const offset = HeaderOffsetMap[type];
>     return buffer.slice(offset, offset + 4);
>   },
>   buf2num(buf: Buffer) {
>     // 注意字节序问题
>     let ret = 0;
>     ret |= buf[3] << 24;
>     ret |= buf[2] << 16;
>     ret |= buf[1] << 8;
>     ret |= buf[0];
>     return ret;
>   }
> };
> 
> let _flag_buf: Buffer | undefined;
> 
> export function getReferenceFlagHash() {
>   if (!_flag_buf) {
>     const script = new vm.Script('');
>     _flag_buf = headerUtils.get(script.createCachedData(), 'flag_hash');
>   }
>   return _flag_buf;
> }
> ```
> 
> 你的实现
> 
> ```
>  `function setFlagHashHeader(bytecodeBuffer) {`,
>   `  if (!dummyBytecode) {`,
>   `    const script = new vm.Script("", {`,
>   `      produceCachedData: true`,
>   `    });`,
>   `    dummyBytecode = script.createCachedData();`,
>   `  }`,
>   `  dummyBytecode.slice(FLAG_HASH_OFFSET, FLAG_HASH_OFFSET + 4).copy(bytecodeBuffer, FLAG_HASH_OFFSET);`,
>   `};`,
> 
>  `function getSourceHashHeader(bytecodeBuffer) {`,
>   `  return bytecodeBuffer.slice(SOURCE_HASH_OFFSET, SOURCE_HASH_OFFSET + 4);`,
>   `};`,
>   `function buffer2Number(buffer) {`,
>   `  let ret = 0;`,
>   `  ret |= buffer[3] << 24;`,
>   `  ret |= buffer[2] << 16;`,
>   `  ret |= buffer[1] << 8;`,
>   `  ret |= buffer[0];`,
>   `  return ret;`,
>   `};`,
>   `Module._extensions[".jsc"] = function (module, filename) {`,
>   `  const bytecodeBuffer = fs.readFileSync(filename);`,
>   `  if (!Buffer.isBuffer(bytecodeBuffer)) {`,
>   `    throw new Error("BytecodeBuffer must be a buffer object.");`,
>   `  }`,
>   `  setFlagHashHeader(bytecodeBuffer);`,
>   `  const length = buffer2Number(getSourceHashHeader(bytecodeBuffer));`,
> ```
> 
> 请你大声告诉我， 是不是巧合

**Comment by Nihiue** [comment]
你这个素质得放到太阳底下晒晒。

For 后来者，我后续在这里讨论这个问题

https://zhuanlan.zhihu.com/p/590315560

**Comment by alex8088** [comment]
不用来这里趁热度
