### ISSUE TITLE
编译报错，启动是正常运动的

### ISSUE THREAD

**Issue by MarkTang3611** [alex8088/electron-vite#672]
### Describe the bug

PS E:\learn\xy-print> pnpm build:win

> xy-print@1.0.0 build:win E:\learn\xy-print
> npm run build && electron-builder --win

> xy-print@1.0.0 build
> npm run typecheck && electron-vite build

> xy-print@1.0.0 typecheck
> npm run typecheck:node && npm run typecheck:web

> xy-print@1.0.0 typecheck:node
> tsc --noEmit -p tsconfig.node.json --composite false

> xy-print@1.0.0 typecheck:web
> vue-tsc --noEmit -p tsconfig.web.json --composite false

E:\learn\xy-print\node_modules\.pnpm\vue-tsc@2.1.10_typescript@5.7.2\node_modules\vue-tsc\index.js:34
            throw err;
            ^
Search string not found: "/supportedTSExtensions = .*(?=;)/"
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v22.11.0

### Electron-Vite Version

2.3.0

### Electron Version

31.0.2

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by codexiaoke** [comment]
因为编译的时候去检查ts的类型，可能版本typescript的版本不一致导致的，把 package.json中scripts的build中的 npm run typecheck 删了即可编译通过
![微信截图_20241129154716](https://github.com/user-attachments/assets/494602ec-d9fc-45fe-ae66-bf61515a7ce8)
删除这一段，再次运行 pnpm build:win，要是打包其它的版本也报错，把对应的script脚本中的npm run typecheck删除即可

**Comment by codexiaoke** [comment]
#671 因为编译的时候去检查ts的类型，可能版本typescript的版本不一致导致的，把 package.json中scripts的build中的 npm run typecheck 删了即可编译通过
![微信截图_20241129154716](https://github.com/user-attachments/assets/17d73dc0-da64-4ad0-88f4-efaf15d80363)

删除这一段，再次运行 pnpm build:win，要是打包其它的版本也报错，把对应的script脚本中的npm run typecheck删除即可

**Comment by MarkTang3611** [comment]
如果删了，咋检查ts语法？

**Comment by MarkTang3611** [comment]
用没有ts版本的，就可以正常启动编译。

**Comment by codexiaoke** [comment]
我知道解决办法了，这个是因为vue-tsc与typescrip版本不兼容，你运行 pnpm list，会发现这里的typescript版本和package的版本不一致（我这里刚刚解决好了）
![微信截图_20241129154716](https://github.com/user-attachments/assets/81e7ffdb-33ce-4fcf-acd9-94bf754accb3)
直接执行 npm install typescript@5.4.5 (package)的版本就可以正常编译通过了

**Comment by codexiaoke** [comment]
这个版本，安装package的来重新安装一下就可以了，参考文章 https://blog.csdn.net/flhhly/article/details/141720431

**Comment by MarkTang3611** [comment]
可以了，我这边也编译成功了

**Comment by skyclouds2001** [comment]
参见 https://github.com/vuejs/language-tools/issues/5018
