### ISSUE TITLE
Can't install @vitejs/plugin-vue 4.x

### ISSUE THREAD

**Issue by ADumaine** [alex8088/electron-vite#69]
### Clear and concise description of the problem

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: electron-vite@1.0.15
npm ERR! Found: vite@4.0.0
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.0.0" from the root project
npm ERR!   peer vite@"^4.0.0" from @vitejs/plugin-vue@4.0.0
npm ERR!   node_modules/@vitejs/plugin-vue
npm ERR!     dev @vitejs/plugin-vue@"4.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0" from electron-vite@1.0.15
npm ERR! node_modules/electron-vite
npm ERR!   dev electron-vite@"^1.0.15" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vite@3.2.5
npm ERR! node_modules/vite
npm ERR!   peer vite@"^3.0.0" from electron-vite@1.0.15
npm ERR!   node_modules/electron-vite
npm ERR!     dev electron-vite@"^1.0.15" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Suggested solution

update peer dependecy

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@ADumaine Thanks, it will update later.

**Comment by alex8088** [comment]
new ver 1.0.16 is out!
