### ISSUE TITLE
Vite默认环境变量有很奇怪的问题

### ISSUE THREAD

**Issue by yy923683900** [alex8088/electron-vite#70]
### Describe the bug

复现条件：
使用electron-vite直接初始化的模板项目

打印一下vite官方的环境变量
![image](https://user-images.githubusercontent.com/12439414/206834963-647301fa-c125-4545-be7f-e1feb63edf89.png)

在控制台查看打印结果
![image](https://user-images.githubusercontent.com/12439414/206834974-b684a9dc-b679-4ff2-8527-6997d28c3679.png)

mode是 development 的情况下  dev为false prod为true，有点奇怪
但是我直接在本地启动一个vite项目，打印正常，只是在electron-vite里面存在这个问题

### Electron-Vite Version

1.0.15

### Electron Version

22.0.0

### Vite Version

4.0.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@yy923683900 谢谢你反馈的问题。 在vite@4下有此问题，在vite@3下没有此问题。但这看起来并非vite@4的问题，在create-vite创建的web项目，并无此问题，具体原因待进一步确认，稍后解决。

**Comment by alex8088** [comment]
![image](https://user-images.githubusercontent.com/25053004/206836388-6b2efa50-b498-46b5-b70d-488f6ef95a36.png)

vite@3下正常

**Comment by alex8088** [comment]
new ver 1.0.16 is out!
