### ISSUE TITLE
Is `externalizeDepsPlugin` taking modules dependencies into accounts ?

### ISSUE THREAD

**Issue by michael-dm** [alex8088/electron-vite#71]
### Describe the bug

I might just misunderstand how the plugin works but I find that dependencies in package.json are correctly externalised, but not their dependencies, forcing me to add each and every one of them to my package.json.

Is it intended behaviour ?

### Electron-Vite Version

1.0.15

### Electron Version

22.0.0

### Vite Version

3.2.5

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@michael-dm 

For the main process and preload scripts, the best practice is to externalize dependencies and only bundle our own code. 
So the `externalizeDepsPlugin` is designed to externalize all dependencies in `package.json` and we need to install the dependencies required by the app into the `dependencies` of `package.json`. When packaging the app, these dependencies will also be packaged together, such as `electron-builder`. Don't worry about them being lost. On the other hand, `devDependencies` will not be packaged.

It is important to note that some modules that only support ESM, we should not externalize it. We should let electron-vite bundle it into a CJS standard module to support Electron. 

For renderers, it is usually fully bundle, so dependencies are best installed in `devDependencies`. This makes the final package more smaller.

**Comment by michael-dm** [comment]
So that I understand, but what about dependencies of dependencies ? When bundling my app I found that they were not packaged by electron-builder.

Current workaround is adding them manually to the root package.json but this is inconvenient.

**Comment by alex8088** [comment]
`electron-builder` will also automatically resolve dependencies of dependencies.  It may be a configuration problem of electron-builder. How the `files` attribute is configured?

**Comment by michael-dm** [comment]
You were right this is because I use pnpm and there is currently a bug : https://github.com/electron-userland/electron-builder/issues/6792#issuecomment-1098555140

Thank you.

**Comment by alex8088** [comment]
@michael-dm 

If you want to use `pnpm` package manager, you can add `.npmrc` file with `shamefully-hoist=true` in root and reinstall deps.
Also, if you use  `pnpm create @quick-start/electron` to scaffold your project, these will be added automatically.
