### ISSUE TITLE
如何引入静态文件

### ISSUE THREAD

**Issue by lyxgy841** [alex8088/electron-vite#72]
### Describe the bug

我有一些可执行脚本或者要读取的文件，应该怎么放到项目里，才可以打包后能正常使用呢，要给主进程使用

### Electron-Vite Version

^1.0.11

### Electron Version

^20.3.2

### Vite Version

^3.1.8

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
参考：https://cn-evite.netlify.app/guide/build.html#%E5%85%AC%E5%85%B1%E7%9B%AE%E5%BD%95

**Comment by alex8088** [comment]
@lyxgy841 问题是否已解决？

**Comment by alex8088** [comment]
@lyxgy841 你的提议是对的，正在编写补充开发章节，这一部分会加入。
