### ISSUE TITLE
Full node-js support for electron main process.

### ISSUE THREAD

**Issue by janakg** [alex8088/electron-vite#73]
### Electron vite for main process

We are new to vite eco-system, moving a large electron application from webpack to vite using electron-vite plugin. One of our dep. package is @aws-sdk , so we landed in the below issue. Vite doesn't have full support for "mainFields" or "environment". We needed to use `ssr:true` in the main. 
https://github.com/vitejs/vite/issues/4405

Once we do that, asset handling of vite is getting messed up. It is trying to fetch() an asset from chunks/hb.cb53d2e0.wasm inside the bundled js code and fails, as it has not exported to that path and also fetch() in node process is a node-fetch polyfill that doesn't support 'relative urls'. 

### Suggested solution

Can we think of a solution out side vite for bundling main scripts as vite is primarily for frontend tooling? also please suggest if there is any simple way to achieve the same.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
For wasm, you can try the rollup plugin [@rollup/plugin-wasm](https://github.com/rollup/plugins/tree/master/packages/wasm). 

Or, via polyfill:

```js
export default defineConfig({
  main: {
    resolve: {
      alias: {
        '@aws-sdk/xxx': 'polyfills/xxx',
      },
    },
  }
})
```

**Comment by alex8088** [comment]
`electron-vite` uses vite's library mode by default for the main process to build the code as a `cjs` standard module to support electron. I was thinking why the build ssr option can meet your needs. Or it will be better understood with an example.

**Comment by janakg** [comment]
```
export default defineConfig({
  main: {
    plugins: [tsconfigPaths], 
    build: {
      ssr: true,
      rollupOptions: {
        input: {
          index: resolve('src/main/index.ts'),
          gen: resolve('src/gen/index.ts'),
        },
        output: {
          dir: resolve(devPath, 'main'),
        },
      },
    },
    resolve: {
      alias: modAlias
    },
  },
```


Above is an example of main config for electron-vite
modAlias - alias of isomorphic modules (which support both both browser and node)
ssr:true - is required to avoid a long list of modAlias. (this is one side of a problem)

Lets say we listed all isomorphic modules and avoided ssr. 

Then here is my bundle output looks like ssr:false
```
out/main/chunks/Roboto-Black.2df97579.ttf   43.78 KiB
out/main/chunks/hb.cb53d2e0.wasm            305.10 KiB
out/main/chunks/mathjs_bg.67cc5380.wasm     1253.67 KiB
out/main/index.js                           212.39 KiB
out/main/chunks/index.d1cae5ba.js           20.33 KiB
out/main/gen.js                             793.62 KiB
```

Then I face two problems. 
1. wasm plugins and vite's in-built wasm support using `file.wasm?init` depend on fetch() in node-js environment. But it is supplied with a relative url, so node-fetch fails with '[Error: only absolute urls are supported](https://github.com/node-fetch/node-fetch/issues/481)' . 

2. I am not sure how to load other assets like a font file in main script  (e.g: to process the font in our font engine for text shaping )
`import fontBlob from './Roboto-Black.ttf'`

After resolution, I get a relative path in both the cases `chunks/hb.cb53d2e0.wasm` and `chunks/Roboto-Black.2df97579.ttf`

I hope this clarifies. May be there is an easier way or the problem is complex, let me know if you have any questions 
around this? if it helps, i can create a test repo with these cases.

**Comment by janakg** [comment]
Simple question would be around. If electron-vite builds the main in library mode then i guess we need to inline all assets. https://vitejs.dev/config/build-options.html#build-assetsinlinelimit

One solution works for me: increase assetsinlinelimit to 1 MB from 4KB (Default value). Then we will have multiple copies of assets (as base64 inlined) in all bundles. We do have child process script as part of the main.

Interestingly : electron-vite version [1.0.12](https://github.com/alex8088/electron-vite/releases/tag/v1.0.12) bundles all assets inline with our explicitly specifying assetsinlinelimit. I guess it is because of library mode but after that something has changed.

**Comment by alex8088** [comment]
@janakg Nice, please provide a test repo. Maybe I try to find a best solution.

**Comment by janakg** [comment]
@alex8088 

PFA test case repo 
https://github.com/janakg/electron-vite-app-test-case

if you enable the `assetsinlinelimit` in electron.vite.config.ts , it will start working.
Else it will throw fetch undefined error. We can install `node-fetch` to polyfill then you will get `only absolute urls are supported` error.

Irrespective of wasm module loading. How to load any asset file like a font in main thread? you can reproduce that , just by commenting off the wasm module lines and just keeping

`import fontBlob from './Roboto-Black.ttf'`

Let me know if you have any questions

**Comment by janakg** [comment]
Even resolution of public assets are not working. PFA a branch with publicDir for assets handling
https://github.com/janakg/electron-vite-app-test-case/tree/public-dir

**Comment by onesianinflaredguard** [comment]
Hello

**Comment by alex8088** [comment]
For wasm, electron-vite plans to support it in future.

**Comment by janakg** [comment]
@alex8088 Thanks! 
I assumed the same and built a function to handle node-js based wasm import. Other assets , as of now, I am inlining them to avoid any other loaders. Loading the wasm from public directory. Thanks again for the reassurance.

**Comment by alex8088** [comment]
new ver v1.0.17 is out! It optimizes the [static asset handling](https://evite.netlify.app/guide/assets.html) in the Electron main process.
