### ISSUE TITLE
Node from renderer

### ISSUE THREAD

**Issue by hatton** [alex8088/electron-vite#74]
Hey, thanks so much for this library!

I'm trying to convert a large project from webpack to vite using electron-vite.  I'm trying to make the renderer be able to us `fs`. 
I have:
```
  const mainWindow = new BrowserWindow({
   ...
    webPreferences: {
      preload: path.join(__dirname, "../preload/index.js"),
      // we do not show external web content, so there is no threat, so no need for sandboxing
      nodeIntegration: true,
      sandbox: false,
     contextIsolation: false
    }
```

However this code works fine in preload, but not in the renderer:
```
import * as fs from "fs";
const csv = fs.readFileSync(
  "somepath/test.csv",
  "utf8"
);
```

In the renderer, I get

```
Uncaught TypeError: fs.readFileSync is not a function
    at index.tsx:12:16
```

This is a large codebase that mostly just does local file management, and all from the renderer. There is no reason to complicate it by moving all this to the main process, since  *there is no security difference between renderer process and main process if the only code being displayed is what ships with the application*.

Is there something I need to do to enable using nodejs functions in the renderer? 

### Electron-Vite Version

1.0.16

### Electron Version

22.3.0

### Vite Version

4.0.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@hatton I think what you say is reasonable. Currently, electorn-vite not support nodeIntegration. But there is also a way to support that is to use `require` to import the node module which is not very elegant. Or you can use plugin [vite-plugin-commonjs-externals](https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals) to handle. 

Also, I'm looking for a better way to support this.

**Comment by janakg** [comment]
@alex8088 this is an important feature for large projects with nodeIntegration:true

**Comment by janakg** [comment]
https://github.com/vite-plugin/vite-plugin-optimizer
Above plugin helped a lot to convert to require statements. But got struck for the globals like process

**Comment by hatton** [comment]
@alex8088 so using your suggestion, I actually can use `fs`. But not `path`.

I've pushed a repo demonstrating this here: https://github.com/hatton/electron-react-vite-lingui

I wonder if you might have any more suggestions?

(I didn't try the `require` because I need various libraries that I don't control to work too, and so I think I need to get this stuff working without an approach that requires changing code.)

**Comment by alex8088** [comment]
@hatton try add `path` into commonjsexternal plugin like `fs`.

**Comment by hatton** [comment]
@alex8088 Well that's embarrassing. Should have quit for the day sooner. Thanks for your patient help. I committed [that fix](https://github.com/hatton/electron-react-vite-lingui.).

OK, so now 'path' is good in *my* code, but a critical library, lingui, is still broken when _it_ tries to use `path`

![image](https://user-images.githubusercontent.com/8448/209443869-cb86f780-d262-4b9f-8db6-ebff50548abb.png)

Note, I have asked vite to exclude `path`:

```
const nodeImportToTurnIntoRequire = ["fs", "path"];
export default defineConfig({
  main: {
    optimizeDeps: {
      exclude: nodeImportToTurnIntoRequire,
    },
```
But that doesn't seem to do anything.

Looking through vite issues [like this one](https://github.com/vitejs/vite/issues/10302), it seems like this is a common problem but each time, the recommendation is "use a different package". That's not an option for me.

**Comment by alex8088** [comment]
try to externalize lingui too?

**Comment by hatton** [comment]
Yeah, externalizing lingui leads to react errors inside of lingui.

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
```
But of course the library does not violate hooks. `npm ls react` and `npm ls react-dom` both show everything using the same version of reacct.

I'm afraid I just don't understand enough about building/bundling... I don't even know what externalizing means.

At this point, let me just thank you so much for your generosity in helping me. I think I'll need to just take a different approach.

**Comment by HappyFerry** [comment]
> @hatton I think what you say is reasonable. Currently, electorn-vite not support nodeIntegration. But there is also a way to support that is to use `require` to import the node module which is not very elegant. Or you can use plugin [vite-plugin-commonjs-externals](https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals) to handle.
> 
> Also, I'm looking for a better way to support this.

error during start dev server and electron app:
TypeError: commonjsExternalsPlugin is not a function

**Comment by MiniSuperDev** [comment]
@hatton Hi, currently which is the way to allow to use node packages in the renderer?
Thanks

**Comment by hatton** [comment]
@MiniSuperDev  Here is the [vite.config.ts](https://github.com/onset/lameta/blob/vite/vite.config.ts) I ended up with.
