### ISSUE TITLE
Duplicate log lines in debug console in vscode

### ISSUE THREAD

**Issue by ADumaine** [alex8088/electron-vite#75]
### Describe the bug

When starting my app with `npm run electron-vite dev` there is only one line for each console.log statement in the main background process.

When starting in vscode, every console.log line is duplicated:  one from main, one from publicUtils.js.
![image](https://user-images.githubusercontent.com/1069218/207117276-5213b0a6-66d8-459c-9de2-f534a890c2bc.png)

This is the launch config
```
{
            "name": "Debug Main Process",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron-vite",
            "windows": {
              "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron-vite.cmd"
            },
            // "runtimeArgs": ["--sourcemap"]
          }
```
I am not sure if this is an electron-vite issue or a vite issue or I just have something misconfigured.

This was also happening prior to vite 4.x

### Electron-Vite Version

1.0.16

### Electron Version

22.0.0

### Vite Version

4.0.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@ADumaine This is a issue with vite.  electron-vite uses vite‘s `createLogger` which make it duplicate output during debugging. But it's okay.  It's not a code bug.

**Comment by ADumaine** [comment]
Ok. Do you know a way to suppress it or should I create a vite issue?

**Comment by alex8088** [comment]
It is unclear whether this problem also exists in web application development (debugging).  I haven't found a way to suppress it.

**Comment by alex8088** [comment]
Later, I will also test whether web application development also has this issue.

**Comment by alex8088** [comment]
It only happens in vscode, it will be fixed in the next version.

**Comment by alex8088** [comment]
new ver 1.0.17 is out!
