### ISSUE TITLE
Can't parse vite config

### ISSUE THREAD

**Issue by adminy** [alex8088/electron-vite#76]
### Describe the bug

```javascript
import { defineConfig, bytecodePlugin } from 'electron-vite'
import preact from '@preact/preset-vite'
import { config } from 'dotenv'
config()

export default defineConfig({
	// Electron Source Code Protection
	main: { plugins: [bytecodePlugin()] },
	preload: { plugins: [bytecodePlugin()] },
	renderer: { plugins: [bytecodePlugin()] },
	build: {
		minify: true,
		cssCodeSplit: true
	},
	plugins: [ preact() ],
	define: { global: {}, 'process.env': process.env },
	esbuild: { logOverride: { 'this-is-undefined-in-esm': 'silent' } },
	resolve: { alias: { './runtimeConfig': './runtimeConfig.browser' } }
})
```

failed to load config from electron.vite.config.js
error during preview electron app:
TypeError: (0 , import_preset_vite.default) is not a function
    at Object.<anonymous> electron.vite.config.js:45:44)

### Electron-Vite Version

1.0.16

### Electron Version

17.1.0

### Vite Version

2.9.15

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
ref: https://evite.netlify.app/config/

**Comment by alex8088** [comment]
bytecodeplugin not support renderer

**Comment by alex8088** [comment]
```js
import { defineConfig, bytecodePlugin } from 'electron-vite'
import preact from '@preact/preset-vite'
import { config } from 'dotenv'
config()

export default defineConfig({
	// Electron Source Code Protection
	main: { plugins: [bytecodePlugin()] },
	preload: { plugins: [bytecodePlugin()] },
	renderer: {
            build: {
		minify: true,
		cssCodeSplit: true
	   },
	   plugins: [ preact() ],
	   define: { global: {}, 'process.env': process.env },
	   esbuild: { logOverride: { 'this-is-undefined-in-esm': 'silent' } 
         }
})
```

**Comment by adminy** [comment]
Now I get:                         throw new Error('build entry field required for the electron vite main config');

**Comment by alex8088** [comment]
https://evite.netlify.app/guide/ electron entry point

**Comment by adminy** [comment]
I have defined that.

**Comment by alex8088** [comment]
Please check whether the path is correct.

**Comment by adminy** [comment]
yes it is.

**Comment by adminy** [comment]
```
failed to load config from electron.vite.config.js
error during build:
TypeError: (0 , import_preset_vite.default) is not a function
```

**Comment by alex8088** [comment]
Scaffold with `npm init @quick-start/electron ` to learn more

**Comment by alex8088** [comment]
or https://github.com/alex8088/electron-vite-boilerplate

**Comment by adminy** [comment]
Its not the most intuitive as to why this works in such way.
