### ISSUE TITLE
可以修改vite配置base

### ISSUE THREAD

**Issue by budou0608** [alex8088/electron-vite#78]
### Clear and concise description of the problem

``` ts
import { defineConfig } from 'electron-vite'
export default defineConfig({
  renderer: {
    base: '/', // 编译后都是./
  }
})
```

### Suggested solution

``` ts
import { defineConfig } from 'electron-vite'
export default defineConfig({
  renderer: {
    base: '/', // 编译后是/
  }
})
```

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
什么目的要修改base，在electron是不必的，内置已做好base设置，dev和build下是不同的，生产模式下必须是 ` ./`, 才能正常运行

**Comment by budou0608** [comment]
electron搭建一个本地服务，用loadURL()打开页面，不用loadFile()

**Comment by budou0608** [comment]
可以不限base

**Comment by alex8088** [comment]
不能不限制，在electron中生产模式base必须是`./`，否则无法正常运行，这个设计是有意而为之。为什么不直接使用node服务来实现。非要这样处理，你可以在renderer目录中增加vite配置，独立打包，但注意输出不应和electron-vite冲突。

**Comment by budou0608** [comment]
谢谢
