### ISSUE TITLE
Native .node addons

### ISSUE THREAD

**Issue by hosnar** [alex8088/electron-vite#79]
### Describe the bug

Hi, 

i am trying to require native .node addon in my project, but i don't know what is the best way to do that. I've tried putting it in public folder like mentioned in another issue, but when i package the app it gets packaged 3 times and then the installer has very large size.

In the old project i was working on (Vue2, Webpack) i've had it in a root folder and i requested it via "__non_webpack_require__" and in electron builder config i packaged it with "extraResources". Is there a similar or a better way to do it here? Thank you 

Edit: Sorry, i didn't mean to label this as bug.

### Electron-Vite Version

1.0.14

### Electron Version

21.3.0

### Vite Version

3.2.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@hosnar I recommend to use `asarUnpack` but not `extraResources` in electron builder config.

**Comment by alex8088** [comment]
@hosnar I found this problem, if you create a public dir named `public`, it will be copied to both the main out dir and the preload out dir (main process and preload scripts work dir is root).  You can set `build.copyPublicDir` to `false` or rename public dir.

**Comment by hosnar** [comment]
@alex8088 Thank you for your help! I will close this issue.
