### ISSUE TITLE
[Question] how to avoid page reloads in main process 

### ISSUE THREAD

**Issue by janakg** [alex8088/electron-vite#80]
### Describe the bug

how to avoid reload of main process and entire electron app. 

We use a common private library between main and renderer process. While I need the HMR to take effect on the renderer process, I do not want the main process to reload itself. 

Tried adding  build watch config and also tried disabling the same, but no effect in electron-vite

Please let me know if there is a way to achieve include and exclude of folders to watch.

### Electron-Vite Version

1.0.16

### Electron Version

22.0.0

### Vite Version

4.0.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Do not set `watch` option in main config. More about [hot reloading](https://evite.netlify.app/guide/hot-reloading.html)

**Comment by janakg** [comment]
@alex8088 thanks!
