### ISSUE TITLE
Bundle for production only config accessed by process.env

### ISSUE THREAD

**Issue by hosnar** [alex8088/electron-vite#81]
### Describe the bug

Hi. I'm very new to Vite and bundlers in general so i apologize if this is a weird question. I have a es6 module that includes several configs.  Something like this:

```
const formatBrandName = name => {
  if (process.platform === 'linux') {
    return name.split(' ').join('-')
  } else {
    return name
  }
}

const configs = {
 brand1: { ... },
 brand2: { ... },
 brand3: { ... }
}

export default {
  ...configs[brand],
 name: formatBrandName(configs[brand].name)
}
```

Is there a way so that Vite would only bundle the config that was targeted via process.env? So if VITE_BRAND_ID is set to "brand2" the final bundle would only include info for that config. Currently it bundles this whole module and then on production it tries to import it and access process.env.VITE_BRAND_ID which isn't available there. Or is there a better way to implement whitelabel/multibrand, that would bundle only the config/settings for selected brand?

Here is an example for vue2+webpack: https://www.nickmcburney.co.uk/blog/vuejs-whitelabel/

Any help would be very appreciated. Thank you.

### Electron-Vite Version

1.0.16

### Electron Version

22.0.0

### Vite Version

4.0.3

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hosnar** [comment]
Thank you for you answer. I've tried that and i can get it to work in the main and renderer process, but is there a way to access this value in `electron.vite.config.js` or `electron-builder.js` file (either of those would be fine)? Since i also need to adjust builder config based on this brand config.

If i try to import this module in `electron.vite.config.js` i get this warning/error:

```
▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    src/shared/whitelabel.config.js:2:14:
      2 │ const brand = import.meta.env.RENDERER_VITE_BRAND
        ╵               ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.
  
error during start dev server and electron app:
TypeError: Cannot read properties of undefined (reading 'RENDERER_VITE_BRAND')
```

And if i try to import this module in `electron-builder.js` i get this error:

```
SyntaxError: Cannot use import statement outside a module
```

**Comment by alex8088** [comment]
I recommend to specify the configuration file to handle. 

e.g.

```json
 "test": "electron-vite dev -c electron.vite.config.foo.js",
```
`electron-builder` can also handle the same.

**Comment by alex8088** [comment]
another way: [Conditional Config](https://evite.netlify.app/config/#conditional-config)

and use `loadEnv` to get envs

```js
import { defineConfig, loadEnv } from 'electron-vite'

export default defineConfig(({ command, mode }) => {
  const envs = loadEnv(mode)
 // ...
})
```

**Comment by hosnar** [comment]
Great, i can probably make that work. Thank you for your help!
