### ISSUE TITLE
导入部分Node模块后，打开 DevTools 报错：DevTools 无法加载来源映射

### ISSUE THREAD

**Issue by ChnJerry** [alex8088/electron-vite#85]
### Describe the bug

通过导入部分 Node 模块，例如 mssql 模块 `const sql = require('mssql')` 或 Sequelize 模块 `const { Sequelize } = require('sequelize')`，都会在打开 DevTools 的时候报错（此时并没有调用任何模块中的方法，单纯只是写了导入语句）。
我尝试调用了模块中的方法，**模块的使用过程中一切正常，只有 DevTools 报错**。且只有在导入部分 Node 模块会出现这个问题，影响调试体验。
我也尝试了升级 Electron-Vite 版本到最新后，再导入模块，依然报错。
![image](https://user-images.githubusercontent.com/48207223/211981493-c3eae018-13cf-4585-acba-05d852d838fa.png)

### Electron-Vite Version

1.0.10

### Electron Version

20.3.1

### Vite Version

3.1.6

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@ChnJerry 这是因为相关库内联soucemap文件，但electron不支持加载，这个并没有什么影响，只是一个警告。

**Comment by ChnJerry** [comment]
> @ChnJerry 这是因为相关库内联soucemap文件，但electron不支持加载，这个并没有什么影响，只是一个警告。

感谢解答，所以这是 electron 自身的缺陷对吗
