### ISSUE TITLE
404 and build fails after project restructure according to docs

### ISSUE THREAD

**Issue by SkySails** [alex8088/electron-vite#86]
### Describe the bug

Hello! Thanks for creating this package, it looks pretty interesting!

I wanted to try this out with a custom project structure that looks like the below:

```
.
├──electron
│  ├──main
│  │  └──index.ts
│  └──preload
│     └──index.ts
├──src # with React
│     ├──main.tsx
│     └──...
├──index.html
├──electron.vite.config.ts
└──package.json
```

I found the [Customizing Project Structure](https://evite.netlify.app/guide/project-structure.html#customizing-project-structure) section in the docs and attempted to follow the provided instructions, but upon running `yarn dev` I was prompted with a white screen, seemingly due to 404 from Vite:

<img width="600" src="https://user-images.githubusercontent.com/46646495/212521160-abcdf803-b400-4ef3-9e81-2827719346aa.png">

I then tried opening the dev server URL in a browser, which also yielded 404. Finally, I tried running `yarn build` to see what the cause might be, and this was the output:

```
vite v4.0.4 building for production...
✓ 2 modules transformed.
out/main/index.js  1.43 kB
vite v4.0.4 building for production...
✓ 1 modules transformed.
out/preload/index.js  0.42 kB
vite v4.0.4 building for production...
✓ 33 modules transformed.
rendering chunks (1)...[vite:build-html] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../index.html".
```

Looking at the error at the end, and especially at the relative path that tries to reach two levels up, I tried moving the `index.html` into `src` and adjusting the config for the change - with the following result:

```
vite v4.0.4 building for production...
✓ 33 modules transformed.
rendering chunks (1)...[vite:build-html] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../index.html".
```

It looks like it has redacted at least one directory from the relative path, but so far I have not been able to make it work, despite the documentation suggesting that it should be possible.

Is there anything that I have missed?

### Electron-Vite Version

1.0.17

### Electron Version

21.3.3

### Vite Version

4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@SkySails 

try

```js
  renderer: {
     root: process.cwd()
  }
```

**Comment by SkySails** [comment]
That works great, thanks a lot! 🙌
