### ISSUE TITLE
bytecodePlugin支持windows32位

### ISSUE THREAD

**Issue by chen-gaoyuan** [alex8088/electron-vite#87]
### Clear and concise description of the problem

什么时候给bytecodePlugin支持windows32位, 现在开启bytecodePlugin打包win32运行不了

### Suggested solution

1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@chen-gaoyuan 实际上是支持的，在x64上打包ia32位的临时解决方案是，重新安装对应版本32位electron，`npm i --arch=ia32 electron@x.x.x`，再重新编译打包程序即可。不太友好。(通常x64都是可以兼容ia32，所以这样处理应该没有问题)

对于非当前开发平台架构字节码支持确实有待改进，也有对应方案，在后续版本应该会对bytecodeplugin进行改进，你可以持续关注。

**Comment by alex8088** [comment]
关于多平台和多架构构建参考： https://cn-evite.netlify.app/guide/source-code-protection.html#%E5%A4%9A%E5%B9%B3%E5%8F%B0%E6%9E%84%E5%BB%BA
