### ISSUE TITLE
无法加载本地绝对路径图片

### ISSUE THREAD

**Issue by sfyang2** [alex8088/electron-vite#9]
### Describe the bug

加载本地图片报以下错误：
Refused to load the image 'file:///C:/Users/sf/Desktop/%E6%91%84%E5%BD%B1/FEEL/1%20(1).jpg' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

//创建窗口也关闭了同源限制
webPreferences：{
    webSecurity: false, 
}

//同时也创建的自定义的file协议的
 protocol.interceptFileProtocol('file', (req, callback) => {
    const url = req.url.substring(8);
    callback(decodeURI(url));
  })

但是还是无法加载本地图片

### Electron-Vite Version

1.0.2

### Electron Version

17.3.1

### Vite Version

2.9.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
这看起来并不是 electron-vite 的问题，你需要知道 CSP 是什么

**Comment by sfyang2** [comment]
感谢大佬，成功解决啦。 获得新知识点
把模板里的index.html里的  <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"

换成下面的就好了

<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
