### ISSUE TITLE
Request info on bytecode limitation

### ISSUE THREAD

**Issue by jeremyben** [alex8088/electron-vite#91]
You mention here that string contents are not protected in V8 bytecode:
https://evite.netlify.app/guide/source-code-protection.html#limitations-of-v8-bytecode

I was wondering if we could build a string from a buffer like so:

```js
const buf = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72])
const str = buf.toString()
```

And the string would then be protected ?

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@jeremyben Thanks! This sounds like a feasible solution 🤔 . I have a similar idea( repacing string via function or buffer). But this still needs some validation experiments. I will try. Your idea is very constructive.

**Comment by jeremyben** [comment]
It seems this works.
I made a test with the [encryptionKey option of electron-store](https://github.com/sindresorhus/electron-store#encryptionkey).

I tried storing the key as plain string, built the app, and I could see in the jsc blob the key next to `encryptionKey`.
Then I tried storing the key built manually from a buffer, and in the jsc blob I could only see `encryptionKey` in plain sight.

🙂

**Comment by jeremyben** [comment]
Hey I figured out a way to do it automatically with a dedicated _tag_.

I use a tagged template that is a noop for development, but that is replaced at build time.
(This is a well-known technique: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#raw_strings)

```ts
export const __protect = (str: readonly string[], ...values: never[]) => String.raw({ raw: str }, ...values)
```
Since we only want to transform string constants, we forbid any interpolation thanks to `never[]`.

Then I added a vite transform plugin to my configuration to replace the tagged strings with the buffer technique:

```js
/**
 * @returns {import('vite').Plugin}
 */
function protectStringsInBytecode() {
	const filter = vite.createFilter(/\.(m?[jt]s|[jt]sx)$/)

	return {
		name: 'protectString',
		apply: 'build',
		transform(code, id) {
			if (!filter(id)) return

			const replaced = code.replace(/__protect`(.+)`/gim, (_, str) => {
				const { data } = Buffer.from(str).toJSON()
				return `Buffer.from([${data.join(',')}]).toString()`
			})

			return replaced
		},
	}
}
```

I think it could be added to your bytecode plugin as an option rather than a independant plugin.

**Comment by alex8088** [comment]
@jeremyben That's great. Thank you for taking the time to study this problem. I'll try again later.

**Comment by alex8088** [comment]
@jeremyben 

Be inspired by you!

I found a better solution. Bytecode does not protect strings but numbers, so we can convert string to char code. The [String.fromCharCode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode) static method is great for this. For example:

```js
const encryptKey = 'ABC'
```
⬇️
```js
const encryptKey = String.fromCharCode(65, 66, 67)
```

This conversion method is very simple and does not require additional processing by developers.

I will add an option(`protectedStirngs`) to the bytecode plugin to specify the strings to be protected. The plugin will convert the specified string to char code and replace it when building.

**Comment by jeremyben** [comment]
Yes that's simpler, maybe less runtime overhead but I cant' say.

What would your api look like ?
I need to protect a lot of different strings (sensitive shell commands), and I can't list them all in the vite config. 
If you want to avoid the tagging function, maybe allow regex ?

Be aware I also discovered that you should escape the strings at build time the way the javascript engine does it,
for example with windows paths.
Try it for yourself and if you encounter the same problem, use this package: https://www.npmjs.com/package/unraw

**Comment by alex8088** [comment]
New ver 1.0.19 is out! Support for protecting strings in v8 bytecode. But regular expression matching strings are not yet supported. Anyway, thank you @jeremyben .

more details: https://evite.netlify.app/guide/source-code-protection.html#limitations-of-v8-bytecode
