### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "events". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by caioregatieri** [alex8088/electron-vite#92]
### Describe the bug

Error on build electron app.

Running app on dev mode it work well.

When I do build the app and run it,  the React components don't load, then enabling and using developer tool with builded version a saw the error : **Uncaught TypeError: Failed to resolve module specifier "events". Relative references must start with either "/", "./", or "../"**.

Someone can help me?

### Electron-Vite Version

1.0.12

### Electron Version

21.2.2

### Vite Version

3.2.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@caioregatieri The modules that may be referenced use `events`. But `events` only works in nodejs. You can also find many similar problems in Vite's [issue tracker](https://github.com/vitejs/vite/issues). Please provide more details.

**Comment by caioregatieri** [comment]
I'm debugging the code and I t think that error is happens after using **twilio-client** package.

The below line crash the app builded, but works fine when dev mode
`import Twilio from 'twilio-client';`

Someone are using twilio-client to help me?

**Comment by alex8088** [comment]
@caioregatieri 
two way you can try:
1. enable `nodeIntegration`, use `require` to instead `import`:
```js
const Twilio = require('twilio-client')
```
2. use  [rollup-plugin-node-polyfills](https://github.com/ionic-team/rollup-plugin-node-polyfills) to polyfill and add the snippet below to the renderer config:

```js
resolve: {
  alias: {
    events: 'rollup-plugin-node-polyfills/polyfills/events'
  }
}
```

**Comment by alex8088** [comment]
@caioregatieri solved?

**Comment by caioregatieri** [comment]
it don't solved

I record an video to explain the error: [video screen record](https://www.loom.com/share/58d4097d6f3f40aaba80af996533be02)

my **electron.vite.config.ts** content:

```
import { resolve, normalize, dirname } from 'path'
import { defineConfig } from 'electron-vite'

import injectProcessEnvPlugin from 'rollup-plugin-inject-process-env'
import tsconfigPathsPlugin from 'vite-tsconfig-paths'
import reactPlugin from '@vitejs/plugin-react'

// yarn add --dev @esbuild-plugins/node-globals-polyfill
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'
// yarn add --dev @esbuild-plugins/node-modules-polyfill
import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill'
// You don't need to add this to deps, it's included by @esbuild-plugins/node-modules-polyfill
import nodePolyfills from "rollup-plugin-node-polyfills";

import { main, resources } from './package.json'

const [nodeModules, devFolder] = normalize(dirname(main)).split(/\/|\\/g)
const devPath = [nodeModules, devFolder].join('/')

const tsconfigPaths = tsconfigPathsPlugin({
  projects: [resolve('tsconfig.json')],
})

export default defineConfig({
  main: {
    plugins: [tsconfigPaths],

    build: {
      rollupOptions: {
        input: {
          index: resolve('src/main/index.ts'),
        },

        output: {
          dir: resolve(devPath, 'main'),
        },
      },
    },
  },

  preload: {
    plugins: [tsconfigPaths],

    build: {
      outDir: resolve(devPath, 'preload'),
    },
  },

  renderer: {
    define: {
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      'process.platform': JSON.stringify(process.platform),
    },

    server: {
      port: 4927,
    },

    publicDir: resolve(resources, 'public'),

    plugins: [
      tsconfigPaths,
      reactPlugin(),
    ],

    resolve: {
      alias: {
        // This Rollup aliases are extracted from @esbuild-plugins/node-modules-polyfill,
        // see https://github.com/remorses/esbuild-plugins/blob/master/node-modules-polyfill/src/polyfills.ts
        // process and buffer are excluded because already managed
        // by node-globals-polyfill
        util: 'rollup-plugin-node-polyfills/polyfills/util',
        sys: 'util',
        stream: 'rollup-plugin-node-polyfills/polyfills/stream',
        path: 'rollup-plugin-node-polyfills/polyfills/path',
        querystring: 'rollup-plugin-node-polyfills/polyfills/qs',
        punycode: 'rollup-plugin-node-polyfills/polyfills/punycode',
        url: 'rollup-plugin-node-polyfills/polyfills/url',
        string_decoder: 'rollup-plugin-node-polyfills/polyfills/string-decoder',
        http: 'rollup-plugin-node-polyfills/polyfills/http',
        https: 'rollup-plugin-node-polyfills/polyfills/http',
        os: 'rollup-plugin-node-polyfills/polyfills/os',
        assert: 'rollup-plugin-node-polyfills/polyfills/assert',
        constants: 'rollup-plugin-node-polyfills/polyfills/constants',
        _stream_duplex: 'rollup-plugin-node-polyfills/polyfills/readable-stream/duplex',
        _stream_passthrough: 'rollup-plugin-node-polyfills/polyfills/readable-stream/passthrough',
        _stream_readable: 'rollup-plugin-node-polyfills/polyfills/readable-stream/readable',
        _stream_writable: 'rollup-plugin-node-polyfills/polyfills/readable-stream/writable',
        _stream_transform: 'rollup-plugin-node-polyfills/polyfills/readable-stream/transform',
        timers: 'rollup-plugin-node-polyfills/polyfills/timers',
        console: 'rollup-plugin-node-polyfills/polyfills/console',
        vm: 'rollup-plugin-node-polyfills/polyfills/vm',
        zlib: 'rollup-plugin-node-polyfills/polyfills/zlib',
        tty: 'rollup-plugin-node-polyfills/polyfills/tty',
        domain: 'rollup-plugin-node-polyfills/polyfills/domain',
        events: 'rollup-plugin-node-polyfills/polyfills/events',
        buffer: 'rollup-plugin-node-polyfills/polyfills/buffer-es6', // add buffer
        process: 'rollup-plugin-node-polyfills/polyfills/process-es6', // add process
      }
    },

    optimizeDeps: {
      esbuildOptions: {
        // Node.js global to browser globalThis
        define: {
          global: 'globalThis'
        },
        // Enable esbuild polyfill plugins
        plugins: [
          NodeGlobalsPolyfillPlugin({
            process: true,
            buffer: true,
          }),
          NodeModulesPolyfillPlugin()
        ]
      }
    },

    build: {
      outDir: resolve(devPath, 'renderer'),

      rollupOptions: {
        plugins: [
          injectProcessEnvPlugin({
            NODE_ENV: 'production',
            platform: process.platform,
          }),
        ],

        input: {
          index: resolve('src/renderer/index.html'),
        },

        output: {
          dir: resolve(devPath, 'renderer'),
        },
      },
    },
  },
})
```

**Comment by caioregatieri** [comment]
I need to use **twilio-client** dependency, and it works in development mode.

I really need to use **twilio-client** because it is the same one that is being used in the web version of this application (using laravel and vue) and this works fine.

**Comment by alex8088** [comment]
@caioregatieri You can use `twilio-client` in `preload script` and expose to `renderer`.

![xe](https://user-images.githubusercontent.com/25053004/215978293-d1fb7714-8123-41d3-9368-ff8f07a8b0b6.gif)

**Comment by caioregatieri** [comment]
I create a repository with minimal code to explain the problem...

https://github.com/caioregatieri/app-electron

The error happens when I instantiate the Twilio.Device class (new Device())
This is on line 11 at file renderer/index.tsx

**Comment by alex8088** [comment]
@caioregatieri If  you use it in preload script, it will work. See the gif above.

```js
const device = new window.api.Twilio.Device()
console.log(device)
```

**Comment by caioregatieri** [comment]
I did  as gif above but don't work 

https://www.loom.com/share/273acf2f4f4942ee93d100c56bd8aad2

I will be commit and push the code to github to review if possible

**Comment by alex8088** [comment]
@caioregatieri 

disable sandbox in browserWindow

``` js
webPreferences: {
      preload: path.join(__dirname, '../preload/index.js'),
      sandbox: false
}
```

**Comment by caioregatieri** [comment]
That work's but after instantiate a new device I need setup the device (device.setup({...})), but now it's broken...

![image](https://user-images.githubusercontent.com/4867331/216737479-a6aebba3-eb0a-4efe-a3db-1beb199499af.png)

![image](https://user-images.githubusercontent.com/4867331/216737295-76b16c7a-4f8e-4762-a665-0fd4fee2494a.png)

**Comment by alex8088** [comment]
Then you need to confirm its usage. The error already indicates that it is not a function.

**Comment by caioregatieri** [comment]
But works perfectly when I execute on dev mode (cross-env NODE_ENV=development electron-vite dev --watch)

**Comment by alex8088** [comment]
electron-vite preview works?
 if works，maybe packaging problem(some module lost). Check your electron builder config.

**Comment by alex8088** [comment]
Are you import any `Twilio` modules in renderer?

**Comment by caioregatieri** [comment]
I solved it with:

electron.vite.config.ts
`
    build: {
      outDir: resolve(devPath, 'renderer'),

      rollupOptions: {
        plugins: [
          injectProcessEnvPlugin({
            NODE_ENV: 'production',
            platform: process.platform,
          }),
          rollupNodePolyFill,
        ],
      },
    },
`
and this:

index.html
`
    <script>
      global = globalThis;
    </script>
`
