### ISSUE TITLE
生产模式是否也可以像开发模式那样win.loadURL，而不是win.loadFile

### ISSUE THREAD

**Issue by blessleon** [alex8088/electron-vite#93]
### Clear and concise description of the problem

你好，我在迁移vuecli electron 项目到electron-vite时遇到打包生产环境多窗口加载路由的问题，vuecli 提供import { createProtocol } from 'vue-cli-plugin-electron-builder/lib' 创建app://./index.html 协议的方式加载路由，而electron-vite 则使用loadFile , 多窗口则需要多个html入口，是否有方式支持生产环境loadURL 路由的方式

### Suggested solution

是否有plugin支持生产环境多窗口使用win.loadURL 加载路由

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
如果是router方式，browserWindow的loadfile第二参数支持hash. 如:
``` js
win.loadFile('./index.html', { hash: 'about')
```
如果是多页，参考
```js
if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
  url = `${process.env['ELECTRON_RENDERER_URL']}/view.html`
} else {
  url = path.join(__dirname, '../renderer/view.html')
}
```

生产模式下，不使用协议只能是`loadFile`

**Comment by blessleon** [comment]
感谢大佬 @alex8088 令我思路打开，之前路走窄了
