### ISSUE TITLE
ReferenceError: self is not defined 

### ISSUE THREAD

**Issue by himalay34** [alex8088/electron-vite#94]
### Describe the bug

i was trying to use pouchdb in the main thread i.e node . while i import pouchdb it throws error.

if i remove pouchdb, error disapeared and app works fine.
 
![image](https://user-images.githubusercontent.com/54813967/216399951-2f3fd674-234a-4b76-95b9-fe7778a67477.png)

### Electron-Vite Version

^1.0.17

### Electron Version

^21.3.3

### Vite Version

^4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [x] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Enable `externalizePlugin` and install punchDB to deps. Do not need to bundle punchDB. PunchDB support browser and nodejs.  More detail: https://evite.netlify.app/guide/dev.html#dependencies-vs-devdependencies

**Comment by himalay34** [comment]
> Enable `externalizePlugin` and install punchDB to deps. Do not need to bundle punchDB. PunchDB support browser and nodejs. More detail: https://evite.netlify.app/guide/dev.html#dependencies-vs-devdependencies

Many many thanks. 

after dodifying like below,it works. is it ok? 
![image](https://user-images.githubusercontent.com/54813967/216427385-b7bd4efb-3a03-43a3-bf61-7c558f512132.png)

**Comment by alex8088** [comment]
There is no need to configure the rollup external option, the externalizeplugin will auto to externalize modules which install in deps

**Comment by himalay34** [comment]
Not working, same error persist....

![image](https://user-images.githubusercontent.com/54813967/216429843-4cbeddf2-6111-4b30-af23-2ca5052a29cc.png)

![image](https://user-images.githubusercontent.com/54813967/216430150-da74148b-b95c-4de1-8459-6a74ef61f611.png)

Pouchdb installed as Dev dependency

**Comment by alex8088** [comment]
should be dep not devdep

**Comment by alex8088** [comment]
https://evite.netlify.app/guide/dev.html#dependencies-vs-devdependencies

**Comment by alex8088** [comment]
just only

``` js
 main: {
    plugins: [externalizeDepsPlugin()]
 },
```

**Comment by himalay34** [comment]
> should be dep not devdep

pouchdb installed as dep and modified the electron.vite.config.ts file as you describe

but error persist...

![image](https://user-images.githubusercontent.com/54813967/216433040-b4e89ef6-e750-494f-8a3c-90030d84138a.png)

**Comment by himalay34** [comment]
only works when i use pouchdb without any plugin i.e pouchdb-find
*settings* ---> 
![image](https://user-images.githubusercontent.com/54813967/216436652-6a1477e5-6782-4ef0-afbe-07ba32503324.png)


    import * as PouchDB from 'pouchdb'
    const Pouch = PouchDB.default.defaults({
        prefix: getPath('userData'),
        auto_compaction: true
    })
    
    const db = Pouch("kittens")
    db.info().then(console.log).catch(console.error)
    
  works fine.
  
  but fails on 
  
      import * as PouchDB from 'pouchdb'
      import pouchdbFind from 'pouchdb-find'
      PouchDB.default.plugin(pouchdbFind)
      
      const Pouch = PouchDB.default.defaults({
          prefix: getPath('userData'),
          auto_compaction: true
      })
    
      const db = Pouch("kittens")
      db.info().then(console.log).catch(console.error)
    
    
![image](https://user-images.githubusercontent.com/54813967/216436007-9a01a41a-a856-4bb2-b9d3-59a828772709.png)

except pouch-find, other 3 plugins works without error

**Comment by alex8088** [comment]
Your pouchDB is latest?

In my project, it works fine.

![x](https://user-images.githubusercontent.com/25053004/216503413-7f6ef7a9-b7b1-443c-ab6e-29d513541e5f.gif)

**Comment by himalay34** [comment]
> Your pouchDB is latest?
> 
> In my project, it works fine.
> 
> ![x](https://user-images.githubusercontent.com/25053004/216503413-7f6ef7a9-b7b1-443c-ab6e-29d513541e5f.gif) [ ![x](https://user-images.githubusercontent.com/25053004/216503413-7f6ef7a9-b7b1-443c-ab6e-29d513541e5f.gif) ](https://user-images.githubusercontent.com/25053004/216503413-7f6ef7a9-b7b1-443c-ab6e-29d513541e5f.gif) [ ](https://user-images.githubusercontent.com/25053004/216503413-7f6ef7a9-b7b1-443c-ab6e-29d513541e5f.gif)

aftrer few try, it works.
Many many thanks for your support. <3
