### ISSUE TITLE
Hope to provide a  way to restart electron when main and preload changed

### ISSUE THREAD

**Issue by cnwander** [alex8088/electron-vite#95]
### Clear and concise description of the problem

Hope to provide a  way to reload contents of all active BrowserWindows within electron when the source files are changed.

### Suggested solution

nodemon or electron reload

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
electron-vite support hot-reloading, see https://evite.netlify.app/guide/hot-reloading.html
