### ISSUE TITLE
Unable to load preload scripts: Preload scripts are not loading for a second window

### ISSUE THREAD

**Issue by jayantasamaddar** [alex8088/electron-vite#97]
# The Error

![ipcRendererError](https://user-images.githubusercontent.com/33408788/216806898-c668880e-447c-4860-9ab7-4d42e95de474.png)

---

# Summary of the Problem

I setup the app using `yarn create @quick-start/electron`. Made sure ipcRenderer is added to preload scripts and managed to send data from renderer to main. All good. The problem happens is when I create a new window in main and then want to send data from Renderer (page A) to New Window via the intermediary main (using ipc). 

**Workflow**: Render ---> Main ----> New Window

This new window seems to unable to access preload scripts despite the path specified. 

---

# The Code

This is how my code looks,

in **`index.ts (main)`**

```js
/** Create New Window */
let newWindow: BrowserWindow;
const createNewWindow = (): void => {
  newWindow = new BrowserWindow({
    title: 'New Window',
    width: 600,
    height: 766,
    autoHideMenuBar: true,
    webPreferences: {
      contextIsolation: true,
      preload: join(__dirname, '../preload/index.js')
    }
  });

  newWindow.loadURL('http://localhost:5173/new');
};

/***************************************************************************************/
/** Event Listeners */
/***************************************************************************************/

/** Respond to ipcRenderer JSON file upload */
ipcMain.on('source:renderer', async (_e, args) => {
  console.log(args)  // Correctly receives from renderer
  createNewWindow();
  newWindow.on('ready-to-show', () => console.log('Ready to Show') // Prints correctly to the console
  newWindow.on('show', () => {
    console.log('Loaded');  // Does not print, meaning the page load fails
    newWindow.webContents.send('source:main', args);
  });
});
```

**This is what on the new Page,** (I've commented out the useEffect and the h1 renders correctly, otherwise it throws an error)

```
export const NewPage = (): ReactElement => {
  const [data, setData] = useState<Record<string, never>>({});

  useEffect(() => {
    // Listen for the event
    window.electron.ipcRenderer.on('source:main', async (_e, args) => {
      setData(args);
    });
    console.log(data);
    // Clean up
    window.electron.ipcRenderer.removeAllListeners('source:main');
  }, []);

  return (
    <div>
      <h1>Testing New Line</h1>
      <div>{JSON.stringify(data)}</div>
    </div>
  );
};
```

> Note: To eliminate clutter, I'm not showing the React Router and the main renderer code as they are irrelevant considering the route is working correctly and would load correctly if I take out the ipcRenderer.

> **Edit**: There might be a possibility my folder structure is interfering and some settings might be necessary in `electron.vite.config.ts`. Do let me know if that's the case here.

Here's how that looks:

```s
├── dev-app-update.yml
├── electron-builder.yml
├── electron.vite.config.ts
├── package.json
├── README.md
├── resources
│   └── icon.png
├── src
│   ├── main
│   │   └── index.ts
│   ├── preload
│   │   ├── index.d.ts
│   │   └── index.ts
│   └── renderer
│       ├── index.html
│       └── src
│           ├── App.tsx
│           ├── assets
│           │   ├── icons.svg
│           │   └── index.css
│           ├── components
│           ├── env.d.ts
│           ├── main.tsx
│           └── pages
│               ├── Home
│               │   ├── Home.tsx
│               │   └── index.ts
│               ├── index.ts
│               └── NewPage
│                   ├── index.ts
│                   └── NewPage.tsx
├── tsconfig.json
├── tsconfig.node.json
└── tsconfig.web.json
```

The `main.tsx` is unchanged. My App.tsx looks like this (Using React Router v6.8.0)

```ts
import { ReactElement } from 'react';
import {
  RouterProvider,
  Route,
  createBrowserRouter,
  createRoutesFromElements,
  Outlet
} from 'react-router-dom';
import { ThemeProvider } from '@zenius-one/ursa';
import { Home, NewPage } from './pages';

const Root = (): JSX.Element => (
  <ThemeProvider>
    <Outlet />
  </ThemeProvider>
);

const router = createBrowserRouter(
  createRoutesFromElements(
    <Route path="/" element={<Root />}>
      <Route index element={<Home />} />
      <Route path="print" element={<NewPage />} />
    </Route>
  )
);

const App = (): ReactElement => {
  return <RouterProvider router={router} />;
};

export default App;
```

---

### Electron-Vite Version

1.0.17

### Electron Version

21.3.3

### Vite Version

4.0.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by jayantasamaddar** [comment]
**Update:** I had to add `sandbox: false` to the BrowserWindow options to get it to work. The question is, what security am I exactly compromising by doing this? The default main window that is created by `electron-vite` seems to have `sandbox` set to `false` as well.

**Comment by alex8088** [comment]
@jayantasamaddar, see
https://www.electronjs.org/blog/electron-20-0 , 

If your preload scripts do not depend on Node, no action is needed. If your preload scripts do depend on Node, either refactor them to remove Node usage from the renderer, or explicitly specify sandbox: false for the relevant renderers.

**Comment by jayantasamaddar** [comment]
> @jayantasamaddar, see
> https://www.electronjs.org/blog/electron-20-0 , 
> 
> If your preload scripts do not depend on Node, no action is needed. If your preload scripts do depend on Node, either refactor them to remove Node usage from the renderer, or explicitly specify sandbox: false for the relevant renderers.

They don't. But it should be totally possible to supply a different set of preload scripts for each window without any issues, right?

**Comment by alex8088** [comment]
Different preload scripts can be loaded in different windows. See

https://evite.netlify.app/guide/dev.html#multiple-windows-app
