### ISSUE TITLE
`electron.vite.config.js`配置无效

### ISSUE THREAD

**Issue by Soltus** [alex8088/electron-vite#98]
### Describe the bug

无论怎么配置，运行`electron-vite dev` 总是会受`package.json`的"main": "./electron/main.js"影响而不是`electron.vite.config.js`配置

### Electron-Vite Version

1.0.19

### Electron Version

23.0.0-beta.8

### Vite Version

4.1.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
electron-vite dev 的主进程默认构建输出为 `out/main/index.js` 因此， `package.json` 的 `main` 应改为 `out/main/index.js` .

相关可以参考 https://cn-evite.netlify.app/guide/project-structure.html

**Comment by Soltus** [comment]
我是在webpack项目中引入electron-vite加速调试，因此希望能不修改package.json入口

**Comment by alex8088** [comment]
可以自己配置输出目录 https://cn-evite.netlify.app/guide/build.html#%E8%BE%93%E5%87%BA%E7%9B%AE%E5%BD%95

**Comment by Soltus** [comment]
好的，我再研究一下

**Comment by Soltus** [comment]
`preload`我是不需要的，尝试配置总是报错，没有办法禁用它吗

**Comment by alex8088** [comment]
移除配置项目即可，同时cli加上 `--ignoreConfigWarning` 忽略配置缺失即可。l

**Comment by Soltus** [comment]
好的，还有一个问题当我运行 electron-vite -dev
我在根目录的index.html中内容
```html
<script src="./stage/sillot/vue.global.prod.js" defer init></script>
  <script type="module" src="/scr/index.ts"></script>
```
第一个顺利加载了，但是第二个报错404
![image](https://user-images.githubusercontent.com/83791825/217315972-5ce9a484-3bb7-4d1b-86f3-d0e77e051823.png)
非常抱歉提出这么多问题，我刚接触vite
electron.vite.config.js有关内容如下：
```js
renderer: {
    server: {
      port: 3000
    },
    root: '.',
    build: {
      lib: {
        entry: path.join(__dirname, 'index.html'),
      },
      rollupOptions: {
        input: {
          view: path.join(__dirname, 'index.html'),
        }
      }
    }
  }
```

**Comment by alex8088** [comment]
你这里可能是路径地址写错了 `scr` 应该是src吧

其次 `build.lib` 不需要，配置了input就不要配lib，再有注意就是input名会是输出名，比如取了view，将会输出成view.html

**Comment by alex8088** [comment]
建议你熟悉vite后(vite和electron-vite的文档都需要阅读一下好点)，整体迁移成vite，开发体验会好很多

**Comment by Soltus** [comment]
确实是我地址写错了。
但还是有其他问题：
![image](https://user-images.githubusercontent.com/83791825/217322248-b64c3ad9-285e-4e21-8e5d-1fe1d04a013b.png)
![image](https://user-images.githubusercontent.com/83791825/217322585-f3de5e18-c7bb-4b59-9006-9126f6cc1e21.png)
我看文档有关 plugins: [splitVendorChunkPlugin()] ，我不清楚有没有关系，加不加都有这个报错

**Comment by alex8088** [comment]
你的原始项目是基于nodeIntegration来开发，electron-vite 目前不支持，当然也有其他方式可以支持，但还是推荐preload方式开发。 详细：https://cn-evite.netlify.app/guide/dev.html#nodeintegration

**Comment by Soltus** [comment]
https://zhuanlan.zhihu.com/p/377697508
根据这个教程解决了

**Comment by Soltus** [comment]
![image](https://user-images.githubusercontent.com/83791825/217417057-f4150262-27b6-4209-8ec2-cd61076f4b5e.png)
看来目前还是不行

**Comment by alex8088** [comment]
试一试 [vite-plugin-commonjs-externals](https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals) 看看

**Comment by Soltus** [comment]
试过了。算了我放弃了
